### PR TITLE
Move Industrial Apiary to gregtech

### PR DESCRIPTION
**Pull request by kuba6000**
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6817
TODO:

- [x] Textures (Made by Jimbno)
- [x] Make bee effects work
- [x] Make better flower detection
- [x] Add a possibility to cancel process
- [x] Add support for gendustry upgrades or make a new ones
- [x] Add upgrades to gate acceleration levels ?
- [x] More options in GUI
- [x] More stats/info in GUI
- [x] Make all GUI tooltips translatable ?
- [x] Add recipes (and remove old one) https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10638

image
image
image
image
image
image
image
image
image
image

### CRYOTHEUM BEE OLD APIARY
image

### CRYOTHEUM BEE NEW APIARY - PEEK ONLY IN CHECKRECIPE (1 tick every 5 sec)
image

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
Seems to work in-game but I think it needs a bit more balancing, the fact you don't pay anything to get in built acceleration is a bit OP. Perhaps new GT apiary only upgrades that enable this functionality given it already supports other upgrades?

Tried on 256x and barely makes any lag though which is brill.

**Comment by kuba6000** [comment]
> Seems to work in-game but I think it needs a bit more balancing, the fact you don't pay anything to get in built acceleration is a bit OP. Perhaps new GT apiary only upgrades that enable this functionality given it already supports other upgrades?
> 
> Tried on 256x and barely makes any lag though which is brill.

Ye, will work on those upgrades.
I opened the pull already as it is working and wanted to get some reviews on code.

**Comment by Connor-Colenso** [comment]
While this block seems to work the in-game implementation seems a bit counter-intuitive and I would personally request a few changes after playing with it for a while.

I believe there should be no in-built acceleration to the block. Currently you are able to accelerate up to 32x and you do pay the EU cost for this but it requires no upgrades. I believe upgrades for each accel tier ranging from LV to UV would be best with perhaps the productivity being separate from the actual acceleration upgrades. This also allows us to easily extend this system in future if required.

E.g. 1 UV accel card will give automatic acceleration by 256x, no button required. The EU cost of this is already balanced well into the multi.

I believe it would be better to instead have upgrades of varying cost. This would allow us to unlock this machine sooner as it has no acceleration, perhaps even at HV or so.

**Comment by Dream-Master** [comment]
> While this block seems to work the in-game implementation seems a bit counter-intuitive and I would personally request a few changes after playing with it for a while.
> 
> I believe there should be no in-built acceleration to the block. Currently you are able to accelerate up to 32x and you do pay the EU cost for this but it requires no upgrades. I believe upgrades for each accel tier ranging from LV to UV would be best with perhaps the productivity being separate from the actual acceleration upgrades. This also allows us to easily extend this system in future if required.
> 
> E.g. 1 UV accel card will give automatic acceleration by 256x, no button required. The EU cost of this is already balanced well into the multi.
> 
> I believe it would be better to instead have upgrades of varying cost. This would allow us to unlock this machine sooner as it has no acceleration, perhaps even at HV or so.

HV is to early if we compare the tier of  the other stuff can used

**Comment by Connor-Colenso** [comment]
> HV is to early if we compare the tier of the other stuff can used

I mean if it's essentially just an apiary that takes some EU then HV is fine, the upgrades are what really makes it powerful and those cost much more in resources and power.

Apiaries can be gotten in basically stone age from villages don't forget.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
