### PR TITLE
Added Steam mixer

### PR DESCRIPTION
**Pull request by evgengoldwar**
Structure Steam mixer

Bronze tier
image

Steel tier
image

Tooltip Steam mixer 
image
image

Also the logic of all steam multis has been changed, now the tiers recipe that a multi can produce depends on tier multi

This change added to the tooltip of each steam multi

### CODE REVIEW

**Comment by Steelux8** [comment]
I thought the new steam multis that were being added were for ore processing, and only those machines would get a steam multi. Is that not true?

**Review by NotAPenguin0 — CHANGES_REQUESTED** [review]
I agree with Steelux here, I thought the point was to only make steam multiblocks for ore processing instead of replacing all electric machines.

**Comment by Dream-Master** [comment]
> I thought the new steam multis that were being added were for ore processing, and only those machines would get a steam multi. Is that not true?

first of all i want all ore processing multis to be added. That was done. But other multis should be aqllowed too. I chat with EvgenGoldWar and we thought a multi mixer is nice as well. Sure we wont replace all single block machines but give people an alternative multi. Sure if this is imblanced and need some changes i am open for suggestions. Overall i think steam should be used and not replaced after LV with Oil.

**Comment by Baerschen** [comment]
No fluids would follow in the footsteps of the steam centrifuge which is also not allowed to centrifuge fluids so that would make it somewhat consistent

**Comment by Dream-Master** [comment]
> I think it makes some form of sense to have a mixer, but it should probably have some form of significant limitation compared to electric mixers. One idea would be no fluids (including cells), another idea would be max 2 ingredients? The latter would allow you to make efficient bronze, red alloy, whatever the heat proof material is called and a few others, plus dough for foods.

sure we can speak of limitaion fluids as an example. Limitaion is bronze macines only process upd to lv and steel up to mv

**Review by NotAPenguin0 — APPROVED** [review]
Implementation looks fine, though I'm not a fan of being able to mix stainless steel in this for such a cheap cost. Replacing some casings or frames with dark steel for T2 should help though, since it's a fairly slow EBF recipe and a bit more expensive. 

Also, I would recommend disallowing input hatches and fluid recipes entirely (so no cells either), so mixing diesel in a steam mixer is also blacklisted.

**Pull request merged**
