### PR TITLE
Make ggfab Linked Input Bus support Assline

### PR DESCRIPTION
**Pull request by reobf**
Assline only checks the No.0 slot of an input bus, however the No.0 slot of Linked Input Bus is the circuit slot.
Therefore Linked Input Bus does not work on Assline.
This PR makes No.0 slot maps to the first slot of shared inventory, instead of the circuit slot.

To do this, this PR:
1. make getSizeInventory() always return 19 even if not linked (canInsertItem returns false for slot 0~17 when not linked, so it's safe to do this)
2. make slot No.18 map to the circuit slot
3. make slot No.0~17 map to the shared inventory

fig1
Fig1: Assline running with Linked Input Buses, before PR assline will not run
fig2
Fig2: Normal Multiblock running with Linked Input Bus, the basic function keeps unchanged
fig3
Fig3: Disconnected Linked Input Bus, its circuit slot still works (without NPE or something terrible)

### CODE REVIEW

**Comment by AbdielKavash** [comment]
Have you tested how this affects existing linked buses with circuits or items already in them when updating?

**Comment by reobf** [comment]
> Have you tested how this affects existing linked buses with circuits or items already in them when updating?
> 
> Also just so that we are clear, this is a significant buff to assline automation, as many asslines can now be linked together to run on the same items, without requiring _any_ external setup (AE stocking buses or similar). I don't know whether preventing this was _the_ reason for the LIB slots being numbered the way they are, but it is currently a significant downside that this PR removes.

This PR did not change how LIB saves shared inventory and the circuit slot and accroding to my test it seems fine.

Original return value of getSizeInventory might change between 2 and 19.
If let the circuit slot be the last slot, its index will change if linkage state changes, and will result in an exception if GUI open.
That might be the reason LIB chose to assign slot No.0 to circuit slot to avoid this problem, I guess.

But its true that this will significantly affects the balance which I didn't take into consideration...
So maybe explictly describe the incompatibility in the quest book or the tooltip of LIB/Assline?
As far as I know there's no such hints(or is it?), it's just so weird that the Assline does not see the first slot in the GUI.

**Comment by reobf** [comment]
How about keep the old slot number, and change the GUI like this?
Arrange slots in order of slot numbers.
And make it obvious that which slot the Assline will see.

**Comment by AbdielKavash** [comment]
That seems a little pointless to me, but I am not categorically against it.

If we want to make the behavior obvious, even a "Can not be used as an Assembly Line input" in the tooltip would suffice. Or, to go the extra mile, make the AL/AAL not form with a LIB.

**Comment by Glease** [comment]
Just FYI 

> It's not intentional
> I don't quite have an opinion on this, even though it did give me some headaches in the past..
> I think I just slap it in slot #0 because it was easier to code that way

**Comment by chochem** [comment]
there was some dev discussion (starting https://discord.com/channels/181078474394566657/939305179524792340/1302967965385490527) with general agreement so far that we do not want this as it makes parallel ALs a bit to easy.

there should be some documentation though for it not working. e.g. it shouldnt form.

I am sorry that you already put some work in. (which can be avoided by discussing changes first)

**Pull request closed without merging**
