### PR TITLE
Adds new UHV material and 2 new coil blocks. Also EBF, multismelter and pyro compat 

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6911

Adds a new material, Infinity Alloy, for the post-Dr* coil. This is slightly better as a turbine than SpNt and somewhat better as a cable for UEV than Dr. If anyone doesn't use lasers I guess. It's Dr\*2Nt2If\*2 at UV in a mixer. Is there any reason not to use more Dr* though? You get tons of it, and you just need the dust right? It's +1800K. Look in the Materials file for the details of the stats.

The second coil uses infinity directly. It's +1800K more. Technically you can make them at the same time, but the latter costs more obviously.

The texture for the 1st coil is probably ok, but the second is a placeholder until someone decides to make it look like the infinity blocks colorwise, cycling through them.

For some reason the EBF time on the IA is weird, not being what I set it to, does anyone know what's up with that? I tried to check in the remove recipes file, since there's an auto-generated EBF recipe, but nothing. Also, why are the numbers on all the VF recipes so weird, is that related somehow?

Also, if you think something should be changed balance-wise, make sure to mention it. And we may want to wait until after the next update to add this? I dunno.

### CODE REVIEW

**Comment by alphaNOVAircraft** [comment]
Why do they both add anouther 1,8k. 
Currently the last two available coil tiers only add 900k, having two more 1,8k increases seems wierd tbh and also not really necessary. I guess the goal of new coils was to enable a perfect oc for cosmic neutronium. But now you can even get two perfect ocs on cosmic and three on neutronium, which seems a bit unnecessary high. 
Imo giving both a 900k increase would continue the scheme currently inplace for fluxed electrum and awdr. 
You would still be able to get the cosmic neutronium oc with the inf alloy coils.
With infinity coils you could then unlock the second perfect oc, if anyone can supply enough energy to keep an mbf running at max parallel with it xD (2 Beu/t).

**Review by bartimaeusnek — CHANGES_REQUESTED** [review]
I still don't get why we would want to expand the codebase even further here, firstly this change is not needed except for Ultra-High-Tier players, which are def. in WiP parts of the pack, of which you don't need more random content, but rather a planned out Rework, starting with ZPM, secondly, this would mean for each of the addons to add even more GTNH specific logic for everything that uses coils. Therefore i would prefer this to be not merged.

On the technical side, it would have been better to just use the MaterialBuilder Class to create new materials, and keeping whitespaces as is, other than that, from a technical perspective, this looks fine.

**Comment by Prometheus0000** [comment]
About 'expanding the codebase', do you mean putting it in GT5U instead of the coremod? I figured that since I have to make changes to the EBF and pyro anyway for them to use it, it wouldn't matter if I add the code to the GT5U stuff. I can move most of it over to the coremod if people agree I should though.

I don't know of any planned out rework though? Where is it? Who did you discuss it with? Do people other than you even think this is needed or wanted? Where's the ticket? Bot didn't seem to know about this, and thought it was a good idea to add another coil or two. And even if we do rework stuff, you have to have something there to work _with_. Are you talking about the changes to producing power with fusion or nq that have been talked about before? That's just power, not how several tiers work? And how would adding more coils mess up this 'rework' of yours? What would it even entail anyway?

About GTNH specific code, are you saying we're _never_ going to add more coils, simply because we...I don't know, don't want them to add a couple lines? I understand not getting compatibility from Alk, because they haven't released a version in 6+ months, but that doesn't mean you can't spend 5m to add them to the MBF, assuming it works like the EBF. Or accept a PR. Were there any other addons that utilize coils? And it looks like at least 1 coil was added by us already, so what's the problem with adding more? Are we just supposed to never add new content, and only rearrange existing stuff, because that's what it sounds like you're saying, and it's very boring.

> On the technical side, it would have been better to just use the MaterialBuilder Class to create new materials, and keeping whitespaces as is, other than that, from a technical perspective, this looks fine.

I don't know what you mean by this, I put it alongside the rest of them? Was there another place to make materials? Or do you mean creating it in the coremod like I mentioned above? And I changed the whitespaces to align with the rest of the materials above, why is that bad?

> Why do they both add another 1,8k.

For more OCs. I figured more is better. If people want it to be 900K each, that's fine, but I don't know what materials get OC'd from each 900K or not. I'll let other people decide on that. Obviously, if we make UEV a real tier, we would need to adjust stuff, but that can come later if it actually happens.

**Comment by bartimaeusnek** [comment]
> About 'expanding the codebase', do you mean putting it in GT5U instead of the coremod? I figured that since I have to make changes to the EBF and pyro anyway for them to use it, it wouldn't matter if I add the code to the GT5U stuff. I can move most of it over to the coremod if people agree I should though.

You can't move the coils to the core mod at the current way they are implemented, and these two coils would be the last one, one could add with the current EBF implementation.

> I don't know of any planned out rework though? Where is it? Who did you discuss it with? Do people other than you even think this is needed or wanted? Where's the ticket? Bot didn't seem to know about this, and thought it was a good idea to add another coil or two. And even if we do rework stuff, you have to have something there to work with. Are you talking about the changes to producing power with fusion or nq that have been talked about before? That's just power, not how several tiers work? And how would adding more coils mess up this 'rework' of yours? What would it even entail anyway?

I was talking about that we _should consider reworking higher tiers_ instead of just adding content to them with different ideas of balance, ways to progress, etc, coordinate our efforts to provide a good experience.


>I don't know what you mean by this, I put it alongside the rest of them? Was there another place to make materials? Or do you mean creating it in the coremod like I mentioned above? And I changed the whitespaces to align with the rest of the materials above, why is that bad?

I meant you could do it like this:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/e8a8ccfd3406338ebb7a772013ae5c63df475efc/src/main/java/gregtech/api/enums/Materials.java#L632

Which is way more verbose than the current Materials constructor, the Builder Class was specifically designed to be used to create materials in a readable, easy fashion. 

>About GTNH specific code, are you saying we're never going to add more coils, simply because we...I don't know, don't want them to add a couple lines? I understand not getting compatibility from Alk, because they haven't released a version in 6+ months, but that doesn't mean you can't spend 5m to add them to the MBF, assuming it works like the EBF. Or accept a PR. Were there any other addons that utilize coils? And it looks like at least 1 coil was added by us already, so what's the problem with adding more? Are we just supposed to never add new content, and only rearrange existing stuff, because that's what it sounds like you're saying, and it's very boring.

I havent said i wouldnt add compability, its just, i have no idea either where it would influence other stuff. If you check what is using coils and update everything accordingly, the argument of mod compability is invalid, but who would check such a thing? Im not an expert in TecTech nor GT++ and neither Tec nor Alk currently have the time to write compats, so here we'd just have some half-integrated stuff. I don't like the idea of having "general" blocks that work everywhere but in 120000 exceptions.

**Comment by bartimaeusnek** [comment]
EDIT: Not the last 2 one, we got 5 more slots.

**Comment by Prometheus0000** [comment]
> You can't move the coils to the core mod at the current way they are implemented, and these two coils would be the last one, one could add with the current EBF implementation.

I meant stuff like declaring the material, or the mixer recipe or whatnot. You can't really change the block though. I'm not sure if that would mess something up though. I also just noticed GTNH_ExtraMaterials, should I have put it in there instead?

> I was talking about that we should consider reworking higher tiers instead of just adding content to them with different ideas of balance, ways to progress, etc, coordinate our efforts to provide a good experience.

I've only gotten to IV, but if _people that have have gotten to later tiers_ say it needs reworking, then it's probably true, and you/they should open a ticket to discuss it. That said, I don't think anyone has time right now for reworking ZPM-UEV right now, so why not add something purely optional to help out players UHV+, especially since I've already done it? I mean, there was a ticket, you could've been the fun police and said no new coils there if you wanted (and saw it). Or do I need to get permission from you (or someone?) for every new thing added? That's why there was a ticket to begin with, and was discussed in discord too.

> Which is way more verbose than the current Materials constructor, the Builder Class was specifically designed to be used to create materials in a readable, easy fashion.

That looked super hacky, so I thought it was only for materials that didn't play nicely or something. Is there any real difference though? As in, is there anything you can only do that way, otherwise I don't see any point in changing it to use the MaterialBuilder class now.

> I havent said i wouldnt add compability, its just, i have no idea either where it would influence other stuff. If you check what is using coils and update everything accordingly, the argument of mod compability is invalid, but who would check such a thing? Im not an expert in TecTech nor GT++ and neither Tec nor Alk currently have the time to write compats, so here we'd just have some half-integrated stuff. I don't like the idea of having "general" blocks that work everywhere but in 120000 exceptions.

As of right now they're purely optional coils, so even if alk doesn't add anything it wouldn't matter too much. The Zyngen, Volcanus and Utupu are the only GT++ multis that use coils. I did forget the multi-smelter though, how embarrassing, I'll go fix that. And I don't know of any TT multis that use coils (non-fusion ones at least), or I'd make the PR myself later if it wasn't hard. And most of that mod is a mystery anyway, since that's how technus likes it. There aren't that many things that use coils to begin with honestly.

**Comment by GTNH-Colen** [comment]
I see no reason to reject this as the code is already done and it would help players out, bart is right we could use a rework down the road for ZPM and up but we can always purge/repurpose this if that ever occurs.

**Comment by Dream-Master** [comment]
@GTNH-Colen i just need a go that this is done and we can review and merge it.

**Comment by Prometheus0000** [comment]
Bot was saying that the thought that just a mixer recipe was too easy if it involves infinity and suggested a process on discord, any thoughts on that? Also, I think the majority of people wanted it to be 900K each?

**Comment by bartimaeusnek** [comment]
Outdated with Heating Coil Overhaul

**Comment by Prometheus0000** [comment]
Do you mean it would have merger problems since you changed the way the coils work, or that you don't like it and closed it because of that? Please use more words. If it's 1, I would think you would just mention that?

**Pull request closed without merging**
