### PR TITLE
Add infused gold bee.

### PR DESCRIPTION
**Pull request by fluffle**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack#13882 as much as is desired.

I just made up the numbers for things like voltages, comb and centrifuge output chances. Feedback appreciated :-)

### CODE REVIEW

**Comment by Alastors** [comment]
> Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack#13882 as much as is desired.
> 
> I just made up the numbers for things like voltages, comb and centrifuge output chances. Feedback appreciated :-)

why are you adding this to GT for example and not Magic bees as an optional dependency? Infused Gold is Automagy and thusly shouldn't the bee be in Magic Bees?

**Comment by Dream-Master** [comment]
@Alastors all custom bees we add to gt so I see no issue with it.

**Comment by Alastors** [comment]
> @Alastors all custom bees we add to gt so I see no issue with it.

It's not a GT material, not a GT bee, this should be in Magic Bees for the aforementioned reasoning

**Comment by Alastors** [comment]
It's a problem with consistency, magic based bee, throw it in the mod we literally already have for magic bees

**Comment by Alastors** [comment]
It's like the thaumium jar being in Kekztech as its only thaum content, sure it's fine but it just doesn't make sense and it's not consistent

**Comment by Dream-Master** [comment]
@Alastors i guess we have no gt handler in magic bees so it would be a pain add all the stuff for one bee?

**Comment by Alastors** [comment]
> @Alastors i guess we have no gt handler in magic bees so it would be a pain add all the stuff for one bee?

We could just handle it in coremod like the rest of the Magic Bees though?

It genuinely wouldn't be a pain

**Comment by Alastors** [comment]
I mean if it's really considered that much of a pain in the ass, I'll add the optional dependency in Magic Bees itself

But if it's that much of an issue to handle in coremod, I could just make the optional dependency and optional recipes in magic bees, I mean we did that for Thaumic Horizons recently, it's really a non-issue

**Comment by fluffle** [comment]
Hi!

The code is in GT5 for a couple of reasons:

1) Primarily, because I'm unfamiliar with the breadth of the GTNH codebase and simply cargo-culted a previous PR by @Runakai1 to get this off the ground. If you can provide a pointer to where the coremod defines magic bees I can probably move it over.
2) I'm less familiar with the magic side of things -- I did enough Thaumcraft to get the quantum armor, pretty much. My primary motivation for having this bee is to make the infused gold demands of Naq Fuel MkII (8 infused gold per 250mb) more manageable. I envisioned it as a space bee gated by Haumea, which is where I've been strip-mining to meet those needs pre-Space Elevator. Of course, these things are easy to change, and it could easily be Gold + Thaumium Dust (perhaps at HV?) instead. It's all just code at the end of the day :-)

**Comment by fluffle** [comment]
Also I'm not sure the consistency argument stands up when e.g. Mithril, Astral Silver, Quicksilver, Shadow Metal, and Thaumium Dust (and many other magic bees) are defined in GT5.

**Comment by Dream-Master** [comment]
> Also I'm not sure the consistency argument stands up when e.g. Mithril, Astral Silver, Quicksilver, Shadow Metal, and Thaumium Dust (and many other magic bees) are defined in GT5.

thats what i mean. i think add it to gt just fine.

**Review by Runakai1 — APPROVED** [review]

**Review by Dream-Master — APPROVED** [review]

**Comment by Runakai1** [comment]
I was so free to merge this since there is no merging rules defined for non-contributies Nor non-devs as of now

**Pull request merged**
