### PR TITLE
Make the EOH store astral arrays internally

### PR DESCRIPTION
**Pull request by GDCloudstrike**
This PR makes the EOH store astral arrays internally to prevent them from being moved around between EOHs.
They can be extracted by right clicking the controller with a wire cutter, and are saved to item NBT so they dont get voided if you (accidentally) break the controller.
Existing setups should not be affected, as astral arrays have to be in the input bus anyways, so they will just be removed from the bus and added to the internal counter after updating.

### CODE REVIEW

**Comment by HoleFish** [comment]
I would like a EIG-style of UI if possible...

**Comment by GDCloudstrike** [comment]
> I would like a EIG-style of UI if possible...

Yeah a GUI would be better but I unfortunately wasn't able to get it to work. If you or anyone else wants to implement it then feel free to close this PR in favor of the GUI.

**Review by NotAPenguin0 — CHANGES_REQUESTED** [review]
Shouldn't the astral arrays also be saved/loaded to NBT data in `saveNBTData` and `loadNBTData`?

**Comment by Dream-Master** [comment]
@GDCloudstrike

**Review by NotAPenguin0 — APPROVED** [review]

**Pull request merged**
