### PR TITLE
Provide higher extensibility for the structural code of the Primitive Blast Furnace

### PR DESCRIPTION
**Pull request by SafariXiu**
Expand the usability and modifiability of the Primitive Blast Furnace by refactoring its structural code

### CODE REVIEW

**Comment by serenibyss** [comment]
I don't understand the point of this PR, it says it is for extensibility yet all of the functions are protected static, I see no gain here

**Comment by SafariXiu** [comment]
> I don't understand the point of this PR, it says it is for extensibility yet all of the functions are protected static, I see no gain here

**In fact, it might be overly secure, leaving almost no way to modify it. Perhaps ASM could work, but it's not very useful in 1.7.10.**

**Comment by SafariXiu** [comment]
> I don't understand the point of this PR, it says it is for extensibility yet all of the functions are protected static, I see no gain here

To be honest, I'm trying to create a mod to beautify, or perhaps modify, some of the multiblocks in GTNH. We've made some progress so far, but the Primitive Blast Furnace is a big problem. I haven't found any way to modify it through an external mod, whether using Mixin or Reflection.

**Comment by serenibyss** [comment]
The target for this in mixin would be something like `gregtech.common.tileentities.machines.multi.MTEPrimitiveBlastFurnace$1`, since it is accessing an anonymous class. I don't see any need for a change like this for a mixin target, especially since it is already possible

**Comment by serenibyss** [comment]
Some further docs: https://wiki.fabricmc.net/tutorial:mixin_tips#how_to_mixin_inner_classes

**Comment by SafariXiu** [comment]
> The target for this in mixin would be something like `gregtech.common.tileentities.machines.multi.MTEPrimitiveBlastFurnace$1`, since it is accessing an anonymous class. I don't see any need for a change like this for a mixin target, especially since it is already possible

thanks i will try it :）

**Pull request closed without merging**
