### PR TITLE
IC2 Toolbox Support

### PR DESCRIPTION
**Pull request by draknyte1**
Fix GT_Tools not going into the IC2 Toolbox.
image

### CODE REVIEW

**Comment by draknyte1** [comment]
Y'all might wanna add a custom tooltip to the toolbox saying "Can be used to fix multi-maint issues with tools inside"
image
image
image

Soldering Iron works if it's not the shitty NULL one with no charge, also works as NULL one in creative.

**Comment by draknyte1** [comment]
Tools also now only take damage when they actually need fix an issue. Stops ruining a whole toolbox of tools when fixing just a wrench issue.

**Comment by Cinobi** [comment]
Actually.... i love this idea,

**Review by mitchej123 — APPROVED** [review]

**Comment by PaulVisschers** [comment]
Might be cool if we could put fine wire in the tool box as well and have it use that for soldering.

**Pull request merged**
