### PR TITLE
Remove crates

### PR DESCRIPTION
**Pull request by boubou19**
Remove crates from GT5U.

### CODE REVIEW

**Comment by querns** [comment]
Along with this, lootbags will need to be altered slightly. Some lootbags give crates of items (e.g. 16 crates of styrene-butadiene rubber bars.) These would need to either be removed entirely or changed (e.g.: a fluid cell with molten s-b rubber inside, or a 16x wire, or similar.)

**Comment by Caedis** [comment]
Waiting on input from Dream in case anyone sees this

**Comment by Dream-Master** [comment]
@Caedis we can deprecate crates but if we add raw ore storage blocks why not improve crates ?

**Comment by Alastors** [comment]
Deprecating and removing them sounds great, they’re literally so useless

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
