### PR TITLE
Add void protection mode to fluid and ore drillers

### PR DESCRIPTION
**Pull request by miozune**
- Add void protection mode to Oil/Gas/Fluid Drilling Rig and Ore Drilling Plant
- Refactor `GT_ParallelHelper` and move its void protection logic to separated class `VoidProtectionHelper`
- Make multiblock controller set void protection enabled by default if it's allowed

### CODE REVIEW

**Comment by Dream-Master** [comment]
@miozune thanks

**Review by BlueWeabo — COMMENTED** [review]
Thanks for the clean up. After a few reads if the code I couldn't find anything that could break things. Seems like things will function normally again. Also if you want to go through with it. Wouldn't it be better to check the hatches/busses when there is a structure check instead of when we do recipes? Aka a hatch or bus gets added and we check if it's an ME one?

**Comment by miozune** [comment]
While it would contribute to a bit of readability if we achieve that, since `mOutputBusses` and `mOutputHatches` are public we need to check all the multis in addons to make sure they update variables correctly, otherwise it might ignore the existence of ME buses/hatches. I don't want to make another source of bug for now. Also iterating over like <10 hatches won't contribute to lag.

**Review by BlueWeabo — APPROVED** [review]
Alright. Will leave it like this then. Shouldn't be a problem.

**Pull request merged**
