### PR TITLE
use GTNH translocators

### PR DESCRIPTION
**Pull request by bombcar**
This fixes a build error caused by a maven going down and some minor other updates

### CODE REVIEW

**Comment by bombcar** [comment]
recommend this be reviewed and merged before the unify script if possible

**Comment by Dream-Master** [comment]
@bombcar we using now gt master branch. After @SinTh0r4s changes i am not sure if this any longer needed?

**Comment by Dream-Master** [comment]
ok not needed anymore

**Comment by bombcar** [comment]
> ok not needed anymore

The third change is the important one - to use our translocators instead of code chicken’s maven which went down.

**Pull request closed without merging**
