### PR TITLE
Amazon warehouse downtiering

### PR DESCRIPTION
**Pull request by Nockyx**
The Amazon Warehouse Depot Multiblock serves as a Packager/Unpackager option but the current recipes gate it at LuV tier, with an extremelly expensive craft.

That is in no way justified since the multiblock's only real use is to recycle tiny/small dusts from ore processing or lathe recipes.

This PR proposes a downtiering of it to the IV tier, where most general purpose multiblocks are unlocked aswell. And making the recipe reasonably not expensive, since it can in no way be justified.

image

image

### CODE REVIEW

**Comment by Alexdoru** [comment]
I don't think you need that much packaging action at this tier anyways since we removed the tiny/small dusts from ore processing

**Comment by LazyFleshWasTaken** [comment]
It's good to have. Not everything was converted, like chipped and flawed gems, part-ingot parts like bolts and rings, etc. either.

**Comment by IncandescenceSy** [comment]
It's also just kind of silly for the Packager of all things to have its multi gated later than most other multis. Honestly, it should probably be one of the HV or EV ones, certainly not LuV

**Comment by Nockyx** [comment]
> I don't think you need that much packaging action at this tier anyways since we removed the tiny/small dusts from ore processing

well, you also don't really need much packaging throughout the whole game really. Which make it even weirder that it was LuV in the first place

**Comment by Reflex18** [comment]
> I don't think you need that much packaging action at this tier anyways since we removed the tiny/small dusts from ore processing

There are still plenty of tiny dusts/piles with implosion compressor and lathe usage.

**Comment by boubou19** [comment]
Proper fix would be to list the recipes giving small /tiny dusts so we don't need this at all. Given we removed those tiny piles from the ore treatment, you don't really get absurd amounts of tiny piles as you used to get. So what can be the recipes you need to use to generate stupid quantities of small/tiny dusts now?

**Comment by LazyFleshWasTaken** [comment]
> Proper fix would be to list the recipes giving small /tiny dusts so we don't need this at all. Given we removed those tiny piles from the ore treatment, you don't really get absurd amounts of tiny piles as you used to get. So what can be the recipes you need to use to generate stupid quantities of small/tiny dusts now?

some I know off the tp of my head: recycling non-full dusts, like chipped, flawed gems; parts like rings, rods, bolts, screws, tho those are understandably left alone; the ebf graphite recipe; lathing shit; small dusts from lenses from plates; implosion compressor.

**Comment by Dream-Master** [comment]
i would not remove small and tiny piles. we can reduce it get as output in recipes but not remove it interiertly

**Comment by boubou19** [comment]
> > Proper fix would be to list the recipes giving small /tiny dusts so we don't need this at all. Given we removed those tiny piles from the ore treatment, you don't really get absurd amounts of tiny piles as you used to get. So what can be the recipes you need to use to generate stupid quantities of small/tiny dusts now?
> 
> some I know off the tp of my head: recycling non-full dusts, like chipped, flawed gems; parts like rings, rods, bolts, screws, tho those are understandably left alone; the ebf graphite recipe; lathing shit; small dusts from lenses from plates; implosion compressor.

most of those doesn't justify using an amazon warehouse... Like gems you are better engraving them until you can macerate full dusts, metal parts can be recycled via fluid extractor/solidifier instead, which also makes you skip the ebf / vacuum freezer for some, Implosion compressor does not generate thousands dusts/s so it's manageable with a packager or even by hand/active crafting with AE2, small dusts from lathe should only give you such dusts for gems, otherwise you have better alternatives in the game than the late for rods...
I really don't see the need for an amazon warehouse anymore in the game.

**Comment by Nockyx** [comment]
>Like gems you are better engraving them until you can macerate full dusts

This isn't true, since it requires an awful ammount of patterns to make it on demand, or an awful ammount of filtering to let it passive on oreprocessing, and being always slow recipes this is just a full waste of energy and time, so the best solution is always either scrap these tiny gems or macerate.

>small dusts from lathe should only give you such dusts for gems

Yes! But this often sums up to hundreds of thousands, and using ae2 molecular assembler is again, an awful ammount of patterns for something that doesn't need it. Usually bases have a passive Packager on the system or ore proc to passivelly treat all these residue.

I understand the argument for it's removal, but i think any other methods of handling these dusts are terrible, it'd probably end up with people using singleblock packagers instead, which doesn't fit with the current philosophy of removing PA and such. And it could probably use some more possible uses on the future, removing a multi like this doesn't really serve any purpose other than make people change the solution they're using.

The small ammount of packager usage in my opnion is what calls for a downtiering. Since even with it being expensive, it isn't an unused multiblock, most people build at least one throught the game to solve this niche problem and i don't see a problem in that. (+ the name is funny)

**Comment by querns** [comment]
The EEC is another big producer of small and tiny dusts. You need to farm evolved cold blazes for cryotheum and fire beetles for fiery steel in order to progress, and both of these generate tons of tiny and small piles. Ditto for Redcap Sappers, though they aren't as necessary for pack progression.

**Comment by FourIsTheNumber** [comment]
Definitely see no harm in downtiering it. Removing sources of tiny/small dust is a different conversation outside the scope of this

**Comment by GirixK** [comment]
Another argument I'd like to propose
No, of course you don't need the multiblock, but people much prefer to handle multiblocks than singleblocks, and as long as there's *any* demand for it, a multiblock should exist, even if completely unnecessary and overkill 

While it's usefulness is of questionably quantity, it exists, and it should stay if purely to not have to use a singleblock

Also it has a charm, it looks kinda cool if you ask me :D

**Comment by boubou19** [comment]
My concern rn is to get sure it's downtiered because it's useful to downtier it and not because people want to downtier it. So i need to know what major sources of tiny/small dusts there still are in game. So far, except the EEC, nothing warrants the usage of the warehouse.

 To solve the issue of tiny / small dusts, players are supposed to use the packager in combination of an item buffer outputting small dusts by multiple of 4 in the packager and tiny dusts in multiple of 9. When we still had tiny piles on ore treatments, you would generate litteral millions of piles per hour. It was so much even one warehouse usually wasn't enough. In comparison, if now we produce via EECs a few thousands per hour, that's not much, but still too high for my own taste.

Also, one does not need to use EEC at all to progress, but i don't see why we would punish people for using mob loots as a source for cryotheum or fiery steel for instance. 

I approve the downtiering because it is justified.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
