### PR TITLE
Magic super fuel fixes

### PR DESCRIPTION
**Pull request by Reflex18**
Noticed a few recipes that were either unuseable or missing from the super fuel line.

### CODE REVIEW

**Comment by EnderProyects** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/2050

**Comment by Reflex18** [comment]
> #2050

They are only obtainable via dungeon loot which is not at all useable for an industrial line. It only serves as a way to confuse the player and should never of been reinstated into the recipe list in the first place.

**Comment by EnderProyects** [comment]
@Reflex18 McGuffium239 has a recipe, but it doesn´t apear at NEI

**Comment by Reflex18** [comment]
> @Reflex18 McGuffium239 has a recipe, but it doesn´t apear at NEI

Even the link that you posted shows that the fluid having a hidden recipe which i cannot find in either the discord or the wiki is "one of the worst design choices ive seen in modded MC".

As far as i know there is no recipe for it and is only found in dungeon loot.

**Comment by chochem** [comment]
not unusable

**Comment by Reflex18** [comment]
> not unusable

So is it expected that the player has to delve into a dungeon to obtain mcguffin at a decent rate to keep there power generation online?

**Comment by chochem** [comment]
removing recipes does not increase your production of anything. just accept that you were wrong -it happens- and focus on something more productive.

**Comment by Reflex18** [comment]
> removing recipes does not increase your production of anything. just accept that you were wrong -it happens- and focus on something more productive.

Sure, there was also a second part to the pr, could i just remove the mcguffin part.

**Comment by chochem** [comment]
ha. I guess I was wrong in missing that there is a second part XD

**Comment by Reflex18** [comment]
> mcguffium is obtainable. please remove those changes.
> 
> in what sense are the other two recipes 'missing', can you elaborate?

Every other recipe for super magic fuel has two types, an alumentum recipe and a diamond dust recipe except for the coal coke.

The coal coke for some reason only has an alumentum recipe.

**Review by chochem — APPROVED** [review]
fair enough

**Comment by C0bra5** [comment]
> @Reflex18 McGuffium239 Kinda has a recipe, but it doesn´t apear at NEI ( you can obtain it using magic sources that gives you items from the loot pool)

McGuffinium239 is generated in village blacksmith and stronghold crossing chests.

As far as I'm aware, no mod pulls loot from either pool when generating items in a re:
- Loonium only generates generic dungeon loot (and consumes enough mana to make it unviable without an infinite source).
- The refilling chest from witchery only works in the torment dimension and generates generic dungeon loot.
- loot bags from Thaum have custom loot pools they pull from, which do not include the pools in which McGuffinium239 generates form.

Looking at the repos owned by the GTNH org, McGuffinium239 is never used as an output for any recipe https://github.com/search?q=org%3AGTNewHorizons+765+OR+org%3AGTNewHorizons+Guffium&type=code

Unless you or someone else can prove it does generate, it would be fair to assume that McGuffinium239 does not have a recipe and is currently non-renewable.

**Pull request merged**
