### PR TITLE
change centrifuge to electrolyzer

### PR DESCRIPTION
**Pull request by Pxx500**
Fixed some ores having recipe in centrifuge, now it's electrolyzer just like most compounds of the same type

### CODE REVIEW

**Comment by Dream-Master** [comment]
why you change that? i not get any reason for it. Can you explain why you change that. did you change it because of a chemical behavior ?

**Comment by Pxx500** [comment]
> why you change that? i not get any reason for it. Can you explain why you change that. did you change it because of a chemical behavior ?

Yes it's because of chemical behaviour. Also makes more sense since ores are generally electrolyzed and not centrifuged

**Comment by chochem** [comment]
I dont see the point. you are just breaking peoples setup for no upside.

**Comment by Alastors** [comment]
First off, !realism

Second off, Chochom w

Third off, yeah this isn't needed, sure it might be more realistic, but we don't need to be on the absolute cutting edge of realism in video games, and yeah this is going to break a lot of existing setups just for the sake of minimal realism, I don't see the point either

**Comment by Pxx500** [comment]
> I dont see the point. you are just breaking peoples setup for no upside.

The upside is that more ores use electrolyzer which is generally faster (54s -> 10.8s , 5400eu->6480eu for uraninite), also it makes sense that most ores should be electrolyzed since they are chemical compounds. Also allows for greater parallelization because now it will be Macer->Macer->Centr->Electr instead of Macer->Macer->Centr->Centr which takes much longer (centrifuge recipes are longer)

Also I think that it's a good thing that e.g. all ores are electrolyzed so you don't have to check every ore whether it's macerator/centrifuge

**Comment by Dream-Master** [comment]
unifying is a good idea but yea after 2.4.0 we can take a look

**Comment by Pxx500** [comment]
> unifying is a good idea but yea after 2.4.0 we can take a look

sure, should I draft the PR?

**Comment by Dream-Master** [comment]
no taged it its ok

**Comment by boubou19** [comment]
Really i'm sick of getting stuff changed for the sake of it. Here are reasons why it shouldn't be changed:
- changing it because of realism and only because of it doesn't bring anything to the game beside satisfying only a handful of people, which is questionable at best
- everyone loves it when their oreprocessing will clog up just because someone changed the machine to process them for the sake of it.
- @Pxx500 you got told numerous times to stop doing changes just because muh realism, so yeah i just want to close the PR just because you don't listen.

> unifying is a good idea but yea after 2.4.0 we can take a look
If you start to go this road @Dream-Master ,  you really must do all these changes in one version, fixing the same setup over and over because "devs didn't do their jobs properly" will annoy tons of players, and if anything, if you want to mess with oreproc, at least we should introduce new machines to make it interesting. It's a game, electrolyser and centrifuges have exactly the same mechanic, just not the same name, so gameplay wise it's boring to change just for "unifying the recipes" or whatever. Really this PR raises all the red flags for me.

**Pull request closed without merging**
