### PR TITLE
Add flag to add attaching NBT crafting recipe

### PR DESCRIPTION
**Pull request by HoleFish**
Before, if you add a crafting recipe: A+B=A (with NBT `Tag_1`), and put A (with NBT `Tag_2`) and B in the crafting grid, you only get A (with `Tag_1`) and lose `Tag_2`. With the added flag, from the recipe you get A (with `Tag_1` _and_ `Tag_2`), so you dont lose the NBT on input item and successfully attach a new NBT on it.

### CODE REVIEW

**Comment by boubou19** [comment]
@HoleFish you gotta be more expressive about your PR descriptions. What does this fix if it's a bugfix?

**Comment by HoleFish** [comment]
I thought I linked the coremod pr?

**Comment by boubou19** [comment]
PR linked or not, empty descriptions is annoying, especially when the PR is not properly labeled, it's not a fix, you add a new feature, without explaining it.

**Comment by Dream-Master** [comment]
@HoleFish can you explain what it does/fix? Thanks

**Comment by HoleFish** [comment]
well, I'm not good at explaining it. maybe I have to close it and wait until someone makes a ticket for it

**Comment by boubou19** [comment]
you know what you did, even if it's not the greatest explaination, you should be able to explain what you did.

**Comment by Dream-Master** [comment]
@HoleFish is this a way give recipe a choice to dismantle them and keep it stack able ? Before we add a nbt tag to have a reverse recipe to check stuff for disassembler . Downside items not stack anymore .

**Review by boubou19 — APPROVED** [review]

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
