### PR TITLE
2.7 Stargate

### PR DESCRIPTION
**Pull request by serenibyss**
A collaborative effort between @GDCloudstrike, @NotAPenguin0 and myself, with some community feedback from others.

Coremod PR: https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/980
Modpack PR: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/17259
Intergalactic PR: https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/74

## Stargate Ring Block
image
_A slight refresh to include the new tiered material blocks, Dark Matter and Magmatter_

## Stargate Chevron Block
image
_Similar to the Ring Block, but also including some new Godforge casings_

## Stargate Chevron Upgrade
image
_A new take on the original recipe_

## Stargate RF Unit
image
_Why shouldn't stargate use gigachad tokens_

## Ridiculously Large Capacitor
image
_A small re-imagining without a major cost change_

## Stargate OC Unit
image
_A full rework, aligning more in cost and design with the RF Unit_

## Stargate Iris Blade
image
_A simple upgrade to include some new materials_

## Stargate Iris Upgrade
image
_With such a nice recipe, now this will be considered part of gate role requirements_

## Stargate Base Block
image
_You knew astral arrays had to be in there somewhere_

## NEW: Stargate Controller
image
_Bringing back a part of history, no longer requiring the OC Interface directly to dial_

## Stargate Plate
image
_"A nice and simple recipe redesign and rearrangement"_

## Stargate Chevron
image
_Keeping a part of history in the new cost_

## Stargate Frame
image
_Removing the free parts of stargate cost_

## Stargate Crystal Dust
image
_Hope your QFT, Godforge and Waterline are upgraded thoroughly_

## Stargate Core Crystal
image
image
_Requiring a maximized Godforge to cook, along with several exotic Godforge plasmas_

## NEW: Stargate Controller Crystal
image
_Because something in every gate nerf has to make someone mad_

# Additional Changes
## Magmatter Nanite
image
_An addition to Universium Nanite, used only for Stargate (currently)_

## Eye of Harmony
image
_Including Godforge in progression more, as well as increasing the cost of a relatively cheap part of endgame_

## Eye of Harmony Casings (Temporal + Spatial)
image
image
_Continuing to include Godforge in progression_

## Dark Matter Changes
- Dark Matter Block in DTPF now requires 1/2 the Star Fuel
- Dark Matter Block now extracts to 64 Shards

## Mining Drone Changes
UEV+ Mining drones now use T9 plates rather than increasing amounts of T8 plates
image

## UXV Component Changes
All instances of Shirabon in UXV component/block recipes (Motor, Pump, Piston etc., CoAL casing, MK3 space assembler, hull, 4a+ energy/dynamo hatches, etc)
Example:
image
image

### CODE REVIEW

**Comment by Dream-Master** [comment]
@serenibyss so it is cheaper now or more expensive or only different ?

**Comment by NotAPenguin0** [comment]
Much more expensive, and including new materials

**Comment by Dream-Master** [comment]
Ok

**Comment by Connor-Colenso** [comment]
image

**Comment by POPlol333** [comment]
Once again a completely useless balance change, things never change I guess

**Comment by Hungerya1** [comment]
Stargate base should need 4 chevron 4 ring blocks as before instead of 8 chevron blocks

**Comment by N2K2021** [comment]
> Stargate base should need 4 chevron 4 ring blocks as before instead of 8 chevron blocks

It looks pretty good to me but doesnt change much.

**Comment by DylanTaylor1** [comment]
One concern, the Mining Drone MK-XIII (UXV) seems uncraftable at the moment. I had an issue with the datastick in my gate playthrough on 2.6.1 so I went to test it again on Nightly 637 after seeing it being used here.

There was no issue with the datastick, but the AL and AAL could not recognize the recipe. I did some more digging and noticed that NEI only shows one fluid requirement (512kL Drilling Fluid) but the code from GTNH-Intergalactic says it also needs spacetime and universium? I'm not sure exactly what the issue is, but neither recipes work which would make this stargate uncraftable until that is resolved.

https://github.com/GTNewHorizons/GTNH-Intergalactic/blob/60b07ba638f2c9ac37a68345badfa4038d0c5694/src/main/java/com/gtnewhorizons/gtnhintergalactic/recipe/MachineRecipes.java#L768

**Comment by NotAPenguin0** [comment]
Should be fixed in https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/74/commits/34be643459033fe2271b9b8f537ef082f0b8e85a

**Comment by serenibyss** [comment]
Status: missing textures for a few things, and one last balance pass and this should be finished

**Comment by EnderProyects** [comment]
Just saying, but instead of 8 keyboards, shouldnt the Stargate Controller use like 2 keyboards, 2 magical memory, 2 tier 4 server, and 2 creative component bus? hehehe ... just so is more like using a computer :3

**Comment by Hungerya1** [comment]
what about fueling controller?
resim
sgcraft naquadah is out of oredic and uncraftable
resim

**Comment by serenibyss** [comment]
> what about fueling controller?

This isn't necessary since we still use the Stargate RF Unit as a mandatory part of the craft + setup

**Comment by Dream-Master** [comment]
@serenibyss what is the status of this pr?

**Comment by serenibyss** [comment]
Basically done, still waiting on a couple textures

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
Will fix it when I be back home . On the phone fix it not work .

**Review by NotAPenguin0 — APPROVED** [review]

**Comment by Tallyballs** [comment]
I made a GitHub account just to tell you that this is completely deranged

**Comment by NotAPenguin0** [comment]
Oh no. Anyway.

**Comment by Tallyballs** [comment]
I didn't mean it as an insult

**Pull request merged**
