### PR TITLE
Bees balance changes

### PR DESCRIPTION
**Pull request by Runakai1**
This PR aims to make bees better. When comparing Bees and Crops, one can say that Crops are better, most of the time. Sure, Bees have a few nice resources Crops don't have however, most of the time users will use Crops over Bees. 
This is mainly due to 3 Issues:
-Bee breeding is painful and requires more attention than Crops. 
-The purpose of Bee combs are to quadruple ore, whereas crops can generate resources directly.
-Bees have specialty Combs, allowing their combs only to be generated with special environmental conditions, 

To overcome those issues, the following changes have been done:
- The chance to get a bee have been increased. Just slightly, about 1-2% of selected bees that are required until Mutatron.
- The ore quadrupling mechanic has been removed. Now, you put the 4 combs into a LCR with acid to get 4 purified ore or other resource.
- Most of the newly added bees (except sunnarium) produce their ores and combs without the specialty requirement. In the future, I will overhaul the specialty requirement to not block combs from production.
 No one wants to place a lot of apiaries in early game across the whole world, thus no specialty combs.
- A lot of bees got their comb chances increased by about 10 to 20%

The following changes will be added in the future:
- A bee Multiblock to reduce iApiary usage (even though kuba6000 made them TPS friendly)
- New Bee Effects will be added to make them nicer and have better purposes (like warp removal effect etc)
- New Bees will be added and old bees removed 
- Alveary Recipes will use less honey and will be moved to GT5U (Assembler recipes)
- Quests will be overhauled completely

List of added Bees:
Helium, Argon, Xenon, Neon, Krypton, Nitrogen, Oxygen, Hydrogen,
Phosphorus, Mica, Seaweed, Walrus, Infusedaer, InfusedTerra, InfusedOrdo, InfusedPerditio, Fluorine, Bedrockium, Nethershard, Endshard, Caelestis, Unknownwater, Essentia, Glowstone, Sunnarium, Sulfur, Explosive, Jaegermeister

Some bees have been added to make the no rocket + sky block run possible:
-Seaweed (made so that normal GTNH play through won't benefit from it) -> only breedable through mutatron for no rocket + sky block
-Unknown Water (in combination with Seaweed) to progress further than UHV.
-Phosphorus (also very handy for normal progression, makes bees more attractable)
-Mica (the only way to get mica is to disassemble coils)

The (Noble)gas-Bees have been added, since another Fluorine resource is needed. While Oxygen, Hydrogen and Nitrogen seem a bit obsolete, they serve a purpose for early game gas gathering, making them more attractive to early users. They all produce 250l per comb, so it's not better than current methods with Planetary Space Siphon. Additionally, after a restart, the space station unloads and the Siphon won't work anymore. Which makes it annoying to deal with.

Some concerns or questions that may occur:
-Sunnarium bee requires a superconduction coil block, so it's not cheesing the actual fusion reactor recipe. It will still be LuV. This bee was added to overcome sunnarium usage and fusion spam. 
-Bedrockium bee was added for tps instances, making cobble generator a bit redundant. 
- Jaegermeister is supposed to be one of the endgame bees. It requires spacetime frame foundation and deep dark dimension. I want to make an endgame bee line and Jaegermeister seemed like a nice fit for it. 
- Sulfur is a very easy to gather resource, but sulfur combs existed, the bee didn't, which bothered me.
- Nethershard and Endshard exist to make mobfarms in the end redundant, saving tps. Also, it is another method to obtain them, for the painful impure tear, making Thaumcraft more bearable. 

Removed quadruple mechanic:
- Let's be honest. No one needs ore quadrupling in GTNH with auto-mining blocks. That's why this mechanic was removed. Instead, you acidify combs to get their resource. It scales with voltage tier.
ULV Combs need Water,
LV Combs need Sulfuric Acid,
MV Combs need Hydrochloric Acid,
HV Combs need Phosphoric Acid,
everything  above needs Hydrofluoric Acid.
For example:
image

Modified Bees:
- Salty Bee has more salt products. Edible salt doesn't have a purpose, and it was removed. 
- Oil bee produces more oil berries now. To be an early game alternative to oil pumping, making them more attractive.
Non bee related changes:

Other changed things, not realted to bees:
- The salis mundus duplication research also allows crystallizing them back to balance shards in the crucible now:
image
- Fluid regulators now need circuit number 3, to avoid conflicting recipes accidentally crafting fluid regulators.
- Fluid extractor recipes have changed to not be that similar to normal extractor.
image

This is by far the biggest PR of the bee overhaul from me, the other ones will be smaller.

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
I think you've actually managed to address a ton of random misc issues surrounding bees I've found personally in one PR. Nice work. Moving Alveary recipes to the assembler is a nice touch.

**Review by Dream-Master — APPROVED** [review]

**Comment by Waisse** [comment]
>The chance to get a bee have been increased. Just slightly, about 1-2% of selected bees that are required until Mutatron.
Not needed. There's a wide assortment of frames, as well as the electrical simulator and Mutator block to get any species you want, before and after unlocking the Alveary. Never been an issue.

>The ore quadrupling mechanic has been removed. Now, you put the 4 combs into a LCR with acid to get 4 purified ore or other resource.
Considering there are bees that can produce metal nuggets right off the bat or quarters of dusts directly, those bees were indeed stupid to have.

>Most of the newly added bees (except sunnarium) produce their ores and combs without the specialty requirement. In the future, I will overhaul the specialty requirement to not block combs from production.
>No one wants to place a lot of apiaries in early game across the whole world, thus no specialty combs.
The questbook already list all the way to change biomes to make your bees happy. You have also teleportation, so why remove the one feature defining bees? The Alveary can modulate its internal climate you know, but if you're going to remove specialties then this won't even be necessary since you'll just have to breed climate tolerance into your bees LOL. Dum.

>A lot of bees got their comb chances increased by about 10 to 20%
That won't change anything to the core issue that one alveary will only ever be able to produce one result every cycle, that result often being a quarter/ninth of an actual, usable product.

**Comment by Runakai1** [comment]
> > The chance to get a bee have been increased. Just slightly, about 1-2% of selected bees that are required until Mutatron.
> 
> Not needed. There's a wide assortment of frames, as well as the electrical simulator and Mutator block to get any species you want, before and after unlocking the Alveary. Never been an issue.
> 
> > The ore quadrupling mechanic has been removed. Now, you put the 4 combs into a LCR with acid to get 4 purified ore or other resource.
> 
> Considering there are bees that can produce metal nuggets right off the bat or quarters of dusts directly, those bees were indeed stupid to have.
> 
> > Most of the newly added bees (except sunnarium) produce their ores and combs without the specialty requirement. In the future, I will overhaul the specialty requirement to not block combs from production.
> > No one wants to place a lot of apiaries in early game across the whole world, thus no specialty combs.
> 
> The questbook already list all the way to change biomes to make your bees happy. You have also teleportation, so why remove the one feature defining bees? The Alveary can modulate its internal climate you know, but if you're going to remove specialties then this won't even be necessary since you'll just have to breed climate tolerance into your bees LOL. Dum.
> 
> > A lot of bees got their comb chances increased by about 10 to 20%
> 
> That won't change anything to the core issue that one alveary will only ever be able to produce one result every cycle, that result often being a quarter/ninth of an actual, usable product.

Mutator doesn't work as people think. It's not a magic tool to increase chance incredibly high. Was fixed by me. 
GT++ frames need to be rebalanced. They werde added without accounting for what they should do. They are overpowerered and outsource what forestry was meant to do. 
Frames shouldn't be calculated into this balance change. 

I agree, the bees producing grains and nuggets directly are not supposed to exist. I removed them, but they need to exist due to backwards compatibility. The new ore generation mechanic is better than nugget bees, making people switch to them. 

You need the biome for the comb speciality. Not the right temperature and humidity. 

We can easily change the cap of generating one comb max per cycle, but we don't want to. The add-ons and frames from external mods didn't account for forestry's base logic and make production over 100% easily achievable, which should never be the case. This will also be reworked. Mainly by heavily nerfing the GT++ frames and readjusting them. So 100% production can still be reached but just more difficult. 
Other suggestions are welcome :)

**Comment by Waisse** [comment]
>GT++ frames need to be rebalanced

I was talking about the more accessible magic frames which are more than enough for breeding purposes. They cover all my needs.

>You need the biome for the comb speciality. Not the right temperature and humidity.

A biome is a combination of temperature and humidity, it's literally the same thing except a bee only cares about living within a range of those two values, it doesn't give a crap about the name of the biome itself. If a bee wants to live in an icy/arid "biome", the biome in question could literally be whatever as long as the temperature and humidity are within the valid values... which can be modulated (not perfectly) by the Alveary.

>We can easily change the cap of generating one comb max per cycle, but we don't want to.

That's literally the only meaningful change that would positively impact beekeeping, and not any of the things I've been reading so far.

Breeding is a non-issue.
Frames are a non-issue.
Specialties are a non-issue.
Productivity and hard-coded limitations are an issue. Uncap the Alveary and comb production.

**Comment by Runakai1** [comment]
> > GT++ frames need to be rebalanced
> 
> I was talking about the more accessible magic frames which are more than enough for breeding purposes. They cover all my needs.
> 
> > You need the biome for the comb speciality. Not the right temperature and humidity.
> 
> A biome is a combination of temperature and humidity, it's literally the same thing except a bee only cares about living within a range of those two values, it doesn't give a crap about the name of the biome itself. If a bee wants to live in an icy/arid "biome", the biome in question could literally be whatever as long as the temperature and humidity are within the valid values... which can be modulated (not perfectly) by the Alveary.
> 
> > We can easily change the cap of generating one comb max per cycle, but we don't want to.
> 
> That's literally the only meaningful change that would positively impact beekeeping, and not any of the things I've been reading so far.
> 
> Breeding is a non-issue. Frames are a non-issue. Specialties are a non-issue. Productivity and hard-coded limitations are an issue. Uncap the Alveary and comb production.

Thanks for your comments. Unfortunately, you're in the minority with this. I have asked a LOT of other people and justified myself why the changes are needed. While it may not be a problem for you going through the bee hell, it was for a lot of other people. 
Issues need to be addressed still, but this PR is already merged and your needs are still fulfilled. A lot of people got happier and you don't harm from it if you didn't benefit from it at all in the beginning.

**Comment by Waisse** [comment]
Beekeepers are a minority. Telling me I'm a minority within a minority is funny at best, and a bad attempt at undermining my feedback at worst. I do bees. I'm very serious about them. When I say breeding or specialties are a non-issue I mean it. The actual issues are elsewhere and seeing a PR completely sidestep what's truly aggravating is something very obnoxious to digest, especially when I'm told I'm not the targeted demography. If I'm not when who is this PR targeting? Speak up, I'm really intrigued now.

Tell me, what's hard in setting up teleportation or changing biomes when there are quests already listing those things?
What's hard in researching and making chocolate and soul frames to breed and kill bees fast? Heck, you can even repair those frames if you don't wanna craft them ever again. Unlock the alveary and it's even easier, and mandatory since electric apiaries are mode from alveary blocks. The Alveary solves breeding and specialties altogether, I cannot believe for a single second anyone serious about bees has been bothered by low mutation rates when you can combines multiple ways to boost mutation rate to alleviate the low % number. Same deal with specialties. Uncapping the Alveary and comb production is big no no, but completely removing a major mechanic like specialties is okay?? I just can't, sorry. I will still be stuck with a multiblock that will only ever produce one ninth of a ninth of a wither skull, and nothing can be done about it even after breeding a bee with the fastest speed, nocturnal, rain tolerant, cave-dwelling, maximum tolerance in the perfect climate thanks to witchery biome changing potions, and pumped with frames to the max allowed multiplier of 16, because this is what balance is.

**Comment by redmage17** [comment]
TY! This was very much needed. Feel like taking a crack at the alveary coding so we can have  GT version?

**Pull request merged**
