### PR TITLE
Rework inventory logic of crop manager

### PR DESCRIPTION
**Pull request by Caedis**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17136  

Replaces the main loop over inventory slots with a loop over the drops so that drops can be merged into existing slots instead of filling up all of the slots with partial stacks.

### CODE REVIEW

**Comment by Dream-Master** [comment]
this is a fix and not need a freeze tag

**Comment by chochem** [comment]
this freeze isnt about releasing a stable version but about very incompatible changes that boubou wants to make

**Comment by Caedis** [comment]
Gotcha, thought it was an all PR freeze

**Comment by chochem** [comment]
> Gotcha, thought it was an all PR freeze

you were correct

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
