### PR TITLE
Centrifuge Changes

### PR DESCRIPTION
**Pull request by Runakai1**
All of the Centrifuge recipes for bees were a joke. Thus, I kept chances and made it output a full dust instead.

Also, Infinity Catalyst, Cosmic Neutronium and Infinity are properly integrated into their respective tiers with better chances.

+ fixed spelling mistake

Example: 
Infinity comb needed 1.375 seconds in apiary for 1 comb and 1 comb would produce 1 tiny pile with 0.01 chance at UIV Voltage needing 4800 seconds.

Now it needs 1375 seconds for 1 comb but produces 1 full dust with 20% chance at 50 seconds UV

### CODE REVIEW

**Review by BlueWeabo — APPROVED** [review]
All is good, this will only be able to alleviate some off the resource costs, but it won't be able to cover all of the costs for those materials.

**Comment by DianeXD** [comment]
Infinite line bees should remain useless
And I don't think this is expected behavior
magic
They are also not in their respective tiers
I doubt anyone cares to balance

**Comment by Runakai1** [comment]
> Infinite line bees should remain useless And I don't think this is expected behavior magic [ magic ](https://user-images.githubusercontent.com/64360468/187071962-fe42523c-6645-458a-a3bb-7e2c8c63fea9.gif) [ ](https://user-images.githubusercontent.com/64360468/187071962-fe42523c-6645-458a-a3bb-7e2c8c63fea9.gif) They are also not in their respective tiers I doubt anyone cares to balance

No they shouldn't remain useless. 
The gif you sent is a problem with the magic apiary not the pr

**Comment by DianeXD** [comment]
What's wrong with these in uhv?
You will not get better results with iapiary.

**Comment by DianeXD** [comment]
I can still use full level iapiary to get 155combs/96s
This makes crafting recipe a joke

There is no reason for the bees to be infinity ore gen.

**Pull request merged**
