### PR TITLE
Extended GUI fluid manipulation support to GT_MetaTileEntity_BasicTank

### PR DESCRIPTION
**Pull request by Glease**
Example use case: https://discord.com/channels/181078474394566657/401118216228831252/863150051063758878

### CODE REVIEW

**Comment by repo-alt** [comment]
That kind of changes are a bitch to check. It _looks_ ok, but it's so simple to miss an occasional dupe here

**Comment by Glease** [comment]
Most of code is taken from the previous PR verbatim. Since we don't yet have any people reporting dupe I'd assume we are safe with this PR as well.

**Comment by repo-alt** [comment]
Sure, I understand that it is the same code rearranged, it's just that compare/merge interface does not allow to easily check that

**Review by repo-alt — APPROVED** [review]
I guess we may just as well test it ingame.

**Pull request merged**
