### PR TITLE
several fixes:

### PR DESCRIPTION
**Pull request by bartimaeusnek**
-removeal of Axe for base entites @draknyte1 is this okay?
-streamlined single block NaquadahReactor
-fixed basegenerator for naquadagen

Signed-off-by: bartimaeusnek <33183715+bartimaeusnek@users.noreply.github.com>

### CODE REVIEW

**Comment by draknyte1** [comment]
`-removeal of Axe for base entites @draknyte1 is this okay?`
It's identical to what my ASM does, which has been proven to work wondrously. (Broken Texture, but pipes still work 100% and can be picked up with a wrench afaik)

There's a reason I only commented on Naq Gen stuff.
If you want some help, poke me tomorrow and I'll ponder over a better way to implement than what I've already suggested. But please, we all need to avoid God classes, so having a extend b extend c extend d -> m beats one class with 13 split classes of code mixed into one. The logic is simple, if everything that is an instanceof or extends class Y cannot use the function or var, it shouldn't be there, with very little exception.

Cause you'd just subclass more.

**Comment by bartimaeusnek** [comment]
thats actually just a quickfix to get the nq's running again after @richardhendricks 1L fix's commit...

**Comment by Dream-Master** [comment]
merging or not?

**Comment by bartimaeusnek** [comment]
@draknyte1 recheck please.

**Comment by Dream-Master** [comment]
@draknyte1 i push this now.

**Pull request merged**
