### PR TITLE
Fix structurecheck button overlaps

### PR DESCRIPTION
**Pull request by GDCloudstrike**
This PR fixes some gui overlaps with the new structurecheck button. 
The affected multis I found were the dtpf, tpm and all waterline multis.

If there are more, please comment.
image

### CODE REVIEW

**Comment by HoleFish** [comment]
PCB/drillers/backfillers/VMs

**Comment by KTech3020** [comment]
maybe move the button to this area instead of on the side since some machines have no space there (pcb for example)
image

**Comment by GDCloudstrike** [comment]
> maybe move the button to this area instead of on the side since some machines have no space there (pcb for example) image

The issue is that some multis (like mbms) have buttons there as well, so standardisation isnt really doable. 
For the PCB factory I did put the button there as theres space, but for the others I just moved their special buttons up a bit (like with the dtpf).
image
image

**Comment by HoleFish** [comment]
godforge module too

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
