### PR TITLE
Make DD Great Again(Adding Tritanium Ore)

### PR DESCRIPTION
**Pull request by TheEpicGamer274**
Adding Tritanium Ore to reduce fusion spam end game and make it reasonable to get it in large quantities.

### CODE REVIEW

**Review by meepmopper — APPROVED** [review]
seems good (idk java)

**Comment by Alastors** [comment]
> seems good (idk java) (HELP I DIDN'T THINK IT WOULD LET ME DO THIS AND I DON'T KNOW HOW TO DELETE)

lmfaoooo that's new, I didn't know non-members could approve

**Review by GDCloudstrike — APPROVED** [review]
seems fine

**Comment by AtomicGrog** [comment]
Why not in EOH DD as well?

**Pull request merged**
