### PR TITLE
Texturework in GT++

### PR DESCRIPTION
**Pull request by BlueHero233**
- Fix Steam Hatch using LuV casing texture, Cryotheum Cooling Hatch and Pyrotheum Heating Vent also using LuV casing (despite being IV)
hatches

- Fix Advanced Boilers top texture being odd
boilers

- Added different texture for the tiered tanks (ULV - HV) instead of reusing the brewery textures
tanks

- Added discrete controller faces for different multis (request from @jimbno)

### CODE REVIEW

**Comment by chochem** [comment]
some pictures in the PR description would be cool.
(also for upcoming-features I guess)

**Comment by FireWarrior2** [comment]
It will be nice if GT++ centrifuge texture will also be fixed
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15963

**Comment by BlueHero233** [comment]
Will add before and after pictures

**Comment by BlueHero233** [comment]
Fixes
- Moved the brewery, replicator, boxinator and scanner from iconsets to their respective basicmachines folder
- Added discrete textures for turbine casings and the nuclear reactor front
- Better texture for the plate covers gtpp
- Minor nuclear reactor code tweaked

**Comment by Dream-Master** [comment]
@BlueHero233 crops plusplus not work with your changes. How i can fix it ?

**Comment by Dream-Master** [comment]
[crash-2024-08-26_11.40.33-server.txt](https://github.com/user-attachments/files/16747088/crash-2024-08-26_11.40.33-server.txt)

**Comment by BlueHero233** [comment]
> @BlueHero233 crops plusplus not work with your changes. How i can fix it ?

i have to make a PR in cropsplusplus to fix the references, since i moved the overlay textures from iconsets to basicmachines/scanner
i may or may not need to also fix the boxinator replicator and brewery if theyre not native from the gt5u package

**Comment by Dream-Master** [comment]
idk if that is needed but the scanner need it

**Review by FourIsTheNumber — APPROVED** [review]
All looks good to me. I like the tanks ❤️

**Pull request merged**
