### PR TITLE
Add Infinity+ coil recycling

### PR DESCRIPTION
**Pull request by StaffiX**
Adds arc furnace and macerator recycling recipes for the infinity, hypogen and eternal coil.
image
image
image

### CODE REVIEW

**Comment by EnderProyects** [comment]
Usually some recycling recipes gives blocks when materials in ingots are more than nine

**Review by serenibyss — APPROVED** [review]
> Usually some recycling recipes gives blocks when materials in ingots are more than nine

While this is true in some cases, I think we shouldn't enforce this except for cases where using Blocks over Ingots would allow the recipe to output more total material by saving space with Blocks, which is not the case here, so I think this PR looks good as it is. Thanks!

**Comment by chochem** [comment]
> > Usually some recycling recipes gives blocks when materials in ingots are more than nine
> 
> While this is true in some cases, I think we shouldn't enforce this except for cases where using Blocks over Ingots would allow the recipe to output more total material by saving space with Blocks, which is not the case here, so I think this PR looks good as it is. Thanks!

non-autogenerated recipes make for a lot of inconsistencies. also for example no fluid extracting at all. This is a super hacky PR. I will not spend time to rework it, but this is not how recycling should be done.

**Comment by Dream-Master** [comment]
@chochem so how it would be implemented better ?

**Comment by chochem** [comment]
you give the item itemdata.

**Pull request merged**
