### PR TITLE
Removal of the GT Arrows

### PR DESCRIPTION
**Pull request by boubou19**
Complete removal of the GT arrows, so no more clutter about arrows, arrow heads, and as a bonus, skeletons will stop shooting you random GT arrows (oftenly radioactive ones from my own experience) to the players every 16 arrows

closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15509
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12963

### CODE REVIEW

**Comment by Caedis** [comment]
I see my placeholder prefix is getting some use

**Comment by boubou19** [comment]
i encountered a null as prefix usage, so i wonder if we can simply pass null as placeholder, even tho i prefer to use explicit placeholders

**Comment by Caedis** [comment]
> i encountered a null as prefix usage, so i wonder if we can simply pass null as placeholder, even tho i prefer to use explicit placeholders

got an example

**Comment by boubou19** [comment]
here: https://github.com/GTNewHorizons/GT5-Unofficial/blob/c4f0cc309989735aae47e47ae0da8b7a4d080896/src/main/java/gregtech/common/items/GT_MetaGenerated_Item_02.java#L263-L297

**Comment by AbdielKavash** [comment]
Crafting of Offensa (a reagent from Blood Magic) requires Titanium Arrows. Please also adjust this recipe to use something else.

**Comment by Alastors** [comment]
But the thaumcraft endgame metal glitch 😔👆

**Comment by boubou19** [comment]
> Crafting of Offensa (a reagent from Blood Magic) requires Titanium Arrows, and crafting Glass Sacrificial Knife and Dagger requires glass arrowheads. Please also adjust these recipes to use something else.
> 
> Possibly do a ctrl+F for other recipes, those are the only ones I remember, but there might be more.

so far i know this is not fixable in GT5U, will do NHCore once this is merged

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
