### PR TITLE
Backend Rework of the Quantum Computer (QC)

### PR DESCRIPTION
**Pull request by DylanTaylor1**
As it stands, the Quantum Computer has absolutely no progression because the best possible setup is available to the player as soon as they can build their first QC. There is a massive balance issue if an APU from OpenComputers (that takes at most UV circuits to craft) heavily outperforms even a UXV circuit in terms of generating computation. This is incredibly uninteresting and leads to unnecessary machine spam in the later tiers.

This PR accomplishes the following:
- Adjusts the values for ALL rack components to align better with progression
- Adds values for optical circuits and the cooling core which were previously not valid rack components
- Reworks the computation/heat/power equations
- Increases the rate at which racks lose their heat (~5x faster)
- Allows racks to face up/down (QC could still form and function fine, so this is purely visual)
- Cleans up other small bits of the code (ie. if statements for heat < 0 which is not possible)

EDIT: Adjusted wording/images to include the Cooling Core which was added after the initial PR.

A simulator is provided on my GitHub for both the old version and this new version. It is 100% accurate and can effectively test any Quantum Computer setups without having to be in-game.

### NEW VALUES FOR RACK COMPONENTS
In this rework, higher tier circuits not only have a higher base computation, but also a higher heat limit and lower heat constant to allow the QC to overclock and overvolt more which leads to even more computation at the cost of power. See the "Stable Setups" below for the whole story and how these values actually translate to computation/s.

image

Not shown, this PR removes many valid rack components that just had no reason to be used at all and cluttered the code. For example, no player is ever going to use LV circuits in a QC to produce an abysmal 2 computation/s.

### REWORKED EQUATIONS
The OLD equations for computation, heat, and power are provided for reference below. The awkward min-maxing in the computation equation is really hard to read/explain to a player and overvolt only ever needed to follow this linear relationship: `overvolt = 1.5 * overclock - 0.5`. These equations were also never very conducive to higher overclock/overvolt values which means the best setups were those that had these parameters <1 which conveniently saved on power as well.

image

image

image

The NEW equations for computation, heat, and power are provided below. Higher overclock values contribute the most to computation and higher overvolt values contribute the most to heat. Alone, this would encourage the player to make overclock as high as possible and overvolt as low as possible, but there is a penalty in the denominator of the computation equation for large differences between overclock and overvolt. This maintains the unique balancing act between the two parameters. The power equation was also modified because this new implementation encourages higher overclock and overvolt values. At first glance it might appear like the power cost for running a QC would be lower, but higher tier circuits are actually much more expensive to run.

image

image

image

Not shown is how computation packet loss is handled. Previously, if overvolt was >0.80 there was no loss at all, and increasing amount of loss for overvolts <0.80 until everything was dropped for an overvolt <0.7. This PR changes it so that any overvolt above 1.0 will not have any loss and increasing amount of loss for overvolts <1.0 until everything is dropped for an overvolt = 0. The intent is to highly discourage setups with parameters <1 because it is a little too good to have the "best" setup also be the one that saves the most power.

### STABLE SETUPS (PER 24 RACKS)
The current best QC setup uses 2x APU Creative and 2x Advanced Heat Vent to produce 27,456 computation/s with a full 24 racks for just 7.2A of UV. The new best setups (PLURAL) for the QC at different stages of the game are as follows. Both the 1 circuit and 2 circuit variants are provided to show their relationship (very similar in computation, but the more expensive 2 circuit setup requires about half the power). 3 circuit variants are not included because they are just not worth it.

image

The following also shows how circuits within the same tier (ie. opticals) all compare to one another. Only the 1 circuit variants are shown because the relationship is virtually the same for the 2 circuit variants. With these numbers, an optical UEV circuit outperforms a bio UEV circuit as one might expect. Even an optical UHV circuit outperforms a bio UEV circuit albeit just barely and for a much higher power cost. It is unlikely for players to use lower tier circuits if they have access to higher tier ones anyway.

image

In terms of BALANCE, the first best setup that the player can make is with the same components as before (2x APU Creative and 2x Advanced Heat Vents) for 30,312 computation/s. This means UV is approximately the same with these changes. The player then unlocks the Wetware Mainframe shortly thereafter and could choose to upgrade their QC for a very slight boost. In UHV, the player gains access to the Bio Mainframe which offers a 50% increase to the performance of the QC for over 50% more power. In UEV, the player gains access to the Optical Mainframe for practically the same benefit. The player will still need to make multiple QC's as they progress (just fewer).

In UIV, the player unlocks Pico Circuits which can produce just over 100k which means only one full QC is needed per Dyson Swarm Ground Unit. There is even a choice between 1 Pico and 2 Picos depending on if the player wants to save on circuits or power more. This alleviates arguably the worst part about setting up more Dysons, but for a cost. Pico circuits are rather expensive at that stage of the game and requires a minimum of 46.33A of UV power which is more than the 28.80A of UV power needed previously for 4x QC. Lastly, in UMV+ the player can then use Quantum Circuits to have the new best QC in the game which produces approximately 5.50x MORE computation/s than the old best setup. This means only 1/5th of the QC are really needed to research EOH and Stargate parts which previously was some meaningless machine spam.

### CONTINUITY

When updating to these new changes, players with the old best setup will unfortunately find their QC empty IF they were running before. This is because the APU Creative and Advanced Heat Vent both have their heat limits reduced from 10,000. The old overclock and overvolt values of 0.36 and 0.80 would hardly produce any heat or computation, but it's that first tick when loading into an updated world where the QC is above their heat limits that causes them to void. Nothing will explode, however.

Endgame players might even appreciate that they void to save them from taking out the components when upgrading to better setups.

Players with 4x QC filled with creative APUs for their Dysons can also just update their overclock and overvolt values to still reach the 100k minimum without having to break or replace anything, IF they turned them off prior to updating.

### CODE REVIEW

**Comment by chochem** [comment]
I dont like the idea of simplifying the formulas. just makes it more boring.

changes some values might be very appropriate though.

**Comment by chochem** [comment]
ah I think I was wrong, maybe its not simplified, sorry. it sounded like you were complaining about the old one being iterative. but it sounds like the new one is too.

still not quite clear on the new formula. I dont understand why you would want to move the undervolt threshold.

**Comment by chochem** [comment]
one other thing (from dev discussions last year):
this would clearly be a much more serious rework. but the idea in the dev team was to have active cooling options or similar. in particular to achieve 3x/3x oc/ov and similar like you describe. that shouldnt be possible without some special cooling.

**Comment by S4mpsa** [comment]
I think the new formula is much easier to grasp (and graph!) for your average player, which makes the quantum computer a bit more approachable instead of just copying values someone else calculated, so that's a plus.

The tiering is also a welcome addition, although the power usage could be slightly steeper (exponential?), as a 10x increase over 5 tiers might not as well even exist. Otherwise this should make QCs a little more interesting and reduce the spam for research. No comment on Dyson.

If you want to get the cooling core working, I can help with that.

**Comment by DylanTaylor1** [comment]
Here's the relationships between the old and new equations for computation (x-axis is overclock and y-axis is computation for a fixed overvolt value). Unfortunately I don't have access to MatLab to show in 3D, but the idea is the same: The old equation is piecewise linear and honestly a bit of a hack. The new equation is a lot more continuous and thought-out. The actual implementations are both iterative.

image

I increased the overvolt threshold from 0.80 --> 1.0 to avoid situations where going under 1.0 is actually better for computation because that also reduces the power consumed. In my opinion, the player should not get BOTH. It is also called OVERvolt and OVERclock which just makes more sense if their values are intended to be >1.

**Comment by DylanTaylor1** [comment]
Latest Commit adds the Gravisuite cooling core as a valid rack component. The numbers for it are the exact same as the advanced heat vent from above and all the other vents were bumped down accordingly. This means the "Stable Setups" from above are also unchanged other than the fact that it should read cooling core instead of advanced heat vent now. No change to the notes on continuity (old setups are still safe and will not void/explode anything).

The intent of this change was to have a cooling component that is slightly more expensive to craft and stacks to 64.

Thanks Sampsa for helping with this!

**Comment by DylanTaylor1** [comment]
Latest commit fixes the information pop-up from using a portable scanner on a rack. Previously, it would report the heat as a percent out of 10,000 which made no sense and only confused the player. This commit also raises the maximum heat to drop an item if a rack is manually broken (500 --> 2000) which also now aligns with the heat LED's "Low" Status.

This was the last change I promise! :)

**Comment by DylanTaylor1** [comment]
A note on the power cost, mostly in response to Sampsa's comment. I think a lot of end-game players build no more than 32 QC for their research station so I will use that as a baseline.

OLD (32 QC): 878,592k Computation/s at 230.4A of UV
NEW (6 QC): 907,488k Computation/s at 323.8A of UV

Although only 1/5 of the QC are needed to achieve roughly the same amount of Computation/s, there is actually a 40.5% higher power cost in the end and obviously a lot of UXV circuits to craft. Personally, I believe that is a reasonable nerf and most of the power should be going into the research station instead of the QC anyway.

**Comment by Dream-Master** [comment]
@chochem @S4mpsa

**Comment by chochem** [comment]
the balance is hard to judge for me. youll need to speak to the devs that are focussed on high-tier content.

**Comment by Dream-Master** [comment]
@GDCloudstrike

**Comment by Dream-Master** [comment]
@NotAPenguin0

**Comment by NotAPenguin0** [comment]
I like the balance, it adds clear progression to QC setups. Reducing the amount of QCs needed per Dyson is not a big problem I think, the cost is increased and right now it's just tedious spam for no reason.

**Comment by Pxx500** [comment]
I agree with penguin, much better than the current QC implementation and less spam

**Review by FourIsTheNumber — APPROVED** [review]
All looks good code-wise. I'm not qualified to give balance feedback on this pr but penguin and pxx approved.

**Pull request merged**
