### PR TITLE
Rewrite GUIs with ModularUI

### PR DESCRIPTION
**Pull request by miozune**
## What is ModularUI?
ModularUI originates from GregTech Community Edition (GTCE), unofficial 1.12.2 GregTech. It has unique UI system called ModularUI, and it's pretty nice. Then CleanroomMC, part of them are also developing for GregTech CE: Unofficial (GTCEu), ported ModularUI system to standalone library mod, ModularUI (mod name).

## Why we need this?
Minecraft block has spread functionality among different classes, `Block`, `TileEntity`, `Container`, and `GuiContainer`. (We also have `MetaTileEntity`, but offtopic here.) This can result in less readability.
To solve this, ModularUI can bundle GUI code (Container, GuiContainer) to TileEntity (or MetaTileEntity in our case).
```java
public class TestTile extends TileEntity implements ITileWithModularUI {
    @Override
    public ModularWindow createWindow(UIBuildContext buildContext) {
        ModularWindow.Builder builder = ModularWindow.builder(getGUIWidth(), getGUIHeight());
        builder.widget(new ButtonWidget()
            .setOnClick((clickData, widget) -> {
                ...
            })
            .setPos(20, 100)
            .setSize(20, 20));
        return builder.build();
    }
}
```

Also, currently we use `detectAndSendChanges` and `updateProgressBar` to avoid inventing custom packet each time we add GUI, but they have some limitations. And they're not directly bound to TileEntity values, which also leads to less readability.
To solve such issues, ModularUI features auto-synced widgets. Simply pass getter and setter, and it will do the rest.
```java
public ModularWindow createWindow(UIBuildContext buildContext) {
    ...
    builder.widget(new CycleButtonWidget()
        .setLength(3)
        .setGetter(() -> this.buttonValue)
        .setSetter(val -> this.buttonValue = val)
        .addTooltip(0, "State 0")
        .addTooltip(1, "State 1")
        .addTooltip(2, "State 2")
        ...
    }
```

It allows you to make more complex GUI with ease. It has a lot of built-in widgets that can be reused in many places. If you're interested, it has pre-built example block (only available on dev env or when enabled with config), so please check it out.

## Rough plan with ModularUI
1. Backport ModularUI <-- Mostly done except fluid slot (I made `FluidDisplaySlotWidget` which is available only for GT, so maybe I won't work on fluid slot unless someone outside of NH ask me to)
2. Migrate GT code for ModularUI <-- this PR
3. Migrade GT addons' code for ModularUI
4. Enhance UIs <-- future, not in this PR

## My review concerns
- `GT_GUIColorOverride` will be moved to indivisual TEs. I don't fully understand how it works, so please let me know if I'm doing in the wrong way.
- I put large effort for inventing `IDataFollowerWidget` and `DataControllerWidget`, but there still might be room for improvement.
- Since cover data is not synced while not opening cover GUI unless specified by `GT_CoverBehaviorBase#isDataNeededOnClient`, there was some time lag between displaying incorrect "default" data and correct data received from server. To solve this, I added initial cover data sync before cover GUI open. (https://github.com/GTNewHorizons/GT5-Unofficial/pull/1381/commits/c239ca594121418f8288ffa972acbb04784a2313) But I'm not sure if this works in 100% of the cases - if client receives packet of cover GUI open first, the data is not reflected on GUI init. Still not a big issue as client receives correct cover data soon after that, but I'm curious if there's situation where packet order is changed.

## Notable changes in functionality
- Most of the ghost slots automatically get drag-and-drop support.
  - Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11137
- NEI omits some UI parts other than item/fluid slot, and has animating progressbar instead.
- Some progressbars have circular animation e.g. washer, mixer
- Machine title is drawn above main window, with configurable style of tab. No more title overlap.
- `IConfigurationCircuitSupport` machines have dedicated ghost circuit slot instead of having on top of GT icon. Integrated circuit overlay is removed from recipe input slots.
  - Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11537
- Rock Breaker NEI shows programmed circuit too (whereas machines GUI does not get extra slot)
  - Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11063
- Cover window is synced with server. If anyone else is editing cover setting in parallel, those changes are synced to client. If TileEntity attached is broken or cover is removed, window is closed.
- Cover tabs open another window on top of main machine GUI. You can have multiple cover windows opened.
- Numerical text field accepts math expression.
- Fix "Insert analyzed bee to see more info" in iApiary not working
- Sorry resource packs, I broke all the GUIs. But I believe these changes will bring flexibility for future changes, not only to default GUIs but also to resource packs.

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
Might be too late to ask this but it'd be superb to have a setTitle method which can be placed above the top of the UI to prevent it overlapping with slots since this is an issue in so many machines/hatches at present.

**Comment by miozune** [comment]
Oh yes I've been thinking of implementing the exact same thing.

**Comment by miozune** [comment]
Finally it's ready for review. Not only code review but also test play are appreciated.

**Comment by Connor-Colenso** [comment]
Nice to see this, GT has long needed UI work done. Some notes after playing with it for a while:

- I don't think the UI should have an animation when closing as this causes a delay and locks you into the screen.

- Using Modular UI on a Mac and holding CTRL does not work with increasing/decreasing stack size of the diamond example. Shift does work.

- The up or down arrows on the 4th tab inside the expandable "info" tab have overlapping boxes so clicking in the middle of two causes both to get triggered.

- The scroll wheels on the 4th page change from white to dark grey when scrolled too far, I presume this is not intended?

- On the pop out window maybe just leave the x outside of a bordered section in the top left?

- The 1st slot on the first page and the slot on the modular UI pop out window share the same stack, idk if this is intended as it's just an example block but thought I'd make a note of it. It actually causes a dupe bug here because the pop out window is a ghost item and placing an item in it means you can retrieve it from the other slot as a "real" item.

- The pop out window is sticky, if you click on it then let go it will continue to follow the mouse until clicked again. Maybe this is intended but not sure if it's good? Idk.

- Placing the modular UI window over an item slot and right clicking will activate the item slot under it, splitting a stack for example (or incrementing the counter in the example slot with a diamond in it on the first page).

- Placing an item in the first example slot on the first page shows the item and its name, removing it and placing it back again then no longer shows its name unless the item is placed back in the players inventory and moved back to the slot again.

- The text slot should probably be locked to alphanumeric inputs only, it allows unicode inputs such as emojis but cannot render them and leaves an invisible character. Very small nitpick so feel free to ignore.

- The increment counter sometimes momentarily is set to 0 when opening the modular UI block, might be unavoidable due to backend reasons but thought I'd note it.

- Allow the item slots to hold up to a long rather than an int? This may not be possible for other reasons but long should always be preferred from now on imo to prevent future issues.

- The 3x3 slots on the first page can be accessed from the 2nd and 3rd page, place an item in them and click on the CMD block or the "Test Text". Same goes for the first slot next to the diamond. 

- Scrolling down on the 4th page and repeating the above note will cause the scrollbars to no longer work. No idea why this might occur.

- Scrolling sideways on a track pad does not cause the 4th page to scroll sideways, very minor and likely nothing you can do about this but worth noting.

- I'm not 100% sure how but I managed to get the text box to appear on the 4th page. Placing a separate instance of the block caused the same behaviour to occur, as if it is sharing some data here? Something static perhaps? Even starting a new world caused this behaviour to persist.

Screenshot 2022-11-10 at 05 35 33

Will try some more tests later.

**Comment by miozune** [comment]
Example block added by MUI is just a showcase of how widgets look like and roughly work, and functionalities are not expected to work fully. If the bug is applied to all the widgets I'll fix it, but if it's specific to certain widgets with bad usage I might not fix it.

> I don't think the UI should have an animation when closing as this causes a delay and locks you into the screen.

I'll make separated config for open animation and close animation.

> Using Modular UI on a Mac and holding CTRL does not work with increasing/decreasing stack size of the diamond example. Shift does work.

Apparently tooltip is lying. I'll fix it.

> The scroll wheels on the 4th page change from white to dark grey when scrolled too far, I presume this is not intended?

GL moment, I'll fix it.

> On the pop out window maybe just leave the x outside of a bordered section in the top left? It looks a bit thick otherwise imo as the border is most of the graphic.

I'm used to this "Windows style". But here are some more styles I come up with.
<details>




</details>

> The 1st slot on the first page and the slot on the modular UI pop out window share the same stack, idk if this is intended as it's just an example block but thought I'd make a note of it. It actually causes a dupe bug here because the pop out window is a ghost item and placing an item in it means you can retrieve it from the other slot as a "real" item.

See the top of this comment.

> The pop out window is sticky, if you click on it then let go it will continue to follow the mouse until clicked again. Maybe this is intended but not sure if it's good? Idk.

This is drag and drop behavior in a bit non-intuitive way. I'll make it so that it won't drag when mouse is released.

> Placing the modular UI window over an item slot and right clicking will activate the item slot under it, splitting a stack for example (or incrementing the counter in the example slot with a diamond in it on the first page).

I fixed left click but forgot about right click. I'll fix it.

> Placing an item in the first example slot on the first page shows the item and its name, removing it and placing it back again then no longer shows its name unless the item is placed back in the players inventory and moved back to the slot again.

`ChangeableWidget` is marked as experimental, and I didn't use it in GT. Maybe I or CleanroomMC people will fix it someday.

> The text slot should probably be locked to alphanumeric inputs only, it allows unicode inputs such as emojis but cannot render them and leaves an invisible character. Very small nitpick so feel free to ignore.

Text field widgets can have regex patterns for which character to accept.

> The increment counter sometimes momentarily is set to 0 when opening the modular UI block, might be unavoidable due to backend reasons but thought I'd note it.

See the top of this comment.

> Allow the item slots to hold up to a long rather than an int? This may not be possible for other reasons but long should always be preferred from now on imo to prevent future issues.

I'm not sure how AE handles long stacksize in Slot, but I _think_ it needs some work. I'll give it a try later.

> The 3x3 slots on the first page can be accessed from the 2nd and 3rd page, place an item in them and click on the CMD block or the "Test Text". Same goes for the first slot next to the diamond.

I'll fix it.

> Scrolling down on the 4th page and repeating the above note will cause the scrollbars to no longer work. No idea why this might occur.

Cannot reproduce.

> Scrolling sideways on a track pad does not cause the 4th page to scroll sideways, very minor and likely nothing you can do about this but worth noting.

I have a macbook but it doesn't even boot, so it won't be fixed until I take it to Apple support or someone else look at the bug.

> I'm not 100% sure how but I managed to get the text box to appear on the 4th page. Placing a separate instance of the block caused the same behaviour to occur, as if it is sharing some data here? Something static perhaps? Even starting a new world caused this behaviour to persist (in fact even rebooting my client caused this to persist).

4th page does have a text field.

**Comment by Connor-Colenso** [comment]
- [ ] Dragging the pop out circuit selector around causes the machine displayed in the UI to darken. Seems inconsistent.
- [ ] Setting a circuit in the pop out menu and then adjusting the circuit in the slot without closing the external window causes them to get out of sync. Scrolling on the circuit item in the base UI slot does the same.
- [ ] Dragging the window around causes the slot under the window to be highlighted, even know it cannot be selected. (very small nitpick)
- [ ] Resizing the game window resets the position of the pop out window to the centre, perhaps make it maintain a consistent position relative to the ratios of the window?
- [ ] Items held over the pop up window appear below the fake circuit items.
- [ ] Placing an item into the circuit selector slot on the pop out window causes the game to crash.
- [ ] Items can be placed in a slot even know the pop out window is over it.
- [ ] Cannot scroll on the "Current" slot in the pop out selector to change the circuit, unlike the one in the original UI.
- [ ]  If a fluid is in a machines slot, using a cell on the slot puts the fluid into the slot, even know the pop up window is over it.
- [ ] Hovering over "recipes available" with an item in your hand causes no text to show up. Same for the fluid/battery/circuit select/item & fluid output slots/buttons.
- [ ] Clicking the "recipes available" with an item in your hand and backing out again causes the item to become invisible. 

Can't see anything else right now. Nice work, as usual 👍.

**Comment by miozune** [comment]
> Items held over the pop up window appear below the fake circuit items.

This is caused by workaround for items present below floating window overlapping items above. I'm not good at GL, need someone else to properly fix it.

> Cannot scroll on the "Current" slot in the pop out selector to change the circuit, unlike the one in the original UI.

I cannot find such behavior in old GUI?

> Clicking the "recipes available" with an item in your hand and backing out again causes the item to become invisible.

I haven't digged in but sounds like NEI issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11784

**Review by Dream-Master — DISMISSED** [review]

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
Works ingame fine

**Pull request merged**
