### PR TITLE
add back turbine wallsharing

### PR DESCRIPTION
**Pull request by Glease**
This was disabled by me back when I integrated structurelib check due to it making a mess on rendering. Now we have more knowledge on rendering, so why not add it back?

https://user-images.githubusercontent.com/4586901/215273076-832bac8e-f8de-487e-8a15-ce088269e8a3.mp4

For texture pack makers: the old `LARGETURBINE_<XXX><_ACTIVE/_EMPTY/><NUM>` (e.g. `LARGETURBINE_TU_ACTIVE3.png`) is now deprecated. They are now replaced by LARGETURBINE_NEW<_ACTIVE/_EMPTY/><NUM>. These textures will be drawn as overlay over turbine casings, and all turbines will use the same overlay texture. See the textures in this PR for an example on how it should look like. 
Usually, you will want to draw a 24x24 animation at the center a 48x48 canvas, the divide it into 9 16x16 png file. This will be the `_ACTIVE` type of texture. Then you pick the first frame only and save this as the `` type of texture (named LARGETURBINE_NEW1.png). Then you wipe the internal blades and save this as the `_EMPTY` type of texture.

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
Is there a technical reason we can't use the simple renderer to draw a 48x48 image and scale it up rather than 9 16x16? Would be easier to work with and if we want to add colouring to turbines in future, much easier to do.

**Comment by Glease** [comment]
> Is there a technical reason we can't use the simple renderer to draw a 48x48 image and scale it up rather than 9 16x16? Would be easier to work with and if we want to add colouring to turbines in future, much easier to do.

Yes. RenderBlocks.renderFaceXXXXX will not draw a face larger than 1x1 block. Not using that method will cause the animation turn off with hodgepodge animation optimization and I will have to reinvent a shitload of lighting and glColor code that is already in that stupid class.

**Comment by Ethryan** [comment]
You know this will be hell for texture packs right?

**Comment by Glease** [comment]
It's no worse than current animation system.

**Comment by Steelux8** [comment]
Does this apply to all large turbines?

**Review by minecraft7771 — APPROVED** [review]

**Pull request merged**
