### PR TITLE
Fix recipe check after previous PR

### PR DESCRIPTION
**Pull request by miozune**
Follow-up to https://github.com/GTNewHorizons/GT5-Unofficial/pull/2358
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14883

### CODE REVIEW

**Comment by bombcar** [comment]
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14883 but I don't know enough to review it

**Comment by chochem** [comment]
to add to that, this PR fixes almost 20000 recipes. new record?

**Comment by bombcar** [comment]
> to add to that, this PR fixes almost 20000 recipes. new record?

I seem to remember a time where we just yeeted all recipes and didn’t load any (minetweaker went nuts iirc)

**Comment by chochem** [comment]
as this is a follow-up to #2358, why are the maxparallel calculated in isRecipeInputEqual in the first place?
that seems like a pretty bad hack and is the cause of the problems as that function is used to determine collision when adding new recipes.

parallels should not be interfere with things like initial recipe generation.

**Comment by miozune** [comment]
> as this is a follow-up to #2358, why are the maxparallel calculated in isRecipeInputEqual in the first place? that seems like a pretty bad hack and is the cause of the problems as that function is used to determine collision when adding new recipes.
> 
> parallels should not be able to interfere with things like initial recipe generation.

`isRecipeInputEqual` actually does accept parallel as parameter (`amountMultiplier`), so it makes sense to me.

**Review by chochem — APPROVED** [review]
important fix

**Comment by HoleFish** [comment]
Have been waiting for it to be merged for a day. Thanks

**Pull request merged**
