### PR TITLE
Fix a small logic bug in Bartworks' glass

### PR DESCRIPTION
**Pull request by wohaopa**

### CODE REVIEW

**Comment by Pxx500** [comment]
I suppose this fixes the bartworks glass being weird with bio vat?

**Comment by Nxer** [comment]
When sometimes use blueprint to auto build a machine with lot of boro glass and let boroglass under ground may cause this bug.
For example Circuit Assembly Line and put the controller on the ground, and use creative mode auto construct.
Will destroy the save.

**Comment by Pxx500** [comment]
are you sure this is the PR? from what I can see this only changes some rendering stuff

**Comment by Nxer** [comment]
> 

image

yea, it is. Elisis and I got this bug.  https://discord.com/channels/181078474394566657/181078474394566657/1248348410055233698

**Review by Pxx500 — APPROVED** [review]

**Pull request merged**
