### PR TITLE
Add Chemical Bath + Thermal Centrifuge mode to IOF

### PR DESCRIPTION
**Pull request by Nockyx**
Closes [#17067](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17067)

### CODE REVIEW

**Comment by HoleFish** [comment]
have you tested how this mode works with stocking hatch?

**Comment by Nockyx** [comment]
> have you tested how this mode works with stocking hatch?

no, i tested only with normal hatch, i'll test it with stocking too later

**Comment by RecursivePineapple** [comment]
@Nockyx Have you tested this with stocking hatches yet? Not sure if you've gotten around to it since it was frozen for a while.

**Comment by Nockyx** [comment]
tested using both stocking bus and hatches.

behaviour using each of the possible fluids on an ore that can accept both
image

behaviour while having both stocked, it prioritizes the mercury process
image

otherwise the consumption is working as expected and isn't causing a dupe or running with both fluid at once creating extra outputs

**Review by serenibyss — APPROVED** [review]

**Pull request merged**
