### PR TITLE
Galena Reverts and a few OCD Cleanups

### PR DESCRIPTION
**Pull request by MineAnPlay**

### CODE REVIEW

**Comment by Dream-Master** [comment]
I don't merge this. Remove the Galena reverts.

**Comment by MineAnPlay** [comment]
They aren't really reverts since Vanilla GT5u also has these (The Galena changes were just copied over)

**Comment by OneEyeMaker** [comment]
@MineAnPlay 
Firstly you changed rotors's recipe (but it's minor change, which can't break balance).
But now you try to break GT ores.
If you can't play with compound ores, if it is *__too hard for you__* - play something another.
If you want to make GT much simplier - you can try, but *not for this modpack* and *not for main repository* (make your own fork and modify GT as you want).
Don't complain and don't bother people to do it's work.

**Comment by SirAzazel** [comment]
@OneEyeMaker @Dream-Master Dont be stupid, go read official Chemistry Update pull that got merged into [original repo](https://github.com/Blood-Asp/GT5-Unofficial/pull/1170). All @MineAnPlay did - added pull which does ***SAME*** thing official GT5U has.

**Comment by MineAnPlay** [comment]
The game is hard? First of all the changes don't make the game harder... They just make you require more ores so that's just grind/repetitiveness/boredom what ever you want to call it. One of the main reasons the revert was done was because you need a LOT more Silver then Lead. First do game balance then realism and sometimes don't do realism because it sometimes can just add repetitiveness without any reason other then making you do extra process or get less materials from something.

**Comment by SirAzazel** [comment]
Maybe lets also change it so 1 bucket holds 12 milibuckets? you know, realism, 12 liters and everything.

**Comment by Dream-Master** [comment]
The changes was made by Johannes because people not because of him. He like to add it like we have but the main gt fork lobby are thinking different. The gtnh fork have many things different then main gt.

**Comment by SirAzazel** [comment]
dream, play modpack at least once from past year, try how useful lead is. you basically need VERY little of it,
Galena vein has silver in it also, thus Galena will 100% have silver impurities rather than default PbS. galena veins are your main source of silver, like more than 50% of it at least.

**Comment by Dream-Master** [comment]
If someone make me some list compare old recipes and new recipes amouts (including quicksilver washing) we can speak more about facts and can see how many % it's different.  Then we can think about solutions.

**Comment by SirAzazel** [comment]
oh, im sorry, noone will like to help you after you completely ignore their oppinions as people who **ACTUALLY** play. want to see %-ge - play yourself.

**Comment by MineAnPlay** [comment]
If you read there was a reason for the change... You need more Silver then Lead. Simple as that. Why make an ore give 0 Silver unless you Wash it with Mercury but you need Silver in large amounts compared to Lead? It's not a small amount either. Atleast in GTNH the largest use of Lead is Batteries till HV and IC2 Nuclear Reactor and then later on Rockets. While Silver usage rockets up starting from HV. Each MOTOR requires SIX Silver and you make a LOT more Motors then Batteries or Reactors. You also need it for alloys most used one being Electrum. So There is a BIG reason these changes/reverts were done in the first place.

**Comment by Dream-Master** [comment]
You have your position i have mine. Now we need to find a third way where we all can live with it.

**Comment by SirAzazel** [comment]
well you know, best compromise here is easiest to see also. Just nerf silver byproduct twice from original GT5U repo? yes, going to be a lot more annoying than with normal gt5u, but no silver at all is a lot more annoying.

**Comment by Dream-Master** [comment]
In which machines you mean that i can look into it?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/2640b6733233cf46a2f58e4ae6974890a6f70d7c

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/d5d06c0606f9ccf79d3cee07b1e5bbc5cc0852c9

**Pull request closed without merging**
