### PR TITLE
Fixed checking of Filter Casings in Cleanroom

### PR DESCRIPTION
**Pull request by 4gname**
Fixed it
image

### CODE REVIEW

**Comment by repo-alt** [comment]
Looks like the filters are already checked below in line 161 (now 173), why is it not working there?

**Comment by 4gname** [comment]
> Looks like the filters are already checked below in line 161 (now 173), why is it not working there?

only the radius is checked there, not the whole area

**Comment by repo-alt** [comment]
Indeed, that check is within `if (dX == -x || dX == x || dY == 0 || dY == y || dZ == -z || dZ == z) `
Should delete it from there then?

**Comment by 4gname** [comment]
> Indeed, that check is within `if (dX == -x || dX == x || dY == 0 || dY == y || dZ == -z || dZ == z) `
> Should delete it from there then?

Hard to answer, haven't tested this part

**Comment by Dream-Master** [comment]
@4gname is this done? did it need changes?

**Comment by 4gname** [comment]
> @4gname is this done? did it need changes?

@Dream-Master It works. We checked it on the IMPACT.

**Comment by Dream-Master** [comment]
ok

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
