### PR TITLE
fix horibe tps lag on multie smelter

### PR DESCRIPTION
**Pull request by botn365**
up to 36x times time consumtion

### CODE REVIEW

**Review by draknyte1 — COMMENTED** [review]
Did you miss a t on tCurrenParrallel?

**Comment by botn365** [comment]
could you point where the missing T is becous i cant find it

**Comment by repo-alt** [comment]
So, every recipe check will process only one item type? Should be faster indeed.

**Comment by repo-alt** [comment]
On the other hand, with the furnace recipe cache in place, should not be _that_ much faster.

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/315/files#diff-b29bd6c98835ef81698be10c6c8273c1R119

**Comment by botn365** [comment]
curent code does 1 recipe check per item not per item type
so if you have a parrallel of 128 that is 128 recipe checks 
wich with the new code is 1

**Comment by repo-alt** [comment]
Per items stack that is. So if you have input bus with 256 slots then yes.

**Review by repo-alt — APPROVED** [review]

**Pull request merged**
