### PR TITLE
butcher recipe time

### PR DESCRIPTION
**Pull request by POPlol333**
butcher to 5 minutes

### CODE REVIEW

**Review by chochem — APPROVED** [review]

**Review by Connor-Colenso — DISMISSED** [review]
I'm confused why you think this is necessary all of a sudden? Can we get some more info?

**Comment by POPlol333** [comment]
image

**Review by BlueWeabo — APPROVED** [review]
Colen. The revolution has started

**Comment by Dream-Master** [comment]
@POPlol333 @Connor-Colenso @BlueWeabo .
I am not that far in tier but if a recipe was 90+ min and now 5 I want to know why . This discord text is not really much info.

**Comment by POPlol333** [comment]
> @POPlol333 @Connor-Colenso @BlueWeabo . I am not that far in tier but if a recipe was 90+ min and now 5 I want to know why . This discord text is not really much info.

We decided to butcher controller recipe because they were way too long for no reason. So we agreed in #github-discussion on a 5 minutes basis.

**Pull request merged**
