### PR TITLE
Add higher tier parts

### PR DESCRIPTION
**Pull request by Prometheus0000**
Specifically, UIV, UMV, UXV, OpV, MAX.
There's no recipes, because they're temp, and may not ever end up getting them, but I feel it's better to have them just in case, and so we can use them with obama, whenever that finishes. They just reuse the UEV icons.

- Also did some editing of the parts/covers text. For example, RAs actually have a speed, the same as conveyors.
- ~~The rotors aren't really being used in the intended way, so I added a bunch of notes. I'd have to PR other repos (coremod, TT) to fix that, and I'd like the rotor to be used to be the same, so there needs to be a discussion.~~ They're used a different way, so I'm reverting that part back.
- ~~I'm not sure if we need higher tier covers, or if they'd cause lag. They can just not be added as covers, like here. We might actually want to remove RA cover functionality, since it's all the same past IV. I don't know if there's any purpose to higher tier FRs either. I'm not sure what you'd be regulating.~~
- Removed LuV+ RA cover functionality, as they're all the same. They become invisible, but you can still get them off with a crowbar. Non-covers are specified with text.

### CODE REVIEW

**Comment by GlodBlock** [comment]
have you solved the crash problem with gt++

**Comment by Prometheus0000** [comment]
I already said I did a long time ago in discord?

**Comment by GlodBlock** [comment]
ah my bad, didn't see it

**Comment by Prometheus0000** [comment]
GT++ is so friggin weird.

**Review by Dream-Master — APPROVED** [review]
Looks ok for me. Need to check ingame

**Review by GTNH-Colen — APPROVED** [review]
Would be better to have proper colours for these tiers but for now this will do as a placeholder.

**Pull request merged**
