### PR TITLE
Fix z ordering for stack size in `Stocking Input`

### PR DESCRIPTION
**Pull request by Laiff**

### CODE REVIEW

**Review by OneEyeMaker — APPROVED** [review]

**Comment by bpwhelan** [comment]
I assume this works in SP, but breaks SMP: NoClassDefFound when attempting to open the gui. pulling ItemRenderHook into the Client-only method fixes the problem.

**Comment by Dream-Master** [comment]
@Laiff

**Comment by Dream-Master** [comment]
> I assume this works in SP, but breaks SMP: NoClassDefFound when attempting to open the gui. pulling ItemRenderHook into the Client-only method fixes the problem.

If that fix it why not make a pr and we can check the code ?

**Comment by bpwhelan** [comment]
> > I assume this works in SP, but breaks SMP: NoClassDefFound when attempting to open the gui. pulling ItemRenderHook into the Client-only method fixes the problem.
> 
> If that fix it why not make a pr and we can check the code ?

You are right, I will do that if I have time later tonight, but havent read anything regarding contributing and didnt have time to branch/fork.

**Pull request merged**
