### PR TITLE
Godforge afterparty

### PR DESCRIPTION
**Pull request by GDCloudstrike**
We're back with even more godforge fixes, yay 

Unresolved issues:
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17615
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17702

Resolved issues:
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17581
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17578
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17661

Sister PRs:
- [x] https://github.com/GTNewHorizons/NotEnoughItems/pull/544
- [x] https://github.com/GTNewHorizons/ModularUI/pull/83
- [x] https://github.com/GTNewHorizons/ModularUI/pull/84

### CODE REVIEW

**Comment by serenibyss** [comment]
Linking https://github.com/GTNewHorizons/NotEnoughItems/pull/544 (Add Helioflare Power Forge to NEI smelting catalysts) for visibility

**Comment by miaowwwwww** [comment]
maxBatteryDiscount = 1 - (1 - Math.pow(1.05, -0.01 * godforge.getMaxBatteryCharge())) / 20;    
image
-0.01 should be -0.05 in the code?

**Comment by serenibyss** [comment]
Linking https://github.com/GTNewHorizons/ModularUI/pull/84 (fix for manual insertion window held stack rendering above the inventory slots) for visibility

**Comment by serenibyss** [comment]
Above commits reverted due to issues with them, will address in next PR

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
