### PR TITLE
Allow Multi Smelter to parallel diff. item types

### PR DESCRIPTION
**Pull request by xSkewer**

### CODE REVIEW

**Review by GlodBlock — CHANGES_REQUESTED** [review]
the different items parallel is removed for tps issue. https://github.com/GTNewHorizons/GT5-Unofficial/commit/68dd34753ccf0d8d646a57e5384122234359cf1c
is it fixed now?

**Comment by Sphyix** [comment]
if it's fixed, can the same thing be done for the mega ebf and the mega vacuum?

**Comment by xSkewer** [comment]
I'm not sure if it's possible to add multiple type parallel for those since the recipes all have different times/voltages. It works for the multi smelter because every smelting recipe has the same time and voltage.

**Comment by xSkewer** [comment]
I'll wait for another opinion but I did a bit of testing in creative with and without the change and it doesn't seem to cause any more lag than it used to. I tried to follow the existing code's logic as much as I could for this change.

**Review by Dream-Master — APPROVED** [review]

**Review by eigenraven — APPROVED** [review]
Better than the previous code which checked many times for each itemstack

**Comment by boubou19** [comment]
might also be because of some optimizations done to the furnace recipe map itself.

**Pull request merged**
