### PR TITLE
Reworked Fluid Shaper Parallels, Tooltip Cleanup, Structure Change

### PR DESCRIPTION
**Pull request by Ruling-0**
Reworked the formula slightly so that a min-width solidifier is usable with actual parallels and not a flat 4. The old formula was 4 + (w * 3) * V, where w is the number of width increments (0-6, total width 9-33) and V is the voltage tier. The new formula is (2 + w * 3) * V. Old vs new parallel counts:

image

Obviously, I balanced around the max-width value since that's generally how they were built. The goal is mainly to allow for using a shorter one in a line that needs just a bit of solidifying (like platline) while not impacting the existing balance of using it for autocrafting (in my experience, always full width).

To reflect this change, and how the structure check has always worked, I've adjusted the tooltip. It reflects the new parallel formula, the proper minimum width, and I removed unneeded capitalizations which are not mirrored on most other multis. I also removed the check for a maintenance hatch in structure check, since this is apparently non-standard and I didn't like that it made projector not print "This multi is complete" when used with gt_no_hatch.
image
image

Finally, and this is the actual breaking change - I made a slight update to the structure. The shape is the same, but I made the back part of the middle symmetrical with the front. This is more visually appealing, and I've seen this opinion reflected by others on the discord. The unroofed glass just stood out as a bit unpolished. The actual shape of the multi is unchanged - this should be a very quick fix for most beta worlds.

Before:
image
image

After:
image
image

### CODE REVIEW

**Comment by NotAPenguin0** [comment]
I think a starting parallel of 84 is way too strong when compared to current multiblocks for fluid solidifying, starting around 20 and ramping up quickly seems better.

**Comment by FourIsTheNumber** [comment]
Agreed, I would expect base parallels for low width to be closer to current LPF values.

**Comment by Ruling-0** [comment]
As mentioned on the discord, there are 3 formulas I've come up with so far

- 2 * V + 3 * w * V, buff to high width vs live, similar scaling per width (+26 for MAX+1 full-width)
- 6 * V + 2 * w * V, high initial with less scaling, roughly equal to current max (what's in the PR)
- 2.5 * (w+1) * V, decimals, nerf at higher widths (-12 for MAX+1 full-width)

Table of formula 1 courtesy of Staffish: https://cdn.discordapp.com/attachments/401118216228831252/1307831246617055423/image.png?ex=673bbc43&is=673a6ac3&hm=c729444b667131e27c865ac78c9f9c0f2b428c452775a5f71160baf2a9d3644e&

**Comment by Ruling-0** [comment]
Changed formula and updated main post.

**Review by TheEpicGamer274 — APPROVED** [review]
Looks fine to me, other opinions would be appreciated regarding parallel

**Pull request merged**
