### PR TITLE
allow pulling items from input bus

### PR DESCRIPTION
**Pull request by botn365**
for #6498

### CODE REVIEW

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6498
I don't remember there being agreement on adding this though

**Comment by botn365** [comment]
and i dont remember a agrement to not add it
i just made the code change and put it as a pull request
so if dream doesnt want it he can just close it

**Comment by Dream-Master** [comment]
i like the idea to pulling it out @botn365 are you sure no cells or other fluids items get voided in this process ?

**Comment by botn365** [comment]
im 100% sure this will not void anything

**Pull request merged**
