### PR TITLE
Make pipes aware of translocators & tinker construct faucets so they can connect

### PR DESCRIPTION
**Pull request by mitchej123**

### CODE REVIEW

**Comment by mitchej123** [comment]
Item Translocator:


Fluid Translocator:


TCon Faucet:

**Comment by mitchej123** [comment]
Should address the following issues:

https://github.com/GTNewHorizons/NewHorizons/issues/2410

https://github.com/GTNewHorizons/NewHorizons/issues/2405

**Comment by mitchej123** [comment]
@Dream-Master

**Comment by Dream-Master** [comment]
Ok cool and thanks @mitchej123

**Pull request merged**
