### PR TITLE
Turbine Rework Beyond Optimal Flow

### PR DESCRIPTION
**Pull request by Steelux8**
- Changed the tooltip of Turbine items to add more data and clarify some values: it now shows all types of optimal flow rates, EU/t values and the new overflow tier;
- Changed the math for the EU/t value above the optimal flow. Before this change, efficiency drops so quickly that EU/t will never raise above that of optimal flow, but with this change, higher EU/t values are possible, with efficiency losses;

image

Currently, all multiblock turbines have an optimal flow, where they reach max efficiency, and a corresponding EU/t output at that flow. Any increase in fuel reduces the EU/t, because of an extreme efficiency loss. I have changed the math so that this isn't the case, and the efficiency curve is different for each type of turbine. 

In terms of being good at maintaining efficiency beyond optimal flow, the types are sorted as Plasma > Gas > SH Steam > Steam, with plasma retaining efficiency very well, and steam doing it poorly.

<details>
  <summary>Visual Graphs</summary>
 
  image
  image
  image
  image
</details>

The graphs above show the amount of power produced, in EU/t, on the y-axis, based on the fuel input, on the x-axis, assuming an optimal flow of 100 L/t and a fuel worth 1 EU/L.

The maximum flow rate is now limited to the new highest EU/t, for each situation.

### CODE REVIEW

**Comment by leagris** [comment]
Voiding fluid in input breaks closed-loop recycling of distilled water to steam.

**Comment by Steelux8** [comment]
> Voiding fluid in input breaks closed-loop recycling of distilled water to steam.

The voiding only happens when a turbine switches from disabled state to enabled state. From then one, it will never void the input unless it's disabled again. To compensate for this, only a small buffer of distilled water is required,

**Comment by leagris** [comment]
> > Voiding fluid in input breaks closed-loop recycling of distilled water to steam.
> 
> The voiding only happens when a turbine switches from disabled state to enabled state. From then on, it will never void the input unless it's disabled again. To compensate for this, only a small buffer of distilled water is required,

Then, instead of voiding, return the corresponding distilled water amount into the output hatch so it does not loose anything.

**Comment by Steelux8** [comment]
Turns out the code already converted the steam to distilled water when "voiding". However, I still had a turbine explode when relogging into my dev environment, so I will have to do this in a different way.

**Comment by Steelux8** [comment]
I undid the input voiding change, and made it so the EU/t doesn't exceed what the dynamo hatch can output, preventing the explosion altogether. The fuel consumption and fluid output are unchanged, and should work as usual.

**Pull request merged**
