### PR TITLE
Oredict support for assline

### PR DESCRIPTION
**Pull request by Antifluxfield**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Technus need help here
@Antifluxfield thanks for add it to GTNH

**Comment by Dream-Master** [comment]
@Antifluxfield seems not to working in nei. It shows only one circuit and not switching.

**Comment by Dream-Master** [comment]
@Antifluxfield works Thanks

**Comment by richardhendricks** [comment]
Really? Assline? :D

**Comment by Dream-Master** [comment]
yes realy

**Pull request merged**
