### PR TITLE
make super/quantum tank/chest keep its contents when harvested

### PR DESCRIPTION
**Pull request by GlodBlock**

### CODE REVIEW

**Comment by draknyte1** [comment]
Shouldn't using `setItemNBT()` alone work fine?

I believe since Dream told me ages ago that my tanks shouldn't keep their contents in GTNH (They do otherwise), it's probably undesired behaviour. Quantum stuff is high capacity, but unmovable. It's kind of the trade-off.

**Comment by GlodBlock** [comment]
> Shouldn't using `setItemNBT()` alone work fine?
> 
> I believe since Dream told me ages ago that my tanks shouldn't keep their contents in GTNH (They do otherwise), it's probably undesired behaviour. Quantum stuff is high capacity, but unmovable. It's kind of the trade-off.

it has some weird problem when i try to use `setItemNBT()`, the items in three slots will get messed up.

@Dream-Master are quantum tanks/chests too op when they become moveable? if so, is it ok only to make super tank/chest moveable.

**Comment by Dream-Master** [comment]
i think it is ok we have this quantum chest or how it called can hold all items when disamantle.

**Comment by GTNH-Afx237v7** [comment]
Why is that OP? You can move drawers/barrels with a dolly or a bedrockium drum with a pickaxe. All it does is save you from tedious cell filling, and filling the tank back up once you have moved it. I would welcome the ability that GT tanks/chests keep their inventory when broken.

**Comment by ArtherCasan** [comment]
If we can make it moveable. We should add many debuff when carry it by particular tool and take only one tank/chest at a time.

**Comment by GlodBlock** [comment]
cuz i think they are pretty advanced-tech stuff, making them movable makes sense.

**Comment by vovaksenov** [comment]
They fit a lot inside and therefore would be unbalanced without some kind of a trade-off. As of now, that is they can not be moved. If the suggested change is to be implemented, it would only be fair if an alternative restriction is suggested.

**Comment by boubou19** [comment]
At least make it like the dolly: give the player slowness while carrying the non empty chest/tank in the inv

**Comment by repo-alt** [comment]
(10 minute slowness after even thinking about moving that amount of fluid)

**Comment by GlodBlock** [comment]
what about this one @Dream-Master 
image

**Review by Dream-Master — APPROVED** [review]

**Comment by iouter** [comment]
10min is too long. since it can be refreshed at any time, 5s is enough.

**Pull request merged**
