### PR TITLE
fix item stuck

### PR DESCRIPTION
**Pull request by GlodBlock**
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9338

### CODE REVIEW

**Review by Glease — COMMENTED** [review]
There is honestly no reason to check for stack size whatsoever. just `mDisableMultiStack || areStackEqual(...)` should be sufficient, but this can be merged as is.

**Comment by GlodBlock** [comment]
> There is honestly no reason to check for stack size whatsoever. just `mDisableMultiStack || areStackEqual(...)` should be sufficient, but this can be merged as is.

no, the size check is necessary. otherwise you will get this:
image

**Comment by Glease** [comment]
Ah I made a mistake. It should be `&&` instead of `||`.
```java
    @Override
    public boolean allowPutStack(IGregTechTileEntity aBaseMetaTileEntity, int aIndex, byte aSide, ItemStack aStack) {
        if (aSide == mMainFacing || aIndex < getInputSlot() || aIndex >= getInputSlot() + mInputSlotCount || (!mAllowInputFromOutputSide && aSide == aBaseMetaTileEntity.getFrontFacing()))
            return false;
        for (int i = getInputSlot(), j = i + mInputSlotCount; i < j; i++)
            if (mDisableMultiStack && GT_Utility.areStacksEqual(GT_OreDictUnificator.get(aStack), mInventory[i])) return i == aIndex;
        return mDisableFilter || allowPutStackValidated(aBaseMetaTileEntity, aIndex, aSide, aStack);
    }
```

**Comment by GlodBlock** [comment]
still have the same result, items won't stuck-up after removing the size check

**Review by Glease — APPROVED** [review]

**Pull request merged**
