### PR TITLE
Add config to spray can

### PR DESCRIPTION
**Pull request by HoleFish**
Add config to change the durability of spray can.

### CODE REVIEW

**Review by Dream-Master — APPROVED** [review]
@HoleFish what config value be good for GTNH?

**Comment by Caedis** [comment]
@Dream-Master default to how it is now

**Comment by Dream-Master** [comment]
yes ik but what was the intention about it? thtas why i ask what are a better value than 512 ?

**Comment by Caedis** [comment]
Why did you merge if you didnt know the intention?

**Comment by Dream-Master** [comment]
i know the intention but i ask what value we should use ? if 512 was ok why it was put to cfg? i approved it because it looks ok and i want to ask what value we should use instead if there any.

**Comment by HoleFish** [comment]
this is an option for players who dont want to fill the can many times when painting laser pipes. personally I think default value 512 is good enough yeah.

**Comment by Dream-Master** [comment]
> this is an option for players who dont want to fill the can many times when painting laser pipes. personally I think default value 512 is good enough yeah.

ok

**Comment by mitchej123** [comment]
I like config options.

**Comment by Dream-Master** [comment]
> I like config options.

Me too, but I was curious about the intention

**Comment by mitchej123** [comment]
to add a config 🧌

**Pull request merged**
