### PR TITLE
Adds Tin Alloy mixer recipe

### PR DESCRIPTION
**Pull request by LazyFleshWasTaken**
closes [#18070](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18070) if added.

### CODE REVIEW

**Comment by Dream-Master** [comment]
If it not override other recipe I see no issue to add it now.

**Comment by Nockyx** [comment]
I don't like all alloy smelter recipes receiving mixer counterparts because this makes the alloy smelter multiblock increasingly underused.

**Comment by Dream-Master** [comment]
Sure if it is a shortcut or make other recipes obsolete we need discuss if it is necessary to add

**Comment by LazyFleshWasTaken** [comment]
> I don't like all alloy smelter recipes receiving mixer counterparts because this makes the alloy smelter multiblock increasingly underused.

Tin alloy ingots are still needed for tin alloy stuff for goodgen. This just makes it a mixer step instead of a macerator step.

**Review by serenibyss — APPROVED** [review]
> I don't like all alloy smelter recipes receiving mixer counterparts because this makes the alloy smelter multiblock increasingly underused.

I agree with the sentiment, but this recipe is very low impact for alloy smelter, and just provides a nicer way to make goodgen alloys, so I see no issue with it. I'll leave it open for a second review, if anyone objects

**Comment by Dream-Master** [comment]
Lets add it

**Pull request merged**
