### PR TITLE
Fix broken assline (for Colen's ass uwu)

### PR DESCRIPTION
**Pull request by bombcar**

### CODE REVIEW

**Review by Glease — CHANGES_REQUESTED** [review]
WTF why you want a 17 slices assline?

**Comment by mitchej123** [comment]
See the title.  Apparently this used to work so Colen built them.  :rofl:

**Comment by boubou19** [comment]
@GTNH-Colen i'm curious to know what recipe is using fully the 16 slots of the assline

**Comment by GTNH-Colen** [comment]
> WTF why you want a 17 slices assline?

@Glease because the gui has 16 slots and you need 1 output. So 17 total length.

This used to work, after the update all 18 of my assembly lines stopped functioning because of this change. No recipe uses it yet, but it was the originally intended way and fits with what the gui shows (4x4, ie 16 inputs).

It's an easy fix and changes it back to how it used to work, I don't see any issue.

**Comment by Glease** [comment]
Assembly line is never intended to have 16th input. Period.

**Comment by GTNH-Colen** [comment]
> Assembly line is never intended to have 16th input. Period.

It always worked like this until it was broken by porting it to structurelib. The GUI literally shows the slot!?

**Comment by YannickMG** [comment]
The implementation should probably be whatever is most intuitive to players.

**Comment by GTNH-Colen** [comment]
> The implementation should probably be whatever is most intuitive to players.

Which logically is 16 inputs, exactly as the gui shows.

**Comment by bombcar** [comment]
We could take it to vote or I could implement a config option brokenAssline=true or soemthing

**Comment by GTNH-Colen** [comment]
Taking a vote over fixing a broken multiblock is the height of GTNH bureaucracy. I love it.

**Comment by boubou19** [comment]
NEI is displaying 16 input slots for items. So 17 slices should be allowed if we want the most intuitive for the players. Now because we don't allow the vertical asslines, we are crossing chunks, and that can cause weird things if you aren't properly chunkloading the chunks the assline is in. To give an idea, i have several asslines crossing 4 chunk boundaries, they work fine (on thermos!)

We have to decide if we want to doom the 16th item slot in the assline, making potentially less room for future pricey items, or if we decide to allow it for now despite it has no use yet. The PR shows how trivial it is to make the change.

**Comment by GTNH-Colen** [comment]
> Now because we don't allow the vertical asslines

Really dislike this theme of telling users what is aesthetically appropriate for their bases, it's a sandbox game, let them choose. 

We actually went out of our way to remove an already done feature because it "upset people" that others wanted upside down asslines. Literally who cares, it's a game where people live in cobble and dirt huts until UEV and this is what we're spending time on...? It has absolutely 0 bearing on balance, it's purely a visual choice that 99% of users won't use anyways.

**Comment by bombcar** [comment]
There’s two issues here - what can we programmatically allow as good defaults, what we want to enforce on the officials, and off by one errors. 

Config options maybe a good compromise but while I agree an upside down DT makes no sense either thematically or ingame, allowing upside down EBFs and forbidding vertical asslines “because we’re a serious pack” seems a bit far. 

There is some truth to if we ALLOW 16 slot asslines someone will someday ADD a 16 slot assline recipe and the we’re forcing across chunks unless we allow vertical.

**Comment by GTNH-Colen** [comment]
Multiblocks crossing chunks is really not as big of an issue as some people have in mind. Most of mine cross chunks and it has never produced issues.

**Review by GTNH-Colen — APPROVED** [review]
Based and fixed.

**Comment by boubou19** [comment]
i thought we decided to exclude officials from any balance decision already? who cares if colen builds his multis upside down in his garden dim?

What purpose config options would serve in that case? if we allow weird multi rotations we don't force people to do them nor stare at them for hours if encountered on a server. config options for that seems extra work for no gain.

But you do point an issue: it is effectively weird that we can put an ebf upside down but we can't make side ways asslines. If i had to chose i'd trade upside down ebf which makes no sense at all given you melt materials in it, so one could argue that thematically gravity is a thing, while it wouldn't really matter in asslines given the robot arms in the crafts. We need a bit of consistency here

**Comment by GTNH-Colen** [comment]
I just don't see why any of it matters, I understand irl an upside down distillery tower makes no sense but it's a meme'd to death modpack in a literal sandbox game. Let the player make the choice for themselves, they don't need us nitpicking how they should play when it's purely visual.

If the user wants to have a normal distillery tower because it matches their base/build then do so, if they want a base where every multiblock is upside down then let them? Who does it hurt?

**Comment by bombcar** [comment]
> Who does it hurt?

Feedthememes might laugh at us.

**Review by Dream-Master — CHANGES_REQUESTED** [review]
it was never desinged to be longer than 16 Blocks. Build over chunckboarders isnt the best idea. I am against this change.

**Comment by GTNH-Colen** [comment]
This is the way it always worked and was intended to work, the gui literally has 16 input and 1 output for a reason.

Screenshot 2022-01-03 at 20 27 34

Why is this controversial???? It's a fix?

**Comment by mitchej123** [comment]
Let's remove the last slot in the GUI to match what was expected.  It's not a fix, it's replicating previous broken behavior.  

Please go ask the person who implemented it if it was intended to act that way, because we only have 15 length recipes.... It's clearly not intended by Dream and the other devs.

**Comment by boubou19** [comment]
like this
image

**Comment by GTNH-Colen** [comment]
> like this image

That looks really clunky, I don't get why we would go out of our way to remove established behaviour and edit a gui to look weird when we can just change 1 number and it'd work as it has for years with no side effects.

**Comment by boubou19** [comment]
anyways, no need to continue the discussion further, Dream has spoken. It is not intended, at least in GTNH

**Comment by GTNH-Colen** [comment]
Given Dream has never even crafted an assline I really don't see how he can know what is and isn't intended on this one.

**Comment by mitchej123** [comment]
image
image

**Comment by GTNH-Colen** [comment]
That's a comment by Dream, who again, has never made an assline (outside of a creative world maybe). So I'm not sure I'd call it an authoritative source in terms of documentation...

**Comment by GTNH-Colen** [comment]
Then the output should be moved on top and 16 length enabled again because 15 inputs looks silly.

**Comment by Dream-Master** [comment]
We find another solution. 
@GTNH-Colen make a ticket with new suggestion (block on top or elsewhere to limit machine to 16 blocks)

**Pull request closed without merging**
