### PR TITLE
Oil rebalance

### PR DESCRIPTION
**Pull request by Pxx500**
to be merged with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16802

Rebalances oil as per this spreadsheet
https://docs.google.com/spreadsheets/d/1X2Q6VEjVu9uBDt89ioR9EyjU6yhaEEuNRQvgndaQcrs
Additional discussion here:
https://discord.com/channels/181078474394566657/1264174719712624701

Buffs Natural gas as an energy source (natural gas amount in chunks increased)
Nerfs naphtha burn value
Normalizes distillation oil inputs to all be 150L (instead of 50, 100 and 150)
Shifts around amount of fractions acquired from different oil types

### CODE REVIEW

**Review by Steelux8 — DISMISSED** [review]
Most of the changes in this PR look okay, except for the oil processing recipes. The normalization should be done for an input of 100L, not 150L, since it's a round number and easier to work with. On top of that, the output amounts are not proportional to what they used to be, and I see no explanation for the new values.

**Comment by Steelux8** [comment]
I'm still waiting on the explanation for why values for Refinery Gas, Naphtha and Light Fuel were changed across several oils. Pxx told me that the new numbers were set so that fractions progressively decrease in volume as they move away from the main fraction for the oil (I think?), but I don't think it's a problem if they don't gradually decrease, and the new numbers can cause problems, such as people who power their oil setup with Refinery Gas.

**Comment by NotAPenguin0** [comment]
I have no strong opinion on what Steelux said above, but overall I do like the goal of the PR of buffing natural gas and nerfing naphtha.

**Review by chochem — CHANGES_REQUESTED** [review]
am I missing something or did you forget the circuit 9 recipes?

**Review by Steelux8 — APPROVED** [review]

**Pull request merged**
