### PR TITLE
Steam Machine Fixes & Improvements

### PR DESCRIPTION
**Pull request by PlayfulPiano**
- New Steam Multis have unique names similar to the grinder and squasher
- Steam steel singleblocks are now named "High Pressure Steam"
- Updated the WAILA tooltip for all steam machines to use L/s
- Slight adjustments to various tooltips
- Steam multis now have a 1.6x recipe duration multiplier (up from 1.5) and a 1.25 L:EU ratio (down from 1.33), giving exact efficiency at max parallel.
- Steam multis also are now tiered between Basic & High Pressure (excluding water pump)
- Various tooltip changes to make them more in line with other multiblocks

I also wanted to try and add a universal tooltip to singleblock HP machines which mention the 2x speed/steam rates below their typical descriptions, but I could not for the life of me figure out how to do it within the steel.java class with a line break. I have the tooltip within the list of changes (it's currently just not shown in game), in case anyone wants to implement it on their end.

image
image

### CODE REVIEW

**Comment by chochem** [comment]
some nice stuff, but:

I really am against renaming the regular steam machines to Low Pressure Steam. That seems awkward and unnecessary.

Steam consumption per tick was better as that is how other machines show it.

Finally, this sounds like it will break a lot of stuff like quests, so not a good idea during freeze.

**Comment by Baerschen** [comment]
> some nice stuff, but:
> 
> I really am against renaming the regular steam machines to Low Pressure Steam. That seems awkward and unnecessary.
> 
Agreed, keeping it simple I think is a better approach.
> Steam consumption per tick was better as that is how other machines show it.
> 
Slightly disagree because while consistency is important I think steam machines kinda warrant an exception because Fluid pipes show what they are capable of in L/sec aswell. So seeing what you need to transport and what you can transport is easier that way though this might be a more general question if we want to give info in per second or per tick (maybe changing fluid pipes would be prefered)
> Finally, this sounds like it will break a lot of stuff like quests, so not a good idea during freeze.
> 
Would this break more than replacing controllers in quests? I will have to redo the steam quests anyway before 2.7 because they are outdated since I wrote them too early before the rebalancing. If its "small" stuff that breaks I could fix them.

**Comment by PlayfulPiano** [comment]
> some nice stuff, but:
> 
> I really am against renaming the regular steam machines to Low Pressure Steam. That seems awkward and unnecessary.
> 
> Steam consumption per tick was better as that is how other machines show it.
> 
> Finally, this sounds like it will break a lot of stuff like quests, so not a good idea during freeze.

- LP is because I was trying to figure out a good way to define the two tiers separately that is made consistent. HP isn't called steel and well "steam x" isn't called bronze to the player. So I figured LP/HP would make that consistent.

- I have it as /s because everything else steam related at steam age is /s. IMO this should be kept consistent universally, so either other steam aspects should be made to /t or these machines should be made to be /s like in the PR.

- That's fair. What could probably be preserved for 2.7 then, just the multi changes I presume? And how are the unique names idea?

**Comment by chochem** [comment]
> Slightly disagree because while consistency is important I think steam machines kinda warrant an exception because Fluid pipes show what they are capable of in L/sec aswell. So seeing what you need to transport and what you can transport is easier that way though this might be a more general question if we want to give info in per second or per tick (maybe changing fluid pipes would be prefered)
> I have it as /s because everything else steam related at steam age is /s. IMO this should be kept consistent universally, so either other steam aspects should be made to /t or these machines should be made to be /s like in the PR.

the steam multis show L/t and still do with this PR.

>Would this break more than replacing controllers in quests? I will have to redo the steam quests anyway before 2.7 because they are outdated since I wrote them too early before the rebalancing. If its "small" stuff that breaks I could fix them.

Not just the multi quests but also 25 singleblock quests potentially :P

**Comment by PlayfulPiano** [comment]
> > Slightly disagree because while consistency is important I think steam machines kinda warrant an exception because Fluid pipes show what they are capable of in L/sec aswell. So seeing what you need to transport and what you can transport is easier that way though this might be a more general question if we want to give info in per second or per tick (maybe changing fluid pipes would be prefered)
> 
> > I have it as /s because everything else steam related at steam age is /s. IMO this should be kept consistent universally, so either other steam aspects should be made to /t or these machines should be made to be /s like in the PR.
> 
> the steam multis show L/t and ~still do with this PR~.
> 
> >Would this break more than replacing controllers in quests? I will have to redo the steam quests anyway before 2.7 because they are outdated since I wrote them too early before the rebalancing. If its "small" stuff that breaks I could fix them.
> 
> Not just the multi quests but also 25 singleblock quests potentially :P

Why would the quests break? Like descriptions sure I understand the need to modify names, but the quests themselves shouldn't break since the reference id isn't changed.

And yeah the PR makes all steam machines use L/s. Boilers already are in L/s, but current version has singles using EU/t and multis using L/t, which means it's extremely inconsistent.

Since NEI is in L/s and L/s is the pipe fluid system, I find that to be the best unit to use here.

**Comment by PlayfulPiano** [comment]
Also with regards to LP I can understand the issue there when it comes to translation. But imo HP machines should at least include Steam in their name instead of just being "High Pressure Macerator"

**Comment by PlayfulPiano** [comment]
- Remove "Low Pressure" mention in singleblocks
- Changed "Low Pressure" tier to "Basic" for multiblocks
- Made a few naming changes for specifically Steam Boilers (separate PR will be done for quests)

**Comment by Dream-Master** [comment]
@PlayfulPiano run spotless to let it build. Thanks

**Comment by PlayfulPiano** [comment]
> @PlayfulPiano run spotless to let it build. Thanks

what do you mean by spotless?

**Comment by Dream-Master** [comment]
Gradlew spotless

**Comment by PlayfulPiano** [comment]
> Gradlew spotless

so I just have to run .\/gradlew.bat spotlessApply in my terminal in the directory then push the changes as a commit, correct?

**Comment by PlayfulPiano** [comment]
Oh it looks like it's saying I'm running on jvm 8, which is weird because I have java 21 installed? But yeah because of this it's not letting me run that command.

**Comment by chochem** [comment]
could you update the pr description when you change what the pr does?

**Comment by PlayfulPiano** [comment]
> could you update the pr description when you change what the pr does?

Done

**Pull request merged**
