### PR TITLE
Update GT_MetaTileEntity_Cleanroom.java

### PR DESCRIPTION
**Pull request by Dream-Master**
Bio Labs recipes working now in a cleanroom

### CODE REVIEW

**Comment by Prometheus0000** [comment]
So by that you mean it now _requires_ the cleanroom rather than fixing working inside one? Do the biolab recipes in NEI say they need it properly?

**Comment by Dream-Master** [comment]
bot tested it and it works now.
The bio lab recipe shows cleanroom but not started before.

**Comment by bartimaeusnek** [comment]
@Prometheus0000 basically, it wasnt setting the reference to the cleanroom, when the recipe was using the cleanroom bit (cleanroom recipes didnt work), so no its a fix not a nerf.

**Comment by Prometheus0000** [comment]
I'm not complaining, the biolab does seem like a thing that would need a cleanroom. It's just that Dream's English is sometimes a little unclear, plus I didn't think it needed a cleanroom previously.

**Pull request merged**
