### PR TITLE
Actually use the Fluid Heater to heat fluids, instead of the Oil Cracker

### PR DESCRIPTION
**Pull request by Ethryan**
image
**This Breaks Existing Setups!**

So everyone have to fix their Ruthenium and Bauxite processing chains.

### CODE REVIEW

**Comment by Nxer** [comment]
What are the benefits of doing this?

**Comment by boubou19** [comment]
for the player? none 😄 But we are preparing yet another big rework, during which we will extract all the recipes in NHCore, and those would be sorted by machines and by mod. And it really doesn't make sense now, before we didn't have a fluid heater multiblock so it was somewhat ok.

**Comment by EnderProyects** [comment]
> What are the benefits of doing this?

Its kinda a buff since doesnt use steam

**Comment by Nxer** [comment]
Well. This change has little impact on ruthenium treatment. But for Bauxite Slurry, players have to use single block machine in EV tier.

**Comment by Ethryan** [comment]
> Well. This change has little impact on ruthenium treatment. But for Bauxite Slurry, players have to use single block machine in EV tier. Efficiency reduced, still acceptable, well.

1 Bucket a second, and you don’t need a big multi block just for heating.

A more compact setup should be possible even if you use multiple heaters to heat the Bauxite Slurry.

Plus it makes it reasonably easy to set this up for use when you get to the moon, to increase titanium production.

**Review by Connor-Colenso — APPROVED** [review]
Seems reasonable.

**Pull request merged**
