### PR TITLE
Finally Fixing Frames (maybe)

### PR DESCRIPTION
**Pull request by CookieBrigade**
Frames should now behave on servers

### CODE REVIEW

**Comment by Dream-Master** [comment]
@CookieBrigade please add it to master branch. Thanks

**Comment by Dream-Master** [comment]
Or is this additional code to an existing pr ?

**Comment by CookieBrigade** [comment]
@NotAPenguin0 said he'll mark a pr to merge into master later

**Comment by Dream-Master** [comment]
@NotAPenguin0

**Pull request merged**
