### PR TITLE
Simple optimization to GT_Utility.moveOneItemStack

### PR DESCRIPTION
**Pull request by hohounk**
Moved a couple of things from inner loop to outer one as the values don't change in the inner loop anyway so they can be precalculated only once instead of every iteration of the inner loop.

### CODE REVIEW

**Comment by boubou19** [comment]
is this called by the conveyor covers?

**Comment by hohounk** [comment]
From my understanding this gets called by nearly everything that moves items between inventories in GT. That includes machines auto-outputting to pipes/inventories and conveyors moving items to/from inventories and machines. 

I'm not 100% certain but I think only when items move from one pipe to another pipe there is another function that handles that with slightly different, hopefully more optimised, logic.

**Comment by Cleista** [comment]
> That particular function would definitely need a whole lot more love as it is at the core of most lag issues caused by moving stuff between big inventories and/or high-tier machines that move a LOT of stacks per tick. I have other ideas how to improve it but as I'm a complete noob where it comes to MC modding I figured I'll start with low hanging fruit.

Would you be able to show some comparisons? Specifically please try to reproduce the laggy setups in #6414 made by @GTNH-Colen and see how much difference your changes make.

**Comment by hohounk** [comment]
I'd absolutely love to but I have no clue how to measure the difference in speed. I did some very basic setups in a new world and used the debug scanner to measure the tile entities but the output of it was varying a *lot*, to the point of being unusable. Are there any tools/methods I could use to get a more useful measurement?

**Comment by Cleista** [comment]
I know [VisualVM](https://visualvm.github.io/) is recommended a lot for GTNH profiling but I haven't used it myself. 

How much was it varying by? Orders of magnitude? Does that mean the lag Colen sees is not reproducible, or just that it lags intermittently?

**Comment by hohounk** [comment]
OK, I'll give VisualVM a try later tonight.

As I was using the default mods that came with cloning the mod from GTNH I lacked the compressed chest and the massive pipes so I settled with smaller pipes and inventories for my tests. There I saw the numbers vary by two orders of magnitude easily. 

I'm convinced that the lag is caused by the function as it does a *lot* of operations with bigger inventories (65k iterations moving things from 256 slot inventory, e.g compressed chest, to another 256 slot inventory, e.g biggest pipes) and for some tileentities it gets called every tick as long as the TE doesn't get put to sleep.

Of course a "proper" fix would be to get rid of the O(n^2) complexity but that would require much more effort. Another thing I thought was to look into if tGrabSlots/tPutSlots could be cached somehow or perhaps not creating them in first place. Those two arrays are created on every function call by iterating over both inventories, appending numbers to array list one by one and finally turning it into an array. That is a whole different topic, though, and will get a separate pull request assuming I can figure out something that works.

**Comment by hohounk** [comment]
Added some extremely hacky but accurate timing code and apparently somehow that code change made the thing run almost 100x slower in a simple test setup. I have no clue how come that major difference didn't come up with GT scanner.

Definitely do not merge the change at the moment. I'll figure out what went wrong and report back when I have some properly tested results to show

**Comment by Dream-Master** [comment]
ok

**Comment by hohounk** [comment]
Ok, this version should now work properly. In my testing with a circle of quantium pipe with UEV conveyor->compressed chest->quantium pipe with UEV conveyor back to first compressed chest I was seeing about 4x speedup compared to previous code when first row of the compressed chest was full of items.

Technically, the previous commit I had here was working properly as well, just the local changes that I didn't commit yet made things worse. The current version is basically the same as initial commit, just moving yet another check up by one loop level and reusing the stack from source inventory in all three places, not two.

Of course it would be nice if other people checked it over but from my part I'm confident enough to say this can be merged.

**Comment by repo-alt** [comment]
Looks good to me.

**Pull request merged**
