### PR TITLE
Cover tabs

### PR DESCRIPTION
**Pull request by YannickMG**
See GTNewHorizons/GT-New-Horizons-Modpack#9367 for details.

Implemented cover tabs with the option to disable them or render them on the right instead.

### Before
BEFORE-TABS-TRUECOLOR

### ✨✨✨ After ✨✨✨
AFTER-TABS

Note: Right now Crafting table covers don't work as tabs due to their implementation, but they're grayed out so there's no buggy behavior.

### CODE REVIEW

**Comment by glowredman** [comment]
Did you preserve the old behaviour?

**Comment by YannickMG** [comment]
> Did you preserve the old behaviour?

The old behavior being no tabs? Yes, they can be turned off in in-game GregTech client settings. (Mod Options button)

**Comment by glowredman** [comment]
No, I mean can you still shift-click the side of the machine to get the cover GUI?

**Comment by YannickMG** [comment]
> No, I mean can you still shift-click the side of the machine to get the cover GUI?

Indeed, and you still exit out the normal way. This is purely additional functionality.

**Review by mitchej123 — APPROVED** [review]
Looks good, let's test on Zeta.

**Pull request merged**
