### PR TITLE
fix all fineWire amount

### PR DESCRIPTION
**Pull request by botn365**
fix all instences where you only get 4 fine wire/ingot instead of 8 when there is no wire version of that material

### CODE REVIEW

**Comment by Dream-Master** [comment]
fix you mean increase ?

**Comment by alphaNOVAircraft** [comment]
Yes, cz currently a few just have 4 instead of 8 for no reaason

**Comment by botn365** [comment]
if a material has a wire you can make 8 fine wires per ingot but when a material does not have a wire you get only 4 fine wire per ingot wich makes no sense 
at the moment there are a few materials witch costom recipes that changes it to 8 fine wire per ingot even if that material has no wire
this will fix this wierd inconsistenty and make it 8 fine wire for 1 ingot for all materials

**Review by Dream-Master — APPROVED** [review]

**Comment by Prometheus0000** [comment]
You didn't link the actual issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6633

**Comment by Prometheus0000** [comment]
@botn365 While it seems that SpNt is fixed, borosilicate glass bars now have a recipe in the wiremill that gives 4 glass fibers, and another in the extruder that gives 8. Is there a way you can fix this? Though bart said in #5904 that it's intended to be 4.

**Pull request merged**
