### PR TITLE
amber dust -> gem recipe

### PR DESCRIPTION
**Pull request by NoX-programer**
For some reason GregTech_API.sThaumcraftCompat.addCrucibleRecipe adds only thaumonomicon visible recipe, but not actual recipe. So with this line and recipe, added via script, we got complete working recipe for amber gem drom dust. Maybe someone skilled will fix GT (or even Thaumcraft) code to add that recipe properly.

### CODE REVIEW

**Comment by Dream-Master** [comment]
maybe ore:gemAber not works so we have to use the Thaumcraft item instead ?

**Comment by NoX-programer** [comment]
I don't adressing gem as <ore:gemAber>. I adressing it as <Thaumcraft:ItemResource:6> - because I know - it's result of recipe, so I specify it explictly. I adressing source material as <ore:dustAmber> - this is acceptable, tested and working.

**Comment by Dream-Master** [comment]
its not proven it was a guess

**Comment by NoX-programer** [comment]
So here's what I found out, in order: after uncommenting the line
`GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.Amber), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.Amber, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))),`
we see thaumonomicon crystallization recipe of amber from dust, but there is no actual recipe. Next, guess, the problem in this line - maybe GT_OreDictUnificator, maybe not - so I replaced arguments with same type, but more explicitly:
`GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, Materials.Amber.getDust(1), GT_ModHandler.getModItem(MOD_ID_TC, "ItemResource", 1L, 6), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))),`
but it not helped - behavior is the same: there is thaumonomicon crystallization recipe of amber from dust, but there is no actual recipe. So, conclusion: the problem exists, but not in this line, but I'm not too skilled to find it. **So, getting back to my 1st suggestion: with PR https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7449 (which adds actual recipe) and this (adds visual of this recipe to thaumonomicon page) we have closing the https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3141.**

**Comment by Dream-Master** [comment]
ok. I will merge it now and check later for alternatives

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
