### PR TITLE
Adjust cleanroom block composition check

### PR DESCRIPTION
**Pull request by Majora320**
This PR modifies the cleanroom block composition check to be more intuitive and more closely reflect the tooltip. Currently, the composition checks the current number of each non-plascrete block (e.g. some kind of glass) against the total number of plascrete blocks in the structure, excluding the top outer edge. If that ratio is more than the ratio set in the config file, the structure won't form. This is quite unintuitive: instead of being able to replace 50% of the plascrete with managlass, as the config file would suggest, only 33% can be replaced to maintain the ratio. This PR makes three changes:

1. We now count the plascrete blocks around the top edges toward the total.
2. The ratio is now the ratio between the non-plascrete block and the total number of blocks in the structure.
3. A new check is added against the maximum allowed percentage of all non-plascrete blocks in the structure, to ensure that you can't just use 50% managlass and 50% borosilicate glass in lieu of any plascrete.

### CODE REVIEW

**Comment by Steelux8** [comment]
Is it a good idea to allow half of the entire cleanroom's blocks to not be plascrete? I thought the maximum amount of other blocks was 1/4 or 1/3 of the total, and it turns out it was 1/3 after all. Since the cleanroom is specifically made to isolate the interior from the exterior, it makes sense to me to limit the amount of other blocks that much, instead of allowing a 50/50 placement.

**Comment by Majora320** [comment]
The motivation behind this change was a 63x63x63 cleanroom build on the hive smp (using a twist space clone of the cleanroom with a higher size cap) that was fully constructed under the assumption that the ratio was 50% and wouldn't form due to the nonintuitive nature of the tooltip. If the desired ratio is less than 50%, I think this PR should be accepted and the numbers changed in the config file to 25 or 33 to make the way the check works more intuitive.

As far as composition goes, it's mostly about aesthetics since plascrete isn't *that* expensive and using other materials would require effort to produce managlass or borosilicate for the player's first cleanroom when these costs are relevant; I personally think aesthetic restrictions should be relatively relaxed, and being able to use a type of reinforced glass for an airtight seal doesn't seem too unrealistic to me.

**Comment by AbdielKavash** [comment]
> Is it a good idea to allow half of the entire cleanroom's blocks to not be plascrete? I thought the maximum amount of other blocks was 1/4 or 1/3 of the total, and it turns out it was 1/3 after all. Since the cleanroom is specifically made to isolate the interior from the exterior, it makes sense to me to limit the amount of other blocks that much, instead of allowing a 50/50 placement.

Before this PR, the limit was *much* lower than 50%, due to the way the limits of the various types of glass interacted. You could get close to a 1 plascrete : 3 glass bocks ratio by combining different types ([moderately cursed example](https://i.imgur.com/ZRSqCWo.png)).

I am personally in favor of just completely getting rid of all the different glass-specific limits, and impose a very simple rule like "at least 50% of the structure has to be plascrete, the rest can be any combination of allowed blocks (glass, doors, elevators, etc.)". If 50% is not sufficient percentage for realism reasons, then the percentage can be adjusted; but keep in mind that the higher you tune it the more currently valid setups you invalidate.

**Comment by Steelux8** [comment]
Is there a possibility that this change will make some existing cleanrooms stop working? If so, it would be a breaking change, so this needs to be accounted for.

**Comment by Dream-Master** [comment]
@Majora320 50 or 33% is to much but 10%-15% would be nice. Its now 5% if i remember right.

**Comment by Majora320** [comment]
> @Majora320 50 or 33% is to much but 10%-15% would be nice. Its now 5% if i remember right.

Currently, the cleanroom config sets the following values:
```cfg
cleanroom_allowed_blocks {
    managlass {
        S:Name=tile.manaGlass
        I:Percentage=50
    }

    elfglass {
        S:Name=tile.elfGlass
        I:Percentage=50
    }

    reinforced_glass {
        S:Name=blockAlloyGlass
        I:Percentage=5
    }

    bw_reinforced_glass_0 {
        I:Meta=0
        S:Name=BW_GlasBlocks
        I:Percentage=50
    }

    bw_reinforced_glass {
        S:Name=BW_GlasBlocks
        I:Percentage=100
    }

    warded_glass {
        I:Meta=2
        S:Name=tile.blockCosmeticOpaque
        I:Percentage=50
    }
}
```

Here is a table of what the actual percentages of allowed blocks look like before and after the change.

| Block | Allowed glass% before | Allowed glass% after |
|---------|---------------------------------------|------------------------------------|
| Reinforced glass |4.76% | 5% |
| Managlass / Elfglass / Borosilicate glass / Warded glass | 33.33% | 50% |
| Mixed glass types | 67.21% | 50% |
| Higher tiers of borosilicate glass | 100% | 100% |

This change is primarily to make these ratios less surprising and more intuitive.

> Is there a possibility that this change will make some existing cleanrooms stop working? If so, it would be a breaking change, so this needs to be accounted for.

It's possible, but it will probably not affect many people. Cleanrooms will only stop working if players were previously mixing lower-tier glass types to get a total glass ratio of more than 50%. Let me know if anything needs to be done to handle this case - it might just mean that this should be delayed to 2.7.

**Comment by Dream-Master** [comment]
its new for me that so much glass in % work before your patch.

**Comment by Pxx500** [comment]
As long as the PR doesn't make cleanroom easier in early game MV/HV then I think it's ok. Increasing the amount of glass allowed with higher glass tiers makes sense, the fix to mixing glass types should definitely be implemented

**Comment by Pxx500** [comment]
> > @Majora320 50 or 33% is to much but 10%-15% would be nice. Its now 5% if i remember right.
> 
> Currently, the cleanroom config sets the following values:
> 
> ```haproxy-config
> cleanroom_allowed_blocks {
>     managlass {
>         S:Name=tile.manaGlass
>         I:Percentage=50
>     }
> 
>     elfglass {
>         S:Name=tile.elfGlass
>         I:Percentage=50
>     }
> 
>     reinforced_glass {
>         S:Name=blockAlloyGlass
>         I:Percentage=5
>     }
> 
>     bw_reinforced_glass_0 {
>         I:Meta=0
>         S:Name=BW_GlasBlocks
>         I:Percentage=50
>     }
> 
>     bw_reinforced_glass {
>         S:Name=BW_GlasBlocks
>         I:Percentage=100
>     }
> 
>     warded_glass {
>         I:Meta=2
>         S:Name=tile.blockCosmeticOpaque
>         I:Percentage=50
>     }
> }

Managlass is too cheap, it should be 5% too. Maybe change high tier glass to something like 90% or 80%

**Comment by chochem** [comment]
did you also have a look at https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16809 ?

**Comment by Dream-Master** [comment]
@Majora320 i get no response for a long time. I set it to draft for now. Feel free to set it undraft when you have time to make it backwards compatible.

**Comment by Dream-Master** [comment]
2.7.0 will be a big update. i chatted with yannik today
Yannick — Today at 9:20 PM
At first glance, there doesn't seem to be a way to make these changes backwards compatible, other than not doing those changes, or doing entirely different changes.

in this case we maybe add it and break existing setups. We can add a warning to start screen so people be aware of it. @GTNewHorizons/developers

**Comment by Dream-Master** [comment]
@chochem @Pxx500 @Steelux8

**Comment by Dream-Master** [comment]
OneEyeMaker — Today at 10:06 PM
Honestly, I'm more than happy with current cleanroom design. And I'm not a big fan of this change. (AFAIR, I already have said that). It maybe sounds harsh, but I'd prefer to keep this PR closed.

**Comment by Pxx500** [comment]
I don't think this PR will go anywhere since original author left, but imo backwards compatibility doesn't matter because:
1) you have to go out of your way to make cleanroom get broken
2) you already are cheesing mechanics which shouldn't be supported anyway
3) you only have one cleanroom or so so even if it breaks it's a matter of minutes to fix it (not running around trying to find what broke)

**Comment by YannickMG** [comment]
I imagine this PR wouldn't need much more additional work if there's agreement that full backwards incompatibility is not a requirement. (It would be a one time annoyance)

The inconsistency looks like a bug more than a design decision so it would make sense to fix it. Excluding the top edges (but not bottom or corner edges) does also sound like an inconsistency that should be resolved.

Focusing only on fixes, it would make sense to keep the original 33% allowed mid-tier glass%.

**Comment by Majora320** [comment]
Hello, I am the original developer. I'm on vacation right now but I saw a few emails about this. I agree with @Pxx500 that backwards compatibility is not necessary since it would only effect the small minority of cases where multiple glass types are being used as once to make a ratio above 50%. @YannickMG: The reason I chose 50% instead of 33% is because it will break almost no setups, while 33% might break a few - and 50% is also a bit simpler to calculate for a human. I don't have a very strong preference on this though, other than the system being changed from what it is currently; @AbdielKavash's idea  of simplifying the system further and having a flat 50% ratio would also work. I do think the system should be changed though, the current way it works is quite confusing and unintuitive.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
