### PR TITLE
Startup threading, Recipe lookup Threading

### PR DESCRIPTION
**Pull request by bartimaeusnek**

### CODE REVIEW

**Comment by Glease** [comment]
Is it necessary to introduce lombok? I don't feel like using it at all.

**Comment by botn365** [comment]
so how will this work with recipes witha 1 tick time will it still be 1 tick or will that 1 extra tick look up time turn it in to 2 ticks

**Comment by Dream-Master** [comment]
@bartimaeusnek any news on this? Will you finish it ?

**Comment by Elisis** [comment]
Has anyone tested this at all? Somehow I don't think Bart is going to finish it if it doesn't work...

**Comment by GTNH-Afx237v7** [comment]
A while ago Bart provided a .jar including these changes to some users on discord, including myself. I did not notice any improvements, iirc Dream tested it as well, catch remember the outcome though. Altogether Bart said the feedback he got from those that tested it was inconclusive and that he would need to look at this again. Doesn’t seem like this is going to happen though, therefore I suggest that, unless someone is willing to take this over, this shall be closed.

**Comment by Dream-Master** [comment]
I rember i tested it and it load up the pack and poured some minetweaker script errors. not sure if it loads up faster or throw any error.

**Comment by boubou19** [comment]
People tested it and it seems there is no visible improvements, and was giving errors as Dream said. So unless there is a real justification to continue that PR, no need to bother with that imo.

**Comment by Dream-Master** [comment]
guess it had to many conflicts anyways

**Pull request closed without merging**
