### PR TITLE
Add New Ore Processing Multi - Integrated Ore Factory

### PR DESCRIPTION
**Pull request by GlodBlock**
a multi for ore processing.

it intergrated macerate, ore washer, thermal centrifuger and centrifuger's function to process ore.
it won't process anything except ore related stuff.
e.g.
input 64x rutile ore
image
output 160x rutile dust + 159x stone dust (crush -> ore washer -> crush -> centrifuge route)
image

every ore takes 30EU/t * 90s (can be overclocked), 2L lubricant, 200L distilled water to process.
these energy numbers are calculated from the crush -> ore washer -> thermal centrifuge -> crush route's energy cost.
it can process 1024x ores at most per time, supporting different ores.

it has 4 modes, switched by right clicking with screwdriver:
1: crush -> ore washer -> thermal centrifuge -> crush route
2: crush -> ore washer -> crush -> centrifuge route
3: crush -> crush -> centrifuge route
4: crush -> ore washer -> sifter route

it allows more compact setup for ore processing, i plan to make it unlocked at Luv or ZPM.

### CODE REVIEW

**Comment by chochem** [comment]
Overall this seems pretty neat. Really like the 'modular' look!

Regarding **tier**:

ZPM at earliest I would say, this should not be LuV. For three reasons actually: 1) its pretty powerful 2) void miners start in zpm and this seems designed around void miners 3) ideally there should be some tier gap to the last ore proc upgrade which is in mid IV (mac stack).

I think I am ok with ZPM but there is also the option of placing it even later as it looks quite powerful.

Regarding **modes**:
- mode 4 seems completely useless unless it is cheaper/faster as mode 1 just gives the same and more output.
- how about an additional mode that is just crush-> wash for siftables or galena/sphalerite?

**Comment by GlodBlock** [comment]
> Overall this seems pretty neat. Really like the 'modular' look!
> 
> Regarding **tier**:
> 
> ZPM at earliest I would say, this should not be LuV. For three reasons actually: 1) its pretty powerful 2) void miners start in zpm and this seems designed around void miners 3) ideally there should be some tier gap to the last ore proc upgrade which is in mid IV (mac stack).
> 
> I think I am ok with ZPM but there is also the option of placing it even later as it looks quite powerful.

yeah it seems more reasonable to gate it at ZPM. Luv is bit too early for it.
> Regarding **modes**:
> 
> * mode 4 seems completely useless unless it is cheaper/faster as mode 1 just gives the same and more output.
> * how about an additional mode that is just crush-> wash for siftables or galena/sphalerite?

didn't notice mode 4 is overwhelmed by mode 1 x), i will remove it.
sifting is also an important step in ore processing. i will add other modes for it.
galena/sphalerite should be separated by yourself if you want it for indium, making them the special case is against its design philosophy

**Comment by miozune** [comment]
Looks really good. Can you add mode for voiding stone dusts, say shift right click with screwdriver? Most of them are just voided anyway and might be the small source of lag.

**Comment by GlodBlock** [comment]
> Looks really good. Can you add mode for voiding stone dusts, say shift right click with screwdriver? Most of them are just voided anyway and might be the small source of lag.

sure i can add a void mode for stone dust, but they are also used at large quanities in drilling fluids

**Comment by chochem** [comment]
yeah I didnt mean it should do indium. just a mode that ends at purified (to then sift/further process yourself). But of course that would not be important if you plan to include sifting itself.

**Comment by LewisSaber** [comment]
What about macerate -> forgehammer -> dustwasher

**Comment by Eranicus** [comment]
Current UV-UHV+ way for processing ore from 10-20+ void miners with Ogannesson is the following: Crush-->Forge hammer --> Washer 

As mentioned abowe please consider introdusing crush --> forge hammer --> washer mode with possibility to void stone dust

**Comment by Chaoschaot232** [comment]
While this multi is gated in ZPM will it get also it's own quest/quest-line maybe?
Will it also support bonus outputs since the tier unlocked definitly every available bonus output 🤔

**Comment by Chaoschaot232** [comment]
> Cool but useless (for lag reduce purpose) due to this: `it has 4 modes, switched by right clicking with screwdriver: 1: crush -> ore washer -> thermal centrifuge -> crush route 2: crush -> ore washer -> crush -> centrifuge route 3: crush -> crush -> centrifuge route 4: crush -> ore washer -> sifter route` since the ppl will still create multiple copies, so the same lag.
> 
> Way to fix: GT++ nineinone way: number of circuit in input bus determine the process mode.

I disagree at this point. Well, tbh GT++ could/should/what ever be fixed but after all you could then spam **every Multi** which are performance friendly written and kill the entiere server/client with them.

Maybe the code for this Multi has optimizable potential but writing that it's usless only because it could be spamed is definitly the wrong way. Who ever does this, has to pay the cost and this count's for every Multi/TE/Machine. Smaller and compressed Setups are the solution here and I would say that even 3 of this big Multi shouldn't harm the FPS/TPS in any form.

**Comment by GlodBlock** [comment]
> Current UV-UHV+ way for processing ore from 10-20+ void miners with Ogannesson is the following: Crush-->Forge hammer --> Washer
> 
> As mentioned abowe please consider introdusing crush --> forge hammer --> washer mode with possibility to void stone dust

you can shift click with screwdriver to enable stone dust void mode. it won't output stone dust even when there is stone dust output.

**Comment by Sphyix** [comment]
I can't figure out the overclock that happens with this machine.
Right now I'm honestly worried it's worse than setting up a gt++ multi ore processing.

Based on my setup, I can process 320 ores/tick using 68A UEV
and setup is 
12 macerators 
6 sifters 
32 thermal 
18 washing

This multi from what I can understand, at the same power (1A UMV~) is slower?

Basing that on the message @GlodBlock you sent on discord, saying at MAX power it needs 2 or 3 ticks to process 1024 ores.
That's 512 or 314 ores/tick at MAX

I think this multi, even tho it'll probably be the unpopular opinion, is not powerfull enough as it is now.

**Comment by boubou19** [comment]
maybe, but lag wise it will be night and day

**Comment by GlodBlock** [comment]
gt++ gives mindless speed and energy bonus, while i do not consider it.

**Comment by Sphyix** [comment]
> gt++ gives mindless speed and energy bonus, while i do not consider it.

then what's the advantage of this multi if it uses 4x power compared to gt++?
i mean, lag is a good reason to switch to this on officials, but I personally don't really like reducing speed for lag reasons

**Comment by GTNHAfx237v7** [comment]
How about giving Glodblock a break and let’s try this out? Balancing can always be done, if this is working fine and needs some feedback for tweaking let’s ship it and tune afterwards.

**Comment by GlodBlock** [comment]
easier setup, you don't need to design the i/o system for oredict. also it's easy to make it matches gtpp's speed, just cutting down time from 90s -> 22.5s.

**Comment by Sphyix** [comment]
@GTNHAfx237v7 if numbers already are here, I don't see a reason to wait for balance. Time and quantity of what gt++ can do are known, new multiblock times are known. Balance is done on spreadsheets not with ingame opinions.


> easier setup, you don't need to design the i/o system for oredict. also it's easy to make it matches gtpp's speed, just cutting down time from 90s -> 22.5s.

Cool, was asking just cause I want to avoid building multiples of the new multiblocks to replace the gt++ way of processing ores.
If it needs to replace it completely, balancing around lategame alternatives is a good way of doing it.
Right now if I would want to remove all gt++ ore processing from my base and move to the new multi, i'd need 8 of them, or accept the fact that moving to the new multi is going to cost me 4x power for less lag.

I see why new endgame players wouldn't even think of going gt++ considering the complexity compared to this multi, but moving to it when setup is already done to get worse speeds or more power consumption isn't really good.

Maybe a middle-ground between 90s and 22.5?

**Comment by Steelux8** [comment]
What about including the chemical bath processing in this?

**Comment by GlodBlock** [comment]
sure, i will check if it is doable to include chemical bath recipe

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
