### PR TITLE
Fix flipped bolt/screwdriver image encoding issues

### PR DESCRIPTION
**Pull request by kumquat-ir**
Reverted and re-did the image flips with pillow, somehow the original PR messed up the encoding in a weird way that made Java 8 unable to read them properly

### CODE REVIEW

**Comment by serenibyss** [comment]
Thanks, testing now

**Review by serenibyss — APPROVED** [review]
Works now after redoing the flip + rotate from the original textures

**Comment by benjamin-kirkbride** [comment]
Sorry for messing that up! @serenibyss any idea what was different with the way you did it?

**Comment by serenibyss** [comment]
@benjamin-kirkbride The images were in grayscale which doesn't work in the version of mc + java we have (for java 8, I guess newer java uses an updated library). We tried converting your images to srgb but there was still some other issue. Not sure what happened but redoing it with a less aggressive image editing tool seemed to do the trick

**Pull request merged**
