### PR TITLE
Nerfed replicator

### PR DESCRIPTION
**Pull request by bartimaeusnek**
+ added a config option
+ made TankSize of Replicator a bit nicer

Signed-off-by: bartimaeusnek <33183715+bartimaeusnek@users.noreply.github.com>

### CODE REVIEW

**Comment by Dream-Master** [comment]
we don't discuss about this change in general but we can talk about the factor because it was way to cheap before.

**Comment by GTNH-Colen** [comment]
> we don't discuss about this change in general but we can talk about the factor because it was way to cheap before.

Why would you not discuss this? Removing the RFC label just makes this look like a super shady stealth nerf?

**Comment by Dream-Master** [comment]
it wasnt a super silent nerf. It was a way to long to cheap.

**Comment by GTNH-Colen** [comment]
We need to be ***very*** careful about choosing a good value here if it is getting nerfed, even putting a multiplier of 2 would make indium cost nearly 13,000 UUM per dust vs the current 114 UUM.

**Comment by Dream-Master** [comment]
factor 1,333 is set now

**Comment by mitchej123** [comment]
What specifically is the problem being solved here.  What is too cheap, and what are the before and after costs?

Sounds like an 0lafe in search of a problem at first glance, without a well thought out plan.

**Comment by Retster** [comment]
maybe not 100% about the issue, but how about to add the multiblock replicator that is accsept multi-amp energy hatces?

**Comment by Bluebine** [comment]
I don't see the point to this... what exactly needs nerfed about UUM? what specific elements require a nerf, and (if i'm understanding how this works correctly) why is it a blanket nerf to all of them? and if replicating an element is the best way to get it, that's a sign that the element needs a proper recipe, not that UUM needs a nerf (although to compensate, the usage of that element would probably need an increase too.)
At the least, it should be configurable per element. Nobody's replicating, say, tungsten or lead, and nerfing recipes that are already useless doesn't make a lot of sense to me.

**Comment by quedral** [comment]
I expressed my opinion on main page however i feel like to repeat since some people don't get it. without adding alternative sources for scarce elements like Indium, nerfing uum only hurts mid tier players.

**Comment by Dream-Master** [comment]
we will choose 1.2 for now and see what happend

**Pull request merged**
