### PR TITLE
16x cutting factory frame texture that resembles the old one

### PR DESCRIPTION
**Pull request by bluhbipo**
the new cutting factory is pink. this is not the natural order of things...

textures in this pr are reminiscent of the original gt++ ones, yet touched up with a coat of paint so they look less.... horrible

i am new to github, the two "delete" commits were because i made a dyslexic typo in the file names when modifying them

### CODE REVIEW

**Review by BlueHero233 — APPROVED** [review]
Looks good

**Comment by Dream-Master** [comment]
@bluhbipo can you add a picture how old and how new multi texture look like ingame ?

**Comment by bluhbipo** [comment]
image
@Dream-Master

**Comment by Alexdoru** [comment]
nice work

**Pull request merged**
