### PR TITLE
change ev motor  wire material to Black Steel

### PR DESCRIPTION
**Pull request by Dream-Master**
(cherry picked from commit 0af04b80d905247cbcdeb2dac8ce38630403c080)
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8747
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/219

### CODE REVIEW

**Comment by Elisis** [comment]
I think using black steel for motors is extremely harsh. More fair to do something like blue steel because it at least doesn't require 10 steps.

**Comment by Dream-Master** [comment]
Black steel have ev cable/wires blue steel havent any wires or cables in this tier.

**Comment by boubou19** [comment]
Here is the following list of EV cables:
- Steel wires
Steel is a bronze age material. Making it at EV is easy, especially if you turn the iron into wrought iron first before turning it into steel.
- Nichrome wires
HV material, but requires a vacuum freezer. Will be a pain to process until the player reaches tungstensteel coils for the EBF, as the tungstensteel coil will give exactly 1800K more, granting a perfect overclock. But even with the perfect overclock, this will turn into a big time gate. (50s per hot ingot with nitrogen)
- Black steel wires
3 different mixer recipes just to make the dusts, mv recipe with perfect overclock while using nichrome coils, so a 15s recipe.
- Aluminium wires
MV material, uses a (small) process line due to recent changes, still easy at EV.

I honestly thinks the black steel wires are the most interesting choice if the goal is to make the player poor various resources into the motor (nickel, gold, silver, copper and steel).

But i'm still questionning this change tho: why does it really need to be changed? like in term of gameplay, what does this change bring? Nerfing for the sake of nerfing isn't great at all...

**Comment by iouter** [comment]
because annealed copper is a low-level material. don't use copper or annealed copper at ev items.

**Comment by boubou19** [comment]
all the resources involved in every ev tier wire is low level so i don't really see the point?

**Comment by Glease** [comment]
I'm against this change in its current state. Scale it down to 1x/2x wires if you want to use expensive material. Keep it copper if you want 8x wires. This makes no sense at all.

**Comment by Dream-Master** [comment]
So which materials should we choose ? Are we need to add more wire materials ?

**Comment by iouter** [comment]
nichrome is a expensive material, but black steel is not.

**Comment by Dream-Master** [comment]
i just wait for suggestion if black steel isnt a good choice.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
