### PR TITLE
Add requireMods for recipe builder

### PR DESCRIPTION
**Pull request by miozune**
This allows more streamlined check for cross-mod ingredients, like:
```java
GT_Values.RA.stdBuilder()
    .requireMods(Railcraft)
    .itemInputs(GT_Utility.copyAmount(3, aStack))
    .itemOutputs(ItemList.RC_Tie_Wood.get(3L))
    .fluidInputs(Materials.Creosote.getFluid(300L))
    .duration(10 * SECONDS)
    .eut(4)
    .addTo(chemicalBathRecipes);
```
instead of
```java
if (Railcraft.isModLoaded()) {
    GT_Values.RA.stdBuilder()
        .itemInputs(GT_Utility.copyAmount(3, aStack))
        .itemOutputs(ItemList.RC_Tie_Wood.get(3L))
        .fluidInputs(Materials.Creosote.getFluid(300L))
        .duration(10 * SECONDS)
        .eut(4)
        .addTo(chemicalBathRecipes);
}
```

### CODE REVIEW

**Comment by boubou19** [comment]
thousands of recipes to rework 😭

**Comment by miozune** [comment]
Well you're not forced to rewrite existing code 😉

**Comment by bombcar** [comment]
Given that the original format allows (pseudocode)

```
if(railcraft){
    fifty.recipies();
}
```

is this actually better/faster if you have more than one recipe?

**Comment by miozune** [comment]
@bombcar It depends

**Comment by Dream-Master** [comment]
@boubou19 let me know when we take this in.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
