### PR TITLE
Charging bus for Tree Growth Simulator

### PR DESCRIPTION
**Pull request by evgengoldwar**
Charging Bus - Charges tools with extra energy
image

Recipe
image

### CODE REVIEW

**Comment by S4mpsa** [comment]
What does it do? With the information we have here, it's a casing with a new texture. (One could look at the code, but pull requests should detail what they add to the pack, especially for new features)

**Review by chochem — DISMISSED** [review]
this defacto removes the tool mechanic from tgs. not a good plan.

**Comment by LazyFleshWasTaken** [comment]
I'd put this farther than iv, maybe zpm/uv

This would completely invalidate the charging mechanic, which means the best bonus will be given forever.
A bypass like the turbine housing in UV for dura/charge should be gated in a farther tier than the multiblock.

Or, if you want to tier it to iv/luv, you could make it give a penalty.

**Comment by evgengoldwar** [comment]
> I'd put this farther than iv, maybe zpm/uv
> 
> This would completely invalidate the charging mechanic, which means the best bonus will be given forever. A bypass like the turbine housing in UV for dura/charge should be gated in a farther tier than the multiblock.
> 
> Or, if you want to tier it to iv/luv, you could make it give a penalty.

Yea better change the recipe to zpm.

**Comment by evgengoldwar** [comment]
> this defacto removes the tool mechanic from tgs. not a good plan.

Changed recipe from iv to zmp

**Comment by AbdielKavash** [comment]
I don't like this at all. Replacing tools with an ME level maintainer is already trivial. There should be *some* reward for actually building an automation setup.

I would rather see a higher tier upgrade chip to the TGS that makes it not require any tools at all and just run perpetually, which is essentially what this does, but in a more explicit sense (and saving a few microseconds as you don't need to check for tools at all).

**Comment by serenibyss** [comment]
After discussion we decided that we do not want to take this PR

**Comment by Dream-Master** [comment]
@serenibyss can you link where this was dicussed?

**Comment by serenibyss** [comment]
https://discord.com/channels/181078474394566657/939305179524792340/1317185946143293491

**Pull request closed without merging**
