### PR TITLE
Change extractor structure

### PR DESCRIPTION
**Pull request by FourIsTheNumber**
Got complaints about extractor structure (justifiably) and Rilliko designed a new one. The footprint is actually basically identical (it's one block taller) but it costs slightly more casings.

image

Breaking change for anyone on betas, so better now than later.

### CODE REVIEW

**Comment by Steelux8** [comment]
"Breaking change" conflicts with the ongoing freeze, doesn't it?

**Comment by FourIsTheNumber** [comment]
This is the only time to change this without breaking stable bases. This should not be frozen.

**Comment by Steelux8** [comment]
This was discussed in meta-dev beforehand, removed the freeze tag.

**Review by chochem — COMMENTED** [review]
yea structure changes to the new multis need to be _before_ stable.

Looks good to me.

**Review by chochem — APPROVED** [review]

**Pull request merged**
