### PR TITLE
Add option to disable removing recipes from IC2 machines

### PR DESCRIPTION
**Pull request by Glease**
The default is to not remove from IC2 machines. This also changes the default of adding recipes to IC2 machines to false.

I'm not exactly sure if this will have negative consequence, as this version of GT is too new to be tested in my local installation of full GTNH pack. Anyone interested please see discord #mod-dev channel for a test build. To have full effect you need to have `AddGTRecipesToIC2Machines` set to false in config file `.minecraft/config/GregTech/GregTech.cfg`. My main concern is this *might* cause some important GT macerator/compressor/extractor/etc recipes go missing.

I'm however not seeing any problem in my striped down development environment though.

### CODE REVIEW

**Comment by mitchej123** [comment]
Personally, I'd just completely remove the option to add GT recipes to ic2 machines, and leave in the part that transfers the (very small) remaining amount of ic2 recipes to GT and deletes them.  

Ic2 machine usage isn't a thing in this pack so let's delete the cruft.

**Comment by Dream-Master** [comment]
@mitchej123 so you approved this or did it need additional changes ?

**Comment by mitchej123** [comment]
> @mitchej123 so you approved this or did it need additional changes ?

I'd rather he completely removed the gt --> ic2 recipe map functionality, instead of keeping it and adding a new config.

**Comment by Glease** [comment]
Superseded by #393.

**Pull request closed without merging**
