### PR TITLE
Add Fusion Reactor Mk4

### PR DESCRIPTION
**Pull request by Spartak1997**
Change class of Fusion Reactor

### CODE REVIEW

**Comment by draknyte1** [comment]
Already exists in GT++...

**Comment by draknyte1** [comment]
Why @Dream-Master?

**Comment by draknyte1** [comment]
So give it recipes? That’s all it’s missing.. it’s been a thing for months and this has been the only thing preventing it. @0lafe even knew this. 

Apologies, I’ve moved half way across the world and have had more important things to do. You get nothing fast if it’s free, so what do you expect?

**Comment by Dream-Master** [comment]
i dont complain and i dont want to rush you and i fully understand that you have rl issue to do like me. If you come the way with your update i will revert my code for t4.

**Comment by 0lafe** [comment]
@draknyte1 is right, it's there and functional, but it does need a little change. Uses UV+ instead of UHV+ hatches, but really just a recipe. Not sure why there needs to be another of these added

**Comment by draknyte1** [comment]
I can adjust the required hatches if needed, forgot to tweak that. As it is, 4x hatch X vs 1x hatch Y makes no real difference to running it, besides mildly mediocre cost differences on hatches. Just make the casings a tad extra expensive to compensate for the time being. (Field generators come to mine for the internal coils)

**Comment by 0lafe** [comment]
Oh yeah there's that, you don't do assembly line crafts do you? Gonna have to use a table craft for mk4 and use parts that come from the assembly line? Or am I just wrong :/

**Comment by draknyte1** [comment]
You (GTNH) can add them however you want. Was just stating Minetqraker can be used to remove it re-add all existing recipes.

**Pull request merged**
