### PR TITLE
makeshift solution of skipping gt hatches

### PR DESCRIPTION
**Pull request by Glease**
basically, set channel `gt_no_hatch` to 1 will cause autoplace to not place any gt hatches.

since currently there is no way to document the channels, this info will have to go to the quest tab for now.

later refactor will add tooltip to channels and ways to enumerate channels used by any given multi. however this wil not happen now.

### CODE REVIEW

**Comment by evgengoldwar** [comment]
Can add such a button to disable hatches, i can do pr i have this ready or change to something else if you say so
image

image

**Comment by Glease** [comment]
@evgengoldwar The simple answer is no. That is not the path that **I** will take.

The long answer is I plan to add tooltip to channels, and a way to retrieve all used channel from a controller, or simply add a drop down list to the channel key textbox (since we only have less than a dozen channels by now). I personally prefer not to special case `gt_no_hatch` here.

Still this is only just **my** opinion. If the team decided that a special case here is more beneficial (especially since the solution is ready right now), I'm fine with merging the feature you just mentioned.

**Comment by vovaksenov** [comment]
Personally i would prefer @evgengoldwar 's idea in this case for 2 reasons: first because it is a true/false trigger for which a tick box feels more user-friendly, and second since this seems to be the only channel that applies to all multiblocks independent of their components.

**Comment by Navatusein** [comment]
The idea of copying channels is an interesting one. It would get rid of the mini-game, guess what I support. But in the case of hatches, I think a switch is better. Firstly, there are two positions, either put it or not. Secondly, I doubt that there will be a need for functionality so that inputs are not placed, but energy hatches are placed.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
