### PR TITLE
Change hardness from 5 to 0.8

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7231

### CODE REVIEW

**Comment by Dream-Master** [comment]
0.8 is a bit weak

**Comment by Dream-Master** [comment]
compare with steel pipes

**Comment by Prometheus0000** [comment]
You need to place/remove hundreds of them.

**Comment by Dream-Master** [comment]
yes ik. I removed 300 and more already with hardness 5 so hardness 1.5 should be a good deal

**Comment by Prometheus0000** [comment]
Changed

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
