### PR TITLE
Multi ToolTip unification

### PR DESCRIPTION
**Pull request by Alexdoru**
Reworked the tooltips of multis to follow the same structure, it needs more work to be completely unified, but I'm gonna stop here.

Currently I have :

- Removed all the "------------" that were used as separators in the tooltips and replaced them with an empty line, it's easier on the eyes
- Moved the indication to use a structure hologram to the same place for all tooltips, its at the bottom of the "shift" page
- Removed all the mentions "Added by MODNAME", modnames being gregtech, bartworks, gt++...
- Moved all the author to the bottom of the front tooltip, and changed "author" to "added by" we ain't writing books here
- Hide the line about pollution if it's equal to 0
- Fixed some multiblocks controller names
- Removed the line saying "Controller block for ..." since the name of the machine is litterally 2 lines above, when the same name, only 4 machines have completely different names
- Add a line jump after the second line, the one that says "Machine type:"

As a result all the tooltips should all look like this :

Frist page :
```
Block name
Machine Type: Type

Some description
Some description
Some description

Hold [LSHIFT] to display structure guidelines
Added by: dev name (optional line)
```

Second page:
```
Block name
Dimensions: (WxHxL)
Structure:
    blocks amount
    blocks amount
    blocks amount
    blocks amount

Structure is too complex!
To see the structure, use a Structurelib hologram projector on the controller!
```

Note: a few other mods add multis outside of GT, I edited them to work with this and linked the PR.

### Future plans

In the future we should add an `int state` field in the `MultiblockTooltipBuilder` class that tracks what component you are currently adding to the tooltip and if you don't do it in the correct order, it will crash when in dev env. This would force developpers to all follow the same patterns.

- I have noticed that some multis don't use the `MultiblockTooltipBuilder`, namely the LESU, maybe more, it should be changed
- we need to create and use unified methods in `MultiblockTooltipBuilder` to add parallels, machine efficiency, machine overclocking behavior
- we need to make all multis use the correct structure definition methods, some use deprectated methods to define their structure
- we need to agree on which order we place each element on the tooltip
- create an enum with the different machine types and use that everywhere, for the single blocks too

I think it should be :

```
Block name
Machine Type: Type
Machine lore (optional)

Efficiency, Parrallels (optional)
OverclockingBehavior (optional)
Some description
Some description

Hold [LSHIFT] to display structure guidelines
Added by: dev name (optional line)
```

### CODE REVIEW

**Comment by ShadowTrolll** [comment]
> Removed all the mentions "Added by MODNAME", modnames being gregtech, bartworks, gt++...
Oh man, I was using that to find out which mod added what multi because otherwise they all originate from GregTech so I cannot search by mod :(

**Comment by Alexdoru** [comment]
> > Removed all the mentions "Added by MODNAME", modnames being gregtech, bartworks, gt++...
> 
> Oh man, I was using that to find out which mod added what multi because otherwise they all originate from GregTech so I cannot search by mod :(

why would you need to search by mod ?

**Comment by AbdielKavash** [comment]
> Hide the line about pollution if it's equal to 0

Slight disagree here. It is better to explicitly say that the multi does not generate pollution, than to leave the player wondering whether the information is just missing from the tooltip.

It is fine if you want to reformat it as "Does not generate pollution" or something like that, if the original wording looks awkward, but this information should be present in some form.

**Comment by ShadowTrolll** [comment]
> > > Removed all the mentions "Added by MODNAME", modnames being gregtech, bartworks, gt++...
> > 
> > 
> > Oh man, I was using that to find out which mod added what multi because otherwise they all originate from GregTech so I cannot search by mod :(
> 
> why would you need to search by mod ?

I am using Twist Space and want to see what multi's originate from there so I know what to be aware of. For reporting bugs/avoiding OP stuff/just knowing.

**Comment by boubou19** [comment]
> > > > Removed all the mentions "Added by MODNAME", modnames being gregtech, bartworks, gt++...
> > > 
> > > 
> > > Oh man, I was using that to find out which mod added what multi because otherwise they all originate from GregTech so I cannot search by mod :(
> > 
> > 
> > why would you need to search by mod ?
> 
> I am using Twist Space and want to see what multi's originate from there so I know what to be aware of. For reporting bugs/avoiding OP stuff/just knowing.

Then ask Twist Space to explicit their multi so GTNH ones don't have to be explicited. We don't support this mod.

**Comment by dagger8243** [comment]
> > > Removed all the mentions "Added by MODNAME", modnames being gregtech, bartworks, gt++...
> > 
> > 
> > Oh man, I was using that to find out which mod added what multi because otherwise they all originate from GregTech so I cannot search by mod :(
> 
> why would you need to search by mod ?

what kind of text we talking about here ? could u send a ss please ?

**Comment by Alexdoru** [comment]
I edited all the mods that depend on the multi tooltip builder.

On a side note is there any reason they are scattered around other mods and not moved all to GT5u ?

**Comment by DmitryScaletta** [comment]
> * Removed the line saying "Controller block for ..." since the name of the machine is litterally 2 lines above, when the same name, only 4 machines have completely different names

You probably forgot to remove these lines:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEDroneCentre.java#L180

https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java#L177

https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTERefinery.java#L59

https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEThermalBoiler.java#L282

https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gtnhlanth/common/tileentity/MTELINAC.java#L180

**Comment by Alexdoru** [comment]
> > * Removed the line saying "Controller block for ..." since the name of the machine is litterally 2 lines above, when the same name, only 4 machines have completely different names
> 
> You probably forgot to remove these lines:
> 
> https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEDroneCentre.java#L180
> 
> https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java#L177
> 
> https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTERefinery.java#L59
> 
> https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEThermalBoiler.java#L282
> 
> https://github.com/GTNewHorizons/GT5-Unofficial/blob/ea45d6b817ba19338196226d861a4fcb93f8ad75/src/main/java/gtnhlanth/common/tileentity/MTELINAC.java#L180

You're right I forgot 2 of these however the 3 others it's intended since the block name if very different or for the water line this is the controller of the water line which means all of the other water multi.

**Comment by NotAPenguin0** [comment]
Yeah I think the line should stay for the purification plant.

**Review by FourIsTheNumber — APPROVED** [review]

**Pull request merged**
