### PR TITLE
Rename a lot of classes in the GT codebase to make naming more concise and consistent

### PR DESCRIPTION
**Pull request by NotAPenguin0**
Now that (almost) all the addons are merged into one repository, I think this is a good moment to do some cleanup of some class names in GT5u. I believe making these names shorter will help with code readability and conciseness. Having all names in the codebase follow a consistent format would also be nice. Right now everything is a mess of using `GT_`, `_EM`, or no prefix at all depending on which mod (and not even inside mods is it consistent). Any feedback regarding new naming conventions is of course possible, I'd like to establish some sort of consistent scheme to enforce for the future.

- Tries to remove the `GT_` prefix from class names when sensible. I kept it where the new name would be too generic or confusing, like `GT_Fluid`, though personally I'd like to rename this to `GTFluid` to get rid of the underscores
- Removes the `MetaTileEntity_` prefix when possible, this adds no value to the class name and only makes identifiers a lot longer.
- Renames `survivialBuildPiece` to `survivalBuildPiece`.
- Moved `GT_Packet_Ores` from `blocks/` to `net/` (Why was a packet in the blocks package?). Also renamed to `Packet_Ores`.

Obviously a lot more changes will need to be done in a few other mods, most notably NHCoreMod and GTNH-Intergalactic. I'll take care of those in separate PRs, but until those are up this shouldn't be merged obviously.

All renames were done using IntelliJ's refactoring tools, so while this is a very large diff no behaviour should have changed.

### CODE REVIEW

**Comment by OneEyeMaker** [comment]
We should probably discuss general naming conventions for GT and NHCore:
* Should MTE classes have special prefixes/suffixes? Which ones (if any)?
* Which prefixes/suffixes should be used for block, item and regular tile entity classes?
* Should underscores be allowed or should we enforce strict UpperCamelCase naming?

and so on.

I also suggest moving `GT_TileEntity_Ores` from `blocks/` to `tileentities/...`.

**Comment by Caedis** [comment]
Want to make this a dev-topic in discord or should we just have the discussion here?

**Comment by NotAPenguin0** [comment]
dev-topics seems like a good place

**Comment by Dream-Master** [comment]
@NotAPenguin0 what is the staus of this pr ?

**Comment by NotAPenguin0** [comment]
I think I will close this for now until we are done with merging all the non-frozen PRs, and then redo it with a new established naming scheme

**Comment by Dream-Master** [comment]
ok

**Pull request closed without merging**
