### PR TITLE
Fix T2 PCBFactory NEI structure preview

### PR DESCRIPTION
**Pull request by RealSilverMoon**
NEI structure preview can't show T2&T3 PCBFactory. I add a check to fix it.

Though it's weird that T2 structure lost part of its back. Maybe something related to the structureDefinition or BlockRenderer6343.

### CODE REVIEW

**Comment by HoleFish** [comment]
https://github.com/GTNewHorizons/BlockRenderer6343/pull/17 will be the better solution

**Comment by Quarri6343** [comment]
If you can, please help me to implement a better UI for https://github.com/GTNewHorizons/BlockRenderer6343/pull/17.
The workaround in this PR just makes dependencies worse

**Comment by Dream-Master** [comment]
@RealSilverMoon

**Comment by RealSilverMoon** [comment]
I have noticed that pr, but it doesn't seem to have anything to do with the tier. Blockrenderer calls survivalConstruct() to render multiblock, and the "tier" button only change the stacksize of trigger. However the pcb factory do not check stacksize at all.

**Comment by HoleFish** [comment]
It means the tier should not be determined by the stacksize, but by the schematic configuration options

**Comment by RealSilverMoon** [comment]
Normally yes. Other multi-tiered machines (like nanoForge) use stacksize on construct&survivalConstruct to determine machine tier, so this button would work:
image
While channel is used in structureElement to determine the tier of each pieces.

**Review by Dream-Master — APPROVED** [review]
work for me

**Pull request merged**
