### PR TITLE
Gradle unfck

### PR DESCRIPTION
**Pull request by bartimaeusnek**

### CODE REVIEW

**Comment by draknyte1** [comment]
Pretty sure having a reference to isTranslocator when the methods been stripped throws MethodNotFound. (In the event translocator isn’t loaded) 

If you don’t expect this to ever be the case, no point adjusting the existing code.

**Review by Glease — APPROVED** [review]
I spawned a new EC2 instance and is able to build the project in that clean environment with standard procedures.

**Comment by Prometheus0000** [comment]
Uh, I'm not sure entirely what this does, but isn't the cofhcore for forestry and rf compatibility? To not have the red underlining in eclipse? Was there no need in this repo? Do we not use the same files for building all of them? And is there a particular reason this repo doesn't have the build.bat and other files? Or am I not supposed to use those to build?

**Comment by repo-alt** [comment]
No, you don't need it to build GT. RF support is in COFH lib

**Comment by Glease** [comment]
Prometheus is probably complaining about the lack of `gradlew.bat`. It's basically the same file across every repo. We could probably just copy one in...

**Comment by Prometheus0000** [comment]
Yeah, it's weird it doesn't have the build.bat, gradlew.bat, SetupDevWorkspaces.bat, and SetupWorkspaces.bat when other repos have them and it makes it so easy to build. Or rather, that's the only way I know how to do so. There's no instructions or anything after all. I don't even know what passing is. Using the command line instead?

**Comment by repo-alt** [comment]
Oh, sorry, I have it in my local copy and assumed it is in the repository.

**Comment by repo-alt** [comment]
Passing parameter to a script is in this case typing **gradlew.bat build** in command line. (When that script will be added, but, really, you may copy it from just any other mod repository)

**Comment by Prometheus0000** [comment]
Yeah, I phrased that wrong, that's what I figured. Making it a bat just means you don't have to type it out. Though it would be nice if there was an included command to not close after building (so I can see why it failed).

**Review by Glease — APPROVED** [review]

**Review by glowredman — COMMENTED** [review]
Looks good, needs to be tested though.

**Pull request merged**
