### PR TITLE
Fix PAs overclocking ulv recipes too much

### PR DESCRIPTION
**Pull request by BlueWeabo**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14186

### CODE REVIEW

**Comment by miozune** [comment]
This test fails:
```java
@Test
void ulvRecipeDoesntOverclockExtraWithAmperageWithoutAmperageOCVersion6() {
    GT_OverclockCalculator calculator = new GT_OverclockCalculator().setRecipeEUt(2)
        .setEUt(V[3])
        .setParallel(64)
        .setDuration(20)
        .setAmperageOC(false)
        .setAmperage(3)
        .calculate();
    assertEquals(V[3] * 3, calculator.getConsumption(), messageEUt);
}
```
```
EUt Calculated Wrong ==> expected: <1536> but was: <512>
Expected :1536
Actual   :512
```
Also I noticed this line does nothing:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/9dde44de0fd4b91e8777bef309c0b54f98ddeed9/src/main/java/gregtech/api/util/GT_OverclockCalculator.java#L387

**Comment by BlueWeabo** [comment]
That line will be doing things tho. If there is any eut modifiers or parallels on the multi it will count them for the final EUt usage instead of discarding them.

**Comment by BlueWeabo** [comment]
The test fails because it is overclocking correctly tho. One shouldn't be able to get to that voltage usage when they parallel is that much. 64 * 2 = 128 eut base. we can only overclock once to 512. overclocking another time will bring us to 2048 and not 1536. if we have 48 parallel it will succeed.

**Comment by miozune** [comment]
I don't see any assignment to class field neither in `calculateFinalRecipeEUt` nor `calculateHeatDiscountMultiplier`?

So is it intended to multiply by parallel then overclock, not overclock then parallel? Then it makes sense.

**Comment by BlueWeabo** [comment]
yeah Otherwise if we overclock first it can lead to using up to too much eut. and that is a miss for me. i forgot i made it return something oops.

**Review by miozune — APPROVED** [review]

**Pull request merged**
