### PR TITLE
reenable collision check

### PR DESCRIPTION
**Pull request by chochem**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17104 and many other recipe issues.

Disabling the collision checks can only happen once the collisions are cleaned up, otherwise nightly is just perma broken and we dont get any testers and of course we cant have this in stable either until the cleanup is finished.

There has also been discussion that we might not disable it long term but instead try to implement a faster (tree-based) collision check. But thats a future decision to be made.

image

### CODE REVIEW

**Review by boubou19 — CHANGES_REQUESTED** [review]
No, collision check will remain off. It's the duty to those who toy with recipes and / or those who are curious to see if there is any. Really, enabled or not, not much people aside you, Four, and I will check this. So we can make the effort to pass the flag to the jvm to test it. This shaves too much loading time to be shipped by default when it's just a debug option.

**Comment by chochem** [comment]
why would you want broken nightlies?

**Comment by chochem** [comment]
this is not about curiosity or just for three devs. the pack relies on this (until collision are cleaned up).

**Comment by boubou19** [comment]
because that's what they are supposed to be: testing versions. We know already that we have a bazillion of collisions,and some are here since a very long time, so they can stay a couple of nightlies more. If we wanted to produce perfect nightlies, we would call them stables.

**Comment by chochem** [comment]
well nobody is gonna play test versions if you break them on purpose.

**Comment by boubou19** [comment]
So fix them instead of hidding the issue under the carpet?

**Comment by chochem** [comment]
you are the one that broke it

**Comment by chochem** [comment]
boubou made an annoucement for people to use arg instead

**Pull request closed without merging**
