### PR TITLE
Added Metering Valve from LV to IV

### PR DESCRIPTION
**Pull request by Glease**
They are fluid regulators but only works once per second, hence can satisfy the need to transfer certain fluid amount not a multiple of 20 per second, e.g 41L/sec.

It can probably use a better icon but this is the best I can do. The recipe is 1 Fluid Regulator + 1 Metal Gear from the same tier but this can be changed.

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Is this...needed for plasma gens? Does fluid not transfer per tick? Does it not transfer any some ticks?
For comparison the fluid regulator does:
1L/t or 20L/s, 2L/t or 40L/s, etc

**Comment by Glease** [comment]
It transfers fluid once per 20 ticks.

**Comment by Glease** [comment]
It transfers fluid once per 20 ticks.

**Comment by Prometheus0000** [comment]
And I guess making the fluid regulator more accurate instead might cause explosions?

**Comment by Glease** [comment]
It can be made as a mode of fluid regulator (work once per tick vs work once per second). However, all existing methods of tweaking fluid regulator behavior is used somehow. All of right click, sneak right click and screwdriver right click are used.

**Comment by Prometheus0000** [comment]
Interface only? Or auto-switches if you select a non-multiple of 20 in the second field?
image

**Review by repo-alt — APPROVED** [review]

**Comment by Glease** [comment]
Don't merge this yet. I think I can do this without adding an new item ~~and my crappy texture~~.

**Comment by Glease** [comment]
#452 is probably better since it doesn't need a new item ~~so my ugly texture would not be released to public~~.

**Pull request closed without merging**
