### PR TITLE
Rearrange Super and Quantum Tank GUI a little bit

### PR DESCRIPTION
**Pull request by wlhlm**
After some complaining in Discord, this brings fluid contents and lock slot on the same line and moves the voiding buttons below the lock slot.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@wlhlm btw is it possible to add some gui buttons for the super chest/quantum chest as well? or is this not necessary ?

**Comment by wlhlm** [comment]
Probably. Let me check, I haven't looked at those.

**Comment by wlhlm** [comment]
Those don't have a lock widget.

**Review by miozune — CHANGES_REQUESTED** [review]
Oh now I remember why I placed widgets like this: It prevented accidentally clicking "void all" button when locking fluid. What do you think? @wlhlm @Dream-Master

**Comment by wlhlm** [comment]
I see, that could be a problem indeed. Is this better?

**Comment by miozune** [comment]
yeah that's better

**Pull request merged**
