### PR TITLE
Implementation: Raw Ore Items as Ore Drops

### PR DESCRIPTION
**Pull request by Ethryan**
This is a pull request that adds Raw Ores  as itemdrops for the different ore blocks in Gregtech 5, this means regular, granite, marble, netherrack and end ores all drop the same item that would then be processed down into crushed ore. 
image
For now, The large ore drilling plant isn't affected.
image

In discussions on discord, 4 options on what to do with this material needs to be decided.

~~Previous running ore processing chains will continue to work, and the new items should just join the old blocks since they got the same oredict.~~ Previous setups probably needs editing since singleblocks refuse to work with this enabled, so I reverted it.

All the following options are available as config options in Gregtech.cfg
1: The full new raw ore system is implemented with support for fortune enchantment and all ores now drop a unified raw ore item.
2: The new system is implemented without fortune support.

3: Unified drop per dimension (all ore blocks in the OW drop the stone variant, Nether drops netherrack variant, End drops endstone variant)

4: The whole system is scrapped and ores continue to work as before.

Depending on the vote result I will modify this pull request to fit.

### CODE REVIEW

**Comment by Caedis** [comment]
My ranked vote is:

1
3
2
4

**Comment by cainiaojun** [comment]
I like the 2nd option. 

In my opinion the raw ore should be unified in all dimensions and output only the first byproduct in HV and higher macerator. In other words, there is no need to make the raw ore able to output any type of stone dust. For ores generated in other dimensions like the nether and the end, simply have them drop double the amount of raw ore to make the output the same as before.

How would the small ore be changed?

The texture of the ore should perhaps be more varied? The metal raw ore can use the vanilla raw ore texture, while some ores such as the niter ore and sulphur ore can use another texture, and the gems with another texture(like the picture shows).

**Comment by Ethryan** [comment]
> I like the 2nd option.
> 
> In my opinion the raw ore should be unified in all dimensions and output only the first byproduct in HV and higher macerator. In other words, there is no need to make the raw ore able to output any type of stone dust. For ores generated in other dimensions like the nether and the end, simply have them drop double the amount of raw ore to make the output the same as before.
> 
> How would the small ore be changed?
> 
> The texture of the ore should perhaps be more varied? The metal raw ore can use the vanilla raw ore texture, while some ores such as the niter ore and sulphur ore can use another texture, and the gems with another texture(like the picture shows).

Small ores isn’t changed and still drops crushed ores, and dusts.

**Comment by Dream-Master** [comment]
If we not use the fortune option why it will be worth to add it at all. I don’t see the benefit. I start the game in 2.5.1 and the few orestone variants I had wasn’t a problem to handle . If we add it we should use the fortune option but balance it to avoid mid/lategame balance.

**Comment by Ethryan** [comment]
> If we not use the fortune option why it will be worth to add it at all. I don’t see the benefit. I start the game in 2.5.1 and the few orestone variants I had wasn’t a problem to handle . If we add it we should use the fortune option but balance it to avoid mid/lategame balance.

Agreed

**Comment by chochem** [comment]
Yea, my choice would also be to no do this at all.

The only potential change that got a good amount of support among devs in #meta-dev was option 3. It's not a huge change, so yea I guess, whatever. But if dream doesn't like it then it is out too.

**Comment by cainiaojun** [comment]
> > I like the 2nd option.
> > In my opinion the raw ore should be unified in all dimensions and output only the first byproduct in HV and higher macerator. In other words, there is no need to make the raw ore able to output any type of stone dust. For ores generated in other dimensions like the nether and the end, simply have them drop double the amount of raw ore to make the output the same as before.
> > How would the small ore be changed?
> > The texture of the ore should perhaps be more varied? The metal raw ore can use the vanilla raw ore texture, while some ores such as the niter ore and sulphur ore can use another texture, and the gems with another texture(like the picture shows).
> 
> Small ores isn’t changed and still drops crushed ores, and dusts.

Bro I just confused the 1st option and the 2nd one sorry :(

That means this change only have a little benefit to the players' backpack. There are voices saying that to fully save players' backpack we should totally replace other ore variants with the stone one(I don't agree this at all and DreamMaster said the ore was not a problem too). In my own view, if we can find a way that enable players to get raw ores instead of annoying crushed ores and dusts(if you are mining in the twilight forest, your backpack would easily be filled by crushed gem ores and gem dusts because almost all kinds of gem small ores generated there), it would be better. But the original plan is still good and if we don't reach an agreement about how to change the small ores, we can just use the original one and do nothing on the small ore at all.

And the option 3 looks very reasonable now after some discussions I had done in other place to fetch more info about the raw ore .

**Comment by Dream-Master** [comment]
> Yea, my choice would also be to no do this at all.
> 
> The only potential change that got a good amount of support among devs in #meta-dev was option 3. It's not a huge change, so yea I guess, whatever. But if dream doesn't like it then it is out too.

What i mean  is we add a new system we not realy use. Why not use the fortune on hand mined level and disabled it with the miner (multi miner not the single block) so eraly game will buffed a bit late and midgame untouched. At Ev and ore drill you not mine the full blocks anyways.

**Comment by Dream-Master** [comment]
If we add this to gt we can disable the behaviour on drills i would guess.

**Comment by Caedis** [comment]
This PR doesnt affect multiblock miners at all, this is only for manually mining and the single block miners that give the ore block.

Multiblock miners will still to continue to give crushed ores and the like

**Comment by Caedis** [comment]
Small ores are also unaffected

**Comment by Caedis** [comment]
Correct. The original idea behind the PR was to give fortune an actual use besides small ores.

**Comment by Dream-Master** [comment]
> Correct. The original idea behind the PR was to give fortune an actual use besides small ores.

ok then i would say choose option one but we need to dicuss the drop rate to make it not that op. And all quests need a rework :(

**Comment by Dream-Master** [comment]
> To make sure this is noted, the raw ores will still have the same oredict as the ore blocks so oredict based ore processing wont be affected

did it not replace oreblock drop or did i read it wrong ? Or did it need a macerator ?

**Comment by Ethryan** [comment]
> > To make sure this is noted, the raw ores will still have the same oredict as the ore blocks so oredict based ore processing wont be affected
> 
> did it not replace oreblock drop or did i read it wrong ? Or did it need a macerator ?

I added it to the "ore" oredict, in order to fix the issue for existing setups.

**Comment by chochem** [comment]
> > Yea, my choice would also be to no do this at all.
> > The only potential change that got a good amount of support among devs in #meta-dev was option 3. It's not a huge change, so yea I guess, whatever. But if dream doesn't like it then it is out too.
> 
> What i mean is we add a new system we not realy use. Why not use the fortune on hand mined level and disabled it with the miner (multi miner not the single block) so eraly game will buffed a bit late and midgame untouched. At Ev and ore drill you not mine the full blocks anyways.

that would need a lot of rebalancing. like drastically reducing vein densities or something. which would have further consequences in turn and so on. Early tiers are in a good state currently without changes.

Also, Gt already has 6 variants (ore, crushed, crushed purified, purified pile, impure pile, dust) for each ore without accounting for stone variants. I really dont think it needs more. this not vanilla where there was only 1.

I dont think redoing the early game all the time is a good way to go about things. There is a reason that is in the Code of Conduct. Supposedly Ethryan has agreed to this CoC.

**Comment by Dream-Master** [comment]
> > > Yea, my choice would also be to no do this at all.
> > > The only potential change that got a good amount of support among devs in #meta-dev was option 3. It's not a huge change, so yea I guess, whatever. But if dream doesn't like it then it is out too.
> > 
> > 
> > What i mean is we add a new system we not realy use. Why not use the fortune on hand mined level and disabled it with the miner (multi miner not the single block) so eraly game will buffed a bit late and midgame untouched. At Ev and ore drill you not mine the full blocks anyways.
> 
> that would need a lot of rebalancing. like drastically reducing vein densities or something. which would have further consequences in turn and so on. Early tiers are in a good state currently without changes.
> 
> Also, Gt already has 6 variants (ore, crushed, crushed purified, purified pile, impure pile, dust) for each ore without accounting for stone variants. I really dont think it needs more. this not vanilla where there was only 1.
> 
> I dont think redoing the early game all the time is a good way to go about things. There is a reason that is in the Code of Conduct. Supposedly Ethryan has agreed to this CoC.

lets have first the vaulus of ores and products and then lets discuss what we can do. Without the fortune system the new process stuff is mostly useless.

**Comment by Caedis** [comment]
> > > Yea, my choice would also be to no do this at all.
> > > The only potential change that got a good amount of support among devs in #meta-dev was option 3. It's not a huge change, so yea I guess, whatever. But if dream doesn't like it then it is out too.
> > 
> > 
> > What i mean is we add a new system we not realy use. Why not use the fortune on hand mined level and disabled it with the miner (multi miner not the single block) so eraly game will buffed a bit late and midgame untouched. At Ev and ore drill you not mine the full blocks anyways.
> 
> that would need a lot of rebalancing. like drastically reducing vein densities or something. which would have further consequences in turn and so on. Early tiers are in a good state currently without changes.
> 
> Also, Gt already has 6 variants (ore, crushed, crushed purified, purified pile, impure pile, dust) for each ore without accounting for stone variants. I really dont think it needs more. this not vanilla where there was only 1.
> 
> I dont think redoing the early game all the time is a good way to go about things. There is a reason that is in the Code of Conduct. Supposedly Ethryan has agreed to this CoC.

That is what this PR is for. To discuss it. I hate having the entire discussion in 1 channel as information gets lost. I would rather the discussion be centralized.


Also if we shrink ore veins, then getting fortune will be required.

**Comment by AbdielKavash** [comment]
> I added it to the "ore" oredict, in order to fix the issue for existing setups.

Does that mean there is no way for automation to filter between the block ores and the broken ores? That is an issue. Unless you mean some other tag starting with `ore`.

---

Another point that has not been brought up here yet is that ore drops being affected by fortune would be a big buff to the Mark of the Falling Tower (meteor ritual) from Blood Magic. Which is, in my own opinion, already borderline overpowered.

---

Overall I am not a big fan of the change, sorry. However I don't have any specific reasons for it. It just feels like a solution that is looking for a problem. If your goal is to unify the different stone type ores, you can make ores appear varied in-world, but when broken, always drop the basic stone variant. If your goal is to buff early game manual mining, there are better ways to do that without having to rework such a fundamental system with potentially unforeseen consequences.

**Review by Connor-Colenso — DISMISSED** [review]
Needs additional discussion in #meta-dev after 2.6.0 given the prior vote result.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
