### PR TITLE
Change UIV motor to use molten PHK rather than Superdense

### PR DESCRIPTION
**Pull request by serenibyss**
Superdense Proto-Halkonite Plates in the UIV motor CoAL recipe proved to be too much of a strain on bases even into later tiers. This PR moves them to using molten forms instead to lessen the load on benders, black hole compressors, and vacuum freezers.

Sidenote: the CoAL recipe loader code is quite challenging, apologies for making it worse 😅 

image
One recipe mirrors the infinity chem bath recipe, while the other mirrors an even split between the Creon and Mellion chem bath recipes

### CODE REVIEW

**Review by NotAPenguin0 — COMMENTED** [review]
Should this also use additional superfluid and super coolant to match the cooling step?

**Comment by boubou19** [comment]
tbh coal recipes should just be hardcoded. Autogen is cool and all, but fuck it, the code is a nightmare

**Comment by miozune** [comment]
It would be cool if we hardcode recipe but still ensure cost by writing test. The original reason of autogen was that hardcoding CoAL recipes can be easily messed up with changes to the base recipes, but now we have right tool to run test that requires booting the game.

**Comment by EnderProyects** [comment]
> Should this also use additional superfluid and super coolant to match the cooling step?

If the normal process need it because it's more materialx I don't see why a machine that does the same but in the inside doesn't

**Comment by serenibyss** [comment]
> tbh coal recipes should just be hardcoded. Autogen is cool and all, but fuck it, the code is a nightmare

I'd love to clean this code up in a follow-up refactor but I think that's out of scope for this PR

**Review by NotAPenguin0 — APPROVED** [review]

**Pull request merged**
