### PR TITLE
Added Fusion Reactor recipe for Naquadria

### PR DESCRIPTION
**Pull request by johnch18**
3 Plutonium + 2 Naquadah -> 1 Naquadria. Takes ~4 seconds, is a UV recipe.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@johnch18 can you post here what is the normal recipe to get Naquadria ? Thanks

**Comment by johnch18** [comment]
The original was:
  ` GT_Values.RA.addFusionReactorRecipe(Materials.NaquadahEnriched.getMolten(15), Materials.Radon.getGas(125), Materials.Naquadria.getMolten(3), 64, 49152, 400000000); `

**Comment by johnch18** [comment]
I'm more than willing to change the recipe, just as long as naquadria gets added :)

**Comment by Dream-Master** [comment]
The idea is not bad adding more recipes to fusion. I guess we need to check first if this is balanced

**Comment by johnch18** [comment]
This one was kind of arbitrary. I used Pu239 because 241 is used in Americium and I didn't want to be repetitive, Naquadah is just kind of a base. If I could change anything I'd probably change it to Enriched Nq and maybe U235.

**Comment by johnch18** [comment]
My general train of thought is (radioactive thing) + (naquadah thing) -> naquadria

**Comment by Dream-Master** [comment]
i see a lot of reverts and stuff. Is this still an pr we have to discussed or closed? @johnch18

**Comment by johnch18** [comment]
No that's just because I had to figure out how to use branching properly lmao. I've never worked with a git project this complex.

**Comment by Dream-Master** [comment]
I am not against new fusion recipes but maybe we add a new pr or branch for it including an rfc issue so we can talk about balance

**Comment by johnch18** [comment]
It's not so much the idea I have issue with. It's the fact that I committed this change to my master branch. I'm really annoyed with that

**Pull request closed without merging**
