### PR TITLE
Opyrobe ticket

### PR DESCRIPTION
**Pull request by POPlol333**
here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9353

### CODE REVIEW

**Comment by POPlol333** [comment]
As now I don't have time for ""huge"" work like this neither motivation, so I'm just gonna close it and open it someday if I feel motivated enough

**Comment by Dream-Master** [comment]
@POPlol333 if you don’t continue it maybe someone else? What us missing to finish it up?

**Comment by POPlol333** [comment]
As far as I remember there the ofBlockTiered implemented, but those tiered block are still missing for test purpose I just placed some random blocks actually, behavior also miss

**Comment by POPlol333** [comment]
I wanted 2 modes (screwdriver go brr), one generating air at good enough speed for a MCR *256 radon 1t so we could avoid having 2 full MS of air intake hatch just to generate fucking air and the others modes for the opyrobe thingy

**Comment by POPlol333** [comment]
or maybe tiered block are already in but miss thing don't remember ngl

**Pull request closed without merging**
