### PR TITLE
Rework Stocking Bus

### PR DESCRIPTION
**Pull request by miozune**
- It now stores actual items instead of ghost items from ME network.
  - Fix longstanding dupe bug.
  - Remove workaround in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2104.
- It tries to push back stored items when broken. You can also safely dismantle the hatch with GUI button.
- You can set fetch interval and fetch limit per slot. You can also apply it for all other slots with one click, or store those settings to data stick.
- Add network status display on GUI.
- Make all texts translatable.

### CODE REVIEW

**Comment by lordIcocain** [comment]
Would be really cool if you make functional that divide storage between all buses in network. For example in storage 64 items and in network 8 stocking buses, so each take 8. Even field were you can manually set num of buses in networks would be fine too.

**Comment by miozune** [comment]
I'm not sure if such a feature is even doable. But you can still keep load balancer functionality by setting maximum amount of items to fetch per slot, that's why I added the feature.

**Comment by lordIcocain** [comment]
What about add check box "load balancer" and another input field, when active you can set divide, so each pull it will calculate "ALL ITEMS / DIVIDER = ITEMS PER FLETCH"
maximum amount of items to fetch per slot will work, but in one situation you need feed 8192 per tick (fast craft), in second you need 64 per 10 second (long craft), with static number per fletch you cant good balance both situation.

**Comment by miaowwwwww** [comment]
is there a way to let an array of buses to pull exact amount at the same time? for ex, pull 1A 2B to bus A &bus B respectively at the same time. because,,,, i use the stocking bus for AAL parallels, it would be a lot harder with the new pulling mechanic. 
image
this is 32 optical assembly AALs. the old stocking allows me to control the item inputs, the new one would force me to put a lot of materials in just to make it fit with the system. which I dislike.

**Comment by miaowwwwww** [comment]
this is basically taking away the best feature of stocking bus. I know that we are trying to fix the dupe bug, but is there a better way?

**Comment by JodieRuth** [comment]
Since it has been changed to a physical item instead of a shadow item, it is necessary to add a new hatch directly linked to the stocking bus, just like the crafting input buffer and its crafting input slaves.Otherwise, the current modifications to the stocking bus will be destructive and will result in it losing some irreplaceable functions

**Comment by tth05** [comment]
Why wasn't [this](https://github.com/GTNewHorizons/GT5-Unofficial/commit/581e5906767054a62d3f56f50dcdaf1a47001cfc) simple fix implement in a proper way instead (i.e. make `endRecipeProcessing` return a boolean which can cancel the recipe check, or something more sophisticated)? With this, the machine would simply disable itself when players build a setup that dupes. Nothing else will change. While the fix is not perfect, it doesn't annoy/prevent any proper usage, but prevents the dupe.

This new behavior breaks the incredible functionality of stocking input bus just to fix a dupe which no player should use and probably has never been used unintentionally.
In my opinion, even without taking into account the simple fix available linked above, fixing a simple niche dupe shouldn't cause tons of bases to be rebuild and tons of setups to break. It's simply not worth it.

**Comment by miozune** [comment]
Thanks for your opinions. I'll think more about this issue tomorrow with a clearer brain.

**Comment by Glease** [comment]
Stocking input bus actually pulling item in also have the added benefit of performance boost, as you won't poll the ME network once per tick (and in a few cases more than once). This is why people found Interface+conveyor+input bus can sometimes cause less lag than one Stocking Input Bus

**Comment by Divran** [comment]
changing it to pull items this way would also require you to go around and increase the pull amount over time as you upgrade your setups so they gain more parallel. especially in ore processing, but also in many other setups. current stocking bus behavior handles that automatically.

> Stocking input bus actually pulling item in also have the added benefit of performance boost, as you won't poll the ME network once per tick (and in a few cases more than once). This is why people found Interface+conveyor+input bus can sometimes cause less lag than one Stocking Input Bus

this doesnt happen with current stocking bus if you simply enable batch mode (which you should always do anyway) because then it will only update once per 6.3 ish seconds. or when in auto pull mode it only updates once per 5s I believe

**Comment by miozune** [comment]
We have found a way to fix the issue without making the hatch storing actual items, so I'm closing this PR.

**Pull request closed without merging**
