### PR TITLE
Rework the UI of singleblock pumps.

### PR DESCRIPTION
**Pull request by AbdielKavash**
Before:

This is not a pump, this is a tank with ambitions.

After:

New, shiny, unified with all other machines.

All functions of the UI work as expected.

The exterior textures also received a small facelift.

This addresses https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14942.

-----------

Some technical details: The singleblock pump class was previously extending `GT_MetaTileEntity_BasicTank`, which caused the previous UI to be what it is. This PR changes the class to extend `GT_MetaTileEntity_BasicMachine`, and employ all of the advanced features such as real input/output slots, battery slot, auto-output, etc.

I have not changed any of the processing logic, other than pointing item and fluid I/O into the correct slots.

The progress bar is still a little buggy, although this is only a visual issue. The pump logic as it exists is *very* non-standard, and the progress bar is basically faked at this point. I intend to rework the pump logic at some point in the near future to bring it in line with most other GT machines; but this will be a new PR.

Existing pumps in world convert correctly, stored fluid and mining pipes are preserved. However as the old pump doesn't care about orientation, the reworked pump starts facing a fairly arbitrary direction. This might potentially result in the pump's front face facing towards the power connection, which would make the pump unable to pull power any longer. After updating, players are advised to check on their pumps and adjust their rotation if necessary.

### CODE REVIEW

**Comment by bombcar** [comment]
Previous pumps had some weird stacking ability hinted by the QB but never actually used by mortal man. 

Anyone know what that was and does anyone use it anywhere?

**Comment by AbdielKavash** [comment]
You can stack up to 21 pumps vertically on top of each other. Then the bottom pump will work N times faster (if N is the number of pumps you stack), while still consuming the same amount of power.

I have never seen this used, in fact I only leaned of this functionality today when I was going over the code. I am strongly considering just removing it. Any objections?

**Comment by mitchej123** [comment]
> You can stack up to 21 pumps vertically on top of each other. Then the bottom pump will work N times faster (if N is the number of pumps you stack), while still consuming the same amount of power.
> 
> I have never seen this used or mentioned by anyone, in fact I only leaned of this functionality today when I was going over the code. I am strongly considering just removing it. Any objections?

I also found it, when refactoring the code to fix pumps... many years back.

It was an interesting easter egg that I didn't see any harm in keeping around.

I've personally used it locally multiple times since learning about it.

I'd be slightly more in favor of keeping it around as an ode to greg, if nothing else.

**Comment by Ethryan** [comment]
Maybe add a note somewhere, something like: Been a thing since stackable pumps.

Just to give people a tiny hint about it.

**Comment by AbdielKavash** [comment]
I am down with fixing it up and mentioning it somewhere. Once the pump is moved to proper processing logic it shouldn't be that hard to increase speed without ugly hacks like it is now. (I actually have it like halfway done already in my fork.)

**Comment by Pilad** [comment]
Thanks for fixing the pump

**Review by OneEyeMaker — APPROVED** [review]

**Pull request merged**
