### PR TITLE
shortened sc cooling times

### PR DESCRIPTION
**Pull request by bartimaeusnek**
-> ductape fix for fusion reactor

+cleaned up code

addresses  4333 Makes fusion craftable in 20h instead of 100ish
(this shortens the cooling time from 28800s to 9600s per CoilBlock at LuV, 14400 to 4800 at ZPM, 7200 to 2400 at UV and 3600 to 1200 at UHV).

Signed-off-by: bartimaeusnek <33183715+bartimaeusnek@users.noreply.github.com>

### CODE REVIEW

**Comment by 0lafe** [comment]
Lowering SC cooling is retarded and doesn't fix anything fusion related. It also doesn't even lower the cost of the completed SC wires. The only thing it does is cheapen the power needed for making the base which isn't an issue to begin with and can even go up without effecting overall completion time. SC cooling would need to be 1600s+ without a pump cost change to make an impact on overall SC time, and 1100s+ with pump change.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4338 <- this thread pretty much sums up why the reduction does makes sense. 

> It also doesn't even lower the cost of the completed SC wires. The only thing it does is cheapen the power needed for making the base which isn't an issue to begin with and can even go up without effecting overall completion time.

In a perfectly balanced setup with unlimited power generation, that might be true, but doesnt reflect actual gameplay.

**Comment by ScriptedPiky** [comment]
> Lowering SC cooling is retarded and doesn't fix anything fusion related. It also doesn't even lower the cost of the completed SC wires. The only thing it does is cheapen the power needed for making the base which isn't an issue to begin with and can even go up without affecting overall completion time.

Explain to me how it doesn't fix anything fusion related. If the change I proposed severely reduces the cooling time of hot Superconductors, will it not lessen the required overall time in some way? Let us assume that a random player at this tier has already cooked 1024 ingots total without cooling them previously, now let's look at the math for how long this will take to cool at exactly 1A IV in 1 Vacuum Freezer:
Current Patch - 450 seconds per ingot, or 460800 seconds total. This would take a total of 5 days and 8 hours of pure IV input. This would require 70,778,880,000 EU to complete all the ingots. This time is also based on absolute perfect 20.00 TPS on a server with no lag in between.
Post Patch - 150 seconds per ingot, or 153600 seconds total. This would take a total of 1 day and 18 hours of pure IV input. This would now require 23,040,000 EU to complete all the ingots. This DRASTICALLY reduces the amount of time and tedium required to cool 1024 ingots.
Now, this is based on 1024 ingots and this may or may not be accurate to represent the current stage of the Fusion Reactor. Overall, I believe that my change to the current Superconductors will affect many parts of the game's balance in a positive way, as to relieve players of the tedious task of cooling these ingots. Remember, a change like this can always improve the positivity of the Community's views on how they view the current Superconductors, we may even see a shift in the meta towards the use of Superconductors if the Community sees it fit

**Comment by Anarack** [comment]
If olafe is going off what I think he is if you look at the total smelting/cooling time of all the supers conductor components required for the reactor the cooling time is lower than the freezing. or that is the case with my original math, not sure what changes have been done so that may no longer be the case.

**Pull request merged**
