### PR TITLE
Re-tiered Mufflers for now

### PR DESCRIPTION
**Pull request by bartimaeusnek**

### CODE REVIEW

**Comment by KiloJoel** [comment]
Doesn't this make LV-EV mufflers worse?

**Comment by Prometheus0000** [comment]
At what tier does it reach 100% reduction? It looks like UHV. Are there any higher tier mufflers? Should we even allow 100% reduction? And of course this make the GT++ one worthless.

**Comment by bartimaeusnek** [comment]
> Doesn't this make LV-EV mufflers worse?

yes. Price/Performance optimum was EV prior to this, which meant, people stop using higher tiered ones.


>At what tier does it reach 100% reduction? It looks like UHV. Are there any higher tier mufflers? Should we even allow 100% reduction?

It was meant to be 100% at MAX tier, but sadly we arent there yet, so logical gameplay choice is to have it at maximum reachable tier (currently UHV), retiering it isnt a big deal later on once we add more tiers.
 
> And of course this make the GT++ one worthless.

well that aint my problem.

**Comment by KiloJoel** [comment]
>yes. Price/Performance optimum was EV prior to this, which meant, people stop using higher tiered ones.

don't mufflers need a buff, not a nerf? pollution isn't a problem only IV+

for reference the change makes it from
100/85/72/61/52/44/37/32/27
to
100/87.5/75/62.5/50/37.5/25/12.5/0

**Comment by bartimaeusnek** [comment]
> >yes. Price/Performance optimum was EV prior to this, which meant, people stop using higher tiered ones.
> 
> don't mufflers need a buff, not a nerf? pollution isn't a problem only IV+
> 
> for reference the change makes it from
> 100/85/72/61/52/44/37/32/27
> to
> 100/87.5/75/62.5/50/37.5/25/12.5/0

Overall that's a pretty big buff for 5/8 available tiers, while being a minor nerf for the others.

**Comment by Prometheus0000** [comment]
And which tiers are most players at though?

**Comment by leagris** [comment]
Pollution was added as an incentive to not du stupid things that too often impact servers performances, like spamming low tier machines.

Now it is turned into a beginners bullying with the top happy few elite not even affected. And you want to amplify the unjust mechanic?

**Comment by Dream-Master** [comment]
If we retier it we need to add better anti pollution machines and stuff.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7217

**Comment by alphaNOVAircraft** [comment]
> Pollution was added as an incentive to not du stupid things that too often impact servers performances, like spamming low tier machines.
> 
> Now it is turned into a beginners bullying with the top happy few elite not even affected. And you want to amplify the unjust mechanic?

So you want to tell me that its fine that its not even worth upgrading mufflers past maybe ev/iv for your mbf, cz even the highest tier mufflers wont protect you. 
In lategame ppl dont spam early game machines anyways, they need the machine cz the balance of lategame is a lot dependend on how much you can smelt. And even 5% pollution of mbf is a shit ton

**Review by Dream-Master — APPROVED** [review]

**Comment by Skiftcha** [comment]
what about advanced mufflers? UHV has 0% and advanced 2% pollution

**Pull request merged**
