### PR TITLE
Liquid Render inside Large Fluid Cells

### PR DESCRIPTION
**Pull request by TimeConqueror**
Suggested in: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8392

### CODE REVIEW

**Comment by D-Cysteine** [comment]
I think this is a simpler way of finding large fluid cells to do the fluid rendering: https://github.com/D-Cysteine/GT5-Unofficial/commit/7072e3cd633a9a1ed9c08ea84885ba9bfb7b89ae
Though, it doesn't support custom window shapes, as I just re-used the regular cell window. What do you think?

**Comment by TimeConqueror** [comment]
> I think this is a simpler way of finding large fluid cells to do the fluid rendering: [D-Cysteine@7072e3c](https://github.com/D-Cysteine/GT5-Unofficial/commit/7072e3cd633a9a1ed9c08ea84885ba9bfb7b89ae)
> Though, it doesn't support custom window shapes, as I just re-used the regular cell window. What do you think?

Well the main problem here is that cells don't have inner part in empty state

**Comment by D-Cysteine** [comment]
Ah, good point! I was just going with how the regular cells look.

Hmm, I wonder if it would be possible to combine the two approaches? Something like, instead of `BitSet`, use `Map<Short, IICon>` to store which things are large fluid cells, as well as their inner icon. This would allow us to not need the unsafe get stack method, as well as change the large fluid cell lookup from `O(# of large fluid cell types)` to `O(1)`.

Actually, materials already have a color associated with them, so maybe even better would be to get the material and just have a single icon and color it by looking up the material color.

**Comment by jesuseduardo90** [comment]
this is beyond my programing levels but for the comment that the large cell doesnt use glass, so they dont have windows, just add glass to the crafting, idunno:v
(the empty cell also doesnt use glass:v)

**Review by glowredman — APPROVED** [review]
Looks good from what I can tell

**Pull request merged**
