### PR TITLE
Plasma Line buffs, EHE nerfs, Unstable Naquadah rebalance

### PR DESCRIPTION
**Pull request by S4mpsa**
The Extreme Heat Exchanger completely bypasses the earlier Plasma Turbine nerf, while additionally increasing the EU per unit of Plasma by !200%! for essentially free. Even more, the intended loop of Distilled Water -> SC Steam -> Steam -> Distilled Water is generally ignored, as 99% of the EU from the plasma is contained within the SC steam, and the distilled water can be bruteforced with a mega distillation tower.

This PR nerfs the EHE by ~40%, heavily incentivizes the usage of a Steam turbine after the SC step, and buffs the Power Plasma line to make it a more attractive option over using simple plasmas such as Helium and Silver with the EHE.

**Material changes**
Extremely Unstable Naquadah has been rebalanced to be similar to SpNt:
375% -> 235% Efficiency 
12M -> 70M Durability
4500 -> 2000 SC Flow

This makes it similar to SpNt, a good Turbine material available 2 tiers later. With its current values, the turbine is only  beaten in efficiency by Shirabon and Eternity (UMV and UXV materials respectively), which is utterly stupid for a material you can acquire in IV.

**Plasma Line changes**
- Change Force Plasma fuel value from 150M to 180M
- Change Force Plasma recipe time from 64 ticks to 32 ticks
(~40% buff per reactor)

- Change Runite Plasma recipe time from 32 to 16 ticks
(~17% buff per reactor)

- Change Celestial Tungsten recipe time from 16 ticks to 8 ticks
- Change Advanced Nitinol Plasma input from 144 to 72
(~50% buff per reactor)

**Extreme Heat Exchanger loop change + nerf**

- Make the EHE be able to consume more Plasma depending on the fuel value (Reduce spam and incentivize higher tiers of plasma)
- Change EHE efficiency from 300% to 120%
- Make SC Turbines produce 100L of Steam per 1L of SC Steam
- This changes the ratio of EU within the turbines from 99:11 (SC:SH) to 66:33, incentivizing the use of normal steam turbines to 1. Recover the distilled water and 2. get one third of the energy from plasma.
- The EHE has a 180% Fuel value efficiency over Plasma turbines by utilizing the extra steam, but requires two sets of turbines instead of one. With just the SC turbine, the efficiency is 120% over using Plasma turbines.

### CODE REVIEW

**Comment by Junyan721113** [comment]
How can a Distilled Water Loop be achieved when 72ML/t of Normal Steam flow is needed by a Mega SC Turbine with Extremely Unstable Naquadah rotors?

**Comment by S4mpsa** [comment]
I'm not sure what you mean?
Supercritical Steam turbine does not use Normal Steam, but Supercritical Steam

The EHE takes in 10L of Distilled Water, creates 160L of SC Steam, which converts into 1600L of normal Steam, which then condenses back into 10L of Distilled Water in the Large Steam Turbine.

**Comment by Junyan721113** [comment]
If I'm not comprehending it wrong, the optimal SG Steam flow of an XL Extremely Unstable Naquadah rotor would be 450,000 L/t after the change. In Mega SC Turbine the SG Steam flow is 16x, which means 7,200,000 L/t, converting into 72,000,000 L/t of normal Steam. Now here is the question: how to delivery 72,000,000 L/t of normal Steam into Large Steam Turbines?

**Comment by S4mpsa** [comment]
Using the same turbines, they consume 49,824,332L of Steam per tick in Loose mode, so turbines will not be the limit here.

ME Stocking Hatches work with XL Turbines, which allow you to process up to 2.14B of Steam per tick.

In a quick and dirty test environment I was able to easily process all of the Steam coming from the EHE, although not at a perfect efficiency. That's the intended tradeoff for using the EHE: How do you handle the massive fluid amounts for good efficiency to gain that +50% EU boost from the Plasma?

If you don't want to deal with the automation problem, you can always use the normal Plasma Turbines / XL Turbines.

**Comment by Junyan721113** [comment]
ME Stocking Hatches consumes energy a lot. ME Stocking Hatch handling 72,000,000L/t of Steam flow could consume ~350M EU/t, which is even more than the power it can generate. This means that a Neutronium Energy Cell is a must, is this an expected side-effect?

**Comment by S4mpsa** [comment]
Do you have access to extremely unstable naquadah turbines without having access to the neutronium energy cells?

**Comment by Junyan721113** [comment]
XL rotor can be produced after MKII fusion,  Extremely Unstable Naquadah can be produced at a ZPM EBF (right after `Nq+` and `Nq*` 
production in ZPM quests), while Neutronium Energy Cell is an UHV quest.

**Comment by S4mpsa** [comment]
But are you realistically going to be producing 822 amps of ZPM (3080 if we factor in efficiency) in ZPM?

There's a lot of hypotheticals that we can have, but the only way to see if the automation problems are too difficult to overcome is by letting players try to solve them. If it turns out there's no way to handle the steam flow, I can add new Steam-only hatches for example.

**Comment by Junyan721113** [comment]
Components costs much more after first Assemble Line in LuV. Before Infinity Ingot could be crafted, EBFs producing `Nt` and `SpNt` at a 'playable' speed requires at least 256A ZPM, not to mention Vaccum Freezers and MT-3662.
However, I agree with adding new Steam-related hatches before other players started to use bugs to avoid the Steam flow problems.

**Comment by Nxer** [comment]
- Better to not adjust the base conversion ratio of SC Steam -> EU. Just adjust output amount of two Steam.
 - Changing EHE 300% efficiency requires more careful consideration, otherwise the steam power generation system will lose its meaning. If the use of EHE cannot increase the actual equivalent output power of the fusion reactor, then players will most likely give up using this system. Of course, it is a good idea to transfer the extra yield from SC to SH.

Suggestions
 - If you want to nerf low tier plasma, you can think of decreasing the conversion speed of every EHE. If the player insists on using low tier plasma, they will have to use more EHEs.
 - Also, improving conversion speed is also a direct buff option.
 - Reduce the conversion rate of plasma-SC and then increase the conversion rate of SC-SH. To transfer benefit.

**Comment by S4mpsa** [comment]
The SC Steam EU Density could probably be kept at 100, and make it output 100L of Steam per 1L of SC Steam consumed. Might be less of a breaking change.

For the EHE efficiency, 300% is *way* too high for the effort required. With this change, the efficiency goes to 150% instead, but the player actually has to do something to get that efficiency (use the normal steam on top of the superheated steam). It's a huge nerf, yes, but tripling the power output for essentially no effort just shouldn't exist.

Making EHEs even slower is counterproductive and leads to people spamming them even more. That's why I increased their maximum flow by 10 times, to reduce the EHE spam.

**Comment by Nxer** [comment]
- Let player to choose whether to use advanced plasma or place more EHEs. Just a consideration.
 - For the efficiency, if there is no direct benefit from using EHE, then in the future it is likely that advanced plasma will be used directly for power generation, giving up the extra benefit of steam in exchange for convenience. Converting to Steam is also a step, its logistics cost is much higher than that of using plasma directly. So I said there should be more careful.
 - I agree with reducing the direct additional efficiency of EHE, but I don't agree with reducing it to 0.

**Comment by S4mpsa** [comment]
I suppose I could dynamically change the maximum amount of plasma the EHE can process per second, based on the fuel value of the plasma.

For the efficiency, that is exactly what this change aims to achieve. Make the player consider if the additional efficiency is worth the increased logistical complexity. Right now it's a no-brainer to always use the EHE. I could keep a small (~20%) boost for the SC steam, which also carries over to normal steam for a total boost of 80%.

**Comment by dimazha** [comment]
> Do you have access to extremely unstable naquadah turbines without having access to the neutronium energy cells

Yes
Unstable Nq can be made even in 16A IV MEBF. It's not something incredible. But energy consumption of Fluid Stocking Hatch is not a problem. Tier of Fluid Stocking Hatch is a problem. You can craft it only in late ZPM-UV. How should we deliver normal steam without Stocking? Compact MK1 with Helium plasma will give 9.5m/t of normal Steam. Even with weak Helium plasma. What about other plasmas in plasmachain? Maybe it's better to add a Steam Input/Output Hatches with increased capacity but usable only for Steam? Like Air Hatch for air distillation

**Comment by Cinobi** [comment]
Actually i have better idea - lets face it, adding one more turbine in a chain add no difficulty and no intererest. Lets just remove SC steam - normal steam convestation and force SC turbine output distilled water. Make it break 2x more often if u want.

**Review by boubou19 — APPROVED** [review]

**Comment by Reflex18** [comment]
While it might be out of scope, it would be nice if there were some use for force and runic as a material. Since currently it is made as a plasma but the material itself it effective a waste product to be voided.

**Pull request merged**
