### PR TITLE
Change graphene recipe again

### PR DESCRIPTION
**Pull request by Glease**
Key points:
1. You do not loss graphite whatsoever.
2. Advanced wafer offers one perfect overclock, and less glue usage (if anyone care at all)
3. Basic wafer got removed. No one use it at all in EV, unless you for some reason really need non smd diodes
4. Time is kept at double as old EBF recipe (except you cannot perfect overclock with coils) at EV.
5. Glue usage is kept the same as Dream's altered recipes.

### CODE REVIEW

**Comment by Dream-Master** [comment]
Process time is to short

**Comment by Glease** [comment]
> Process time is to short

How long do you want player to be able to finish preparing the graphene dusts for an IV assembler, using an array of 4 EV assembler?

**Comment by Glease** [comment]
If you got lost among the numbers, I'll offer a few premade choices - you are free to use your own.

1. 5 minutes.
2. 10 minutes
3. 20 minutes

**Comment by Sphyix** [comment]
Don't forget about the time for wafers, 1 boule for 64 graphene dusts for what you proposed glease
javaw_0lcKcQKzLD

**Comment by Dream-Master** [comment]
So the wafer tier one is skipped ?

**Comment by Sphyix** [comment]
Yes, at Ev when you need this recipe you are not using t1 wafers anymore.
I'm just not sure about the amount of wafers needed for the recipe. Wafers take a lot of time to smelt, and using too many of them could end up as a EBF time gate to IV

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
