### PR TITLE
Change Cinobite alternative breeding requirement to Arcanite

### PR DESCRIPTION
**Pull request by StaffiX**
Changes the alternative way to be available earlier after the https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/967 nerf.
image
image

### CODE REVIEW

**Comment by chochem** [comment]
its just t4 rocket. that seems reasonable to stay imo

**Review by Dream-Master — DISMISSED** [review]
you remove all conditions. No i am against it.

**Comment by StaffiX** [comment]
Changed no breeding requirement to require the end dimension

**Comment by Dream-Master** [comment]
> Changed no breeding requirement to require the end dimension

why? i dont understand the intention of this pr.

**Comment by StaffiX** [comment]
The intention of this PR is that since indium bee doesn't give indium directly for free, there isn't really any reason to be gated after assembly line, just like most of the other bees.
Other bees that are gated later is also needed only later, at the same time as where you need them.
The bee before solved a huge problem that other players had to deal with, but now people who do bees also have to deal with the same thing, they just get more as a result of dealing with bees.

**Comment by Dream-Master** [comment]
ok but the bee has some alternative and is not dim looked if you look at the code. So why remove this. And why end?

**Comment by StaffiX** [comment]
The first way is Venus locked, and since mutatron is disabled, you can't get around that.
The second way is gated further, since it takes cinobite block, which is an alloy that can only be made in ZPM so instead of being gated after assembly line, that way is gated behind the first fusion reactor.
Why end in particular? Mostly to make it still take an extra effort, since you have to move some of the bee stuff to the end this way while not gating it that far.

But if this change isn't wanted, I'll just close it.

**Comment by Dream-Master** [comment]
I just want to know why. This can be open but maybe we find a better solution. Btw you unlock mutatron in your other pr so i guess we can keep venus and add some otehr way like the cinobite block but in a earlier tier? thoughts?

**Comment by StaffiX** [comment]
I like that idea.
I'll revert the Venus change and modify the cinobite requirement to arcanite to make it IV if you get ichorium.

**Review by Dream-Master — APPROVED** [review]
fine for me.

**Pull request merged**
