### PR TITLE
Deprecate GT_RecipeBuilder#noXXXYYY methods

### PR DESCRIPTION
**Pull request by miozune**
As discussed in these places:
https://discord.com/channels/181078474394566657/603348502637969419/1148929204025573426
https://discord.com/channels/181078474394566657/603348502637969419/1148946754318913710
https://discord.com/channels/181078474394566657/603348502637969419/1148961755347812493
https://discord.com/channels/181078474394566657/603348502637969419/1149575874040053853

### CODE REVIEW

**Comment by chochem** [comment]
I was not part of that discussion. please explain.
This seems like a bad move as we couldnt find broken recipes anymore, right?

**Comment by miozune** [comment]
Cherry-picked from my Discord messages:
- It kills one of the benefit builder pattern has: optional method calls.
- I don't even need to know there's no output, because all I care about is what it has, not what it doesn't have.
- It's unfriendly for new contributors. If they're looking at code using `fluidOutputs` but they want to add a recipe that doesn't have fluid outputs, how are they supposed to find `noFluidOutputs` requirement?

> we were able to find lots of broken recipes because of that and fix them. has been quite successful

Well I was not in a part of RA2 migrations, broken as in?

**Comment by chochem** [comment]
broken as in gas instead of fluid or vis versa, simple typos, incorrect ids, ... anything that breaks stuff.
we were able to fix loots of recipes thanks to RA2.

in short RA2 has a nice debug functionality and you are removing it.

**Comment by miozune** [comment]
You might be confusing the two: I removed checks if `inputsBasic` etc. not being set at all, but I did not remove checks if arrays containing null item / fluid. You're referencing to the latter.

**Comment by chochem** [comment]
well you are not explaining anything. guess Ill dive into the code

**Comment by chochem** [comment]
ah, so you are not replacing it by itemInputs() but by doing nothing at all. I see.

**Comment by miozune** [comment]
Previous behavior: If neither `noItemInputs` nor `itemInputs` are called, it crashes
New behavior: `noItemInputs` is not required, simply forget about item inputs

Preserved behavior: If there's null in the item / fluid arrays, debug mode or panic mode shout it out

> gas instead of fluid or vis versa, simple typos, incorrect ids, ... anything that breaks stuff

These are all detected by null being passed to `itemInputs` etc, not by `noItemInputs`

**Comment by boubou19** [comment]
this won't make me change my scripts if i do any RA2 migration work tho. So i guess you'll have to clean after me.

**Comment by miozune** [comment]
yeah I can

**Review by minecraft7771 — APPROVED** [review]
I think it's cleaner as it more strictly follows the code pattern.

**Pull request merged**
