### PR TITLE
buffed drilling area in chunk mode for it to be not smaller than in t…

### PR DESCRIPTION
**Pull request by repo-alt**
…he block mode

fixed scanner info & tooltip
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5836

### CODE REVIEW

**Comment by repo-alt** [comment]
Being insane at T4 is quite ok. Not sure I understand what do you mean about center chunk though? You mean - not dig central chunk first?

**Comment by repo-alt** [comment]
Ah, I think I understand what do you mean, but would it not look weird/unexpected when the drill is in the chunk center?

**Comment by botn365** [comment]
unless you want to mine 1 ore vein or are using T2 drill there most people i assume would place it in a corner to mine al the veins

**Comment by repo-alt** [comment]
How would you explain that in tooltip? And, what about T2 rig indeed?

**Comment by botn365** [comment]
T2 has a radius of 1.33 ore veins while all other ore drills have a whole number
does it realy need to be on the tool tip?
"in chunck load mode clossest chunck corner is seen as center" is what i can think of

**Pull request merged**
