### PR TITLE
Removing the LEG

### PR DESCRIPTION
**Pull request by Alastors**
Screen_Shot_2024-08-03_at_2 14 32_PM
This PR formally marks the LEG for deprecation, to be removed next dev cycle. Or perhaps to be further reconsidered in the future.

Through conversations in #Meta-Dev, it has been thought that there is no place for the LEG in GTNH in the way that it is, and likewise there is no good way to actually rebalance it without nerfing it into the ground or likewise, to remove everything and anything that makes it good.

As such, the only way forward is to deprecate the LEG and to reconsider a future path after deprecation and removal.

### CODE REVIEW

**Comment by TimeConqueror** [comment]
Hi! May you explain the reason of why do we deprecate it?

**Comment by Alastors** [comment]
> Hi! May you explain the reason of why do we deprecate it, please?

updated

**Comment by TimeConqueror** [comment]
Since it already exists for some time, and you want to add another way (based on words "reconsider a future path after deprecation and removal"), I think it would be better to not deprecate it for now, but instead try to make alternative. And when the alternative is done, we may slowly deprecate it. I think this way will be highly accepted by community, since we suggest them the alternative in the moment, but not promise them to do it in future

**Comment by Steelux8** [comment]
I brought up the LEG in the meta dev channel that eventually led to this PR, so I'll leave my perspective on this here.

I've been doing some balance work to solve powergen viability problems that I've seen being mentioned by players on Discord. I made a complex spreadsheet to help me figure out how to best solve those problems, and I've been trying to buff some setups that are generally considered weak, such as HOG, while nerfing others that are considered very easy to scale up across several tiers, such as the XLGT. However, the most frequent topic in this kind of conversation is the LEG, the one considered to be the strongest in its tiers, and the hardest to balance, if even possible to do so.

At this point, I consider the LEG to be too hard to balance to exist in progression, and the reason for that is the magic mechanics that make it work. While tech has been increasingly worked on by a big part of the team, magic is less developed, and it has a lot more unknowns that are often discovered when some player tries something new and then shares it. The LEG has been known to be better than basically everything else for some 4 or 5 tiers, and the setups used for this multi have had factors like these:

* Huge throughput of essentia for "free" through bees or other systems, which were balanced around a condenser "infinite essentia" bug that was accepted as the meta, because the option of wisp spawning did the same but was very laggy;
* Liquid death supply, which creates huge amounts of warp, only for the warp to be ignored by methods such as using an extra player in multiplayer, or automating the setup in a different dimension and never going there;
* Golems being used for automation as one of the several possible tools that would avoid nerfs done to the LEG.

The main point here is that magic balance, while being acceptable within magic, leaks over to tech, where these things aren't acceptable and would have already been dealt with. Under these setups, many others might hide, which will eventually be discovered if specific nerfs are applied to the LEG. Because it is so hard, and so unreliable, to apply a de-facto nerf that would insert the LEG into the balance levels that would be wanted of it to allow other powergens to compete directly with it, deprecation surfaced as a real option.

**Comment by EnderProyects** [comment]
Just saying, your are going to remove the mechanic and the controller, or all the blocks around LEG, sine some of them are used in other recipes in and outside gtnh

**Comment by Alastors** [comment]
> Just saying, your are going to remove the mechanic and the controller, or all the blocks around LEG, sine some of them are used in other recipes in and outside gtnh

Only effects the controller's recipe

**Review by Dream-Master — CHANGES_REQUESTED** [review]
This need to be discussed first. I am against just yeet stuff.

**Comment by Nxer** [comment]
We can’t say “maintaining TPS while using LEG” is free.

**Comment by MeiTianyou** [comment]
I personally spam LEGs because the only other alternative until naqfuel is nitrobenzene. Between the two LEGs and drainers are easier to spam out and upgrade. Both are boring to do for so long. Both should be obsoleted by fission and fusion. Fission just sucks, and fusion is ok but if i already have leg or nb why would i switch infra completely just for 1.5 tiers or whatever when i can just spam more.

Honestly I would enjoy the game more though if I didn't feel like I needed 128A+ of on tier voltage in IV,LuV and early ZPM, but smelting times suck I don't see that ever changing in NH

**Comment by LazyFleshWasTaken** [comment]
Let me preface this with the 'i'm not a dev or a contributor, but I have played gtnh for a long while now, so here are my thoughts.'

YOu're right, there are no alternatives to benzene/LEG, because they both are simply too powerful. If we exclude the two most 'powerful' fuels, you'll find there are quite a few competing power gen options, such as oil/biodiesel into cetane, which lasts from lv to luv/zpm if you stretch it; Vacuum nukes which can generate 10s of ks with a bit of automation risk, which is plenty for ev/iv if you make a few; lava heat exchanging which can generate a ton in iv now that the XL steams were downtiered, I had a setup making 1.2 mil per 2 whakawhiti; and even the solar tower. Hell, Orderedset even had us going on purple rocket fuel from the time we got the ucfe to later UV.

It's not that there are no other competing energy sources, its that two of them were unintentionally buffed beyond the others, and are now being brought in line. Some generation options are being buffed, others are being nerfed.

**Comment by Alastors** [comment]
> It's not that there are no other competing energy sources, its that two of them were unintentionally buffed beyond the others, and are now being brought in line. Some generation options are being buffed, others are being nerfed. I do disagree with full removal tho. 

Nope, the LEG was never buffed once, besides a minor tier shift when we removed the laser hatch capability, it has been repeatedly nerfed since its inception.

**Comment by coyotekira** [comment]
i dont think it makes sense to remove it and an entire branch of powergen with it, its actually a rather fun multiblock, getting to strategize around which coolant and fuel combo you can supply at the quantity you need to run your base. it sounds like the taint focus needs to be disabled individually for reasons of grief, and maybe some of the highest fuel value essentia should be removed completely so wood isnt millions of EU, it already doesnt support every essentia so i dont think that would be weird. really, i dont think anyone would be calling it overpowered if they had to use unstability with krypton as the coolant. honestly i have to wonder how much could be solved by making a set of complex coolants in the same way that we already handle magical super fuel. reducing the efficiency down to a quarter would probably also help, via stability points so it doesnt break anything.

**Comment by Alastors** [comment]
I will note this is prefaced by a bunch of conversations regarding nerfing it into the ground, some proposals going as far as to "limit the LEG to a single amp, or four amps and cheapening the recipe"

**Comment by Hikari1nVoid** [comment]
So this PR was opened even before an issue or a public vote is casted in discord server...?
Now we are heading to arrowheads....

**Comment by Alastors** [comment]
> So this PR was opened even before an issue or a public vote is casted in discord server...?
> 
> Now we are heading to arrowheads....

It was discussed extensively in meta dev before it was moved here, this is the place to discuss it with the public, there was no need for unnecessary steps inbetween.

Though as has been noted before, we are not beholden to the results of any vote, or are required to make a vote in the first place.

**Comment by boubou19** [comment]
We need to deprecate it in its current form, even if later we recycle the block for a new version of the LEG, because we can't just break a multi without warning people first.

**Review by boubou19 — APPROVED** [review]

**Review by Steelux8 — APPROVED** [review]

**Comment by Dream-Master** [comment]
Isn’t there a chance for improve or rewrite it. Deprecate and remove I don’t like personal if we have other options .

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
