### PR TITLE
make covers can use nbt to store data

### PR DESCRIPTION
**Pull request by GlodBlock**
allow covers to use nbt to store data, so maybe it can be more useful in the future.

### CODE REVIEW

**Review by Glease — APPROVED** [review]
The same problems that exists in BaseMetaPipeEnetity also exist in BaseMetaTileEntity. Please fix them there as well.

If possible, modify an existing cover show how these new functionalities are supposed to work. The contract of these methods are not as apparent and simple as some dumb getters/setters.

**Review by Glease — CHANGES_REQUESTED** [review]
Crap, pressed the wrong button.

**Comment by Glease** [comment]
Also please resolve merge conflict.

**Comment by GlodBlock** [comment]
It is much more difficult than I used to think to implement this PR. I have encountered some problems that beyond my ability. It maybe wiser to let someone who is more experienced in mod developing to finish it in the futrue.

**Pull request closed without merging**
