### PR TITLE
fix recipe check

### PR DESCRIPTION
**Pull request by GlodBlock**

### CODE REVIEW

**Comment by Prometheus0000** [comment]
What does it fix though?

**Comment by GlodBlock** [comment]
> What does it fix though?

see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8215

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8166#issuecomment-873464111
Does this break those optimizations?

**Comment by GlodBlock** [comment]
no, this pr is aimed to solve the singleblock machine recipe check bug.

**Comment by Glease** [comment]
What if I put in 64 item X in first slot and place 1 item X in the second slot, but the recipe require 100 item X?

I don't currently have enough time for a thorough examination of the overall control flow and logic of this function, but, at the first glance this situation would still require less than expected amount of item.

**Comment by GlodBlock** [comment]
i have tested the situation you said in game just now, the machine won't start if the amount of item doesn't meet the requirement of the recipe. i use `HashSet<Integer> isUsed = new HashSet<>();` to make sure every stack of items will be checked only once.

**Comment by Glease** [comment]
That's good then. 
I'm not sure if HashSet is the best solution here though. This is a performance critical piece of code and we are trying to catch an edge case that happens less than 1% overall. It will probably need some proper benchmarking to be sure, but maybe someone on the team has prior experience related to this. @GTNewHorizons/developers any ideas?

**Comment by Prometheus0000** [comment]
Is there really a need to use recipes that have more than 64 of the same item in them? Aside from the assline and maybe CAL, which definitely use it, and probably use different code somewhere.

The other uses are non-stacking items, which maybe could use code specifically for them? I had to mess with the neutron reflector recipes before in addition to the ones pointed out in the issue.

**Comment by Dream-Master** [comment]
Why we not test it on zeta?

**Comment by GlodBlock** [comment]
well, the `HashSet` may not be thread safe, so i changed it into `ConcurrentHashMap` which should be no problem now.

**Review by Dream-Master — APPROVED** [review]

**Comment by TimeConqueror** [comment]
Converting HashSet to ConcurrentHashMap still doesn't make it threadsafe: #containsKey & #put are not the single atomic operation. it should be changed to #putIfAbsent with appropriate logic.

**Comment by D-Cysteine** [comment]
I think I see a possible bug with this implementation. Say we have a recipe that requires 72 iron, which is split into a stack of 64 and a stack of 8. If we provide the machine with 2 stacks of 48 iron each, then I think the current code will not recognize this as satisfying the iron requirements. The issue is that the 64 stack of iron in the recipe will check both of the 48 stacks of iron in the input, and they'll both get added to the `isVisited` map. Then, when we try to check the 8 stack of iron in the recipe, since both stacks are already visited, we'll fail to satisfy that requirement, even though 72 < 96.

One possible solution is to copy the input fluid stacks and item stacks, then run the `aDecreaseStacksizeBySuccess` logic on the copies. Then, at the conclusion of the `for`-loop reducing the fluid / item stacks (i.e. [between these two lines](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Recipe.java#L444-L445) and [between these two lines](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Recipe.java#L474-L475)), we check if `amt > 0`. If it is, then we return `false` immediately since the input requirements were not met. At the very end, if `aDecreaseStacksizeBySuccess` is true, then we iterate through the input fluid / item stack arrays once more and set their amounts equal to the amounts in the corresponding copied fluid / item stack.

I'm not sure how fast this will be, but if most of the calls to this method have `aDecreaseStacksizeBySuccess` set to true, then this could very well be faster (we get to basically skip the existing recipe input check logic entirely since we get it "for free" when we do the stack size decrease). Calls where `aDecreaseStacksizeBySuccess` is false may be slower, depending on how fast it is to copy the fluid / item stacks. If those are just plain structs, then this should be pretty fast. Also, I *think* this solution handles `aDontCheckStackSizes` correctly, but we should probably double-check that it works in that case.

Also, all that aside, I'm not sure if we need to worry about making the `isVisited` hash map thread-safe? It's local to this method, so I don't think it should be possible for other threads to read or write to it? (Though, I am not very familiar with Java concurrency)

**Pull request merged**
