### PR TITLE
make the cleanroom to accept 2 doors so alastor is happy

### PR DESCRIPTION
**Pull request by POPlol333**
@Alastors go sleep now

### CODE REVIEW

**Comment by Alastors** [comment]
> @Alastors go sleep now

neverrrrrrrr

**Comment by Alastors** [comment]
and you proposed this abomination yourself, I just told you I'd implement it if you wouldn't, lie in the hole you dug sir :thunkban:

**Review by Alastors — APPROVED** [review]
Literally one line, shouldn't break anything, but if it does worst case scenario we'll have to decrement the mHullCount requirement by 2

**Comment by POPlol333** [comment]
tbh hull are more important than door lmao

**Comment by Alastors** [comment]
> tbh hull are more important than door lmao

yeah but if the doors prevent it because it needs hulls, then it wouldn't kill us to decrement it by 2 if we have to

**Comment by Alastors** [comment]
at the very least this should allow massive cleanrooms to have a second door anyway

**Comment by Dream-Master** [comment]
In Never have more than one door not waste rare space but ok

**Pull request merged**
