### PR TITLE
add setOreBlock() to API

### PR DESCRIPTION
**Pull request by Minepolz320**
For https://github.com/GTNewHorizons/twilightforest/pull/36

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Minepolz320 you need to run spotless

**Comment by Minepolz320** [comment]
@Dream-Master Whoops 😅

**Comment by YannickMG** [comment]
Isn't `GT_TileEntity_Ores::setOreBlock` already public static and thus usable directly in Twilight Forest? Is the idea that you'd prefer to use a method that's explicitly part of the API?

**Comment by Minepolz320** [comment]
@YannickMG damn it's actually even easier

**Comment by Minepolz320** [comment]
@YannickMG  yes but how can you allow the mod to run without gregtech 
just prevent the method from being called or so that the jvm does not load the class

I'm a bit of a noob when it comes to mod integration.

**Comment by Minepolz320** [comment]
and yet it seems to me more obvious to have this method in the API 
but maybe that's just me

**Comment by Caedis** [comment]
Any mod specific code needs to be guarded with `Loader.isModLoaded(modID)`.

The output of that method should be cached in a public static variable during preinit so that its not constantly checking if a mod is loaded.

**Comment by YannickMG** [comment]
You could also consider not adding any dependency on gregtech.

Instead you could add an API to Twilight Forest to allow overriding the code used to set the ore for each stalactite and call that API from NewHorizonsCoreMod.

I can detail this tonight if you'd like.

**Comment by Minepolz320** [comment]
@YannickMG 

> Isn't GT_TileEntity_Ores::setOreBlock already public static and thus usable directly in Twilight Forest? Is the idea that you'd prefer to use a method that's explicitly part of the API?

I think this is the best option for now

**Pull request closed without merging**
