### PR TITLE
feat(render): tile ambient occlusion

### PR DESCRIPTION
**Pull request by leagris**
Render smooth lighting ambient occlusion on all Gregtech tiles:
- Ores
- Machines
- Pipes, Cables, Wires, Frames

Add new Client-side configuration entry in Gregtech.cfg.
If false, the flat lighting rendering of older versions is used.

```yml
render {
    B:TileAmbientOcclusion_true=true
}
```

Animated illustration of the changes:
AODemo

### CODE REVIEW

**Comment by leagris** [comment]
Already PM @Mineshopper a friendly permission request to re-use his [LGPL Licensed Code](https://github.com/Mineshopper/carpentersblocks/blob/master/LICENSE-carpentersblocks.txt) I derived this from [here](https://github.com/Mineshopper/carpentersblocks/blob/MC-1.7.2/src/main/java/com/carpentersblocks/renderer/helper/LightingHelper.java)

Poking you @Mineshopper one more time, so you have one more chance to get that notified to you.

**Review by repo-alt — APPROVED** [review]
I won't lie that I actually understand the lighting calculation, and I don't see the point in repeating that job, but since it works, and doesn't show up in profiling, it should be merged and further tested ingame.

**Comment by leagris** [comment]
> I don't see the point in repeating that job
Vanilla provides incomplete AO computation that is not usable for Gregtech because of these reasons:

- Vanilla AO is only available for full block top and bottom faces. North East South and East sides supports partial block ambient occlusion but only for partial height, (slab sides).
- Vanilla AO and overall vanilla face rendering for the NegativeY (IE Bottom face) is flipping the texture horizontally and it is inappropriate to render Gregtech textures (except copied textures or ore overlay textures).

Each of the 6 sides has a LightingHelper method because writing a unique side-relative method would have added even more computation to deal with 3D Vectors, (relative rotations and offsets).

The LightingHelper class object is instantiated for each side because it holds ighting information for each side corner. It could not return a single value in the call stack. It has to be an object of some kind (objects of 4 corner light values or array of 4 light values) same new object each time it has to return te computed light values for a face. The colouring of the face occurs within the same LightingHelper instance (no new instance) since it re-uses the same 4 lighting values. This I use for overlayed textures faces to avoid recomputing the ambient occlusion four values at each layer.

The LightingHelper is very lightweight and is not causing any additional lagg and is not even showing-up in VisualJVM reports. It is no more complex than the AO computation performed by net.minecraft.

Yes it is complex in term of 3D orientation, logic and averaging light values mid-face.
I Took guidance from block publications here here:

- https://greyminecraftcoder.blogspot.com/2013/07/rendering-non-standard-blocks.html
- https://greyminecraftcoder.blogspot.com/2013/08/lighting.html

I also studied the decompiled RenderBlock from vanilla Minecraft, even regenerating meaningful variables names and understanding the actual computation before I'd re-implement it.

I also derived my LightingHelper Class from the one written by Mineshopper for Carpenter's block, because It has correct computation for partial faces I was having issues recreating it from scratch.

Notes for @draknyte1 and @bartimaeusnek 
1. Please consider updating your mods to support this new AO computation.
2. Think about using the GT_StdRenderedTexture class rather than the GT_RenderedTexture to render ores as I created the Std class specifically to reproduce the exact texture orientation used with vanilla ores (flipped negative Y side), so your ores renders exactly like vanilla ones when seen from below.

**Comment by repo-alt** [comment]
(I meant - repeating _your_ job, but more comments are always good)

**Pull request merged**
