### PR TITLE
Added IV HOG only LCE

### PR DESCRIPTION
**Pull request by Prometheus0000**
I need help with:
 - How do you determine the lowest metadata # that's free for the controller? I just put whatever worked for now
- I recolored the intake in a terrible way, because I don't know how to do it properly so it matches the TS color
image
- https://github.com/GTNewHorizons/GT5-Unofficial/compare/experimental...Prometheus0000:LCE2?expand=1#diff-5be766f41146d04169c54820dd4b9cc83995fd62d1cccb49fb6ba7c006f257a0R85 Has a for loop to go through the diesel fuels, which is unnecessary since it only uses one. But aFuel is also somehow declared there? So I don't know how to do that and not be a for loop.
- I'll remove my notes when it's not a draft
- I'm sure extending the LCE would be better, but I'm not sure I could get it working that way
- Opinions should go in the ticket about it

### CODE REVIEW

**Comment by Prometheus0000** [comment]
This is ready now, if no-one wants to recolor the air intake texture. Balancing comments are welcome too, once someone tries it out.

Also, big thanks to Glease for helping me out.

**Comment by Dream-Master** [comment]
Will check the color now

**Comment by Dream-Master** [comment]
Texture done have to check ingame

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
https://cdn.discordapp.com/attachments/673116585350922251/779298363815362580/unknown.png

**Review by repo-alt — APPROVED** [review]

**Pull request merged**
