### PR TITLE
Fix NEI fuel recipes for large boilers

### PR DESCRIPTION
**Pull request by Ableytner**
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17512
grafik
grafik
The handling of fluid fuels in the NEI preview also needs a rework, which I'll do after the feature freeze. 

Also fixes the order in which anvils are displayed in the industrial forge hammers' structure preview.

### CODE REVIEW

**Comment by spacebuilder2020** [comment]
How does this handle boiler throttling?  For example, if you have a fuel that can burn one tick in a bronze boiler and you throttle a large boiler to 50% (500, since the large boiler is a tiny bit more efficient), will you still be able to burn the fuel?

**Comment by Ableytner** [comment]
This does not touch the actual boiler processing logic, just the recipe registration, which is only done once at game startup. So the throttling behavior is still the same as before (which is to look at the burn time without throttle).

**Comment by spacebuilder2020** [comment]
I took a look at an older version, pre boiler rebalance, (2.0.9.0 QF4) and noticed that on that version you could burn sodium (or even wood pulp in a large tung boiler. (the close enough equivalent steam and eff output to the current large steel boiler on that version)



I am going to check on a newer version to see if this was introduced as a bug with the boiler rework or it was a newer bug.

**Comment by spacebuilder2020** [comment]
Tested on 2.5.1 and bug exists with fuels less than 1000.  Perhaps that was desired with the rebalance to not accept a fuel that could not burn at least 0.5 seconds.


I think it will be worth while determining if that was desired by the initial rebalance (#866) and if so, I think clarifying the tooltip is good.  Otherwise, it may be worthwhile fixing the underlying logic so it can burn an arbitrary fuel as long as there is enough fuel to burn a single tick.

**Review by spacebuilder2020 — APPROVED** [review]

**Review by serenibyss — APPROVED** [review]

**Pull request merged**
