### PR TITLE
Change sterile casing texture

### PR DESCRIPTION
**Pull request by BlueHero233**
Hopefully the final time we change this
(whoops)

Before and After

### CODE REVIEW

**Comment by Dream-Master** [comment]
@BlueHero233 why you changed it ? Are Brick Texture match more ?

**Comment by chochem** [comment]
> @BlueHero233 why you changed it ? Are Brick Texture match more ?

because they are not bolted copper casings. but mostly wood. I dont think brick was every in consideration. but there were a few now I might have missed one.

**Review by chochem — APPROVED** [review]
I approve. and other people in #texturedev also seem to like it

**Comment by BlueHero233** [comment]
Do not merge yet, i have to add the controller face Theo worked on

**Comment by Dream-Master** [comment]
@BlueHero233 i set it draft until it is done

**Comment by BlueHero233** [comment]
tgs (5)

**Review by Ethryan — APPROVED** [review]
Looks really nice.

**Pull request merged**
