### PR TITLE
PBI & Iron III Chloride Recipes

### PR DESCRIPTION
**Pull request by Zoko061602**

### CODE REVIEW

**Comment by 0lafe** [comment]
Looking at the PBl recipe it doesn't look like much was changed. Could totally be that I can't read code/git, but is it still using zinc potassium and stuff? Imo a big part of it is that there's no fluid bases to use for lategame. Nitric acid and stuff isn't really much better than like an aluminum screw. Really should involve distilling fluid naquadria at high EU/t (LuV+), something that uses fusion too, and like a higher tier fluid. Maybe argon/radon for that part, or use a plasma.

**Comment by Dream-Master** [comment]
In real loife Iron 3 chloride is FeCl3 so the formular before not match.

**Comment by richardhendricks** [comment]
Maybe we can add a route using HCl from magnetite ?

Dissolving iron ore in hydrochloric acid
Fe3O4(s) + 8 HCl(aq) → FeCl2(aq) + 2 FeCl3(aq) + 4 H2O(l)

Fe3O4 is magnetite.

**Comment by Dream-Master** [comment]
ok but this one I pull now. @richardhendricks we can make a new one for your suggestion.

**Pull request merged**
