### PR TITLE
+adjusted Lava recipe to be more realistic

### PR DESCRIPTION
**Pull request by bartimaeusnek**
+added an Integrated Circuit

### CODE REVIEW

**Comment by mitchej123** [comment]
What problem is being solved with this?  

~~Kind of~~ Super annoying to have recipes constantly changing without discussion; messes up a lot of automated setups..

**Comment by mitchej123** [comment]
Please submit an RFC or spreadsheet before unilaterally nerfing lava....

**Comment by 0lafe** [comment]
It's kind of stupid to not touch the ++ lava making if you wanna nerf this, considering it alone is worse than normal lava giving the same products.

**Comment by Dream-Master** [comment]
Should i merge this ? 
@bartimaeusnek @mitchej123 @0lafe

**Comment by 0lafe** [comment]
The concept is great, more interesting lava proc is a solid idea, but still leaves a bit of a cheat with the ++ lava proc. Considering it's already significantly more powerful than current centrifuging, making a change that's point is that current centrifuging is too easy, still leaves you with something even more broken. Iirc the boiler multi is equivalent to 64+ MV centrifuges. Pretty sure it's cheaper than an LHE too, and would accomplish the same thing as an LHE, 64+ MV centrifuges, and a little over an amp of IV. I'd suggest either changing the outputs of the boiler, retiring it, or removing the recipe. No sense in intentionally leaving in a bypass for an upcoming change. 

Personally I'd love to see phosphorus as an output of normal lava, as phosphorus gen is sort of confined to bees/uu atm, but that's much less important.

**Comment by mitchej123** [comment]
@0lafe can you please stop complaining about GT++ in basically every communication you have?  Take it a separate issue.

@Dream-Master would need to read through the RFC and figure out where things landed on this

**Comment by 0lafe** [comment]
xD

**Comment by richardhendricks** [comment]
Original ticket 

https://github.com/GTNewHorizons/NewHorizons/issues/4816

**Pull request merged**
