### PR TITLE
Add glass to Multi Lathe tooltip

### PR DESCRIPTION
**Pull request by FireWarrior2**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17847

### CODE REVIEW

**Review by AbdielKavash — CHANGES_REQUESTED** [review]
Could you write "Any tiered glass" or "Any HV+ glass" instead? There are many blocks called "glass" in the game that are not actually valid tiered glass here.

**Comment by FireWarrior2** [comment]
> Could you write "Any tiered glass" or "Any HV+ glass" instead? There are many blocks called "glass" in the game that are not actually valid tiered glass here.

The problem is that other machines such as Separator and Autoclave also have "Any glass".
"Any tiered glass" will be also not very correct because it accepts any glass and this glass does not define machine tier.
"Any HV+ glass" also bad because Ender IO glasses are also HV+ but can't form structure.
Some common decision should be made about these glasses

**Comment by FireWarrior2** [comment]
Maybe smth like "Borosilicate HV or any EV+ glass"?

**Comment by AbdielKavash** [comment]
This is still not correct. As it stands now, the structure accepts anything that is in `chainAllGlasses` -- this includes warded glass, for example.

The real problem here is that "glass" is currently defined in two places: [https://github.com/GTNewHorizons/GT5-Unofficial/blob/a37c908f6801467df99bea00ea813cabefe530a7/src/main/java/gregtech/api/multitileentity/multiblock/casing/Glasses.java#L18](`chainAllGlasses`), which simply specifies "this is a valid glass", and [https://github.com/GTNewHorizons/GT5-Unofficial/blob/a37c908f6801467df99bea00ea813cabefe530a7/src/main/java/bartworks/common/loaders/RegisterGlassTiers.java#L42](`registerGlassTier`), which specifies the tier of each glass. The two need to be synchronized; or ideally replaced by a single approach (and ideally also added to the tooltip builder, so that information in all multiblocks can be presented consistently).

If other multis have the same problem right now, they should be fixed too.

**Comment by FireWarrior2** [comment]
Then maybe just write "Any EV+ tier glass"? Or how?

**Comment by FireWarrior2** [comment]
Closing this pr because a lot more work needs to be done:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17852

**Pull request closed without merging**
