### PR TITLE
Reducing Hypogen consumption in Naqfuel MK4 recipes

### PR DESCRIPTION
**Pull request by KTech3020**
Implements https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17208.
Swapped:
- 720L Hypogen to 720L Infinity in the T4 recipe
- 8 Infinity dust to 1152L Hypogen in the t5 recipe

### CODE REVIEW

**Comment by srdr2k3** [comment]
Doesn't this make Naqfuel MK5 basically unusable? Last time I did Naqfuel, Hypogen was impossible to keep up even at Endgame.

**Comment by kstvr32** [comment]
> Doesn't this make Naqfuel MK5 basically unusable? Last time I did Naqfuel, Hypogen was impossible to keep up even at Endgame.

I think this reduces the amount of Hypogen used. 

Previously: 500L MKV would take 2000L of MKIV which takes 4 * 5 = 20 Hypogen

After: 500L MKV would take 8 Hypogen

**Comment by S4mpsa** [comment]
This makes the base recipe of Mk5 massively worse, which isn't great. I would just reduce the Hypogen consumption of the alternate Mk4 recipe instead, maybe to 240L instead of 720L. This acts as a direct buff to the problematic recipe without breaking the rest of the chain balance.

**Comment by KTech3020** [comment]
after discussions in discord (mainly between @ iamworking and @S4mpsa), i reverted the infinity/hypogen swap and reduced current hypogen usage by 66%

**Pull request merged**
