### PR TITLE
Output bus/hatch - Only auto output to connected pipes

### PR DESCRIPTION
**Pull request by mitchej123**
Only auto output to connected pipes, instead of any pipe in front of it.

### CODE REVIEW

**Comment by mitchej123** [comment]
Fixes #81

**Comment by mitchej123** [comment]
CC @Dream-Master @Antifluxfield

**Comment by Dream-Master** [comment]
@Technus

**Comment by Antifluxfield** [comment]
Well, essentially this bug is at the pipe side...

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/fcb663754350649e9ce01769f54f850a2c6d262e

**Comment by Technus** [comment]
easy done for pipe

**Comment by Technus** [comment]
How to do that on item pipe side, no idea IInventory seems useless...

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/83/commits/049ca143db0c8c1865a18a8c6aa708acb72c2283 -Thanks @Antifluxfield

**Pull request closed without merging**
