### PR TITLE
Make Uncertain Resolver X the default version

### PR DESCRIPTION
**Pull request by StaffiX**
Uncertainty is a minigame that you have to solve to make Quantum Computers actually produce computation.

In that minigame, you have to balance around 16 squares.

The way you have to balance it is by making the values very similar, the symmetry depends on the mode it gives you.

Uncertainty Resolver comes in 3 versions:

1. Where the values are shown by blinking rate
uncertainty1

2. Where the values are shown by brightness
uncertainty2

3. Where it solves it for you, no input required

The issue is that the way the first version of uncertainty resolver represents the values makes it very difficult to see the differences, causes players to usually just randomly click the buttons until it gets solved instead of doing the minigame normally.

This replaces the resolver X recipe to the regular one,
Removes the recipe for basic resolver,
And adds deprecation warning to it.

This also makes basic resolver acts like the X version, so it shows the values by brightness level.

image
image
java_ODkgGMf4JL

Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10374

### CODE REVIEW

**Comment by boubou19** [comment]
On the principle i like it, it'll also reduce risks of epilepsy for some players.

**Comment by chochem** [comment]
was blocked last time, by colen I think?

**Comment by StaffiX** [comment]
I found this ticket https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10374 about this change, but other than that I couldn't find where it was blocked, either on discord or github

**Comment by chochem** [comment]
hmm maybe not a hard block but only decided against yea. I was in favor as you can see and still am but if something was already considered and decided against then discussion is certainly productive instead of just PRing :P

**Comment by boubou19** [comment]
blocked or not, it clearly is helping readability of the puzzle, and makes it way more clear about what the player must do. It's not making the puzzle easier to solve, but it now is more accessible. It's plain dumb to have two different things doing the same exact thing, but with different skins.

**Comment by Connor-Colenso** [comment]
I don't recall having an opinion on this topic @chochem

**Comment by chochem** [comment]
perfect

**Comment by DylanTaylor1** [comment]
I like the idea of deprecating the "blinking speed" for the minigame, but I also like having several tiers to the uncertainty resolver. I suppose an alternate solution is to make the basic uncertainty resolver similar to the uncertainty resolver X but have more shades/hues to make it slightly more difficult. For example:
- Basic Uncertainty Resolver: 7 Shades
- Uncertainty Resolver X: 4 Shades
- Uncertainty Resolution: 1 Shade

**Comment by AbdielKavash** [comment]
> On the principle i like it, it'll also reduce risks of epilepsy for some players.

I agree with this. Even as somebody who doesn't suffer from visual sensitivity, the rapid blinking is just obnoxious to look at.

**Review by serenibyss — APPROVED** [review]
I think this could be revisited to expand the puzzle more like others suggested, but this change on its own I think is worth taking. We can do a follow-up PR if someone wants to work on the more detailed puzzle

**Pull request merged**
