### PR TITLE
Added the miniature wormhole generator

### PR DESCRIPTION
**Pull request by RecursivePineapple**
This adds a new multiblock structure called the Miniature Wormhole Generator which transfers EU wirelessly with minimal losses. It isn't too expensive structure-wise, but this is balanced by the mechanics of it.

When the multi is first built, it starts in the idle state. The multi needs an AE2 entangled singularity (the one used in quantum bridges) to link two of them together. When EU is fed into an energy hatch, the multi will try to consume an AE2 singularity (not an entangled one), which kick-starts the wormhole. The multi will then transfer as much EU as possible between each laser hatch/laser source pair.

The multi keeps track of all EU transferred, and the "wormhole" will grow or shrink in response to the EU/s. The energy stored in the wormhole is the optimal EU/s rate.

If there is extra energy in the laser targets, the multi will overclock the transfer rate; every time the input energy is quadrupled (divided by the wormhole energy), twice the EU will be output into the matching laser source.

If either multi is toggled off or the energy input stops, the wormhole energy will rapidly decay to zero. Once the wormhole energy is less than 32 EU (the initial EU when kick-started), it will collapse. Once collapsed, another singularity will need to be consumed to open the wormhole again.

The transfer efficiency is 99.974%, which is 64x more costly than an active transformer. This can be easily tweaked if needed.

An interesting emergent mechanic is that cycling the same EU through the wormhole generator will keep the wormhole open, if the rate is too intermittent. The average window is 90 seconds, which means it takes 90s for the wormhole to open completely (to 100% efficiency).

The sender:

The receiver:

### CODE REVIEW

**Comment by RecursivePineapple** [comment]
I need to update the structure & tooltip in a few hours, but I'm happy with the mechanics for this. It seems like most devs don't have a problem with the idea, so I think this is ready for a proper review.

**Comment by RecursivePineapple** [comment]
I updated the structure (see new screenshots) and fixed a minor bug. This should be ready for review.

**Comment by Nxer** [comment]
Tested main function and running fine.

Are there plans to add special effects to this device?

**Comment by RecursivePineapple** [comment]
@Nxer BucketBrigade was working on a TESR, but I don't have any plans to do anything. He said it his implementation was half done.

**Comment by chochem** [comment]
eu p2p has 5% loss. This is higher tier, so I dont mind it being better, but you basically set the loss to 0.

**Comment by OmdaCZ** [comment]
Microwave transmitters also have near 0 loss, while being IV ish. (when they worked with just having an osmiridium block next to them instead of nitrogen plasma)

**Comment by RecursivePineapple** [comment]
@chochem What do you think the loss should be? I didn't want to make it too high to start out with. Maybe 1024x an active transformer? (99.5% efficiency, 1 amp in every 244)
I have no idea what UHV+ powergen is like, so I'm not sure what a reasonable cost is.

**Comment by CookieBrigade** [comment]
Now with a cute wormhole to the pocket dimension you are transporting energy to.
https://github.com/user-attachments/assets/a2ac686d-644f-42ed-8ad1-413d02bb04bb

**Review by Nxer — APPROVED** [review]
Cool machine.

**Pull request merged**
