### PR TITLE
Chemical rebalance

### PR DESCRIPTION
**Pull request by Pnc6lx**
1 item unit =(how many atom in it) items
1 fluid unit = 1b
still working

### CODE REVIEW

**Comment by Pnc6lx** [comment]
there is what gtce do [https://github.com/GregTechCEu/gregicality-legacy/pull/388](https://github.com/GregTechCEu/gregicality-legacy/pull/388)
and there is gt5u [https://github.com/Blood-Asp/GT5-Unofficial/pull/1334](https://github.com/Blood-Asp/GT5-Unofficial/pull/1334)

**Comment by Pnc6lx** [comment]
there are 3 recipe to make Ca(CH3COO)2·H2O , 1 Ca or 1 CaO or 1 CaCO3. and you can get 0.75 CaO back. this means you can input 0.2 Ca and get 0.375 Ca.
so i change it to use 1 Ca or 2CaO or 5CaCO3 and get 2CaO back

**Comment by Pnc6lx** [comment]
Na + H2O = NaOH + H 200t, 30EU/t (nerf to 400t, because it can easily reduce H produce in early age after this change
NaOH = Na + O + H

**Comment by Pnc6lx** [comment]
why does H + Cl = HCl + H2O ?
where is H2O come from? 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/dc097373463a1f751bcd9765f0845b6a78a28278/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L2987

**Comment by Pnc6lx** [comment]
> Na + H2O = NaOH + H 200t, 30EU/t (nerf to 400t, because it can easily reduce H produce in early age after this change NaOH = Na + O + H

this recipe can change after discuss

**Comment by Dream-Master** [comment]
@Pnc6lx any update ?

**Comment by Pnc6lx** [comment]
i want to change fluid Electrolyzer recipe from use n cell to use 1 cell + empty cells. but i failed to do this

**Comment by Dream-Master** [comment]
@Pnc6lx any news on this pr ? Are you still on GTNH Discord?

**Comment by chochem** [comment]
the distilling recipe for salt water should only be changed together with the mixing one: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10477

**Pull request closed without merging**
