### PR TITLE
Convert tiny dust output in oreproc to chanced full dust output

### PR DESCRIPTION
**Pull request by GlodBlock**
it will remove all tiny dusts in ore washer/thermal centrifuge/centrifuge. these tiny dusts will become full dusts with 11.11% output chance

### CODE REVIEW

**Comment by GTNH-Afx237v7** [comment]
Think that should also be discussed (or rather continued) here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7791

**Comment by GlodBlock** [comment]
yeah, let's reopen it

**Comment by Glease** [comment]
Renamed to better represent the idea of this PR.

**Review by Glease — COMMENTED** [review]
How about recipes copied over from IC2 recipe map, e.g. washing crushed glod ore? Do they still exist?

**Comment by GlodBlock** [comment]
the old washing recipe seems to be overrided by gt5's recipe
image
recipe with gold dust output doesn't exist

**Review by Glease — COMMENTED** [review]
Checked out your branch and it seems working correctly in game. __Code is fine then.__ 

Since this is a change that needs some discussion and probably dream's decision, I'll not just directly approve it.

**Comment by mitchej123** [comment]
Nobody has the time or effort to implement less laggy tiny dust handling so this should be fine

**Review by mitchej123 — APPROVED** [review]

**Review by boubou19 — APPROVED** [review]
i'm also approving this because when i see that i generate 2ms of lag just for it, i want it to be gone. Also, it doesn't change the output on average so balance wise it's fine.

**Comment by bombcar** [comment]
What happens to the ones that had a percentage chance of tiny? Do we see 0.002374% full dust in NEI now?

@D-Cysteine would this complicate the ore processing NEI display page?

**Comment by bombcar** [comment]
Also the sifter makes tinies - does this affect those too?

**Comment by boubou19** [comment]
> What happens to the ones that had a percentage chance of tiny? Do we see 0.002374% full dust in NEI now?

Do you have an exemple of such recipe? because as far as i understood, this PR change the byprods of thermal centrifuge, orewashing, and dust (im)pures.

**Comment by bombcar** [comment]
> > What happens to the ones that had a percentage chance of tiny? Do we see 0.002374% full dust in NEI now?
> 
> Do you have an exemple of such recipe? because as far as i understood, this PR change the byprods of thermal centrifuge, orewashing, and dust (im)pures.

**Comment by Dream-Master** [comment]
@bombcar the autogenerated i guess. This recipes are added manual so they not changed now.

**Comment by bombcar** [comment]
Stone and planetary dusts also iirc

**Pull request merged**
