### PR TITLE
add info display and fluid container feature to filled tank

### PR DESCRIPTION
**Pull request by GlodBlock**

### CODE REVIEW

**Comment by GlodBlock** [comment]
they have huge debuff when carried with and are more expensive than the large cell. btw, large cell is already useless when you can mass produce bedrockium drum, they are more OP than these tanks

**Comment by bombcar** [comment]
Agreed - large cells are very cheap comparatively and are perfect for “let’s move 4m diesel to the drilling rig”, refilling poly on an assembler, etc. bedrockium drums are already almost effectively a movable supertank (only missing covers) and they don’t break the game.

**Review by boubou19 — APPROVED** [review]

**Comment by Dream-Master** [comment]
how it work? click with a tank on the gui?

**Comment by bombcar** [comment]
> how it work? click with a tank on the gui?

No. Break a supertank full of liquid and pick it up. Should retain the liquid and show what it is in inventory I think

**Comment by GlodBlock** [comment]
> how it work? click with a tank on the gui?

it will have tha same feature as the normal fluid container, including gui fluid interation

**Pull request merged**
