### PR TITLE
Add BloodMagic's slates in Magic Absorber

### PR DESCRIPTION
**Pull request by Spartak1997**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Ghengis88 is this balanced ?

**Comment by Spartak1997** [comment]
@Dream-Master we told about it. Olafe, Cinobi and another person liked it

**Comment by Dream-Master** [comment]
like it is one thing but is it balanced ? Idk thats why i ask. @Spartak1997

**Comment by Spartak1997** [comment]
@Dream-Master I think it's balanced. BM is high-tier magic but useless and these recipes can help players develop further.

**Comment by Cinobi** [comment]
Some useful sttuff for bloodmagic? sign me in!

**Comment by bartimaeusnek** [comment]
400EU per Blank Slate? I'd suggest multiply the saltes EU output by 5.

**Comment by Ghengis88** [comment]
And the amount of eu in 1 slate? Thaumcraft shards is 700 000?  1 blank slate is almost 1 shard 1 Stone and 2125 LP
I world sugest 1 400 000 EU. Becous it is quite allt på work untill you could autocraft them. And the magic absorbera dont go above HV? That world make then last 2734 ticks

**Comment by Spartak1997** [comment]
@bartimaeusnek 400 * 1000

**Comment by Dream-Master** [comment]
@Spartak1997  Thanks

**Pull request merged**
