### PR TITLE
Enhance GPL for several multis

### PR DESCRIPTION
**Pull request by HoleFish**
- LCR batch mode
- Oil cracker batch mode
- AL batch mode & subtick
- ~AAL subtick~ well at least AAL now stops overclocking when reached 1 tick already
- Fix oc calculator for custom OC

### CODE REVIEW

**Review by GDCloudstrike — CHANGES_REQUESTED** [review]
Thanks for the enhancements, getting batch mode on more of the widely used machines is a great anti lag measure. 
The one thing on this list that should be reconsidered is the AAL subtick functionality, as that has wider balancing implications, as previously discussed in meta dev.

**Review by serenibyss — DISMISSED** [review]
I agree with @GDCloudstrike, (summarizing from Discord) I think that AL/AAL subtick should be considered at a future point after endgame circuit crafting is moved to the NAC, at which point this change would imo be more of a nice "fix up some random fast spammed recipes being slow" change rather than a large endgame rebalance right before a more thorough rework of these recipes

**Review by GDCloudstrike — APPROVED** [review]
thanks again

**Comment by Ruling-0** [comment]
> very late to the party but I did not see this at the time. buffing LCR is super questionable. do we really want this in 2.7?

Isn't this just batch mode for performance improvement? Actual recipe yield shouldn't change (unless LCR subticking is new to 2.7 from elsewhere).

**Pull request merged**
