### PR TITLE
Fix small ore generate always tends to positive coordinate.

### PR DESCRIPTION
**Pull request by yukieiji**
Maybe fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8800

### CODE REVIEW

**Review by Glease — CHANGES_REQUESTED** [review]
The whole idea of sticking to `[aChunkX, aChunkX+16]` and `[aChunkZ, aChunkZ+16]` is to run a "Chunkified" world gen, otherwise cascade worldgen would happen, trashing the tps. 

While I like the idea of getting small ores to generate where they should, the way it's currently implemented totally defeats the purpose of this convoluted chunkified world gen.

**Comment by boubou19** [comment]
what is the bias of the previous algorithm?

**Comment by yukieiji** [comment]
Since x and z are only generated in the positive direction with respect to the vein, the generation of the small ore would result in the following image(The area circled in red is the area of generation that is covered by the vein.).

・Ore vein

・Small ores(Ore veins ores)

**Comment by Glease** [comment]
IMO just drop the ore if it's outside `[wx, ex]` or `[nz, sz]`.

**Comment by Dream-Master** [comment]
@yukieiji

**Comment by Dream-Master** [comment]
@Glease can you help Yuki with this?

**Comment by D-Cysteine** [comment]
It looks like the `+2` may be intentional, and the regular ores may be shifted the same way:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_Worldgen_GT_Ore_Layer.java#L155

Maybe there was some crash that this fixed?

**Comment by yukieiji** [comment]
It seems that the coordinates of the veins have been calculated additively for quite some time.
https://github.com/GTNewHorizons/GT5-Unofficial/blob/02e556598ed5d34f6344a916d189c64edccce5e7/src/main/java/gregtech/common/GT_Worldgen_GT_Ore_Layer.java#L67

**Comment by Glease** [comment]
After re-reading this twice I think I've finally got your point. Sorry for giving a wrong suggestion. I guess all we need is to remove that +2 from the formulas you have changed, so it'll distribute evenly in the current chunk.

**Comment by yukieiji** [comment]
Are you saying that this fix is not a problem? Does the area around L155 also need to be modified?

**Comment by Glease** [comment]
On second thought, I'm honestly not sure why would it need to be biased by 2 blocks in the first place. Can't find why would it trigger a cascade worldgen otherwise... I mean, it's already stepping into another chunk's realm (east chunk), isn't it already cascade worldgen? I'm utterly confused right now.

**Pull request closed without merging**
