### PR TITLE
1909: Fix oregen issue with empty chunks. Problem was caused by not u…

### PR DESCRIPTION
**Pull request by richardhendricks**
…sing threadsafe techiniques on ArrayList. Also add and fix some more debug messages, including messages to show a vein being genererated in the air, and if an orevein failed to be chosen after 256 tries.

Fixes issue with Oregen leaving completely blank chunks with no GT oregen. Problem was worse on potato computers. See issue #1909 for details.

Thanks to bigbass and mitch for contributing.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@richardhendricks thanks

**Comment by OneEyeMaker** [comment]
@NNM42 How do you pregen chunks for testing?

**Comment by NNM42** [comment]
some stats for RTG defaul generation x=-1024 z=-1024 to x=1024 y=1024 Dim=0, 5.09.32.01 (w/o small ores and stones) generation dirt, sand, graver — off as Ores under dirt layer.

https://docs.google.com/spreadsheets/d/1Z9mGK-EuUVxpsjyOzcjy65kbMV8cfS1dqVf4nZtTwWI/edit?usp=sharing

*later run test GTNH config ore spawn by dims* (need more time and CPU resourse)

@OneEyeMaker 
1. https://mods.curse.com/mc-mods/minecraft/235036-chunkgen
after
2. http://teamcofh.com/docs/cofh-core/commands/#clearblocks 
if you want see this
3. gregtech log parse
4. give stats.
5. profit.
PS: if you (any player) want harcore orespawn – you may to see TFC orespawn. IMHO.

**Comment by Muramasa-** [comment]
@richardhendricks Is this an issue with the master too?

**Comment by richardhendricks** [comment]
Master?  I don't think so, threaded chunkgeneration was brought in 

https://github.com/GTNewHorizons/GT5-Unofficial/commit/929073a7aea2ff925aa04403be746398b1fc57e7

**Pull request merged**
