### PR TITLE
Buff PCB Parallel

### PR DESCRIPTION
**Pull request by StaffiX**
Currently the PCB Factory uses parallel formula of ln2(numberOfNanite)+1, which meant that after getting a couple of parallels, you needed an incredible amount of nanite to increase it, and the parallel was capped to 32, which needs max int amount of nanites

This changes the formula to 2.1^(ln(numberOfNanite), rounded up with a maximum of 256 parallel.

```
Nanite Count: 1    | Parallel: 1
Nanite Count: 2    | Parallel: 2
Nanite Count: 4    | Parallel: 3
Nanite Count: 8    | Parallel: 5
Nanite Count: 16   | Parallel: 8
Nanite Count: 32   | Parallel: 14
Nanite Count: 64   | Parallel: 23
Nanite Count: 128  | Parallel: 39
Nanite Count: 256  | Parallel: 64
Nanite Count: 512  | Parallel: 108
Nanite Count: 1024 | Parallel: 182
Nanite Count: 2048 | Parallel: 256
˙˙˙

### CODE REVIEW

**Comment by HoleFish** [comment]
it's just n^(ln2.1) ~ n^0.74

**Comment by serenibyss** [comment]
> it's just n^(ln2.1) ~ n^0.74

Simplifying the formula to n^0.75 would result in:
```
Nanite Count: 1    | Parallel: 1
Nanite Count: 2    | Parallel: 2
Nanite Count: 4    | Parallel: 3
Nanite Count: 8    | Parallel: 5
Nanite Count: 16   | Parallel: 8
Nanite Count: 32   | Parallel: 13** (-1)
Nanite Count: 64   | Parallel: 23** (+1)
Nanite Count: 128  | Parallel: 38** (+1)
Nanite Count: 256  | Parallel: 64** (+2)
Nanite Count: 512  | Parallel: 108** (+5)
Nanite Count: 1024 | Parallel: 181** (+9)
Nanite Count: 2048 | Parallel: 256 (since it is maxed)
```
I think this results in just as good of a curve without the formula needing to be as complex

**Review by serenibyss — APPROVED** [review]
Looks good, balance change agreed upon by myself and @GDCloudstrike, will leave open for now for anyone else to comment

**Review by GDCloudstrike — APPROVED** [review]
Looks good to me, should go well with the planned dupe removal

**Pull request merged**
