### PR TITLE
Change pure tungsten to tungstate on europe

### PR DESCRIPTION
**Pull request by botn365**
remove pure tungsten ore from europe so line can only be skipped in T5+ planets

### CODE REVIEW

**Review by bartimaeusnek — CHANGES_REQUESTED** [review]
It's a rare Vein on a Water based planet.
Assuming people would massively use this (and have greater return than with the line) Pre-LuV is not realistic.

**Comment by Dream-Master** [comment]
What is so bad replace pure tungsten with tungstate? We did the same for Titanium.

**Comment by botn365** [comment]
europa has like 5 difrent veins making this vein not super rare
miners can still mine this vein so the water makes no difrent exept making manualy finding this fein easyer
and from my 3 runs of GTNH i have used this vein as my source of tungsten evry time

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
I vote for change it to Tungstate.

**Comment by boubou19** [comment]
it's very attracting to go on Europa to mine pure tungsten ore, shortcircuiting the tungsten line process. Europa is a T3 rocket planet, which is IV tier. Denying the pure tungsten ore in europa means it's only availiable at T5 or higher rocket, which requires ZPM power in an assline, so it can be done in LuV. so this would move the Pure tungsten ore one tier later, which is not that bad, considering we moved pure Ti ore from HV to IV, so 2 tiers later.

**Comment by iouter** [comment]
In fact, the T5 rocket needs europium. When players have europium, they can be considered to have entered ZPM, but hv-iv and iv-zpm are not equal. The latter requires an assembly line and a fusion reactor MKI, which is much longer than the former.

Therefore, I think it is best to add pure tungsten (or small ore) on the T4 rocket planet.

**Comment by Dream-Master** [comment]
> In fact, the T5 rocket needs europium. When players have europium, they can be considered to have entered ZPM, but hv-iv and iv-zpm are not equal. The latter requires an assembly line and a fusion reactor MKI, which is much longer than the former.
> 
> Therefore, I think it is best to add pure tungsten (or small ore) on the T4 rocket planet.

small tungsten is ok but this is a tungston vein

**Comment by iouter** [comment]
add the tungsten vein at io or venus?
actually, after the multiblock miner, there is no difference between the vein and small ore.

**Comment by botn365** [comment]
first pure titanium vein is on a T4 planet wich requires assline 
assline to me is basicly LuV so titanium is first found on T1 planet and pure is on T4 or HV(EV) - LuV
tungsten is first found on T2(ignoring the end) planets and with this change on T5 pure or EV(IV) - ZPM

**Comment by iouter** [comment]
> 在 io 或 venus 添加钨静脉？

sorry, this should be the chrome vein


> 第一个纯钛矿脉是在 T4 行星上，它需要
> 我的Assline Assline 基本上是 LuV，所以钛首先在 T1 行星上发现，纯钛在 T4 或 HV(EV) 上 - LuV
> 钨首先在 T2（忽略末端）行星上发现并在 T5 pure 或 EV(IV) 上进行此更改 - ZPM

yu shouldn’t make an analogy like this. otherwise, we can say that because there is small titanium ore on mars, small tungsten ore should be added on a T3 planet.

and pure manganese only exists in this chrome vein. If you delete it, you can only find pure manganese on T8 planet TcetiE.

so add the chrome vein on io or venus.

**Comment by botn365** [comment]
read the commit it changes the tungsten to tungstate ore not remove the vein

**Comment by iouter** [comment]
I misread it, sry.

**Comment by Glease** [comment]
In case anyone messed it up again I've changed the title.

**Comment by iouter** [comment]
but the small tungsten ore should be added on a t4 planet.

**Comment by botn365** [comment]
with how OP small ores become around T4 planets i dont think small ore should exist of it before T5 planet

**Comment by GlodBlock** [comment]
the main idea is to make tungsten line meaningful, if there is small ore at T4, i am sure everyone will place the multiblock miner on these planets instead of using line.

**Comment by iouter** [comment]
there is already a long distance between t3 and t4.

**Comment by Dream-Master** [comment]
Lets add small tungsten to t3 or t4 and Test out.

**Comment by iouter** [comment]
t3 is too early

**Comment by iouter** [comment]
it would be great if all pure ore can be deleted. lol

**Pull request merged**
