### PR TITLE
Fix multipipes

### PR DESCRIPTION
**Pull request by Antifluxfield**
Fix https://github.com/GTNewHorizons/NewHorizons/issues/2447

### CODE REVIEW

**Comment by Antifluxfield** [comment]
Hmmm... Maybe you can ask @shpakovivan for his pr: https://github.com/Blood-Asp/GT5-Unofficial/pull/1378 
It can also fix that bug, and have some extra enhancement.

**Comment by Prewf** [comment]
please make sure this fix works with multiple fluids actually going through the pipe

**Comment by Dream-Master** [comment]
@Antifluxfield @Prewf we try  @shpakovivan fix fist.

**Comment by Dream-Master** [comment]
@Antifluxfield your fix works.
we have issues with the other code.

**Pull request merged**
