### PR TITLE
Allow configurable non-GT blocks in cleanroom structure

### PR DESCRIPTION
**Pull request by repo-alt**

### CODE REVIEW

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8487

**Comment by Glease** [comment]
No support for differentiating between different block meta? Not saying it's a necessity, just curious if it's needed.

**Comment by repo-alt** [comment]
Yes I thought to add meta, just didn't find a use case. It is trivial to add in config.

**Comment by GlodBlock** [comment]
don't bart's glasses have block meta?

**Comment by Glease** [comment]
What about warded glass?

**Comment by repo-alt** [comment]
Bart's glass do have meta, but it doen't seem like they should have different percentage.
I'll look at warded glass

**Comment by repo-alt** [comment]
Indeed warded glass is a good use case. How much percentage should it have by default what do you think?

**Comment by Glease** [comment]
50% maybe? It's not as expensive, but require you to have at least one warding focus.

**Comment by GlodBlock** [comment]
> Bart's glass do have meta, but it doen't seem like they should have different percentage.

i think you would be better to add different percentages for these glasses, the most cheap borate glass almost cost nothing

**Comment by repo-alt** [comment]
I check config with meta first, then w/o meta, so it is possible to override percentage for individual blocks

**Comment by D-Cysteine** [comment]
Would it be worth setting the required plascrete ratio to be the minimum of configured percentages for all glasses used in the structure? Or even just restricting to only one unique type of glass allowed per structure?

Otherwise if we add in a separate percentage for too many different glass types, we'll end up allowing a lot of glass by mixing types. E.g. with 5 types each at 50%, we could have 20 plascrete, plus 10 each of the 5 glass types, for a final ratio of 20-50 plascrete-glass.

What I mean by minimum ratio is something like, look up the config percentages for all keys in `otherBlocks`, and take the minimum percentage. For keys that had a percentage limit (i.e. not a count limit), sum up the values to get a total mixed glass block count. Then compare the mixed glass block count against plascrete count with that minimum percentage.

This makes sense to me from a real-life perspective, where if the percentage restriction comes from the glass blocks weakening the structure, it makes sense that a wall is only as strong as its weakest point / weakest block. Though probably difficult to succinctly explain how it works to the player.

**Comment by repo-alt** [comment]
Well, as far as I understand "edges" are always plascrete, so the illusion of structural integrity will be preserved. Total percentage is indeed somewhat difficult to make user friendly.

**Comment by Savallator** [comment]
My approach would be to alloq 10% Glass flat out based on EV Glass, make IV count half, IV count 1/4 etc...
That would balance Mixed Glass types as well, and would still be easy to understand.

**Review by GlodBlock — APPROVED** [review]

**Pull request merged**
