### PR TITLE
Remove convert gendustry bees code

### PR DESCRIPTION
**Pull request by DianeXD**
Maybe it's a legacy issue, is there any special reason?
close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6026

### CODE REVIEW

**Comment by boubou19** [comment]
well the code was set so it would autoconvert the gendustry bees into GT bees (was made for the bee update). Since it's a converting code, it should stay here. As to why it triggers the conversion, that is the actual bug.

**Comment by DianeXD** [comment]
Eh, it's been over three years...

**Comment by Dream-Master** [comment]
we check this after stable release

**Review by minecraft7771 — APPROVED** [review]
If the conversion was in for this long, then it can go without an issue imo. You get way worse problems when trying to update a 3 year old world.

**Pull request merged**
