### PR TITLE
Standardized Bee Comb processing recipes

### PR DESCRIPTION
**Pull request by impbk2002**
if the config nerf beeComb is disabled. GT_comb processing recipes go totally Messed up. So I separated the nerfed part and un nerfed part. Also added enum values to the recipes to automatically generate the required voltage and duration, required cleanRoom by the required Voltage Tier. This will make us easier to add new honeycomb or balancing Beekeeping.

Only five function is needed for Any Honey comb process except for Infinity Bee line.
addProcessGT : this only adds AutoClave and Chemical Process related to the Voltage Tier
addCentrifugeToMaterial
addCentrifugeToItemStack
addChemicalProcess
addAutoclaveProcess

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
> required cleanRoom by the required Voltage Tier

That one doesnt really make sense imo...

**Comment by impbk2002** [comment]
> That one doesnt really make sense imo...

I thought, my comments in this code, were enough for explaining. My function accepts voltage Tier, and if required Tier is over HV, it will add cleanRoom requirement just like original recipe. Is this doesn't make sense?

**Comment by Prometheus0000** [comment]
Do all comb centrifuge recipes over HV require a cleanroom as it currently is? It also seems kinda weird that they would need one at all. Combs are messy, organic things, not super-precise circuitry.

**Comment by impbk2002** [comment]
> Do all comb centrifuge recipes over HV require a cleanroom as it currently is? It also seems kinda weird that they would need one at all. Combs are messy, organic things, not super-precise circuitry.

Maybe there is a misunderstanding. CleanRoom requirement only applies to the AutoClave and Chemical Process. I didn't add any cleanRoom requirement for Centrifuge.

**Comment by Dream-Master** [comment]
@impbk2002 did you change the recipes or just the logic behind it ?

**Comment by impbk2002** [comment]
> @impbk2002 did you change the recipes or just the logic behind it ?

My idea is to keep recipes same and changing only the functions. All of the recipes should be the same as original. But maybe some can be differ if I missed to recipes.

**Comment by Dream-Master** [comment]
@impbk2002 did you check the recipes ingame ? I mean if they work like before ?

**Comment by impbk2002** [comment]
> @impbk2002 did you check the recipes ingame ? I mean if they work like before ?

I'm not sure about the unnerfed version. Cause that config break and override recipes strangely. I didn't check all the recipes of beecomb inGame.
But in nerfed version at least the combs(about 80%) that I checked in NEI have same recipe ( except circuit number and voltage requirement for centrifuge lower or same as LV tier). 
Maybe the EU/t requirement for centifuge recipes for some LV tier Combs might be slightly larger than original recipe
My functions are based on original functions: addprocessLV addprocessMV, addprocessHV ... addprocessUV

**Comment by Dream-Master** [comment]
ok i merged it localy and put it into zeta update. Maybe @GTNewHorizons/developers @GTNewHorizons/core can check those pr

**Review by Glease — COMMENTED** [review]
the code looks good, but a few recipes are indeed changed. mostly it's recipe time change, not voltage tier change or cleanroom requirement, so it's not very game breaking. nevertheless I'm not sure we should indeed have a standard recipe time according to voltage tier. on one hand a unified standard make things easier to handle, on other hand materials of the same tier does have different values, so it'd make sense for more valuable material to have a longer recipe time and vice versa.

**Comment by Dream-Master** [comment]
@impbk2002

**Comment by impbk2002** [comment]
Commit: ae823a5
Added Parameter for Centrifuge to set duration Manually. This applies to Myst Crystal and Planet Combs. Duration of Centrifuge still can be set automatically.
High Tiers Centrifuge Comb recipes now have same duration compare to the recipes before this PR. ( before this commit, I used the duration of Centrifuge from addProcess() which does not applied to nerfed config.)

This Pull Request is intended to unify the Comb processing recipes. Recipes components change is not intended in this PR.
For now only intended recipe change in this PR is Infinity Line Combs EU/t. Which changed very slightly.

COSMICNEUTRONIUM: 2M EU/t -> 1,966,080
INFINITYCATALYST: 8M EU/t -> 7,864,320
INFINITY: 24M EU/t -> 31,457,280
This is an intended change in the unification process. (Centrifuge EU/t is 15/16 of its Voltage Tier except  Tier 0)
Everything else of Recipes changes is unintended.

**Review by Glease — APPROVED** [review]

**Pull request merged**
