### PR TITLE
Split Materials.java initializer to avoid class too large errors

### PR DESCRIPTION
**Pull request by NotAPenguin0**
Splits the loading of materials into different classes to keep Java happy. As a part of this, I might write a script that converts all material initializers to `MaterialBuilder`.

### CODE REVIEW

**Comment by OneEyeMaker** [comment]
Just an idea (I haven't put much thought into it yet):
What about splitting the main class into smaller *logical* classes for different materials instead of temporarily solving the problem by splitting the initializer? I mean - leave all methods in main class and move the static fields and initializers. And access materials like this: `Materials.EndGame.SpaceTime` or `EndGameMaterials.SpaceTime`.

Or should we consider major changes to material system?

**Comment by NotAPenguin0** [comment]
This is already done for `MaterialsUEVPlus`, but I think it adds some confusion because you now need to think about which class the material you want is in, which might become harder with many different categories.

**Comment by boubou19** [comment]
@NotAPenguin0 is this required for now or is it just a nice thing you want done?

**Comment by NotAPenguin0** [comment]
> @NotAPenguin0 is this required for now or is it just a nice thing you want done?

Nice to have, but not really necessary I think

**Comment by Dream-Master** [comment]
@NotAPenguin0 what is the status of this pr?

**Comment by NotAPenguin0** [comment]
I can finish this soon probably, just need to put aside some time for it

**Comment by NotAPenguin0** [comment]
All material initializers have now been moved to `MaterialsInit1`. If class-too-large errors start appearing again, another initializer class can be made. I'll admit, I'm not 100% sold that this is much better than the current version, since now you have to go through two steps to find how a material is defined, but using proper IDE tools this is probably a fine tradeoff to not having to move all materials into their own classes entirely, like `MaterialsUEVPlus` does.

**Review by FourIsTheNumber — APPROVED** [review]
LGTM

**Pull request merged**
