### PR TITLE
Two slots wiremill

### PR DESCRIPTION
**Pull request by Dream-Master**
Addon mods recipes can changed later
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/403

### CODE REVIEW

**Comment by Dream-Master** [comment]
image

**Comment by Dream-Master** [comment]
image

**Review by POPlol333 — APPROVED** [review]

**Review by Glease — CHANGES_REQUESTED** [review]
Need to add slot migration. Will do a few hour later.

**Review by Glease — APPROVED** [review]
should be ok now

**Pull request merged**
