### PR TITLE
Redraw Missing Crops textures?

### PR DESCRIPTION
**Pull request by Minepolz320**
Tomato - blockCrop Tomato 4
Tea - blockCrop Tea 4
Onion - blockCrop Onion 4
Lemon - blockCrop Lemon 4
Cucumber - blockCrop Cucumber 4
Corium - blockCrop Corium 4
Chilly  - blockCrop Chilly 4
Grape - blockCrop Grape 4

### CODE REVIEW

**Comment by Prometheus0000** [comment]
I don't remember them being missing? IE: a big purple and black texture. Did it skip changing the texture for a growth stage or something?

**Comment by Minepolz320** [comment]
@Prometheus0000 all this crops in final stage have a same texture 
blockCrop Cucumber 4

**Comment by Prometheus0000** [comment]
OK. If you're not just recoloring things, I'd suggest trying to keep them looking like the real thing. Like, cucumbers are long and green, that kind of thing. Though I'm pretty sure lemons normally grow on trees, so 🤷 .

**Comment by Minepolz320** [comment]
I thought it would be better than nothing 😞

**Comment by Prometheus0000** [comment]
It is. I can't do textures either.

**Comment by Minepolz320** [comment]
making lemons on a tree is a good idea

**Comment by Minepolz320** [comment]
Cucumber - Cuc
Lemon lemon

**Comment by Minepolz320** [comment]
@Prometheus0000  But it's feel less (ic2 style) what do you think?

**Comment by Prometheus0000** [comment]
We have bonsais already, so a tiny tree is fine. I do feel like the cucumbers should be longer, but I guess there isn't space for that? Anyway @leagris is the one to ask about textures and such I think.

**Comment by leagris** [comment]
> We have bonsais already, so a tiny tree is fine. I do feel like the cucumbers should be longer, but I guess there isn't space for that? Anyway @leagris is the one to ask about textures and such I think.

This is all good and better than previous. About re-using or expanding on other crop/sapling assets, GregT already did for most/all of his initial crops added to GT like the SlimePlant using the dead bush as a base.

I really appreciate @Minepolz320 's contribution. It makes Gregtech more refined; and there is much room for improvement when talking about refinement with Gregtech.

**Review by leagris — APPROVED** [review]
Much appreciated dude. Good work!

**Comment by Minepolz320** [comment]
@leagris What do you think which option would be better?
the one that was originally proposed or the one that was below
ps
I'm just learning how to use github for now, so didn't update textures 🙄

**Pull request merged**
