### PR TITLE
Europium bee line

### PR DESCRIPTION
**Pull request by Volence**
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14669

Adds similar specs to what's described. Rare earth bee is made with Redstone and Fluorine, picked because fluorine is relatively far down the gas line and it'll still keep neodymium more of a challenge to get to, as well as there's quite a few items in the rare earth that give fluorine.

image

Gives Rare Earth and Neodymium combs as a special production.

image

Neodymium is Rare Earth + Iron on a block of neodymium for a 10% chance.

image

It produces rare earth combs and neodymium combs as its specialty

image

And finally we have the europium bee, produced with neodymium and hydrogen (like the fusion recipe). It has a 1% chance over a block of europium.

image

It outputs europium 3 oxide and europium combs in a mega apiary

image

Overall for this line you have to progress pretty far into gas, and then need a mega apiary to make the europium bee more useful. You also can't get it without fusion for the initial europium block.

While I was doing this, I wound up fixing another issue that I've had with combs in that a lot of their names weren't accurate to their products:

image
image
image

This is now fixed to match their items so when you search for the material in NEI you'll find the comb as well:

image

I also applied this to some of the comb's drops to capitalize the second word in the name (which was generally lower case and kind of ugly), and again didn't match with its other materials:

image
image

Is now:

image

### CODE REVIEW

**Comment by Nxer** [comment]
Bee God would be stronger.

**Review by chochem — DISMISSED** [review]
As discussed on discord, I do not think that adding more strong bees is a good idea.

Bees are in a very strong place and can already make *almost* everything. We rather want a game were people look at many different resource generation options not one were they use the same solution for every problem - in particular when its a passive one.

I say we close it - unless an admin thinks otherwise.

**Review by Nxer — CHANGES_REQUESTED** [review]
At least, put Europium Bee to a more later tier. For example, unlocked with Fusion Casing MK-II.

**Comment by Volence** [comment]
> At least, put Europium Bee to a more later tier. For example, unlocked with Fusion Casing MK-II.

There was some discussion in the discord and it seems like there was a consensus between some of the devs that this should work if the base block for this was compact mark 1, and also to change americium to compact mark 2 base

**Comment by chochem** [comment]
> There was some discussion in the discord and it seems like there was a consensus between some of the devs that this should work if the base block for this was compact mark 1, and also to change americium to compact mark 2 base

as a dev that was there, that is not true.

**Comment by Volence** [comment]
image
image
image

All starting roughly around here https://discord.com/channels/181078474394566657/401118216228831252/1269741169458413701

**Comment by Nxer** [comment]
> change americium to compact mark 2 base

Americium Bee has been limited in mega apiary, so Americium Bee has no problem. Obviously, making Europium Bee be limited in mega apiary is not suitable. 

Advanced Compact Fusion Coil would be a choice, I agree. At least, Bee shouldn't replace Fusion at too early time.

**Comment by Volence** [comment]
> > change americium to compact mark 2 base
> 
> Americium Bee has been limited in mega apiary, so Americium Bee has no problem. Obviously, making Europium Bee be limited in mega apiary is not suitable.
> 
> Advanced Compact Fusion Coil would be a choice, I agree. At least, Bee shouldn't replace Fusion at too early time.

That was actually another thing discussed, and it seems like a few people want the europium bee to be pushed to only produced it with mega apiary (which is how it's currently implemented in the pr) just so that you still have to do a bit of fusion infra before having more easy access to the passive comb. I believe they wanted the americium one mk2 just for the consistency with the change for this one.

**Comment by Dream-Master** [comment]
Add stronger bees are ok but they need to be balanced very well.

**Comment by Volence** [comment]
> Add stronger bees are ok but they need to be balanced very well.

A quick summary of the balance discussion (if we're to implement this) is that:

Europium bees need Mega Apiary.

Europium bees need compact fusion mk 1 controller as base for breeding.

Europium bees are blacklisted from genetics to acquire the bee.

Americium bees become gated with a compact fusion mk 2 controller as base (for consistency).

These were agreed upon by a few, but @Nxer believes having the europium bee be locked to Mega Apiary would be gating it too hard. If we're to continue discussion/look to implement these bees, I think that's the next conversation to have.

**Comment by boubou19** [comment]
No more OP bees. Bees are too strong, i get it that people are super fans of bees, but even tho they are cool and all, they were never meant to be meta. The fact they were and are still meta in some spots is an issue.

**Comment by Volence** [comment]
Side note, if we decide to not add the Europium bee, would it be cool to rework this so that it's just the text changes at least? Also, @boubou19 would you consider the Rare Earth and Neodymium bees as OP as well or are they something we want to consider if the Europium one is not?

**Comment by Dream-Master** [comment]
I the bees is op we need to reduce the amount of europium you get from it to balance it against normal europium process line values?

**Comment by Dream-Master** [comment]
> image image image
> 
> All starting roughly around here https://discord.com/channels/181078474394566657/401118216228831252/1269741169458413701

@Volence are you add this suggested block?

**Comment by Volence** [comment]
> > image image image
> > All starting roughly around here https://discord.com/channels/181078474394566657/401118216228831252/1269741169458413701
> 
> @Volence are you add this suggested block?

@Dream-Master I can but I also wanted to get approval on it before doing more work so I didn't just do the work and then it get denied.

**Comment by Dream-Master** [comment]
sure if the bee is balanced right i will add it. @Volence

**Comment by Volence** [comment]
Made the changes for the bee base block requirements for europium and americium:

image
image

I have not blacklisted the bees from gendustry yet though, still need to find where that blacklist lives.

**Comment by Dream-Master** [comment]
Gendustry have a lot of config files guess it’s in there @Volence

**Comment by Dream-Master** [comment]
image
add values to tuning.cfg

**Comment by OneEyeMaker** [comment]
And be sure to add these values [here](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/gendustry/overrides/tuning.cfg). Editing the [original config](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/gendustry/overrides/tuning.cfg) won't take effect if there is an override.

**Comment by Volence** [comment]
Made a PR for the blacklist, I only edited the overrides since the GT specific bees were only in them, keeping to the pattern of that. Thank you all for the locations of the configs! https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16977

**Review by Nxer — APPROVED** [review]

**Comment by chochem** [comment]
not much has changed, no.

**Comment by Dream-Master** [comment]
So what need to change else? change the tier? change the output? change the requirements?

**Comment by Dream-Master** [comment]
i merge this now but we need to rework bees in general with new mechanics.
@Volence wrote me this
```An idea for a nicer way have bees be less powerful, let them have better and easier tiering for developers while not losing their passive use:

New gating system for specific production bees that starts in HV with industrial apiary new Nectar Source Upgrades (level 1 through x):
    - Certain bees will now only produce their special comb in the industrial apiary with a specific level of NSU or above.
    - Would not be needed/used for a lot of the more basic bees, but instead be used for specific material production bees
    - This will generally be limited to tiered materials and have the requirement be within the tier or above it:
        - Eg Aluminium will only be allowed in the "HV" tier upgrade, allowing you to not just breeze through the MV part of the pack but once you start having to worry about stainless, it allows you to then start gaining resources from the previous tier passively
        - This could also be used to gate certain tier skips if we wanted, or be able to restrict more powerful bees beyond "this needs higher energy to process combs", or "needs mega apiary"

We could also use this concept for the mega apiary, seeing as there are more endgame items that go beyond it. Specifically a hatch that can hold higher tier levels of the Nectar Source Upgrades which could allow us to have a better control over adding more powerful bees to the endgame without making any specific parts of progress too easy do to bees.```

**Pull request merged**
