### PR TITLE
Remove Dynamic Adjustment logic and instead apply the adjustment right away if a fuel is eligible for super eff increase

### PR DESCRIPTION
**Pull request by spacebuilder2020**
This is intentionally behind master by one commit since something in the most recent commit is causing a infinite loop when loading Iguana Tweaks.

See [discord](https://discord.com/channels/181078474394566657/603348502637969419/1281089864057753681) for the reasoning behind this change.

### CODE REVIEW

**Comment by spacebuilder2020** [comment]
I am leaving this in draft state until the issue with https://github.com/GTNewHorizons/GT5-Unofficial/pull/3050 is resolved and once that is done I will retest with a updated branch.

**Comment by spacebuilder2020** [comment]
Seems like the crash is still happening on the most recent merge, however it is a slightly different one.
Going to go ahead and remove this PR from draft since there isn't really much I can do about this crash.
[fml-client-latest.log](https://github.com/user-attachments/files/16907049/fml-client-latest.log)

**Comment by Dream-Master** [comment]
@spacebuilder2020 vexatos make a new build maybe that work

**Comment by spacebuilder2020** [comment]
alright, I will try that one.

**Comment by spacebuilder2020** [comment]
I just tested [5.09.49.71-pre](https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.49.71-pre) with nightly 629 and it also had the same crash.
[fml-client-latest.log](https://github.com/user-attachments/files/16907178/fml-client-latest.log)

**Comment by spacebuilder2020** [comment]
https://github.com/user-attachments/assets/f4f77cfe-3088-4029-bee4-c205ded82142

Tested and working with most recent merge.

**Comment by spacebuilder2020** [comment]
Btw, I feel it is important to note that this is also a  bug fix since the previous PR introduced a bug while I was sleeping.
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3044/commits/60514365f0bf4228a7daa9d0d4eda0c3a706d912

By changing the logic from less than to less than or equal, it caused the adjustment logic to get called endlessly until such point it overflowed.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
