### PR TITLE
add caching to boxinator + other optimazation

### PR DESCRIPTION
**Pull request by botn365**
add caching to the crafting fuction of the packeger to make it not consume insane amouts of ticktime

### CODE REVIEW

**Review by bartimaeusnek — CHANGES_REQUESTED** [review]
@botn365 i tried a similar thing already and aparently the lagg its creating isnt coming from caching issues. please benchmark this, before we merge code that isnt nessecary.

**Comment by botn365** [comment]
@bartimaeusnek i did soem profiling 
without caching it is 8.6 ms
with the caching it is .175 ms

**Comment by Dream-Master** [comment]
@bartimaeusnek so worth to add it ?

**Comment by Glease** [comment]
What if you use the cache in `allowPutStack` as well? it is also calling crafting handlers.

**Review by bartimaeusnek — APPROVED** [review]

**Pull request merged**
