### PR TITLE
Optimize GTUtility.getTier call

### PR DESCRIPTION
**Pull request by kstvr32**
Forked from GTNewHorizons/GT5-Unofficial#3163.

Implements `GTUtility.getTier` using `Long.numberOfLeadingZeros` which is implemented in hardware as an x86 primitive (see https://www.felixcloutier.com/x86/lzcnt for more info).

I ran a microbenchmark with three different approaches:

```java
    // original getTier code
    public static byte getTierOriginal(long l) {
        byte i = -1;
        while (++i < V.length) if (l <= V[i]) return i;
        return (byte) (V.length - 1);
    }

    // log based approach from koi
    public static byte getTierLog(long l) {
        if(l > V[14]) {
            return 15;
        }
        return (byte)Math.ceil(Math.log(Math.max(l,8) / 8.0) / LOG4);
    }

    // lzcnt approach
    public static byte getTierLZCNT(long l) {

        if(l > V[14]) return 15;
        if(l <= V[0]) return 0;

        // numberOfLeadingZeros is implemented in hardware by x86 LZCNT
        // this operation should take only a couple of hardware cycles
        // (64 - numberOfLeadingZeros(l - 1)) = ceil(log_2(l))
        int log2L = 64 - Long.numberOfLeadingZeros(l - 1);

        return (byte)((log2L - 2) / 2);
    }
```

```
Benchmark                   Mode  Cnt         Score         Error  Units
GetTierBenchmark.log       thrpt    3    727059.626 ±   48446.800  ops/s
GetTierBenchmark.original  thrpt    3   1032288.717 ±   14205.032  ops/s
GetTierBenchmark.lzcnt     thrpt    3  22245749.943 ± 1704142.219  ops/s
```

This optimization improved throughput in the synthetic benchmark by ~22x

### CODE REVIEW

**Comment by boubou19** [comment]
looks like a nice optimization, however i never seen this to show in profilers. What makes it interesting to patch? Also if you use cpu specific instructions, does it work on like m2 macs or gaming android phones?(via pojav launcher)

**Comment by kstvr32** [comment]
I agree it probably it is a pretty small optimization, but it is simple to speed up with counting leading zeros. 

The hardware intrinsic should be available on ARM (Apple silicon/Andriod) as [CLZ](https://developer.arm.com/documentation/dui0473/m/arm-and-thumb-instructions/clz).

**Comment by Glease** [comment]
even if it's not available (e.g. on RISCV without B extension), a software based fallback will be provided by jvm. that one should be at least as performant as the current implementation 

as long as you aren't using a jvm made by monkeys...

**Review by NotAPenguin0 — APPROVED** [review]
Even if it's only slightly faster I don't see why not.

**Pull request merged**
