### PR TITLE
reactivate GT Tools

### PR DESCRIPTION
**Pull request by Dream-Master**
(cherry picked from commit 520156e27469c936572064f6839da2ff442a488f)
reactivate GT Tools crafting (only assembler LV/MV)

### CODE REVIEW

**Comment by Dream-Master** [comment]
Soft Malett and Hard Hammer not works. Will doing this tomorrow

**Comment by GTNH-Colen** [comment]
Wasn't this voted down already? 
Screenshot 2021-01-03 at 02 32 48

**Comment by mitchej123** [comment]
> Wasn't this voted down already?
> Screenshot 2021-01-03 at 02 32 48

A suggestion for the pack maintainer ;)

**Review by Glease — APPROVED** [review]
code wise looks ok, and dream convinced me this change is totally fine.

**Pull request merged**
