### PR TITLE
Electric jukebox

### PR DESCRIPTION
**Pull request by eigenraven**
Adds electric jukeboxes for LV-IV tiers with the following features:
- Increased range with each tier, up to 160 blocks max (10 chunks)
- Wireless headphones you can wear and bind to a jukebox with even larger range, becoming unlimited at highest tiers
- Support for Sound P2P to spread the music throughout your base without needing headphones
- Playback seamlessly resumes on the client after changing dimensions or logging out and back in
- Optional Shuffle and Repeat modes for easy music automation, or you can use the input and output slots to build your own
- Customizable range slider to play in a smaller radius than default, separate for the main jukebox and the P2Ps
- Deprecates the badly broken GT++ Sir Mixalot, and adds a recipe to convert between them

Recipes will be added to the coremod once this gets merged.

### CODE REVIEW

**Comment by chochem** [comment]
might be best to also remove the very buggy not really functional gt++ one, dont want people mistaking that disaster for your work :P

**Comment by eigenraven** [comment]
Deprecating it is already a plan, I added it to the PR description

**Comment by eigenraven** [comment]
@Dream-Master I removed the review request, this is not ready yet (missing a third of the code or so)

**Review by boubou19 — APPROVED** [review]

**Comment by boubou19** [comment]
@eigenraven fix the merge conflicts and this is good to go

**Pull request merged**
