### PR TITLE
add shapes to existence (no texture)

### PR DESCRIPTION
**Pull request by POPlol333**
Added: 

- LUV and UHV shape placeholders, they miss texture
- GT_MetaGeneratedItem_04 because others were already full

Proposed material for now are:
- Rhodium for LuV
- Black Plutonium for UHV

This subject need discussion as people seem to disagree if whether or not they want that.

It aims to:
image

### CODE REVIEW

**Comment by Hikari1nVoid** [comment]
What's the actual recipe for these molds/shapes?
Also it would be nice if we can remove the stargate assemble from the requirement since the recipe could use an UHV/UEV precise assembler/assemblyline.

**Comment by miozune** [comment]
Metaitem ids are actually not full at all. You can dump free ids with in-game NEI config > Tools > Data Dumps > GT5u.
49 - 76 and 112 - 139 of metaitem.01 are sets of consecutive free 28 ids.

**Comment by chochem** [comment]
GT_MetaGeneratedItem_03 seems to have hundreds of free ids and thats where the white dwarf ones are too.

I see a lot of other issues though.
1. the gameplay perspective: what is actually the point of these? tiering is already done by voltage anyway. Speed up of low tier stuff seems useless. seems like bloat unless you have some clear idea. I already asked you this on discord and didnt get an answer. whats the goal/idea?
2. you would need to adjust all the recipes. Including addons.
3. ideally you would first add a way to easily ask for 'any bolt extruder shape as copy(0)' or 'any bolt extruder shape with tier UHV+ as copy(0)'. Just copying every recipe 4 times sounds silly. Ideally that should also just show one in NEI, not sure if that is easy to do.
4. not an expert on textures but wouldnt it make sense to use the existing ones and just have a variable color? not sure how white dwarf was implemented.
5. your quote by mc7771 says shapes and molds. I only see shapes. So you decided against that? might be fine, but you didnt mention anything.

**Comment by Steelux8** [comment]
What's the purpose of a change like this? It does make sense that molds for advanced materials should be more durable, but this is a very basic change whose only effect, from what I understand, is getting players to switch all their molds in their extruder multis two times, and that's it. I don't think that's a worthwhile change.

**Comment by POPlol333** [comment]
pretty much everyone forgot that ever existed

**Comment by POPlol333** [comment]
> pretty much everyone forgot that ever existed

 (including me)

**Pull request closed without merging**
