### PR TITLE
Singleblock machine internal fluid tank scaling standardization

### PR DESCRIPTION
**Pull request by Pxx500**
Buffs some machines fluid tanks, standardizes scaling of internal tanks in singleblock machines

resolves https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13472
requires https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/615

### CODE REVIEW

**Comment by Dream-Master** [comment]
standardization is good but if a Block have a 64 Bucket tank in LV and now decreased to 16 its a bad idea.

**Comment by wlhlm** [comment]
Yeah, I haven't been able to test this personally, but I was also wondering what happens if you already have a machine that is filled with 64k and the tank gets shrunk.

**Comment by Dream-Master** [comment]
yea i guess it will voided.

**Review by Dream-Master — CHANGES_REQUESTED** [review]
please scale up to max tier. 
atm you only tier lV-HV
this is a huge nerf atm.

**Comment by Connor-Colenso** [comment]
This should probably start at like 32k and scale linearly rather than exponentially.

If 16 buckets is LV then we'll have

MV: 32
HV: 64
EV: 128
IV: 256
LuV: 512
ZPM: 1024
UV: 2048
UHV: 4096
UEV: 8192
UIV: 16384
UMV: 32768
UXV: 65536
MAX: 131072

Just grows out of control very quickly.

**Comment by Dream-Master** [comment]
we can stop at IV or Luv with it

**Comment by Dream-Master** [comment]
guess after that tier its irrelevant

**Comment by GDCloudstrike** [comment]
After HV it could just scale additively by 64 buckets each tier, so EV 128, IV 192, etc.

**Comment by Connor-Colenso** [comment]
Just feels weird to go from linear to exponential all of a sudden. Either way it's not like it matters what the capacity of a UIV etc single block is since it'll only ever be used in a PA (if that).

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
