### PR TITLE
full RA1 removal

### PR DESCRIPTION
**Pull request by boubou19**
This PR aims to finally say goodbye to RA1 🥳 However, we need to remove any external RA1 call before we merge this PR.

This is ready to be merged, as well as the following PRs:
 https://github.com/GTNewHorizons/Botanic-horizons/pull/29
https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/111
https://github.com/GTNewHorizons/HydroEnergy/pull/26
https://github.com/GTNewHorizons/Computronics/pull/25
https://github.com/GTNewHorizons/StorageDrawers/pull/31
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/pull/63
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/895 (this one needs this current PR to be merged first)

### CODE REVIEW

**Comment by chochem** [comment]
(potentially incomplete) list ofmods that need adjusting:

- [ ] galaxyspace
- [x] visual prospecting
- [ ] hydroenergy
- [ ] tinkers gregworks
- [ ] computronics
- [ ] storage drawers
- [ ] minetweaker gt addon

**Comment by Caedis** [comment]
Cant we add stub RA1 calls that log when called?

**Comment by boubou19** [comment]
logs tend to be ignored, a straight removal forces us to fix the code. Different approach, same result.

**Comment by Caedis** [comment]
Good point

**Comment by boubou19** [comment]
i think i'm done for now, still tons of stuff to do, but the PR is already big enough, and RA1 is actually gone in this PR

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
