### PR TITLE
ForgeDirections fix for GT Boilers

### PR DESCRIPTION
**Pull request by chochem**
was caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1895 from what I can tell but the code documentation was wrong too.

fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13783

### CODE REVIEW

**Comment by wlhlm** [comment]
> was caused by #1895 from what I can tell but the code documentation was wrong too.

This PR was not culprit for this. This is how the code looked before `ForgeDirection`:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/ac0b7a7da46646d325def36eed811941dbfc5950/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler.java#L354-L360

**Comment by chochem** [comment]
hmm, well I dont fully understand the old byte code. I assumed its the '<6' but I have no idea, hence me trying to get mitchs or leagris attention.

**Comment by wlhlm** [comment]
>  I assumed its the '<6' but I have no idea

You might actually be right. I'm gonna shut my mouth.

**Comment by chochem** [comment]
well actually, more likely DOWN is i=0 which is excluded too. would make more sense

**Review by miozune — APPROVED** [review]

**Pull request merged**
