### PR TITLE
add unlocalizedname fluid map

### PR DESCRIPTION
**Pull request by GlodBlock**
add special map to deal with the stupid unlocalizedname in output hatch

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
Doesn’t FluidRegistry already have the unlocal:fluid map?

**Comment by GlodBlock** [comment]
> Doesn’t FluidRegistry already have the unlocal:fluid map?

no they don't have unlocalized name map, only for fluid name map.

**Comment by draknyte1** [comment]
> > Doesn’t FluidRegistry already have the unlocal:fluid map?
> 
> no they don't have unlocalized name map, only for fluid name map.

I’m pretty sure it’s unlocal names.

**Comment by GlodBlock** [comment]
which one then?

**Comment by GlodBlock** [comment]
`fluids`: fluid's name to fluid
`fluidIDs`: fluid's id to fluid
`fluidNames`: fluid's id to fluid's name
`fluidBlocks`: fluid block to fluid
`masterFluidReference`: fluid's unique name to fluid (unique name isn't unlocalized name)
`defaultFluidName`: fluid's name to fluid's unique
`delegates`: fluid to fluid delegate

**Comment by draknyte1** [comment]
```
    public Fluid(String fluidName)
    {
        this.fluidName = fluidName.toLowerCase(Locale.ENGLISH);
        this.unlocalizedName = fluidName;
    }
```
`fluids` Works fine.

```
    /**
     * Returns the unlocalized name of this fluid.
     */
    public String getUnlocalizedName()
    {
        return "fluid." + this.unlocalizedName;
    }
```
Just adds a useles prefix.

**Comment by GlodBlock** [comment]
that is what i thought before. but in fact a lot of mod doesn't follow this rule, like fluids in ic2.

**Comment by draknyte1** [comment]
IC2 just uses the prefix ic2 for it's fluids.. I've just never seen a use for unlocal fluid names in 8 years..

**Comment by GlodBlock** [comment]
> IC2 just uses the prefix ic2 for it's fluids.. I've just never seen a use for unlocal fluid names in 8 years..

then you should ask who wrote the fluid hatch lock code, he/she used the unlocalized name to store the fluid info. since i can't transform unlocalized name into fluid by removing `fluid.` so i have to made a another map to store it.

**Comment by draknyte1** [comment]
> > IC2 just uses the prefix ic2 for it's fluids.. I've just never seen a use for unlocal fluid names in 8 years..
> 
> then you should ask who wrote the fluid hatch lock code, he/she used the unlocalized name to store the fluid info. since i can't transform unlocalized name into fluid by removing `fluid.` so i have to made a another map to store it.

You can, just look at the function above.

Why not just fix the hatches to not use unlocal name?

**Comment by repo-alt** [comment]
Vanilla placeable fluids (lava & water) have "tile." prefix. This is indeed a good change, because those prefix guessing did look weird. (I have no idea if there is a ready map in forge for those names so can't say if there is a better way to deal with them)

**Comment by repo-alt** [comment]
Fixing the hatch would probably be better in the long term, but it would break existing filters, unless the prefix guessing would go to readFomNBT or something

**Comment by draknyte1** [comment]
> Fixing the hatch would probably be better in the long term, but it would break existing filters, unless the prefix guessing would go to readFomNBT or something

The code already exists to use unlocal names, so why not use that to get the fluid and then only use the correct name?
Only ever has to be done once and it's fixed.

**Comment by GlodBlock** [comment]
let's go back to the topic. the fact is: 1. no unlocalized name map exist in FluidRegister. 2. we can't transform the unlocalized name into fluid name corretly always. so this pr has no problem. whether the hatch should use what to lock is another thing and we shouldn't discuss it here.

**Comment by repo-alt** [comment]
Eh? How is that offtopic. If the hatch will be fixed to use proper names this map won't be necessary. And it actually is a proper fix, not another bandaid.

**Comment by GlodBlock** [comment]
@repo-alt the hatch lock name has been changed into fluid name. it will auto change the exist unlocalized name into the proper one so it won't break the exist setup. **but it will break everything if you downgrade the pack version**

**Comment by Glease** [comment]
I thought downgrading has never been supported

**Review by Glease — APPROVED** [review]

**Comment by Dream-Master** [comment]
Merge or not ?

**Pull request merged**
