### PR TITLE
Digital chests refactored, preserving binary compatibility.

### PR DESCRIPTION
**Pull request by repo-alt**

### CODE REVIEW

**Comment by repo-alt** [comment]
Eh, not really, you see, mItemCount & mItemStack is not duplicated (it would not really work)

**Comment by repo-alt** [comment]
Also, there is no super chest in the upstream

**Comment by draknyte1** [comment]
Afaik the only logic difference is capacity. The same data should be saved in the parent class as there’s no reason either child should override that. 

They’re in GT++ though.

**Comment by repo-alt** [comment]
I could not move mItemCount to the common base because it would break binary compatibility. and duplicating it does not help, because these are not "virtual" properties, just dumb data, and they would be physically duplicated, so, need to be synchronized.

**Comment by draknyte1** [comment]
Rename them in the parent.. then in child leave the fields and point them to parent fields. Binary Compat but for all intensive purposes, they’re just deprecated variables. (Which can be tagged as such)

**Comment by repo-alt** [comment]
I cannot just point them to parent fields, they will desync. Also whoever accesses them now will meet a broken contract, what's the point of such 'compatibility'?

**Comment by draknyte1** [comment]
If child.mItemCount = getItemCount(), that’s fine. 
mItemCount will always return the correct value from the function handled by parent.

**Comment by repo-alt** [comment]
You mean, replace the fields with the properties with the same name? Does it not break compatibility?

**Comment by draknyte1** [comment]
A field can have a method as a value, provided it’s not final.

**Comment by repo-alt** [comment]
I'm accustomed to call such fields "properties" like in C# to differentiate from the "dumb" fields. But really, I don't see any benefits in this approach, compared to what I did, It is just an alternative. Perhaps even more readable.

**Pull request merged**
