### PR TITLE
New sounds for multi

### PR DESCRIPTION
**Pull request by evgengoldwar**
Sounds by @krezhvick  -  †Theo†

Precise 
https://github.com/user-attachments/assets/3e8b4ee5-942a-4c2e-8561-7398fe77d780

Ore Washer
https://github.com/user-attachments/assets/c75edc1b-86cb-43fe-94a2-b43ae8285072

Mega Vacuum Freezer
https://github.com/user-attachments/assets/d16ee4bf-73d5-417d-a6bd-9c3af105cc59

Vacuum Freezer
https://github.com/user-attachments/assets/d95cca8a-0232-4c16-ae1a-4028b9359f31

Eye Of Harmony
https://github.com/user-attachments/assets/20b5455a-8865-471f-955d-432a20376743

Extreme Entity Crusher
https://github.com/user-attachments/assets/37ab2c93-c79d-42d1-9e33-d29892452428

Cutting Machine
https://github.com/user-attachments/assets/5773eb83-720c-4476-8279-dabd555555e2

Arc Furnace
https://github.com/user-attachments/assets/f3487391-d624-4566-8550-9119581e0cea

Mega Industrial Apiary
https://github.com/user-attachments/assets/c9e7465e-946d-4691-a751-a852c06dbaa8

Algae
https://github.com/user-attachments/assets/7157c8e1-8e31-4333-8d47-8602c094f28b

Thermal Centrifuge
https://github.com/user-attachments/assets/be79df61-ec5c-4009-9cbf-74ccf22d46ff

Sifter
https://github.com/user-attachments/assets/eea206ba-2747-4b7f-b23b-9bba9622919f

Cryogenic Freezer
https://github.com/user-attachments/assets/0a04c845-8a3c-4e85-8d4a-2d5b09843441

EBF
https://github.com/user-attachments/assets/3b3a22d8-c315-40c7-8446-ac2da6c5e275

God of Forge
https://github.com/user-attachments/assets/f79349de-28b8-4e27-8a92-d1771ebfebd4

MEGA EBF
https://github.com/user-attachments/assets/bee417d0-7700-447d-9e48-d4e38223f556

Oil Drilling
https://github.com/user-attachments/assets/7a9f843d-8b77-4d8f-9a7e-1a0ad9ac1e69

QFT
https://github.com/user-attachments/assets/331eb7cb-8f26-4bc4-810e-a1248000ddc9

Large Turbine
https://github.com/user-attachments/assets/08e2224c-50f5-4036-8ea9-375791f47570

Volcanus
https://github.com/user-attachments/assets/21fcce51-0b89-4b70-8d8c-0ed33e828fbf

### CODE REVIEW

**Comment by Volence** [comment]
Having a discussion with the sound designer through discord (they reached out to me earlier this week on some topics) and giving a couple bits of feedback

**Comment by boubou19** [comment]
sound author asked a delay to fix sounds according to feedback

**Comment by boubou19** [comment]
image

**Comment by NotAPenguin0** [comment]
In my opinion the EEC sound is a little disturbing, though it does fit the multi.

**Comment by Dream-Master** [comment]
lets add it. If a sound not match or can be improved we can open a new pr.

**Review by Dream-Master — APPROVED** [review]

**Comment by User198263321** [comment]
I can't wait for a video essay of the making of these sounds, lol. I personally would be interested.

**Pull request merged**
