### PR TITLE
Several Fixes

### PR DESCRIPTION
**Pull request by bartimaeusnek**
Signed-off-by: bartimaeusnek <33183715+bartimaeusnek@users.noreply.github.com>

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
should resolve:
https://github.com/GTNewHorizons/NewHorizons/issues/4384

**Comment by bartimaeusnek** [comment]
should resolve:
https://github.com/GTNewHorizons/NewHorizons/issues/4229

**Comment by bartimaeusnek** [comment]
@Dream-Master well hopefully... its a lot of duct taping here...

this should fix:
https://github.com/GTNewHorizons/NewHorizons/issues/3405
https://github.com/GTNewHorizons/NewHorizons/issues/4239
https://github.com/GTNewHorizons/NewHorizons/issues/3722
https://github.com/GTNewHorizons/NewHorizons/issues/3170
https://github.com/GTNewHorizons/NewHorizons/issues/2892

**Comment by Dream-Master** [comment]
@bartimaeusnek can this be merged or will you add more stuff?

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4303

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4446

**Pull request merged**
