### PR TITLE
Rework item renderers

### PR DESCRIPTION
**Pull request by UltraHex**
Fixes bugs with fast graphics.

### API breaking changes (minor):

- Subclasses of `GT_GeneratedItem_Renderer` may need updating
- Subclasses of `GT_GeneratedMaterial_Renderer` may need updating
- Subclasses of `GT_DataStick_Renderer` may need updating

### CODE REVIEW

**Comment by UltraHex** [comment]
BTW, transcendent stuff in item frames looks like this now:

**Comment by UltraHex** [comment]
Universiuim renderer is broken in my local build. Could be a problem with this PR. Investigating.

**Comment by UltraHex** [comment]
### Status:
without OptiFine: everything works
with Optifine: Universium inventory rendering is broken
with Optifine and shaders: Universium rendering is borked in general


Going to have to dig into Avaritia's shader code for this one. Might take a while.

**Comment by Connor-Colenso** [comment]
Universium item renderer does work, but has a bug which sometimes causes it to fully be universium. There is a difference.

**Comment by UltraHex** [comment]
> > Universiuim renderer is broken in my local build. Could be a problem with this PR. Investigating.
> > Update: Issue caused by OptiFine and shaders. Expect one or two commits to address.
> 
> universium renderer never really worked. so not your doing. see [GTNewHorizons/GT-New-Horizons-Modpack#12693](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12693). (unless your issues are different) Probably can just be changed to something completely different as nobody has been able to fix it in so long.

That's the bug alright. I'm going to take a crack at it anyway.

**Comment by UltraHex** [comment]
I fixed the OptiFine issue on Avaritia's side. I'll do the shader patch in a separate PR if I ever figure it out. This PR can go ahead now. (as soon as somebody reviews it :P)

**Review by eigenraven — APPROVED** [review]

**Comment by UltraHex** [comment]
Thanks @eigenraven !

**Pull request merged**
