### PR TITLE
Change Canola back to Rape seed

### PR DESCRIPTION
**Pull request by Caedis**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15351

### CODE REVIEW

**Comment by Caedis** [comment]
Then you can also make my other suggestion while you are at it :P

**Comment by chochem** [comment]
I dont think that fixes the ticket, does it? As I understand the thing that is decisive is the 'canola' tag, not the name on the itemlist.

**Review by boubou19 — APPROVED** [review]

**Review by chochem — CHANGES_REQUESTED** [review]
doesnt do what it promises from what I can tell

**Comment by Caedis** [comment]
I thought all items were based off the ID and not the name

**Comment by Caedis** [comment]
Checking in a dev world with it fully reverted and then this applied

**Comment by Caedis** [comment]
Yep, IC2 goes off the name. Now it fully reverts back to the rape name

**Pull request merged**
