### PR TITLE
Move assembly line NEI tab before all other GT NEI tabs

### PR DESCRIPTION
**Pull request by D-Cysteine**
This will move the assembly line tab before the scanner tab.

### CODE REVIEW

**Comment by Glease** [comment]
Code is fine. Is this needed though? Surely it helps when you are looking up recipes, doesn't seem as helpful when you are looking up usage

**Comment by D-Cysteine** [comment]
Oh yeah, good point about the usage lookup. Thanks for pointing that out! I've updated this to support any order of handlers, and placed assembly line and scanner at the back.

Longer term, we might want to add a config of some sort to NEI and do the re-ordering there, but this will work for the time being.

**Comment by Dream-Master** [comment]
@D-Cysteine @Glease so i let this open untill you add a cfg ?

**Comment by D-Cysteine** [comment]
I think this PR should be fine as-is; adding the config would be for NEI, and it might be a while before that gets done anyway.

**Pull request merged**
