### PR TITLE
Allow chemical bath to count flowing water as a valid fluid block

### PR DESCRIPTION
**Pull request by NotAPenguin0**
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3322 made some changes to how the chemical bath counts water in its structure, and forgot to account for flowing water. This simply adds back the check for flowing water.

### CODE REVIEW

**Comment by Alexdoru** [comment]
do we really want flowing water to count as valid blocks ? it's akward

**Comment by dagger8243** [comment]
my chemical bath MB last playthrought (2.6.1) had flowing water and it still worked :thinking:

**Comment by NotAPenguin0** [comment]
> do we really want flowing water to count as valid blocks ? it's akward 

It is, but the automatic filling code results in flowing water.

**Comment by NotAPenguin0** [comment]
> my chemical bath MB last playthrought (2.6.1) had flowing water and it still worked :thinking: 

Yes, this PR fixes a regression introduced in nightly 688

**Comment by Alexdoru** [comment]
> > do we really want flowing water to count as valid blocks ? it's akward
> 
> It is, but the automatic filling code results in flowing water.

wouldn't it be better to fix the water filling code ?

**Comment by NotAPenguin0** [comment]
Maybe, but looking at it gives me a headache

**Review by FourIsTheNumber — APPROVED** [review]

**Pull request merged**
