### PR TITLE
Add "recipe" for Fluid Void Cell "ME Defective Fluid Digital Singularity Storage Cell"

### PR DESCRIPTION
**Pull request by lordIcocain**
for https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/234
image

### CODE REVIEW

**Comment by Dream-Master** [comment]
The chance is to high I would say . Did you test how often you got this cell when unpack 100 or 1000 packs ?

**Comment by lordIcocain** [comment]
I tested by hold click in creative, i got one per 1-2 min. I dont think it should have very low chance, nothing special, just voiding cell. I just like concept when you get defective part from scrap. Also it enforce ppl  to do something except make "just pattern in ae".

**Comment by Dream-Master** [comment]
This chance is to high . The idea is good but the Chance need to be changed .

**Comment by lordIcocain** [comment]
@Dream-Master So which chance you would like?

**Comment by spacebuilder2020** [comment]
Personally, I don't think the idea of adding 'recipes' to the scrap box is a good idea as the only way to get an item.  I like the idea of it being an alternate way but I think there should be a conventional way as well.  I get the idea of it being defective so perhaps a recipe that plays on that, for example, smashing a normal singularity fluid cell with a hammer would be a intuitive way of making a 'defective' singularity cell...

**Comment by C0bra5** [comment]
I would take a singularity from ae2 + a fluid cell; it combines the concepts and isn't going to achieve the "desired" result. Having stuff on low chances is just bound to be a situation where someone ends up going way above the odds for no reason than being unlucky.

Being someone with notoriously terrible luck, I hope the way to get those won't be random/tied to RNG.

**Comment by Miklebe** [comment]
image
You are 6 times less likely to get vanilla diamond (or any other gem) than singularity, considering one can be acquired in steam/LV, while the other won't have any uses till EV at least? Unless it should be considered as "trash" by some players like a steak? (shovels and other unstackables still have higher chance to drop, so not as bad as them)
image
It would seem like a good gimmick at first, but item void cell is HV/EV locked and can be easily crafted with 3 tungsten ingots, is there a need to make it not a simple recipe because it's fluid cell? Maybe instead of tungsten use tungstensteel?

**Comment by LazyFleshWasTaken** [comment]
Honestly, adding defective items to scrap boxes, that either have a use, or can be repaired for cheaper than making a new one, sounds like neat idea.

**Comment by duckedddd** [comment]
Sounds super fun and creative I love it, atm there’s nothing particularly worth going for in scrap boxes and this is a fun addition

**Comment by spacebuilder2020** [comment]
I still feel that adding a special cell to void items is a step in the wrong direction.  Personally, I think it would be better to just add a void option that you could enable in the partitioning instead of having craft a special kind of cell to void 'electronic' items.

**Comment by Iamworking12** [comment]
> I still feel that adding a special cell to void items / fluids is a step in the wrong direction. Personally, I think it would be better to just add a void option that you could enable in the partitioning instead of having to craft a special kind of cell to void 'electronic' items.

Unfortunately, AE2 code is a dev repellant.

**Comment by C0bra5** [comment]
> I still feel that adding a special cell to void items / fluids is a step in the wrong direction. Personally, I think it would be better to just add a void option that you could enable in the partitioning instead of having craft a special kind of cell to void 'electronic' items.

we've had the void cell for long enough that it's basically just how we do it, the fact that it's called a "defective fluid singularity" is more the problem here, it should just be named "fluid void cell" so that it's in line with the original one and easy to find in NEI.

**Comment by boubou19** [comment]
the amount of item obtained per batch is a binomial law. With the current proba, with 1k boxes you afe supposed to get 1.2 with a standard deviation of 1.1.
 
The amount of tries to get the first cell is a geometric law and you need on average 833 tries, with a standard deviation of 833. So unlucky people can have way more tries required. Knowing that you need only one most of the time, this might be too easy depending on the recipe of the cell.

@lordIcocain please post a pic of the normal recipe of the cell to compare

**Comment by lordIcocain** [comment]
@boubou19 it's only possible way to obtain, for now at least

**Review by Alexdoru — CHANGES_REQUESTED** [review]
Please make a normal recipe
If you want to add a scrapbox mechanic to obtani this item, why not, but add one for the item void cell too and also lower the chances by alot, 0.12% is too much. Something like 0.005% would be more reasonable.

**Comment by EnderProyects** [comment]
If you want for people to use scrap just add scrap into the recipe, so you can have that both "recipes" uses scrap, also I agre the chance is to high

**Review by NotAPenguin0 — CHANGES_REQUESTED** [review]
As others already said this definitely needs a normal recipe. I'd honestly also remove the scrapbox recipe because it feels really weird to me.

**Comment by Dream-Master** [comment]
> @boubou19 it's only possible way to obtain, for now at least

Add a recipe

**Comment by Dream-Master** [comment]
> @boubou19 it's only possible way to obtain, for now at least

@lordIcocain add a recipe

**Comment by lordIcocain** [comment]
@Dream-Master https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1057

**Comment by Dream-Master** [comment]
will check

**Pull request closed without merging**
