### PR TITLE
fix(GT)rename Field Generator Tiers

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Review by Ethryan — APPROVED** [review]
This is probably to help with tiering, 
but personally, I liked the roman numerals.

**Comment by Dream-Master** [comment]
Yes but i looks wired if you using Tier IV-EV @Ethryan or i am wrong?

**Comment by Prometheus0000** [comment]
Do we need the number at all? The other parts like emitters don't have it?

**Comment by Dream-Master** [comment]
Sure its original named as LV, MV, HV but there are people said they can't craft it at a certain time so i renamed it. But sure we can rename it back.

**Comment by Ethryan** [comment]
You mean like this?:
Field Generator (LV)
Field Generator (MV)
and so on.

**Comment by KiloJoel** [comment]
The gt++ ULV one doesn't have a number currently
image

**Comment by Prometheus0000** [comment]
It's far more confusing to try to keep track of it with just the number, and if we have both, the number is meaningless since people will memorize the tiers, not the number of the tiers. Especially since they're different in the QB to the GT tiers.

**Comment by Dream-Master** [comment]
@Prometheus0000 @Ethryan better now ?

**Pull request merged**
