### PR TITLE
fix(API): GT_Fluid

### PR DESCRIPTION
**Pull request by leagris**
- Fix: Use `registeredFluid` instead of the returned `GT_Fluid` to configure Materials and containers to prevent crashes when retrieving fluids references from those.
- Impr: Adjust fluid luminosity computation to better fit with Tungsten as maximum
- Impr: Remove transparency from the `fluid.molten.autogenerated.png` texture to prevent molten materials to appear diluted.

### CODE REVIEW

**Review by Glease — COMMENTED** [review]
Should asFluid() made to return registeredFluid when it is not null?

**Comment by leagris** [comment]
> Should asFluid() made to return registeredFluid when it is not null?

Yes and night taught me I shall have a distinct interface `IGT_RegisteredFluid` and `GT_RegisteredFluid` extending `Fluid` and to be used for the `ConfigureMaterials` and `Register<>Containers` methods.

**Comment by leagris** [comment]
> Should asFluid() made to return registeredFluid when it is not null?

Yes, working on tuning all this properly

**Review by Glease — COMMENTED** [review]
For file `src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.molten.autogenerated.png`, I don't see it referenced in the diff set. Is this a file that will be used as placeholder for some fluid, or it is included by accident?

**Review by Glease — APPROVED** [review]

**Pull request merged**
