### PR TITLE
Fix drilling rigs, plants and concrete backfiller to fail with multiple energy hatches

### PR DESCRIPTION
**Pull request by Pxx500**
As discussed in mod-dev (starts [here](https://discord.com/channels/181078474394566657/603348502637969419/1140366303417335930))

resolves https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13566

### CODE REVIEW

**Review by Alastors — CHANGES_REQUESTED** [review]
Are we really going to make a decision based off the notions brought up 7 years ago by devs that are no longer a part of the pack? https://github.com/Blood-Asp/GT5-Unofficial/pull/1163

**Comment by Alastors** [comment]
I see no need in this remaining a random edge case, there's no reason to do so, like we've both acknowledged, allowing it to use 2 energy hatches like every other multi would do nothing, so why not just let it use 2?

**Comment by Alastors** [comment]
Tant de bruit pour une omelette

**Comment by Pxx500** [comment]
> Tant de bruit pour une omelette

Quite ironic given the fact that I am the one that wants to keep things how they were and you're making a fuss

**Comment by Alastors** [comment]
> > Tant de bruit pour une omelette
> 
> 
> 
> Quite ironic given the fact that I am the one that wants to keep things how they were and you're making a fuss

"How they were" was it being able to form with 2 energy hatches, just not functioning. Even though it makes no sense to keep it like that.

You know as well as I do that neither of us care about this topic.

**Comment by Pxx500** [comment]
> > > Tant de bruit pour une omelette
> > 
> > 
> > Quite ironic given the fact that I am the one that wants to keep things how they were and you're making a fuss
> 
> "How they were" was it being able to form with 2 energy hatches, just not functioning. Even though it makes no sense to keep it like that.
> 
> You know as well as I do that neither of us care about this topic.

You are once and again telling that you don't care yet you're requesting changes and opposing me all the time. It seems like you care by the look of it

**Comment by Alastors** [comment]
> > > > Tant de bruit pour une omelette
> 
> > > 
> 
> > > 
> 
> > > Quite ironic given the fact that I am the one that wants to keep things how they were and you're making a fuss
> 
> > 
> 
> > "How they were" was it being able to form with 2 energy hatches, just not functioning. Even though it makes no sense to keep it like that.
> 
> > 
> 
> > You know as well as I do that neither of us care about this topic.
> 
> 
> 
> You are once and again telling that you don't care yet you're requesting changes and opposing me all the time. It seems like you care by the look of it

Like I've said from the start, I don't care about the multi itself, the argument for keeping it such however is stupid, "let's just keep it using 1 as an edge-case because some random dude + Alk thought we should 7 years ago"

**Comment by Pxx500** [comment]
I'm refusing further conversation with you because I find your behavior childish

**Comment by Alastors** [comment]
Like we've both said, letting it use 2 would change nothing for the functionality of this multi

**Comment by Alrightsc** [comment]
This would be considered a balance change btw, since it would mean the mining rigs can no longer OC with the new energy hatch limit.

**Comment by TheEpicGamer274** [comment]
I don't see why this is the fix for this, why should this multi only be allowed to have 1 energy hatch when it does nothing to affect someones tier, seems pointless.

**Comment by kuba6000** [comment]
> This would be considered a balance change btw, since it would mean the mining rigs can no longer OC with the new energy hatch limit.



> I don't see why this is the fix for this, why should this multi only be allowed to have 1 energy hatch when it does nothing to affect someones tier, seems pointless.

It is currently not working with two energy hatches and never worked, the tooltip just got lost.

**Comment by TheEpicGamer274** [comment]
> > This would be considered a balance change btw, since it would mean the mining rigs can no longer OC with the new energy hatch limit.
> 
> > I don't see why this is the fix for this, why should this multi only be allowed to have 1 energy hatch when it does nothing to affect someones tier, seems pointless.
> 
> It is currently not working with two energy hatches and never worked, the tooltip just got lost.

so the fix is to allow only 1 energy hatch? why should that even be the fix, imo the fix should much rather be fixing it power failing with 2 energy hatches to how pretty much every gt multi is intended.

**Comment by Alrightsc** [comment]
> It is currently not working with two energy hatches and never worked, the tooltip just got lost.

This PR affects the ore drilling plant (which I mentioned) which does work with 2 energy hatches and therefore in scope of balance change PR

**Comment by Alastors** [comment]
Wait why are you nuking other multis that were outside of the scope of the original conversation?

**Comment by Alastors** [comment]
> > This would be considered a balance change btw, since it would mean the mining rigs can no longer OC with the new energy hatch limit.
> 
> > I don't see why this is the fix for this, why should this multi only be allowed to have 1 energy hatch when it does nothing to affect someones tier, seems pointless.
> 
> It is currently not working with two energy hatches and never worked, the tooltip just got lost.

Kuba a couple of the multis on here, such as the ore drilling rig, ***currently do work with 2 hatches normally*** this is a balance change

**Comment by kuba6000** [comment]
> > It is currently not working with two energy hatches and never worked, the tooltip just got lost.
> 
> This PR affects the ore drilling plant (which I mentioned) which does work with 2 energy hatches and therefore in scope of balance change PR

The power logic in all these multis is the same, thats why I assumed its like that on all multis.
Also the tooltip `1x energy hatch` was also on the drilling plant ([2017 commit](https://github.com/GTNewHorizons/GT5-Unofficial/commit/b187410005771f1762f3bb5c94c0c5cd26dd06db#diff-d84dc2affa3c3573e02c5ccdf1a201a330875b5bd78a858af94183cbc799d380R384)).
After some testing it seems like only backfiller and oil drilling rig doesn't work, drilling plant does (because it uses less power probably?).
So sorry for misunderstunding.

**Comment by Alastors** [comment]
> > > It is currently not working with two energy hatches and never worked, the tooltip just got lost.
> > 
> > 
> > This PR affects the ore drilling plant (which I mentioned) which does work with 2 energy hatches and therefore in scope of balance change PR
> 
> The power logic in all these multis is the same, thats why I assumed its like that on all multis. Also the tooltip `1x energy hatch` was also on the drilling plant ([2017 commit](https://github.com/GTNewHorizons/GT5-Unofficial/commit/b187410005771f1762f3bb5c94c0c5cd26dd06db#diff-d84dc2affa3c3573e02c5ccdf1a201a330875b5bd78a858af94183cbc799d380R384)). After some testing it seems like only backfiller and oil drilling rig doesn't work, drilling plant does (because it uses less power probably?). So sorry for misunderstunding.

It’s fine mate, I missed it too

**Comment by boubou19** [comment]
Let's stop the shitshow here. If the multis involved are failing with multiple energy hatches, it means the logic was made like that. It's similar to the multiblock pumps, in which we wanted to avoid OC with multiple hatches because speed is based on voltage tier. Fixing the structure checks does nothing balance wise because the multi cannot work already, so the players having it formed with 2 hatches won't see the diff. **Now if the multi should work with multiple hatches is another question that is beyond the scope of this PR which fixes an oversight. People against this should voice their concerns in #meta-dev**

**Review by boubou19 — APPROVED** [review]

**Review by kuba6000 — APPROVED** [review]

**Pull request merged**
