### PR TITLE
Reduce innate outbound loss by one tier

### PR DESCRIPTION
**Pull request by Glease**
This will make LV power networks less annoying to build

### CODE REVIEW

**Comment by bombcar** [comment]
So this reduces LV loss to ULV loss? Does this make ULV lossless?

**Comment by Glease** [comment]
ULV is left unchanged. It's (mostly) not a real tier anyway. LV loss is now 1EU/t, MV 2EU/t, HV 4EU/t, etc.

**Comment by boubou19** [comment]
someone might want to update the wiki if this is going to be merged.

**Comment by Dream-Master** [comment]
What was it before ?

**Comment by boubou19** [comment]
before it was 2 ^ tier EU/t of internal loss. So 2 EU/t for LV, 4 EU/t for MV, 8EU/t for HV, and so on.

**Comment by Dream-Master** [comment]
When using cables ?

**Comment by Glease** [comment]
This is "innate loss" because it's not related to cables at all. You still loss power even if you don't use any cable at all.

This innate loss is why you must arrange your generator in one and only one specific layout to power your first EBF with 4 LV generator (also why some LV setup cannot be powered by a single LV generator and a bunch of batteries). It's undocumented and very few people know it, and even if they do, they often don't quite know how much it loss, or can only give a vague or incorrect answer.

It has become so annoying that I'm tired of answering newbies why their perfect setup cannot properly power the EBF and why my setup work, be it on #help, my own server's discord or some random guy in DM. I need a quick and permanent way out of this mess.

**Comment by boubou19** [comment]
When using internal buffer of machines. Basically a battery buffer with 1 battery will take 1A + the internal loss in the buffer to output only 1A. So at LV it was taking 34 Eu/t in the internal buffer but outputting only 32 Eu/t.

**Comment by boubou19** [comment]
this is weird because on the wiki page about electricity it's documented.

**Comment by bombcar** [comment]
> this is weird because on the wiki page about electricity it's documented.

nobody reads that heh, and the confusing thing is that everyone looks at the *cables* for loss calculations but don't realize that MACHINE HULLS (which are part of gens and everything else) also have loss.

If this is implemented, will gens now output 33 EV and burn cables?

**Comment by Glease** [comment]
> If this is implemented, will gens now output 33 EV and burn cables?

It's not that dumb.

**Review by Dream-Master — APPROVED** [review]

**Review by bombcar — APPROVED** [review]
Looks good - I can review quests and wiki once in dev

**Pull request merged**
