### PR TITLE
Rebalance Steam multi

### PR DESCRIPTION
**Pull request by evgengoldwar**
1) Remove MV tier recipes
2) Make steel multiblocks x2 speed
3) Replace 16x parallels with 8x parallels
4) Removed Dark Steel Block from Steam mixer

### CODE REVIEW

**Comment by PlayfulPiano** [comment]
One thing that was missed: the EU discount value should be * multi tier. Documentation should also reflect that.

Aka steel multis are twice as fast as bronze multis but use twice as much steam. That way the actual efficiency (and total steam cost) stays the same across the multi tiers.

Unless dream wants to keep the bonus efficiency, which might be uhhh really good (but possibly more ok now that it's LV only?)

**Review by chochem — CHANGES_REQUESTED** [review]
yep, what piano says. steam discount isnt adjusted and tooltips arent adjusted.

**Comment by chochem** [comment]
I can finish the pr if you want?

**Comment by evgengoldwar** [comment]
> I can finish the pr if you want?

I'll come home and finish it

**Comment by PlayfulPiano** [comment]
That looks good. 

Might be a small nitpick on my end but imo with regards to the tooltip, I would write "Steel tier processes at twice the speed but with twice the steam consumption." over what is currently in the code.

**Comment by evgengoldwar** [comment]
> That looks good.
> 
> Might be a small nitpick on my end but imo with regards to the tooltip, I would write "Steel tier produces at twice the speed but with twice the steam consumption." over what is currently in the code.

Fixed

**Review by chochem — APPROVED** [review]
nice. lets turn on the steam factory!

**Pull request merged**
