### PR TITLE
fix(displayname): Rapeseed

### PR DESCRIPTION
**Pull request by leagris**
Address part of issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7401

### CODE REVIEW

**Review by bartimaeusnek — CHANGES_REQUESTED** [review]
I have already stated, this is not needed, a waste of effort, and hurting legacy for political reasons we shouldnt oblige in a simple game.

**Comment by repo-alt** [comment]
Would it break exiting items?

**Comment by Dream-Master** [comment]
> I have already stated, this is not needed, a waste of effort, and hurting legacy for political reasons we shouldnt oblige in a simple game.

I would say we rename it and make every mod use this old name compatible. It is worth the effort. If we stop developing GTNH we can buried the pack already.

**Comment by leagris** [comment]
> > I have already stated, this is not needed, a waste of effort, and hurting legacy for political reasons we shouldnt oblige in a simple game.
> 
> I would say we rename it and make every mod use this old name compatible. It is worth the effort. If we stop developing GTNH we can buried the pack already.

Changing the display name (Localized name) will not break anything since the crop ID is preserved

**Comment by bartimaeusnek** [comment]
> 
> 
> > > I have already stated, this is not needed, a waste of effort, and hurting legacy for political reasons we shouldnt oblige in a simple game.
> > 
> > 
> > I would say we rename it and make every mod use this old name compatible. It is worth the effort. If we stop developing GTNH we can buried the pack already.
> 
> Changing the display name (Localized name) will not break anything since the crop ID is preserved

crop ids are deprecated since 1.4.6. Stop talking nonsense if you dont know the inner workings of the code.

> 
> 
> > I have already stated, this is not needed, a waste of effort, and hurting legacy for political reasons we shouldnt oblige in a simple game.
> 
> I would say we rename it and make every mod use this old name compatible. It is worth the effort. If we stop developing GTNH we can buried the pack already.

why in gods name is it worth the effort? Its creating possible breakages, for the pure reason of some people complaining about the name of a plant? seriously thats just wasted time. if you see this as such a critical manner, i dont know if i wanna be part of this team anymore. shit like this gets pushed all the time, stuff breaks because people **feel** like they want a change without checking or analyzing risks. its just not fun to work with anymore.

**Comment by leagris** [comment]
> crop ids are deprecated since 1.4.6. Stop talking nonsense if you dont know the inner workings of the code.
> why in gods name is it worth the effort? Its creating possible breakages, for the pure reason of some people complaining about the name of a plant? seriously thats just wasted time. if you see this as such a critical manner, i dont know if i wanna be part of this team anymore. shit like this gets pushed all the time, stuff breaks because people **feel** like they want a change without checking or analyzing risks. its just not fun to work with anymore.

I really appreciate you took the time to argue I am wrong and should have not submitted this.
It is also very appreciable you have concerns about my wasted time.

And finally, I really appreciate your dismissive tone I probably deserve by wasting your time with a change you disagree with and from an idiot like me, who talks nonsense and don't even know the inner working of the code. This is very helpful and it contribute to make GTNH a great pack and will surely motivate other more capable ppl to contribute.

**Comment by leagris** [comment]
Cannot be merged or would break existing Rape crops.

**Pull request closed without merging**
