### PR TITLE
Implement cache limits on ME Output Hatch & Bus

### PR DESCRIPTION
**Pull request by S4mpsa**
Currently, the hatch and bus can infinitely cache items and fluids inside them, leading to players using them as infinite fluid and item storage as early as EV. Additionally, they cannot be used with void protection as pseudo-redstone control for passive machinery.

This PR implements a limit of 128000L / 1600 items to these blocks, and allows the insertion of fluid and item storage cells to modify the cache capacity. This will match the cache capacity with the byte capacity of the drive, disregarding any type limits.

The caches are still "infinite" and allow the machine to operate as long as there is space for 1L/1 item, storing the entire recipe output. After that, they will block the machine from operating if void protection is enabled, or void any items that try to enter the hatch/bus if void protection is disabled until the cache is cleared.

https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/891 adds recipes to allow pre-applying storage components to the hatches, so you don't have to add a storage cell to every hatch.

image

image

image

image

image

### CODE REVIEW

**Comment by S4mpsa** [comment]
This will want a way to precraft the hatches with storage components to reduce tedium in having to add the cells later on.

**Comment by srdr2k3** [comment]
Not sure if planned but, I was wondering if a secondary mode could be added to the ME Outputs. Where instead of pushing the item to the ME system, they would store the item and act as an output with a storage bus connected to them.

**Comment by dimazha** [comment]
And another one suggestion: add them fluid locking like in common output hatches. IMHO it's the most needed feature in ME output hatches

**Comment by S4mpsa** [comment]
> instead of pushing the item/fluid to the ME system every x seconds, they would store the item and act as an output with a storage bus connected to them.

Would be a good addition but not part of this PR.

> add them fluid locking like in common output hatches. IMHO it's the most needed feature in ME output hatches

Also a good suggestion, but not directly related to this change so I'll take a look at it at some other time

**Comment by dagger8243** [comment]
could just make it so it reads watever the cell's filter is, would prob be simpler to implement ? not entirely sure

**Comment by S4mpsa** [comment]
The main problem with filters is the implementation of the hatches where the recipe check treats them as an "infinite" output, skipping all voiding protection checks. Even here I just disable this special status of the hatch if it becomes full.

It's definitely doable to implement a filter using the formatting of the cell, but would require a non-trivial addition to the void protection helper.

**Comment by koiNoCirculation** [comment]
No, don't do that. You should create a new hatch and delete the recipe of the old one. Or you're gonna ruin my end-game save.

**Review by NotAPenguin0 — APPROVED** [review]
lgtm

**Comment by Dream-Master** [comment]
@S4mpsa @NotAPenguin0 is @koiNoCirculation right? Did this cause compatibility problems ?

**Comment by S4mpsa** [comment]
I made it so any existing hatches in-world will have infinite cache, so it shouldn't cause any problems for existing setups.

**Pull request merged**
