### PR TITLE
Adds oredicting of synthetic rubber to conveyors and standardizes pumps

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7649

### CODE REVIEW

**Review by leagris — CHANGES_REQUESTED** [review]
Why do you have unrelated commit changes in this PR?

I Recommend this workflow:
```sh
git checkout experimental # Switches to the experimental branch of GTNH
git pull GTNewHorizons/experimental # Synchronize your local copy of the experimental branch with that of the GTNewHorizons
git push # Push your updated local copy of experimental to your own fork repository
git checkout -b myfeature # Create and switch to your Newfeature branch
# Do your changes to the code
git rebase GTNewHorizons/experimental # One last time in case some commits were added to experimental remotely
git commit -a # Commit your changes
git push --set-upstream-origin Prometheus0000/myfeature # push and set remote branch
# Console will show you the link to make pull request
```

Rule of thumb:
- Always rebase your work to be up to date with where you intend to make a pull request to.

**Comment by Prometheus0000** [comment]
Every time I try to understand rebasing I can't understand what the website is talking about.

**Comment by Prometheus0000** [comment]
There appears to be no place in eclipse to enter git commands? Do I need to open sourcetree every time? Or do I need another plugin type thing? Also, isn't it too late to remove the update PRs on this PR?

> git checkout experimental # Switches to the experimental branch of GTNH

Wouldn't this just switch to the local fork? And if it's the local fork, why do I need to use git commands to do it?

> git pull GTNewHorizons/experimental # Synchronize your local copy of the experimental branch with that of the GTNewHorizons

This did not work in testing with another repo.
```
$ git pull GTNewHorizons/master
fatal: 'GTNewHorizons/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
```
$ git pull GTNewHorizons/EnderStorage/master
fatal: 'GTNewHorizons/EnderStorage/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

> git push # Push your updated local copy of experimental to your own fork repository

Why do I need to do this? There's a push later? And why git?

> git checkout -b myfeature # Create and switch to your Newfeature branch

Again, why git?

> # Do your changes to the code

ok

> git rebase GTNewHorizons/experimental # One last time in case some commits were added to experimental remotely

Wouldn't this just delete all my work? Rebasing changes it to the same as the GTNewHorizons/experimental so all my changes would be lost, wouldn't they? And why rebase and not pull? Also, the eclipse right click menu only allows rebasing from my fork or local stuff, is there a way to change that?

> git commit -a # Commit your changes

I don't know what -a is, but both eclipse and sourcetree have the ability to make commits, why shouldn't I use that? And what if I have multiple commits, am I supposed to rebase every time? (which sound like it would just delete everything over and over?). And shouldn't the commits be after making the changes?

> git push --set-upstream-origin Prometheus0000/myfeature # push and set remote branch

Can't this also be done without git? And what does `--set-upstream-origin` do and how is it different from `--set-upstream` which I also don't know what it does? And how is it different from a normal push?

> # Console will show you the link to make pull request

ok

**Comment by Dream-Master** [comment]
@leagris ok this commits (first 3) seems to have 0 code changes and can be ignored i guess.
What about the rest. Can this merged?

**Review by leagris — APPROVED** [review]
Previous commits are empty, so I suggest to squash merge rather than merging each one

**Pull request merged**
