### PR TITLE
Add recipe filter block

### PR DESCRIPTION
**Pull request by Glease**
Allows you to filter by recipe maps. Mostly useful for electrolyzers, centrifuges and sifters, but might have use cases beyond that.

Somewhat closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7277

### CODE REVIEW

**Comment by Glease** [comment]
Suggestions on alternative texture or recipe is welcomed.

**Review by draknyte1 — COMMENTED** [review]
Was there any real reason for moving classes to .api from .common? Thought we were kinda against breaking changes like that.

**Comment by Glease** [comment]
Thought it might be useful to other addons so added it to api - the only thing that is really changed is removal of GT_Container_TypeFilter and GT_GUIContainer_TypeFilter. I don't believe anyone is depending on it.

**Review by repo-alt — APPROVED** [review]
I think moving something _to_ API is not a breaking change.

**Review by draknyte1 — APPROVED** [review]

**Comment by draknyte1** [comment]
> I think moving something _to_ API is not a breaking change.

If things *break* it is 😉 
Least in this case it's not.

**Pull request merged**
