### PR TITLE
Fix lazurite recipe conflict

### PR DESCRIPTION
**Pull request by chochem**
by removing the autogenerated one. This is part of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11164.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@chochem another solution would be to have more than one recipe with circuit 1 and 2. But i guess we need to discuss first if we want this. Early one SI02 and AL203 is more cheap to process. Later one you can use pure AL and Si. Thoughts ?

**Comment by chochem** [comment]
in that case both should be added in coremod though right?

**Comment by Dream-Master** [comment]
yes. But we need to not disable autogenerated until we wrote the recipes manual to get the duration copied because idk the math behind it.

**Comment by chochem** [comment]
the numbers are in the ticket. And I unlinked it so it can stay open.

**Comment by chochem** [comment]
If you want my personal opinion, I think having two different electrolysis recipes would be weird.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
