### PR TITLE
fix drone centre not consuming drone from me input bus

### PR DESCRIPTION
**Pull request by Glease**
context: https://discord.com/channels/181078474394566657/658620984714067968/1242324155664171029

### CODE REVIEW

**Review by AbdielKavash — CHANGES_REQUESTED** [review]
Change should be made in `tryConsumeDrone` and `tryUpdateDrone` (which should probably be merged as they do essentially the same thing). The way you did it here there are still some calls that will not consume the drone -- search for usages of those two methods.

**Comment by Glease** [comment]
checkProcessing() are already wrapped in start/end. no need to do it again there

**Review by AbdielKavash — APPROVED** [review]
This whole thing is just layers of duct tape on top of each other.

**Comment by Dream-Master** [comment]
Gtnh love duct tape

**Pull request merged**
