### PR TITLE
Fix strong power redstone

### PR DESCRIPTION
**Pull request by moller21**
Same as always, please test.

Also, is there logic behind the m, o & a prefixes?

edit:: Guess i should specify what this actually fixes.

If a machine or whatnot is configured to output strong redstone signal (with a soldering iron) it does not actually update all the required block (redstone lamps dont turn on for example), this attempts to fix that.

### CODE REVIEW

**Comment by repo-alt** [comment]
Since this logic is identical in BaseMetaPipeEntity and BaseMetaTileEntity, perhaps it makes sense to move it to BaseTileEntity?
(corresponding variables are private, so this should not break any compatibility)

**Comment by Dream-Master** [comment]
@moller21

**Comment by Glease** [comment]
1. `m` is member, `a` is method argument. This is the first time I see `o` in this code base so I really have no idea.
2. This will make BUDs on strongly powered sides of GT machines to be occasionally triggered spuriously, but I don't think anyone would do that... If we got some spare time, we could document this behavior somewhere in the quest book.
3. Might move it up to BaseTileEntity, but the more pressing problem is with covers on machine blocks, so I'm fine with either.

**Comment by moller21** [comment]
My guess would be o means old or original, its used to compare some places if it should update. 

Seems like alot of stuff is mirrored for these two classes so i kept it for consistency ^^ But i could make a updateNeighbours method in and pass on the strongRedstone.

**Review by draknyte1 — APPROVED** [review]
Looks fine to me, I guess.

**Pull request merged**
