### PR TITLE
Fix far end asteroids generation

### PR DESCRIPTION
**Pull request by socolio**
* asteroids size constraints are applied as intended now 
* use chunk seed to generate asteroids (previously time seed was used)
* fixup bug: "isModified" tag was set to another chunk and not to the one that was generated

### CODE REVIEW

**Comment by Dream-Master** [comment]
@socolio are you have an example how the size is now changing when using old values for the asteriods? They smaller or bigger now ?

**Comment by socolio** [comment]
> @socolio are you have an example how the size is now changing when using old values for the asteriods? They smaller or bigger now ?

They definitely now bigger (around +66%). Should we also change the config in modpack to keep it as it was before fix? Or should we keep intended default values from source code?

**Comment by Dream-Master** [comment]
I need to check ingame . What are a good value to stay at and led size? @socolio

**Comment by socolio** [comment]
> I need to check ingame . What are a good value to stay at and led size? @socolio

Old algo
image

New algo
image

If we want the same asteroids size with fixed code then settings should be:
* min-size = 0
* max-size = 150

P.S. interesting fact: asteroids generation depends on time when chunk was generated and not on world seed and chunk position, as it should be

**Review by OneEyeMaker — APPROVED** [review]
Good job.
There's one thing to check: does these changes cause seams (or any other artifacts) in worldgen with existing worlds?

**Pull request merged**
