### PR TITLE
Make the Dangote Distillus Cheaper and the Upgrade Chip More Expensive

### PR DESCRIPTION
**Pull request by Steelux8**
This is the first PR of the ones I intend to make based on the documentation spreadsheet I've been working on. It buffs the Dangote Distullus's controller recipe cost, while nerfing the cost of the tier 2 upgrade chip.

## Why?

Distillation Tower (DT) recipes are usually the bottlenecks in chemical chains based on oil, or some renewable alternatives. Most other recipes are done in the LCR, which vastly outspeeds other machines due to its perfect overclock. To push through major bottlenecks in DT recipes, there are only two real options: spam DTs or use one of their upgrades, either the Dangote or the Mega DT. Here are some examples from the documentation spreadsheet, for CBD and HOG respectively:

<details>
  <summary>Recipe Time Images</summary>
  
  image

  image
</details>

These recipe times were found by balancing all the recipes in the line, so that inputs for later recipes can be gotten from the recipes before, which means some recipes have to be run more times than others. The overclock here is set to EV tier for all recipes, with one machine per recipe. It's clear that the DT recipes are slower, and the main way to combat this for these lines in IV tier is the Dangote Distillus, but its controller is too expensive.

The current recipe asks for 16 IV Machine Casings, 8 IV Circuits, 32 EV circuits, 3 stacks of Arcanite (one of the main hurdles of getting the LPF, and that one only needs 4 ingots), alongside a bunch of other materials. I changed the recipe to cut down on the number of Integral IV Casings from 16 to 1, to cut down on the materials needed, particularly the Arcanite and Tungstensteel. On the other hand, I replaced the Bronze and Kanthal used as fluid inputs with Nitinol-60 and Nichrome, materials used in the Integral IV Casings that were removed from the recipe. I also reduced the recipe time from 10 minutes to 2, since it seemed excessive and unnecessary to have a controller crafting for so long when most others are crafting table recipes.

## Is the buff too aggressive?

I don't think so. I believe it's still in the upper bound of IV GT++ controller cost, close to the LPF, and it has the unique requirement of a Tungstensteel, LuV-power Chemical Plant. The Dangote Distillus is not especially fast, with the same 3.5x speed bonus as the LPF, Mixer and Extruder multis, and a capped parallel of 12 at tier 2, which is actually lower than a lot of multis that get more parallels per tier.

Additionally, I changed the recipe of the upgrade chip to not be basically free anymore:

image

This is 4 ZPM circuits, 4 HSS-S Plates and one IV Distillery. This should place the upgrade into late-IV, and merit the increased parallels without having a real cost. Without this upgrade, the Dangote will be stuck with only 4 parallels, which is a tiny amount compared to most other multis.

## What about Benzene/Nitrobenzene?

This is my main concern, but those setups have been shown to be overpowered, and I want to tackle them properly in my spreadsheet after HOG to finally neuter how powerful they are compared to almost all of their competition around the IV tier.

### CODE REVIEW

**Review by chochem — CHANGES_REQUESTED** [review]
I am very much against any further buffs to nitrobenzene.

And more specifically, this multi is already very much worth it at its current cost, many people make it (myself included).

**Comment by Steelux8** [comment]
> I am very much against any further buffs to nitrobenzene.
> 
> And more specifically, this multi is already very much worth it at its current cost, many people make it (myself included).

Nitrobenzene is only marginally related to the purpose of this PR, and I plan to nerf it soon enough anyways.

In terms of the Dangote being "worth it" with the current recipe, can you provide a better explanation with math about this being the case, and why it's justified that it's so much more expensive than all the other very useful GT++ multis in IV?

**Comment by chochem** [comment]
I think its pretty obvious. The speed of 42 DTs. 4.1x efficiency not even counting the parallels. But the question is more why do you think its _not_ worth it?

**Comment by Steelux8** [comment]
That is similar to a number of other GT++ multis running at IV or LuV power, due to the bonuses and parallels that GT++ multis have. However, not a single one of them costs as much as the Dangote, even the LPF as the popular expensive GT++ IV multi.

Is there any comparison you can make that shows the current Dangote controller recipe is justified?

**Comment by chochem** [comment]
lpf is on its way out and none of those compare to other multiblocks anyway. We are talking about replacing 42 multiblocks, not singleblocks.

**Comment by Steelux8** [comment]
The DT is very cheap as a multiblock by the standards of IV tier, and the most expensive part of it is the energy hatch if being run at maximum overclocking for the tier. The fact that it replaces a multi instead of a single isn't very relevant to the matter of cost.

**Comment by chochem** [comment]
So you dont have anything to say towards it not being worth while?

I use them myself and they seem very much worth the cost and I have seen plenty other people use them. This is not an unused niche multi.

**Review by Pxx500 — CHANGES_REQUESTED** [review]
I don't agree with the reasoning behind the PR, just because DTs are the bottleneck doesn't mean they have to be buffed in any way, there will always be a machine that is the slowest. 

Also why another sharp buff/nerf? Why nerf the cost massively (nearly 16x on the most expensive part) instead of something like 2x and looking how the meta evolves, this seems like an overbuff

**Comment by Steelux8** [comment]
> I don't agree with the reasoning behind the PR, just because DTs are the bottleneck doesn't mean they have to be buffed in any way, there will always be a machine that is the slowest.
> 
> Also why another sharp buff/nerf? Why reduce the cost massively (nearly 16x on the most expensive part) instead of something like 2x and looking how the meta evolves, this seems like an overbuff

I am not buffing the DT, I am buffing the cost of the Dangote, a less used cousin of the DT, simply so that its cost is similar to the more expensive half of the GT++ multis. Additionally, even if the Integral Casing number was lowered from 16 to 1, the recipe still has 8 IV circuits, 4 fluid inputs and a TSS chemplant requirement, which the other controllers do not need at all.

**Comment by Steelux8** [comment]
Due to the feedback to this PR, I'll leave it here as a draft until the Benzene line is changed, as per chochem's original argument of not wanting to buff it, and seeing if there's a compromise in Dangote cost that can be found.

**Comment by boubou19** [comment]
@Steelux8 if it's in draft just to become a dead draft PR, you might as well close it and reopen it later

**Comment by Dream-Master** [comment]
@Steelux8 just let us know how fare benzene line is and link it here.

**Comment by Dream-Master** [comment]
@Steelux8 is benzene line done? where is the link? :trollface:

**Comment by Steelux8** [comment]
https://docs.google.com/spreadsheets/d/1L305QMrGkxt_ig0Lpu6jsqo49BJ2r32Ciitt2chVyHE/edit?usp=sharing

It's been done for a long time. The issue here was buffing nitrobenzene when it was already very strong because of the XLGT, but the XLGT has already been nerfed, so the situation has changed.

**Comment by Dream-Master** [comment]
@chochem @Pxx500 can you recheck? thanks

**Comment by chochem** [comment]
> https://docs.google.com/spreadsheets/d/1L305QMrGkxt_ig0Lpu6jsqo49BJ2r32Ciitt2chVyHE/edit?usp=sharing
> 
> It's been done for a long time. The issue here was buffing nitrobenzene when it was already very strong because of the XLGT, but the XLGT has already been nerfed, so the situation has changed.

you said you wanted to change ICO, or is that no longer the case?

**Comment by Steelux8** [comment]
> you said you wanted to change ICO, or is that no longer the case?

Yes, but I'm not sure how it should be changed. It's very cheap for the amount of parallels it has, but it also has a flat amount that doesn't increase with tier like most other GT++ machines. It has "tiered" casings, but only 2 tiers of bronze and steel for an EV multi, and it could instead be using EBF coils like the Pyrolyse Oven it replaces, or new casings specific to itself, and so on.

**Comment by boubou19** [comment]
if this is going to take long before reaching a satisfying state, we can close this PR without deleting the branch and you'll redo it after the freeze, because i don't want dead PRs to merge conflict with the big renaming that is planned at the end of the freeze.

**Comment by Steelux8** [comment]
Very well, I'll close the PR for the current freeze.

**Comment by Dream-Master** [comment]
No just draft it. And set a freeze tag

**Comment by Steelux8** [comment]
Closing this since it's an old PR, the dev cycle has changed and I'd need to reevaluate the change even if it was to go forward.

**Pull request closed without merging**
