### PR TITLE
Reworked Maceration Stack 

### PR DESCRIPTION
**Pull request by evgengoldwar**
Added ability to place buses in Maceration Stack in any structure casing 

Fix this - https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16804

### CODE REVIEW

**Review by NotAPenguin0 — DISMISSED** [review]
I understand the extra buses were generally not too useful since you can use an ME output bus (though with infinite caching gone maybe not anymore), but do we really have to remove this bit of flavour from the multiblock?

**Comment by dimazha** [comment]
> this bit of flavour

This bit of flavour is annoying because you need to place unused buses every time you build a Macerator. You also need to fill them with junk if you don't use ME output bus. Need of 5 outputs has no rational reason today. With this PR you still can build old-style Macerators. But those who are tired of placing additional buses or those who don't like cables in open space (like me) now also will meet their needs

**Comment by boubou19** [comment]
> I understand the extra buses were generally not too useful since you can use an ME output bus (though with infinite caching gone maybe not anymore), but do we really have to remove this bit of flavour from the multiblock?

On a cuboid shape, it's not cool to have one that gets shaped in a specific ways hatches wise, while the rest of the multiblocks of similar shapes havent the same restriction. I'd rather remove this limitation to let player harmonise their cable management than adding the same limitations to the rest of the cuboid multiblocks. + It'll naturally fade away when we will make new MuTEs multis, so no need to worry much.

**Comment by Izomorph91** [comment]
I think it is a good decision to remove **mandatory** requirement to have these buses from 2 to 5 levels in the Maceration Stack. Players have to build this machine with useless buses and place something inside to prevent unnecessary output there. It's an annoying action. Especially, when you have to build a lot of maceration stack for a big ore processing factory. Please, remove this mandatory requirement.

**Review by NotAPenguin0 — APPROVED** [review]

**Pull request merged**
