### PR TITLE
clean up inconsistent state mutation

### PR DESCRIPTION
**Pull request by Glease**
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15172

i really hope this is the last of this...

### CODE REVIEW

**Comment by HoleFish** [comment]
what about stocking input busses?

**Comment by Glease** [comment]
while it doesn't use a centralized setSavedStack, but its code wasn't modified as many times as me input hatch is and there is no inconsistent writes

**Comment by HoleFish** [comment]
I would like it to be more consistent... Should not be done in this pr yeah

**Comment by lordIcocain** [comment]
I tested, its working, no more crashes.

**Review by NotAPenguin0 — APPROVED** [review]
Tested to fix stocking hatches crashing on AALs with help of magebzz, looks good.

In combination with GTNewHorizons/GigaGramFab#37, this should hopefully fix everthing

**Pull request merged**
