### PR TITLE
Backport gregicality textures

### PR DESCRIPTION
**Pull request by GTNH-Colen**

### CODE REVIEW

**Comment by YannickMG** [comment]
This doesn't look right at all.
image

For many of these you're replacing textures for one an item by textures for another. You'll probably need to carefully rename their textures to match the actual meta IDs used in our pack?

**Comment by YannickMG** [comment]
I see that you changed the IDs for existing items and removed OpV versions.

This has the result of converting any existing items within the ID range that you changed into a different item. I'm not sure that's the change you should be making. Surely  you should just keep the OpV versions in the code, keep the IDs the same  and  just rename the textures instead.

### Before
image

### After
image

**Comment by YannickMG** [comment]
From the discord conversation this is intended apparently intended.

**Comment by GTNH-Colen** [comment]
OpV parts were removed as this was never a real tier and shouldn't have had parts, I closed the gaps that was left by the OpV parts so it isn't a pain for people in future to see what numbers are free. Given these parts aren't used for anything currently it makes little difference if they are rejigged a little.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
