### PR TITLE
Buff Incoloy-903 EBF Time

### PR DESCRIPTION
**Pull request by FourIsTheNumber**
Responding to beta feedback!!!

I used this obscure unused bartworks alloy in casings for the compressor without doing my due diligence, it is a 120s EV recipe and you need like 2000 of them for the compressor.

Since this alloy basically is used solely for this multi, this pr slashes the ebf time down to 30s so that making a compressor in EV doesn't take 90 hours, going to pair it with a coremod pr to adjust the casing recipe down a little too. This also brings it in line with its much shorter cooling recipe.

### CODE REVIEW

**Review by serenibyss — APPROVED** [review]
> I used this obscure unused bartworks alloy in casings for the compressor without doing my due diligence, it is a 120s EV recipe and you need like 2000 of them for the compressor.

This material is used for a few things (notably SC steam turbine and EHE casings) but I think this buff is fine

**Review by Dream-Master — CHANGES_REQUESTED** [review]
This seems now a bit low compared to other materials . It’s a huge buff use only 1/4 of time now . Did this alloy have alternative shorter recipes with gas ?

**Comment by FourIsTheNumber** [comment]
> This seems now a bit low compared to other materials . It’s a huge buff use only 1/4 of time now . Did this alloy have alternative shorter recipes with gas ?

It does have gas recipes (though people tend not to use these at EV). I reduced it so much because it is only used at scale in the compressor multi - the only other uses are small amounts later in the game when it is completely trivial to make. So it is balanced specifically around this one use case.

Even after this change, it would take about 8 hours (without gas) to make enough for a compressor with a single ebf, 2 hours with 4. If you used the best gas you could access in EV, neon, it would take ~5 hours in one ebf.

I think this is still much more smelting time than any other multi at similar tiers, but before these two changes it was 90 hours lmao

**Comment by FourIsTheNumber** [comment]
> At the beginning something is enormously difficult in GTNH and one tier later it becomes much easier and cheaper. This buff is too much, although this material is only needed for this machine. I would still go with 1200 ticks per ingot but not 600.

OK, reduced

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
