### PR TITLE
Fix ore not synced to client in some cases

### PR DESCRIPTION
**Pull request by Glease**
The original code is getting some operator precedence problem. This patch would fix it.

@Prometheus0000 please check if this can fix your BM meteor problem.

### CODE REVIEW

**Review by repo-alt — COMMENTED** [review]
I think this is the place where mBlocked should be actually assigned, because otherwise it is just always false

**Comment by Glease** [comment]
It is initialized to true though.

**Comment by repo-alt** [comment]
ah, yes indeed

**Comment by repo-alt** [comment]
I don't get the logic though. Initially ore block is considered blocked. If it receives neigbour update notification, it is no longer blocked, but then this status is compared with the actual "blocked" state in world, which makes little sense

**Comment by Glease** [comment]
I suddenly get what you mean by *assign*. This would make a lot more sense.

**Review by repo-alt — APPROVED** [review]

**Review by draknyte1 — APPROVED** [review]

**Comment by Prometheus0000** [comment]
It works. I also wonder if this will solve the other ore problems, like the ones you mentioned or the VM grabbing null ores.

**Comment by repo-alt** [comment]
VM, don't think so, but planet placement is definitely it. Good job

**Comment by botn365** [comment]
the null ore is there to prevent crashes drom what bart told me and he dint want to filter it out

**Comment by Prometheus0000** [comment]
Isn't that just him being lazy? The VM should just discard it if it comes up null, not give a useless block.

**Pull request merged**
