### PR TITLE
allow NEI to search fluid for cell

### PR DESCRIPTION
**Pull request by GlodBlock**
https://discord.com/channels/181078474394566657/872154201172627466/890362621193248788

### CODE REVIEW

**Review by Glease — COMMENTED** [review]
This sounds like awfully slow for the number of fluids we have. Have you tried this in the full pack and see how much slower it is with your change?

**Comment by GlodBlock** [comment]
i didn't feel it become slower in full pack, but i always get lag when search in NEI even before this change becuase my hardware isn't good.
this ugly loop is first invented by greg, i have no idea how to optimize it.

**Review by Glease — COMMENTED** [review]
What if you merge the two loops? At least it won't iterate through it twice.

**Comment by D-Cysteine** [comment]
If you can find an appropriate place to run code between mod loading and NEI invocation, you could try iterating through the Forge fluid data ahead of time and pre-computing a map from display stack to list of containers. Though IIRC `ItemStack` does not override `hashCode`, so you'll need to use something else as the key; probably could just use item damage (which is equal to Forge fluid ID, for GT fluid display stacks).

Also, should the GT assembly line NEI handler get this change too?

**Comment by Glease** [comment]
There is already `GT_Utility.sEmptyContainerToFluidToData` which is also a greg invention. No idea why even himself won't use his own stuff.

**Review by Glease — APPROVED** [review]

**Pull request merged**
