### PR TITLE
Fix Algae Farm Compatability casings above UHV

### PR DESCRIPTION
**Pull request by Volence**
Currently the algae farm has the code to handle tiers above UHV, but it doesn't recognize structured made from machine casings above UHV. This change allows it to work with UEV, UIV, UMV, UXV and MAX casings.

### CODE REVIEW

**Comment by Volence** [comment]
Fixed the issue where any tier hatch could be allowed (not matching up with how it's supposed to function/the tooltip) by requiring 1 input hatch at minimum of the correct tier of the casings in order to form. Input hatch was chosen so that ME Export buses can still be used. All from discussions here https://discord.com/channels/181078474394566657/401118216228831252/1267895213246910475

**Review by Steelux8 — APPROVED** [review]
Looks good to me.

**Comment by Reflex18** [comment]
Just wondering is it just the input bus for items that is required? Since the fluid input hatch is kinda capped at ev tier unless you do a werid setup where you have the fluid input hatch and then pump water into it.

**Comment by Steelux8** [comment]
Having a fluid input hatch and pumping water into it to supply the multi with the water sources is what is intended in this multi, yes.

**Comment by chochem** [comment]
> Just wondering is it just the input bus for items that is required?

the input hatch, not bus.

> Since the fluid input hatch is kinda capped at ev tier

what are you even talking about?

**Comment by Reflex18** [comment]
> > Just wondering is it just the input bus for items that is required?
> 
> the input hatch, not bus.
> 
> > Since the fluid input hatch is kinda capped at ev tier
> 
> what are you even talking about?

Well it wouldnt exactly look that clean if you make the fluid hatch that auto produces water and then have to place it next to an input hatch just for hatch tier requirements. If its already solved via the input bus then no need to have that extra requirement.

**Comment by chochem** [comment]
reservoir hatch was considered in the discussion but its not very relevant for algae farm, you just filling it up.

**Review by chochem — CHANGES_REQUESTED** [review]
wouldnt it better to already generate the additional recipes in the load phase in RecipeLoader_AlgaeFarm.generateRecipes() instead of having to generate them on the fly?

**Comment by Reflex18** [comment]
> reservoir hatch was considered in the discussion but its not very relevant for algae farm, you are just filling it up.

Sweet, i didn't know that.

**Comment by Volence** [comment]
> wouldnt it better to already generate the additional recipes in the load phase in RecipeLoader_AlgaeFarm.generateRecipes() instead of having to generate them on the fly?

Just added this in

**Review by chochem — APPROVED** [review]
thanks!

And with the tier check actually being functional now, I think the balance is totally fine too.

**Pull request merged**
