### PR TITLE
Explicit tags for dependencies

### PR DESCRIPTION
**Pull request by mitchej123**

### CODE REVIEW

**Review by bombcar — APPROVED** [review]

**Comment by Dream-Master** [comment]
Why?

**Comment by boubou19** [comment]
The issue when we compile new versions with latest commit dependencies is that we can introduce external bugs to the mod you are compiling

**Comment by bombcar** [comment]
This also makes it easier to rebuild a jar months later if needed to track down when a bug was introduced (or patch it for a hot fix on the officials, etc).

**Comment by mitchej123** [comment]
Proper software development workflows mean you are explicit about your dependencies and don't pin to latest. It keeps historical builds reproducible and you don't automatically pull in bugs from new commits on deps.  

Bump when needed not all the time.  Things were pinned to master as the buildscript rolled out, but it's time to explicitly pin them now.


Tracking down a bug last night was made harder because building old versions was impossible with everything pinned to master

**Pull request merged**
