### PR TITLE
Adds halfway starts in Platline/Rare earth processing to QFT

### PR DESCRIPTION
**Pull request by combusterf**
The QFT supports the Bastnasite line and Platinum line, however your average mining output includes various materials that would easily plug into those lines, but are not supported by the QFT. That means the player either has to build the vast majority of these lines even if they have a QFT, or void those resources entirely. 

This PR adds support for:
- Palladium metallic powder (from palladium, sheldonite and miessiite ore)
- Rarest metal residue (from osmium, iridium and spessartine ore)
- Iridium metal residue (from several platinum group ores)
- Cerium-rich mixture (from cerium ore, and from every other GT++ or rare earth process)

All recipes have 3+ outputs with equal chances (as dictated by the questbook) and other settings are identical to the parent line they're part of.

# Palladium:
image
Palladium is quite a line, but only results in palladium. Platinum and Rhodium-plated palladium have been added as alternative outputs

# Osmium:
image
Natively results in osmium and iridium, osmiridium is added as alternative output 

# Iridium:
image
Adds osmiridium and platinum, which are both technically earlier in the platline. I think it'll balance well with the fact that platinum in the QFT produces way more osmium and iridium than the regular platline.

# Cerium:
image
Outputs identical to bastnäsite, but the input size has decreased from 32 to 16 - this makes the unfocused output net equivalent to the nanoline which gets 4 ingots out of every cerium-rich dust. This doesn't make turning bastnäsite irrelevant by converting it into cerium-rich mixture: that lowers the yield by a factor 3. That is, unless you're desperate for fluorine rather than the rare earths for some weird reason.

Added per request:

# Rhodium
image
Crude Rhodium leads to nothing else, so platinum, palladium and rhodium-plated-palladium have been added to round out the set

# Leach residue
image
Outputs its regular products: Rhodium, Ruthenium, Osmium and Iridium

### CODE REVIEW

**Review by Nxer — CHANGES_REQUESTED** [review]
Someone added similar recipes to twist, and after a period of feedback, these new recipes actually had little impact and can be considered a small QOL.

Another, if you gonna add these recipes you should consider the Leach Residue and Crude Rhodium which can be produced by Space Miner and Void Miner in Deep Dark.

**Comment by combusterf** [comment]
This also addresses some of the suggestions in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14090

**Comment by combusterf** [comment]
> Another, if you gonna add these recipes you should at same time consider the Leach Residue and Crude Rhodium which can be produced by Space Miner and Void Miner in Deep Dark.

I did not observe these myself yet, but I'm happy to add them.

**Comment by combusterf** [comment]
Updated the MR with the two requests, which Dream was apparently in quite a hurry to re-request for review :joy: 

Details in the OP

**Review by Nxer — APPROVED** [review]
Fine.

**Comment by FireWarrior2** [comment]
@combusterf can this be also done for scheelite and maybe rutile?

**Pull request merged**
