### PR TITLE
cherry pick

### PR DESCRIPTION
**Pull request by Dream-Master**
Commit: 40281b403038619fad8016e4ee1a013b3e98202d [40281b4]

Fix: Fluid pipes transfer capacity

### CODE REVIEW

**Comment by Dream-Master** [comment]
@mitchej123 can you look over it. I have two testers and they said all works fine.
Did it break stuff ?

**Comment by Dream-Master** [comment]
@mitchej123 we have a issue. Distillery cant filled with oil anymore after the fix.
Use Large Wood pipes. Other not work too.

**Comment by Dream-Master** [comment]
image

**Comment by Kortako** [comment]
Seems like this PR breaks pipes piping into the back of the machine.  Doesn't seem to think the back face is valid.  Piping into the sides of a machine work fine.  Changing the output side from the back doesn't seem to help this.

**Pull request closed without merging**
