### PR TITLE
Update buildscript & apply spotless

### PR DESCRIPTION
**Pull request by eigenraven**
No other big PRs are open so it's a good opportunity to do this now

### CODE REVIEW

**Comment by eigenraven** [comment]
oops, based off the wrong commit, one sec I'll push a fixed version

**Review by Dream-Master — APPROVED** [review]

**Comment by boubou19** [comment]
are the NEI handler changes related to this PR?

**Comment by eigenraven** [comment]
It was a build error fix, static methods overriding identical non-static method in the superclass

**Comment by Dream-Master** [comment]
> are the NEI handler changes related to this PR?

where ?

**Comment by eigenraven** [comment]
huh the first commit looks weird, let me double check what happened during rebase

**Comment by Dream-Master** [comment]
or should i reverse it first and we make a new pr after ?

**Comment by eigenraven** [comment]
One sec, I'm making a fixing pr by reverting this one already

**Pull request merged**
