### PR TITLE
Added means of customizing GUI colors for resource packs

### PR DESCRIPTION
**Pull request by Flanisch**
Added an Enum that contains all hardcoded UI text colors and linked them to their corresponding classes. Included a way for users to change these colors through the GT5u lang file.

This also makes it possible for resource pack creators to easily make text more readable/change it.

### CODE REVIEW

**Comment by leagris** [comment]
This is wrong design to put GUI colour to lang files.
This kind of setting shall be part of resources, in the texture directory. Either in a toml, forge cfg or JSON format file. It has no place in the language file.

While I am very positive with the principle of configurability in the resources path; I am firmly opposed to this change as-is at the wrong place.

**Review by leagris — CHANGES_REQUESTED** [review]
GUI colour has no place in language files.

**Comment by Flanisch** [comment]
I'll try to separate the changes to a json file. Since lang files are already used to change text color through minecrafts chat formatting I thought it would be best to keep all UI-text related settings in the same file.

**Comment by Flanisch** [comment]
You do mean resources in the mc root directory?
Can a resource pack change files in that directory? If it can't that would make it less user friendly to install any sort of UI textures that require that change.

**Comment by leagris** [comment]
The very same resources path used for loading textures which default to loading the resources available in the jar file, languages, sounds can be overridden by resources packs.

**Comment by Flanisch** [comment]
Also thank you for being patient with me. I'm still new to java and especially minecraft.

**Comment by repo-alt** [comment]
Tbh I see nothing much wrong in using the language file for colors (why reinvent the wheel) , but anyway, if you switch to Json it would make sense to make the same change in AE2. Also If I'm not mistaken you read and parse Json file to fetch every color value any time you need it. Yes this is GUI code, but still.

**Comment by Flanisch** [comment]
Yeah, whichever approach gets chosen here will also be adapted to the ae2 commit.

I don't see an issue to get the color everytime a gui is opened. It's the same for getting the translation. Everytime a translation is needed, the translation file is read.

I know not enough about mc coding to change that behaviour, but am open for suggestions ^^

**Comment by repo-alt** [comment]
> Everytime a translation is needed, the translation file is read.

Is it? I was under impression that translations are cached in net.minecraft.util.StringTranslate in StatCollector instance

**Comment by repo-alt** [comment]
Also you seem to be using client classes server side, look at the GH build result

**Comment by Flanisch** [comment]
Actually, yeah that does make sense that it crashes Server Side, since servers don't have resources to load.

I will try to fix that.

**Comment by Flanisch** [comment]
It was my assumption, that was how it worked the translations worked. Your statement does make a lot more sense though.

I'll look into it more and see what can be done.

**Comment by Flanisch** [comment]
I hope this implementation is better. Took me long enough to figure resource loading and server/client separation out.

**Review by leagris — CHANGES_REQUESTED** [review]
The base idea to have colours configurable for the client in the resources path is very nice and appropriate. Although there is a design/specification issue that shall be dealt with before it can be merged because any later change/expansion to the specification cab be a burden if not thought out initially.

In your current code, you use a big single JSON whose name does not reflect it use as container for text colour entries, and where the use of dot namespaced string keys is inappropriate in a JSON file whose format is natively designed for a hierarchy of object containers.
Lets take as example your implementation for the maintenance hatch GUI:
```java
        textColorTitle = GuiColors.maintenanceHatch.getColor(),
        textColorRepair = GuiColors.maintenanceHatchRepair.getColor();
```
These gets read from the `gregtech:textures/guiColors.json` `resourcePath`:
```json
{
  "...": "...",
  "GT5U.gui.color.maintenanceHatch": "404040",
  "GT5U.gui.color.maintenanceHatchRepair": "404040",
  "yada": "...",
}
```
But the GUI texture png file is read from:
`gregtech:textures/gui/Maintenance.png`

So, rather than having all GUI colours in one big inappropriately flat JSON file, it would seems more appropriate to have a smaller JSON at the same path like:
`gregtech:textures/gui/Maintenance.colors.json`:
```json
{
  "bg": "D2DCFF",
  "fg": "000000",
  "title": {
    "bg": "D2DCFF",
    "fg": "404040"
  }
  "repair": {
    "bg": "D2DCFF",
    "fg": "404040"
  }
}
```
Then each texture would have an optional related `<texturename>.color.json` to define colour elements used for this texture's context.
This can optionally replace the global colour selector for GUI background and machine tints.
This would replace hardcoded orange or gunmetal background tint applied to bronze and steel steam machines GUI.
Having both background and foreground elements in the JSON, would allow providing sufficient contrast for whatever colours are defined in a resource pack.

**Comment by Flanisch** [comment]
@leagris Thank you so much for your thorough review.

I will change the files to be in line with the .editorconfig. Thank you for telling me.

I do however want to talk a bit about the design specification before I go about implementing it.

### How background color works
First and foremost, I think there is a misunderstanding how gui-tints work. All possible tints a GUI can have are defined in `Dyes.java`. If a machine is not colored with a color applicator, the background color defaults to white (see `GT_GUIContainerMetaTile_Machine.java - getColorization()`).

The background color will then be multiplied with the overlying gui texture. I don't really have a source for this, since my knowledge with Minecrafts renderer is basically nonexistent, but that's what my testing resulted in. See the following example with a normal packager gui and one of the textures I changed to be dark.

| Normal (White) | Painted (Blue) |
| --- | --- |
| Packager_normal | Packager_blue|
|CA_normal | CA_blue|

Note how everything (including Buttons) is submerged with a strong blue tint? This is quite suboptimal behavior for resource pack creators.

This is the same effect I get when multiplying a gui texture with a layer in solid color in Photoshop.

The colors for the bronze and steel boiler also don't have a standard tint, the texture itself has a different color.

### Effect of `Dyes.java`
The dyes which are specified in here don't only apply to GUI tints but to all sorts of stuff, like painting pipes, machines, etc...

So its effects range beyond just UI-textures. That's why I would add a number of separate colors which shall only affect the UIs and nothing else.


### Having a json for every texture
While I do think that having a .json for every texture adds descriptiveness, I believe managing over 120 different json (there are over 120 UI textures in GT5u) files is just not user friendly for anyone that wants to work with them.

I do however agree with the thought of adding more structure to the .json file. How about keeping one JSON-File and structuring it with UI-Class and color functions instead?

Example: 
```json
{
	"Dyes":
	{
		"enableGUITint": true,
		"color.guiTint.Red": "0xFF0000"
	},
	"GT_GUIContainer_MaintenanceHatch":
	{
		"color.text.MaintenanceHatch": "404040",
		"color.text.Repair": "404040" 
	}
}
```

I know that you dislike the idea of namespacing inside the json. I think it helps keeping the json file easy to view and edit and might also make parsing it easier. If you have a different idea, I am glad to hear it.

**Review by leagris — APPROVED** [review]

**Comment by Dream-Master** [comment]
We test this on zeta

**Comment by leagris** [comment]
Not good, missing dependency and nothing for casual player to test it with. It is just meant to be customised by resource_pack to suit their need to adjust text color with GUI textures. Please revert!

**Comment by eigenraven** [comment]
Minecraft also already bundles GSON (google json library) so there's no need to bundle/add another one in

**Comment by Connor-Colenso** [comment]
This is causing kekztech to crash now. I don't think it needs reverting but the dep certainly needs to be added as it stalls dev in other areas );

**Comment by Ranzuu** [comment]
I understand this is an old project, but might be connected to what I am suggesting:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21401

**Pull request merged**
