### PR TITLE
Fix solar boiler heat up speed

### PR DESCRIPTION
**Pull request by Glease**
Signed-off-by: Glease <4586901+Glease@users.noreply.github.com>

### CODE REVIEW

**Review by leagris — COMMENTED** [review]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/c4b82eac92cbb9cf46f7d819be8e07d761c9475f/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Solar.java#L33-L36

These numbers shall not be literal but true values computed from the actual mechanic of the boiler, like sharing computations with infoData.

**Comment by leagris** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/c4b82eac92cbb9cf46f7d819be8e07d761c9475f/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Solar.java#L42-L51

Replace with:
```java
        for (int color = -1, i = 0; color < 16; color++, i++) {
            final short[] colorModulation = Dyes.getModulation(color, Dyes._NULL.mRGBa);
            ITexture[] textureBottom = {new GT_RenderedTexture(Textures.BlockIcons.MACHINE_BRONZEBRICKS_BOTTOM, colorModulation)};
            rTextures[0][i] = textureBottom;
            ITexture[] textureTop = {new GT_RenderedTexture(Textures.BlockIcons.MACHINE_BRONZEBRICKS_TOP, colorModulation), new GT_RenderedTexture(Textures.BlockIcons.BOILER_SOLAR)};
            rTextures[1][i] = textureTop;
            ITexture[] textureSide = {new GT_RenderedTexture(Textures.BlockIcons.MACHINE_BRONZEBRICKS_SIDE, colorModulation)};
            rTextures[2][i] = textureSide;
            ITexture[] textureFront = {new GT_RenderedTexture(BlockIcons.MACHINE_BRONZEBRICKS_SIDE, colorModulation), new GT_RenderedTexture(BlockIcons.OVERLAY_PIPE)};
            rTextures[3][i] = textureFront;
        }
```

**Comment by leagris** [comment]
return Math.max(this.basicMaxOuput, this.basicOutput - ((this.mRunTime - CALCIFICATION_TIME) / (CALCIFICATION_TIME/150))); // Every 288*25 ticks, or 6 minutes, lose 1 L output.
→
```java
            return Math.max(this.basicMaxOuput, this.basicOutput - ((this.mRunTime - CALCIFICATION_TIME) / (CALCIFICATION_TIME/this.basicMaxOuput))); // Every 288*25 ticks, or 6 minutes, lose 1 L output.
```

**Comment by Glease** [comment]
There is something wrong with solar code. Will need more inspection.

**Review by leagris — APPROVED** [review]

**Pull request merged**
