### PR TITLE
Fix radon recipe amount/time

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8166

PS: calculating the recipe at a higher voltage when it starts at ULV is ass.

### CODE REVIEW

**Review by Dream-Master — CHANGES_REQUESTED** [review]
change eu to 480

**Comment by Prometheus0000** [comment]
It automatically downvolts it.

**Comment by GlodBlock** [comment]
why not use 8 plutonium block?

**Comment by Prometheus0000** [comment]
Like I stated in the issue, it's so people don't have to do 2 processes.

**Comment by Dream-Master** [comment]
> It automatically downvolts it.
> 
> image
> 
> See? That's also why the other radon one is 7, not 8.

Yes I know but it would better change it to 480 since we use that value for ages

**Comment by Prometheus0000** [comment]
Done

**Review by Ethryan — APPROVED** [review]

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
