### PR TITLE
Buff Thaumium Reinforced Jar recipe

### PR DESCRIPTION
**Pull request by Gofer2x**
The Thaumium Reinforced Jar has quadruple capacity compared to a normal one, but cannot be picked up while full. This makes it useful for making stationary setups like smelteries more compact.
But its cost makes it extremely expensive to make even a few, and it's gated by titanium - which is also what gates essentia AE2 which obsoletes jars for majority of cases.
This PR changes the recipe to be way more reasonable and ungated, but still thaumium-hungry so they can't be spammed like the cheap normal jars (if you do enough smelting to need them, you can afford them). Also uses managlass for bit of crossmod magic.
Current recipe:
image
New recipe:
image

### CODE REVIEW

**Review by boubou19 — APPROVED** [review]

**Review by Dream-Master — CHANGES_REQUESTED** [review]
No wait . Titanium might a bit high but tier it from ev to lv ?

**Comment by Dream-Master** [comment]
Aspects are are a joke now. From was it before

**Comment by Ruling-0** [comment]
> No wait . Titanium might a bit high but tier it from ev to lv ?

As was mentioned, this requiring titanium made it useless. It provides 4x the capacity of a normal jar. For comparison, the essentia reservoir also stores 256 essentia, but of multiple types (sometimes useful sometimes not) and cannot be interacted with using phials. The reservoir requires infusion and void metal, a bit of a higher magic gate, which is fair given its extra usefulness in storing multiple types + rotation. However, this solidly places it MV-HV, which is before the old recipe. Within the thaum tiering alone it was useless.

However, titanium also unlocks AE and leads to essentia cells, which store _way_ more than any jar, so why would you bother crafting this jar when you can instead use essentia cells? There was no purpose to this being an EV gated recipe. Being LV gives it actual purpose.

**Comment by boubou19** [comment]
Aspect wise, most of the previous ones werent making sense as it's too much for something that is barely relevant in the pack progression. I guess we can put back one or two like tutamen and vacous, or add them all back but reducing the amount of them.

Right now, this has little to no place in the pack progression because you can have the Essentia Reservoir at HV, and Thaumic Energistics unlocks in EV. Given you don't start much toying with essentias until you have the infusion matrix which requires HV for the eye of ender. If you put harder materials in the recipe, players will just skip this and go to the reservoir. 

the recipe of the reservoir
image

**Comment by Alastors** [comment]
I agree with Boubou, as it currently stands the Thaumium Jar is a fucking joke and there’s no reason to use it, like I’ve been saying this needs to be below the reservoir which means it needs to be pre infusion, otherwise, like boubou said, why would they ever use the thaumium jar when it’s the same size as the reservoir but can only store a single aspect

**Review by Alastors — APPROVED** [review]
This needs to happen, frankly even this is a bit too expensive IMO for how useful this jar will be considered by people, it’s merely 4x bigger than a normal jar and can’t be picked up with essentia in it, so at that rate why not just use 4x more normal jars for a fraction of the price.

**Comment by Dream-Master** [comment]
Will edit it later

**Comment by Dream-Master** [comment]
I not forgot about this and will edit it as soon I have time for it.

**Comment by Dream-Master** [comment]
i check the orginal recipe from old Kekztech code and it was a infusion recipe
```JAVA
    public static void postInit() {
        final AspectList aspects_jarthaumiumreinforced = new AspectList().add(Aspect.ARMOR, 3)
            .add(Aspect.WATER, 3)
            .add(Aspect.GREED, 3)
            .add(Aspect.VOID, 3);
        @SuppressWarnings("unused")
        final ResearchItem jar_thaumiumreinforced = new ResearchItem(
            "THAUMIUMREINFORCEDJAR",
            "ALCHEMY",
            aspects_jarthaumiumreinforced,
            3,
            -4,
            2,
            new ItemStack(Blocks.jarThaumiumReinforced, 1))
                .setPages(
                    new ResearchPage("kekztech.research_page.THAUMIUMREINFORCEDJAR.0"),
                    new ResearchPage(Recipes.infusionRecipes.get("THAUMIUMREINFORCEDJAR")),
                    new ResearchPage(Recipes.infusionRecipes.get("THAUMIUMREINFORCEDVOIDJAR")),
                    new ResearchPage("kekztech.research_page.THAUMIUMREINFORCEDJAR.1"))
                .setConcealed()
                .setParents("JARLABEL")
                .registerResearchItem();```

**Comment by Dream-Master** [comment]
and it used titanium as well
```JAVA
        // Thaumium Reinforced Jar
        final ItemStack[] recipe_jarthaumiumreinforced = {
            GameRegistry.makeItemStack("Thaumcraft:ItemResource", 15, 1, null),
            GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
            new ItemStack(net.minecraft.init.Blocks.glass_pane),
            GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
            new ItemStack(net.minecraft.init.Blocks.glass_pane),
            GT_OreDictUnificator.get(OrePrefixes.frameGt, Materials.Titanium, 1),
            GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
            new ItemStack(net.minecraft.init.Blocks.glass_pane),
            GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
            new ItemStack(net.minecraft.init.Blocks.glass_pane), };
        final AspectList aspects_jarthaumiumreinforced = new AspectList().add(Aspect.ARMOR, 64)
            .add(Aspect.ORDER, 32)
            .add(Aspect.WATER, 32)
            .add(Aspect.GREED, 16)
            .add(Aspect.VOID, 16)
            .add(Aspect.AIR, 8);
        infusionRecipes.put(
            "THAUMIUMREINFORCEDJAR",
            ThaumcraftApi.addInfusionCraftingRecipe(
                "THAUMIUMREINFORCEDJAR",
                new ItemStack(Blocks.jarThaumiumReinforced, 1, 0),
                5,
                aspects_jarthaumiumreinforced,
                ItemApi.getBlock("blockJar", 0),
                recipe_jarthaumiumreinforced));```

**Comment by Alastors** [comment]
> and it used titanium as well https://github.com/GTNewHorizons/KekzTech/blob/master/src/main/java/common/Recipes.java#L55C1-L81C48
> 
> ```java
>         // Thaumium Reinforced Jar
>         final ItemStack[] recipe_jarthaumiumreinforced = {
>             GameRegistry.makeItemStack("Thaumcraft:ItemResource", 15, 1, null),
>             GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
>             new ItemStack(net.minecraft.init.Blocks.glass_pane),
>             GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
>             new ItemStack(net.minecraft.init.Blocks.glass_pane),
>             GT_OreDictUnificator.get(OrePrefixes.frameGt, Materials.Titanium, 1),
>             GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
>             new ItemStack(net.minecraft.init.Blocks.glass_pane),
>             GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.Thaumium, 1),
>             new ItemStack(net.minecraft.init.Blocks.glass_pane), };
>         final AspectList aspects_jarthaumiumreinforced = new AspectList().add(Aspect.ARMOR, 64)
>             .add(Aspect.ORDER, 32)
>             .add(Aspect.WATER, 32)
>             .add(Aspect.GREED, 16)
>             .add(Aspect.VOID, 16)
>             .add(Aspect.AIR, 8);
>         infusionRecipes.put(
>             "THAUMIUMREINFORCEDJAR",
>             ThaumcraftApi.addInfusionCraftingRecipe(
>                 "THAUMIUMREINFORCEDJAR",
>                 new ItemStack(Blocks.jarThaumiumReinforced, 1, 0),
>                 5,
>                 aspects_jarthaumiumreinforced,
>                 ItemApi.getBlock("blockJar", 0),
>                 recipe_jarthaumiumreinforced));```
> ```

Look man, as long as this is MV, I genuinely don't care about the specifics, it just needs to be tiered before the reservoir and after the normal jar

**Comment by Dream-Master** [comment]
I will rework this later

**Comment by Gofer2x** [comment]
oh right, this lol. i wrote up something and made a change for it a few days ago but forgot to post here.
here is what i made, the new recipe.
image

so,
normal jar - not gated at all. can hold 64 of a single aspect. can be picked up while full. be used manually with phials.
thaumium reinforced jar - mv and botania gated (dense plate and managlass). can hold 256 of a single aspect. cannot be picked up while full. can be used manually with phials.
essentia reservoir - eldritch research and infusion gated. can hold 256 of any combination of aspects. cannot be picked up while ful. cannot be used manually with phials. has lower suction (24 instead of jar's 32).

the idea is to make the reinforced jar actually usable. it's just an upgraded version of the normal jar that cannot be picked up. it cannot entirely outclass the reservoir as those have lower suction and can hold multiple types of essentia, making them more flexible for more complicated setups.
of course not expecting you to immediately open this back up and merge it, just lol i forgor to post this and only remembered when i saw the notif this was closed.

**Comment by Dream-Master** [comment]
> oh right, this lol. i wrote up something and made a change for it a few days ago but forgot to post here. here is what i made, the new recipe. image
> 
> also more of an actual comparison, normal jar - not gated at all. can hold 64 of a single aspect. can be picked up while full. can be used manually with phials. thaumium reinforced jar - mv and botania gated (dense plate and managlass). can hold 256 of a single aspect. cannot be picked up while full. can be used manually with phials. essentia reservoir - eldritch research and infusion gated. can hold 256 of any combination of aspects. cannot be picked up while ful. cannot be used manually with phials. has lower suction (24 instead of jar's 32).
> 
> the idea is to make the reinforced jar actually usable. it's just an upgraded version of the normal jar that cannot be picked up. it cannot entirely outclass the reservoir as those have lower suction and can hold multiple types of essentia, making them more flexible for more complicated setups. of course not expecting you to immediately open this back up and merge it, just lol i forgor to post this and only remembered when i saw the notif this was closed.

sorry but this is not what i want to see. I take care the recipe and have it on my list

**Comment by Gofer2x** [comment]
fair enough. i'll just wait and see then.

**Pull request closed without merging**
